### ISSUE TITLE
`ftplugin/python.vim` sourced after a dein-managed plugin, even if lazy loaded

### ISSUE THREAD

**Issue by galou** [Shougo/dein.vim#101]
# Problems summary

`ftplugin/python.vim` sourced after a dein-managed plugin.

## Expected

`ftplugin/python.vim` sourced before dein-managed plugins.

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('ivanov/vim-ipython',
            \ {'on_ft': 'python'}
            \ )
call dein#end()
```

`ftplugin/python.vim`:
```vim
let g:ipy_perform_mappings = 0
```

## The reproduce ways from Vim starting (Required!)

 1. start vim with a Python file
 2. use a IPython mapping, the mapping exists though it shouldn't

**Comment by Shougo** [comment]
You must write `let g:ipy_perform_mappings = 0` in your vimrc.
ftplugin is just FileType autocmd.
The autocmd order is not guaranteed.
