### ISSUE TITLE
Improve unite log viewer

### ISSUE THREAD

**Issue by petobens** [Shougo/dein.vim#103]
Is it possible to improve the unite log viewer to make it similar to neobundle?
Currently I'm using:
```vim
nnoremap <Leader>bu :call dein#update()<CR>:Unite -no-start-insert -log
            \ dein/log<CR>
```
and I get
![screen shot 2016-05-22 at 15 30 26](https://cloud.githubusercontent.com/assets/2583971/15455687/49535da8-2032-11e6-81d0-ced4c31f8319.png)

It would be nice to only get the list of plugins (along the github URI) that were actually updated. If no plugin was update simply show something like `No updates`. 

A last question: in neobundle there was a log file that could be set like this:
```vim
let g:neobundle#log_filename = $CACHE . '/plugins/neobundle/neobundle.log'
```
does dein have a log file?

**Comment by Shougo** [comment]
I will implement it.

**Comment by Shougo** [comment]
Implemented.

**Comment by petobens** [comment]
Thank you!. A couple of minor things:

i) the docs are wrongs, it should say `g:dein#install_log_filename` but they say `g:neobundle#install_log_filename`.
ii) Is there (or can you implement) a unite source similar to `Unite neobundle/update:all`?
I would like to run something like `:Unite -log dein/update` and have dein updated plugins shown in the Unite buffer. Currently if I run `Unite dein/log` once the update finishes I get:

![screen shot 2016-05-27 at 10 08 59](https://cloud.githubusercontent.com/assets/2583971/15608896/111ba688-23f3-11e6-9574-aa17d8f16d58.png)
I would be nice if that updated buffer i)only shows the updated bundles and not the complete log and ii) that he candidates are added to the buffer asynchronously.  

PS:  BTW I don't understand this part of the docs:
> If argument 1 is "!", the updated logs are displayed.

How do you pass `!` to `Unite dein/log`?

**Comment by Shougo** [comment]
> i) the docs are wrongs, it should say g:dein#install_log_filename but they say g:neobundle#install_log_filename.

Fixed.

> How do you pass ! to Unite dein/log?

`:Unite dein/log:!`

**Comment by Shougo** [comment]
> ii) Is there (or can you implement) a unite source similar to Unite neobundle/update:all?

I don't want to implement it.
It is too complex source to implement.

**Comment by petobens** [comment]
> It is too complex source to implement.
Ok. Thanks anyway

**Comment by Shougo** [comment]
Please update dein and unite.vim to the latest version.
I have fixed them.

**Comment by petobens** [comment]
Can I somehow automatically run `Unite dein/log:!` immediately after `dein#update()` finishes?  Is there an autocommand for instance? Thanks for the help.

**Comment by Shougo** [comment]
You can create new command for it.

**Comment by petobens** [comment]
Thanks Shougo but I don't know how to do that. Specifically I don't know how to detect that the `dein#update()` process finished.

**Comment by wsdjeg** [comment]
@petobens you will see the red message, `Done`

**Comment by wsdjeg** [comment]
`[dein] Update started: (2016/05/31 22:28:22)`
and
`[dein] Runtimepath updated: (2016/05/31 22:29:50) `

**Comment by petobens** [comment]
@wsdjeg ok but I don't know how to create a command that uses that message to detect that the update finished. I need some sort of autocommand I guess.

**Comment by Shougo** [comment]
@petobens Why don't you create the wrapper command like this?
You don't have to hook the function.

```vim
command! DeinUpdate  call s:dein_update()
function! s:dein_update()
  call dein#update()
  Unite dein/log:!
endfunction
```

**Comment by petobens** [comment]
@Shougo thank you!!!!
