### ISSUE TITLE
Would love to have some submodule awareness

### ISSUE THREAD

**Issue by dkowis** [Shougo/dein.vim#104]
I have this set up and running, but I store all my stuff in a git repo, a dotfiles repo.

I suppose I could have done something to install all the stuff outside of it, but it'd be an awesome feature to have it not just clone, but detect if the directory it's cloning into was also a git directory, and instead do a submodule.

Additionally, it'd be nice to know what things are .gitignore-able, it seemed to have done lots of metadata changes, not all I thought I needed, but I'm not really sure :)

So it'd be pretty sweet if this could have some logic around it that if it knows it's being used in a git repo, or what metadata is per-machine and shouldn't be tracked, or something like that.

Thanks!

**Comment by Shougo** [comment]
I think it is too complex and not useful.
Closing.

**Comment by ypid** [comment]
> I don't like submodule feature.

Can you explain this? #353 also went into this direction and you went with implementing something by yourself rather than using an existing solution like git submodules for this.

**Comment by Shougo** [comment]
Really?  I don't want to explain it in English...

git submodule is complex feature and I often forget git submodule commands.
If the feature is really needed, you can implement it.
This is open source solution.

**Comment by ypid** [comment]
> git submodule is complex feature and I often forget git submodule commands.

That depends on who you ask. I now looked closer at `dein#save_rollback` and `dein#load_rollback`. You basically reimplemented git submodules with that. Submodules also tracks the commit hash. The main difference is that you decoupled it form git. You could have achieved the same by creating an independent parent repository which holds all the submodules below `~/.cache/dein`. Then you would have all the metadata and the full power of git for free.

So my take on complexity is different here. If everybody presents their own solution I would now need to learn 100 instead of just one.

> If the feature is really needed, you can implement it. This is open source solution.

The question is would you merge it :) ?

**Comment by Shougo** [comment]
I don't want to depends on git submodule behavior.

If I use git submodule, it breaks current downloaded repositories and it adds complexity.

**Comment by Shougo** [comment]
The merge is depends on your diff size and the advantages.

I think the advantage is not so big.

**Comment by ypid** [comment]
Thanks, I will consider it. It depends a bit on if SpaceVim would be onboard also (ref: https://github.com/SpaceVim/SpaceVim/issues/4024). A migration strategy would be needed of course and is possible. My idea would be that people don't need to deal with submodules until they need advanced features like rollback.

But as I am thinking about it, it may be better to start a plugin manager fresh with git submodule support as it’s "selling point". But dedicating the amount of time into it to make it happen is not something I can do short term.

**Comment by Shougo** [comment]
Hm. If it has compatibility and the advantage is big, I will consider about  it.
