### ISSUE TITLE
Dein can not detect the default branch of a repo.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#108]
here is a source of unite
https://github.com/klen/unite-radio.vim
and the default branch is develop, not master.
I use `call dein#add('klen/unite-radio.vim')`, dein will auto install the master branch.but the master branch has some bugs.I know I can use an option to make dein to use the branch I want.but I think dein maybe able to detect the default branch.

**Comment by Shougo** [comment]
Fixed.
