### ISSUE TITLE
dein#add from other host with ssh

### ISSUE THREAD

**Issue by florianm93** [Shougo/dein.vim#109]
# Problems summary
I have list of plugins on a git-repo which is hosted at my work's git-server. I am only able to pull with ssh (https is not supported for security reasons). It looks like when I am browsing through your code [(https://github.com/Shougo/dein.vim/blob/master/autoload/dein/types/git.vim#L89),](https://github.com/Shougo/dein.vim/blob/master/autoload/dein/types/git.vim#L89) that you only allow ssh with github.com as host. 

Is there a reason or are you able to add this feature in the future? 

## Expected
ssh pull working for other hosts beside github.com

## Environment Information
 * OS: Mac OS X 10.11.5
 * Vim version: 7.4.1412

## Provide a minimal .vimrc with less than 50 lines

```vim
" Your minimal .vimrc
set runtimepath^=~/.vim/dein/repos/github.com/Shougo/dein.vim$
call dein#begin(path)
call dein#add('git@example.com:vim/snippets', {'name': 'ta-snippets'})$
call dein#end()
```

## The reproduce ways from Vim starting

 1. Install new plugins `call dein#install()`
 2. error log: `[dein] fatal: unable to access 'https://github.com/git@example.com:vim/snippets.git/': The requested URL returned error: 400
[dein] Error installing plugins:
[dein]   ta-snippets
[dein] Please read the error message log with the :message command.
[dein] Runtimepath updated: (2016/05/31 14:47:35)`
3. see message below

## Upload the log messages by `:redir` and `:message`
`Messages maintainer: Bram Moolenaar <Bram@vim.org>
".vimrc" 590L, 21175C
[dein] Update started: (2016/05/31 14:47:25)
[dein] /Users/macherey/.vim/dein/repos/github.com/git@example.com/vim/snippets
[dein] Maybe wrong username or repository.
[dein] Cloning into '/Users/macherey/.vim/dein/repos/github.com/git@example.com/vim/snippets'...
[dein] fatal: unable to access 'https://github.com/git@example.comvim/snippets.git/': The requested URL returned error: 400
[dein] Error installing plugins:
[dein]   ta-snippets
[dein] Please read the error message log with the :message command.
[dein] Runtimepath updated: (2016/05/31 14:47:27)
[dein] Update started: (2016/05/31 14:47:32)
[dein] /Users/macherey/.vim/dein/repos/github.com/git@example.com/vim/snippets
[dein] Maybe wrong username or repository.
[dein] Cloning into '/Users/macherey/.vim/dein/repos/github.com/git@example.com/vim/snippets'...
[dein] fatal: unable to access 'https://github.com/git@example.com:vim/snippets.git/': The requested URL returned error: 400
[dein] Error installing plugins:
[dein]   ta-snippets
[dein] Please read the error message log with the :message command.
[dein] Runtimepath updated: (2016/05/31 14:47:35)`

**Comment by Shougo** [comment]
Fixed.
