### ISSUE TITLE
neobundle#append() equivalent

### ISSUE THREAD

**Issue by jeaye** [Shougo/dein.vim#111]
# Problems summary
I don't see an equivalent to `neobundle#append()`, which allows compartmentalization of packages instead of having them all listed inside one begin/end. Is this something which dein may support, or will it work against the path optimizations being done?

**Comment by Shougo** [comment]
I can implement this feature.  But I don't use the feature...
Why you need the feature?

I think you can split the initialization like this without `dein#append()`.

```vim
dein#begin()

source a.vim
source b.vim

dein#end()
```

**Comment by jeaye** [comment]
Yeah, I had my configs laid out like

```viml
source layer/a.vim
source layer/b.vim
```

Where each `.vim` file stands alone and does its own `neobundle#append`. After switching to dein, I've refactored that so that each layer is a directory with a `package.vim` and `config.vim`. The former is sourced inside of the `dein#begin` block and the latter is sourced after.

```viml
" Register all packages across layers
let packages = split(globpath($HOME . "/.vim/layer", "**/package.vim"), "\n")
if dein#load_state(s:dein_dir)
  call dein#begin(expand('~/.vim/dein'), packages)
    call dein#add('Shougo/dein.vim')
    call dein#add('Shougo/vimproc.vim', {'build' : 'make'})

    for f in packages
      exe "source" f
    endfor
  call dein#end()
  call dein#save_state()
endif

" Install missing packages
if has('vim_starting') && dein#check_install()
  let g:dein#install_process_timeout = 60 * 10
  call dein#install()
endif

" Load each layer's config
let files = globpath($HOME . "/.vim/layer", "**/config.vim")
for f in split(files, "\n")
  exe "source" f
endfor
```

I'm ok with this separation, and it means you don't need to implement the analogous append feature. Thanks for following up.

**Comment by Shougo** [comment]
OK
