### ISSUE TITLE
the completion for command been echoed, instead of show in statusline

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#112]
# Problems summary
when use dein manager plugin lazyload by on_cmd, if the command has completion func, all the result has been echo out instead of shown in statusline
![2016-06-13-20 38 59](https://cloud.githubusercontent.com/assets/13142418/16007798/1489b438-31a7-11e6-95e4-ad3e2685919b.png)

## Expected

![2016-06-13-20 39 26](https://cloud.githubusercontent.com/assets/13142418/16007813/24388896-31a7-11e6-9975-211a954d86ff.png)

## Environment Information
 * OS:arch
 * Vim version:neovim master

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/vimfiles'))
call dein#add('wsdjeg/vim-cheat',{'on_cmd' : 'Cheat'})

call dein#end()

filetype plugin indent on
syntax on

```

## The reproduce ways from Vim starting (Required!)

 1. nvim -u test.vim
 2. `:Cheat ` +`<tab>`

**Comment by Shougo** [comment]
It is intended behavior.
#100

**Comment by wsdjeg** [comment]
It just looks too strange.

**Comment by DeaR** [comment]
Because the calling `cmdline-completion` do not know whether the `<C-D>` or `'wildchar'`.

**Comment by wsdjeg** [comment]
I understand, I am not family with cmdline-completion.

**Comment by wsdjeg** [comment]
after  firsttime type`<tab>` ,I got
![2016-06-13-20 38 59](https://cloud.githubusercontent.com/assets/13142418/16007798/1489b438-31a7-11e6-95e4-ad3e2685919b.png)
if type `<tab>` again, I got
![2016-06-16-20 18 10](https://cloud.githubusercontent.com/assets/13142418/16116490/d4aded74-33ff-11e6-83db-f18454f65117.png)

I think maybe we need a `redraw the windows`
