### ISSUE TITLE
dein#set_hook() not working

### ISSUE THREAD

**Issue by fsworld009** [Shougo/dein.vim#114]
# Problems summary
I'm trying to use dein#set_hook() to set 'hook_add' hook to unite-outline plugin (refer below for my hook function), but it seems that it does not add the hook. The `g:test` remains undefined when I start neovim

but if I change `dein#set_hook()` call to `dein#config()`, then it worked.

I need to use `hook_add` because I want to move `g:Unite_source_outline_setup` function to another .vim file later.

## Expected
`g:test` should have been set to 1

## Environment Information
 * OS: Windows 7 x64
 * Vim version: neovim-qt

## Provide a minimal .vimrc with less than 50 lines (Required!)
**NOT Working:**
```vim
call dein#begin({plugin_base_path})
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/unite.vim')
function! g:Unite_source_outline_setup()
  let g:test = 1
endfunction

call dein#add('Shougo/unite-outline')
call dein#set_hook('unite-outline','hook_add',function('g:Unite_source_outline_setup'))
call dein#end()
```
**Working:**

```vim
call dein#begin({plugin_base_path})
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/unite.vim')
function! g:Unite_source_outline_setup()
  let g:test = 1
endfunction

call dein#add('Shougo/unite-outline')
call dein#config('unite-outline',{'hook_add':function('g:Unite_source_outline_setup')})
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. put above script to your vimrc
 2. restart neovim
 3. invoke ex command `:echo g:test`
 4. you get `Undefined variable` error

**Comment by Shougo** [comment]
Fixed.
