### ISSUE TITLE
Notification message is empty

### ISSUE THREAD

**Issue by khalidchawtany** [Shougo/dein.vim#115]
# Problems summary
When I set `﻿﻿let g:dein#enable_notification=1` and have **terminal-notifier** installed, the shown notification message is empty.

Changing [this line](https://github.com/Shougo/dein.vim/blob/master/autoload/dein/util.vim#L97) from 
`\ . string(title) . ' ' . string(a:msg)
`
to 
`\ . string(title) . ' -message ' . string(a:msg)
`
fixes the issue.

## Expected
Notification message not to be empty

## Environment Information
 * OS: OS X 10.11.5

## The reproduce ways from Vim starting (Required!)

 1. Set `g:dein#enable_notification=1` to 1
 2. Start neovim and execute `call dein#update()`

## Screen shot (if possible)
![screen shot 2016-07-09 at 11 56 11 pm](https://cloud.githubusercontent.com/assets/1681606/16710253/ca4e37a6-4630-11e6-9123-c995f7698de0.png)

**Comment by Shougo** [comment]
Fixed thanks.
