### ISSUE TITLE
Install script accepts relative paths, but generates a bad .vimrc

### ISSUE THREAD

**Issue by ExpHP** [Shougo/dein.vim#117]
# Problems summary

The install script accepts a relative path, but assumes it is an absolute path when generating the example `.vimrc`.

## Steps to reproduce

**1.** Install dein using a **relative** path. (e.g. **bundle**, not **~/.vim/bundle**)

    mkdir ~/test-dir && cd ~/test-dir

    curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
    sh ./installer.sh bundle

**2. It gives you the following .vimrc**

    "dein Scripts-----------------------------
    if &compatible
      set nocompatible               " Be iMproved
    endif

    " Required:
    set runtimepath^=bundle/repos/github.com/Shougo/dein.vim
    
    " Required:
    call dein#begin(expand('bundle'))
    
    " Let dein manage dein
    " Required:
    call dein#add('Shougo/dein.vim')
    
    " Add or remove your plugins here:
    call dein#add('Shougo/neosnippet.vim')
    call dein#add('Shougo/neosnippet-snippets')
    
    " You can specify revision/branch/tag.
    call dein#add('Shougo/vimshell', { 'rev': '3787e5' })
    
    " Required:
    call dein#end()
    
    " Required:
    filetype plugin indent on
    
    " If you want to install not installed plugins on startup.
    "if dein#check_install()
    "  call dein#install()
    "endif
    
    "End dein Scripts-------------------------

**3. Use that .vimrc and open vim.**  You will immediately see:

    Error detected while processing /home/lampam/.vimrc:
    line   10:
    E117: Unknown function: dein#begin
    line   14:
    E117: Unknown function: dein#add
    line   17:
    E117: Unknown function: dein#add
    ...more...

## Expected

`installer.sh` should produce the following lines instead.

    " Required:
    set runtimepath^=/home/lampam/test-dir/bundle/repos/github.com/Shougo/dein.vim
    
    " Required:
    call dein#begin(expand('/home/lampam/test-dir/bundle'))

## Environment Information

**OS**

    $ uname -a
    Linux lampam-ThinkPad-T430 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Vim**

    $ vim --version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
    [...]

## Provide a minimal .vimrc with less than 50 lines (Required!)

See step 2.

**Comment by Shougo** [comment]
Fixed.
