### ISSUE TITLE
Long time installing plugins in neovim

### ISSUE THREAD

**Issue by mhartington** [Shougo/dein.vim#12]
# Problems summary
Not sure if this is an issue with Dein or my setup, but plugin install is taking a rather long time. On hour 2 right now. 

Also there are some errors randomly popping up 

```vim
Error detected while processing function <SNR>39_install_async..<SNR>39_check_loop..<SNR>39_check_output:
line   21:
E900: Invalid job id
```

## Environment Information
 * OS: Mac OSX
 * NeoVim version: NVIM v0.1.1-165-g074d3dc (compiled Jan  4 2016 11:59:01

## Provide a minimal .vimrc with less than 50 lines (Required!)
https://gist.github.com/mhartington/2bac361929a18e801106

**Comment by Shougo** [comment]
Please update dein.vim to latest version.
I think your dein.vim is old.

**Comment by mhartington** [comment]
Looks like that was it. Wonderful, love the addition of the progress at the bottom, looks great. Thanks
