### ISSUE TITLE
Why loaded vital.vim?

### ISSUE THREAD

**Issue by ryunix** [Shougo/dein.vim#120]
# Problems summary

遅延ロードを設定した`vital.vim`が`on_cmd`のコマンドを実行していないのにロードされてしまう。

## Expected

`vital.vim`を使用しているプラグインが実行された時にロードされている？ (これは、対象のプラグインが`on_cmd`でも`on_i`でも同様でした)
また、`vital.vim`を使用していないプラグインとして`calendar.vim`を選択しています。

## Environment Information

* OS: OS X v10.9 Mavericks
* Vim version: MacVim 7.4.1941

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath^=~/sample/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/sample/dein'))

call dein#add('Shougo/unite.vim',     { 'on_cmd' : [ 'Unite' ] })
call dein#add('itchyny/calendar.vim', { 'on_cmd' : [ 'Calendar' ] })
call dein#add('vim-jp/vital.vim',     { 'on_cmd' : [ 'Vitalize' ] })

call dein#end()

filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

0. echo g:dein#_plugins['vital.vim']['sourced'] " => 0
0. Calendar
0. echo g:dein#_plugins['vital.vim']['sourced'] " => 0
0. Unite
0. echo g:dein#_plugins['vital.vim']['sourced'] " => 1

## Upload the log messages by `:redir` and `:message`

None.

**Comment by Shougo** [comment]
Fixed.

**Comment by ryunix** [comment]
dein.vimを最新化し、試してみましたが直っていないように思います。

**Comment by DeaR** [comment]
軽く斜め読みしかしてないですが
vital#○○をcallした時にFuncUndefinedが発生してしまう故に
読み込まれているのでは無いかと思います
対処方法としてはvital.vimはlazy=0にするくらいしか

参考: vim-jp/issues#755
参考: http://lingr.com/room/vim/archives/2015/09/11#message-22437064

**Comment by ryunix** [comment]
参考読みました。
`vital.vim`を遅延ロード設定にするのはやめておきます。
ありがとうございました。

**Comment by Shougo** [comment]
それはバグです。修正したので dein を更新してください

**Comment by ryunix** [comment]
修正確認できました、ありがとうございます！
