### ISSUE TITLE
~/.vim is not the first in runtimepath

### ISSUE THREAD

**Issue by galou** [Shougo/dein.vim#121]
# Problems summary

`'~/.vim'` is not the first in `runtimepath`. This causes the issue for example that the spell directory is not the expected `'~/.vim/spell'` but, according to the documentation, the first writable directory in runtimepath, which is a directory managed by dein.vim.

## Expected

`'~/.vim'` should be the first in `runtimepath`.

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible

set runtimepath^=~/.vim/bundle/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.vim/bundle'))
call dein#add('Shougo/dein.vim')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. Type `:set runtimepath?`
 2. See that `~/.vim` is not the first in the list

**Comment by Shougo** [comment]
Fixed.

**Comment by galou** [comment]
Thanks a lot for fixing this so quickly. However, I had to change my `.vimrc` to have this work and thus do NOT respect the documentation.
I would also change the documentation:
```
set runtimepath^={path to dein.vim directory}
```
to
```
set runtimepath+={path to dein.vim directory}
```

**Comment by Shougo** [comment]
Thanks.  I have fixed.
