### ISSUE TITLE
Suddenly "cannot find color scheme"

### ISSUE THREAD

**Issue by skorlir** [Shougo/dein.vim#122]
# Problems summary
Installing vim-two-firewatch no longer works. It worked earlier today. I get the message that vim cannot find colorscheme now every time I start the editor.

The colorscheme did not update, though I have recently installed updates to neovim.

I have tried deleting the dein files for two-firewatch from the repos folder, but it makes no difference.

## Expected
The colorscheme should be found.

## Environment Information
 * OS: Ubuntu 16.04
 * Vim version: neovim 0.1.5-dev

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Minimal init.vim
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('rakr/vim-two-firewatch', { 'script_type': 'colors' })
call dein#end()

colors two-firewatch
```

## The reproduce ways from Vim starting (Required!)

Simply start neovim by typing `nvim` at the terminal. The colorscheme cannot be found.

## Screen shot (if possible)
![screenshot](http://i.imgur.com/FTfcA7f.png)

## Upload the log messages by `:redir` and `:message`
`:redir: gives an error, saying "missing argument."
`:message` gives

```
Error detected while processing /home/fluffywaffles/.config/nvim/init.vim:
line  169:
E185: Cannot find color scheme 'two-firewatch'
Could not resolve airline theme "twofirewatch". Themes have been migrated to git
hub.com/vim-airline/vim-airline-themes.
E475: Invalid argument: 
```

**Comment by Shougo** [comment]
```vim
call dein#add('rakr/vim-two-firewatch')
```

Please read the documentation.

```
						*dein-options-script_type*
script_type	(String)
		Specify the script type. It is useful for non-official
		categorized plugins.
		For example: "indent", "plugin", "ftplugin", ...
		Note: You must not specify it for categorized plugins.
```
