### ISSUE TITLE
Any plan to support original vim 8.0?

### ISSUE THREAD

**Issue by liweijian** [Shougo/dein.vim#125]
I don't if it is ok to post this question here, but I couldn't find a channel to ask.

Well, vim 8.0 just release, in which version, it supports

- Asynchronous I/O support, channels, JSON 
- Jobs 
- Timers 
- Partials, Lambdas and Closures 
- Packages 
- New style testing 
- Viminfo merged by timestamp 
- GTK+ 3 support 
- MS-Windows DirectX support 

Vim learned a lot from Neovim, I can't leave Neovim because I love dein.vim, deoplete and so on.

I just wondering if maybe dein.vim would support original vim 8.0?

**Comment by Shougo** [comment]
Vim8 asynchronous API is already supported.
Closing.

**Comment by kiryph** [comment]
Should dein.vim on Microsoft Windows 10 with vim8 also do updates without blocking the editor?

In my case running `:call dein#updates()` blocks the editor and I have to wait until the update is finished.

**Comment by Shougo** [comment]
@kiryph I have fixed the problem.

**Comment by kiryph** [comment]
Thanks. Right now I have check it only on vim8 on OSX and it  looks good.

I have noticed two comments in the documentation that neovim is required to have async behaviour for update or check_update:

- `dein#update()` https://github.com/Shougo/dein.vim/blob/1dd1f3e/doc/dein.txt#L178-L179
- `dein#check_update()` https://github.com/Shougo/dein.vim/blob/1dd1f3e/doc/dein.txt#L226-L230

Are they up-to-date?

**Comment by Shougo** [comment]
Thank you.  I have fixed.
