### ISSUE TITLE
Benchmark vs vim-plug

### ISSUE THREAD

**Issue by pickfire** [Shougo/dein.vim#126]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I don't see a problem here.

## Expected
Nice to see a benchmark vs vim-plug.

## Environment Information
 * OS: Linux
 * Vim version: nvim 0.1.5

**Comment by Shougo** [comment]
I have not much time.
You can create it!

**Comment by ismay** [comment]
Maybe this gist can be of help: https://gist.github.com/b4b4r07/3eccb4f8dd9438c706fe7950ef2f669f
