### ISSUE TITLE
'hook_add' function get called twice on lazy plugins

### ISSUE THREAD

**Issue by fsworld009** [Shougo/dein.vim#128]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Hi:

Looks like hook_add get called twice on lazy plugins. With the minimal script below I get two echos when I start nvim:

```
$  nvim
tern
tern
Press ENTER or type command to continue
```

If I remove the on_ft condition then only one message is shown.

## Expected
Only one "tern" message when I start nvim

## Environment Information
 * OS: Mac OSX 10.11
 * Vim version: neovim 0.1.5

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)

function! s:tern_for_vim_setup()
  echo "tern"
endfunction

call dein#add('ternjs/tern_for_vim', {
      \ 'on_ft': 'javascript',
      \ 'hook_add':function('s:tern_for_vim_setup')
      \})

call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. put the minimal script
 2. start nvim
 3. two "tern" messages are shown

**Comment by Shougo** [comment]
I have tested your minimal init.vim.
But I cannot reproduce it.
Please check your minimal init.vim.

**Comment by fsworld009** [comment]
Sorry for the trouble, I figured out it was an issue with my init.vim

**Comment by Shougo** [comment]
OK
