### ISSUE TITLE
Plugins are not updated if there are already plugins installed

### ISSUE THREAD

**Issue by crondog** [Shougo/dein.vim#13]
# Problems summary
Plugins are not updated if there are already plugins installed

## Expected
Plugins are updated

## Environment Information
 * OS: Arch Linux
 * Vim version: NVIM v0.1.3-133-g12938b8

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.config/nvim/bundle/repos/github.com/Shougo/dein.vim
call dein#begin(expand('~/.cache/dein'))
call dein#add('Shougo/dein.vim')
"call dein#add('Shougo/deoplete.nvim')
"call dein#add('Shougo/neosnippet')
"call dein#add('Shougo/neosnippet-snippets')
"call dein#add('Shougo/neoinclude.vim')
"call dein#add('zchee/deoplete-clang')
call dein#end()

```

## The reproduce ways from Vim starting (Required!)

* Remove all plugins
* Run :call dein#update() to install all your plugins
* Close nvim
* Open nvim
* :call dein#update() will now not update plugins

## Upload the log messages by `:redir` and `:message`
```
Error detected while processing function dein#update:
line    1:
E119: Not enough arguments for function: dein#install#_update
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.
I think your dein.vim is broken.  Please reinstall dein.vim.

**Comment by wsdjeg** [comment]
I also get this issue,I will try to find it out tonight

**Comment by crondog** [comment]
Ok so I removed .cache/dein and .config/nvim/bundle/repos/github.com/Shougo/dein.vim and then redownloaded dein.vim and it now works. Sorry for the noise
