### ISSUE TITLE
Why not loaded neoclojure.vim? (Specific plugin problem?)

### ISSUE THREAD

**Issue by ryunix** [Shougo/dein.vim#130]
# Problems summary

[ujihisa/neoclojure.vim](https://github.com/ujihisa/neoclojure.vim) と [thinca/vim-ref](https://github.com/thinca/vim-ref) の連携を行おうとしています。
neoclojure.vim は plugin/ を持っていないので、`dein#check_lazy_plugins()` の対象となりました。
`on_ft` を設定している場合は正常に連携できていますが、`on_ft` を設定しない場合はうまく連携できていないようです。
特定のプラグインの問題かもしれませんが、よく分かっていません。

## Expected

`on_ft` を設定している場合は、`:scriptnames` に `~/sample/dein/repos/github.com/ujihisa/neoclojure.vim/ftplugin/clojure.vim` が含まれていますが、`on_ft` を設定しない場合は、含まれていないようです。

## Environment Information

* OS: OS X v10.9 Mavericks
* Vim version: MacVim 8.0.0005

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif

set runtimepath+=~/sample/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/sample/dein'))

call dein#add('Shougo/vimproc.vim', { 'build' : 'make' })
call dein#add('thinca/vim-ref')
call dein#add('ujihisa/neoclojure.vim')
" call dein#add('ujihisa/neoclojure.vim', { 'on_ft' : [ 'clojure' ] })

call dein#end()

filetype plugin indent on

syntax enable
```

## The reproduce ways from Vim starting (Required!)

1. インサートモードで次の文字を入力する -> cons
2. ノーマルモードでKキーを押下する

## Upload the log messages by `:redir` and `:message`

None.

**Comment by ryunix** [comment]
以下のように `merged` を指定すると正常に動作しました。

```vim
call dein#add('ujihisa/neoclojure.vim', { 'merged' : 0 })
```

これは正しい使い方でしょうか？
ファイルが競合している際に有効かと思いましたが、ファイルの競合はありませんでした。
ディレクトリは競合していますが、これはマージできないのでしょうか？

[neoclojure.vim/autoload/ref at master · ujihisa/neoclojure.vim](https://github.com/ujihisa/neoclojure.vim/tree/master/autoload/ref)
[vim-ref/autoload/ref at master · thinca/vim-ref](https://github.com/thinca/vim-ref/tree/master/autoload/ref)

**Comment by Shougo** [comment]
ref の内部実装を調査したところ原因が分かりました。

ref が標準で clojure 用に定義するプラグインに clojure.vim があり、これが neoclojure の提供する neoclojure.vim と競合しています。
ref の設計上、各 filetype に一つしかプラグインを定義できないようです。
merged = 0 のときは、runtimepath の定義する順番の関係上、neoclojure で上書きされるので問題が起こらないのでしょう。

**Comment by ryunix** [comment]
なるほど、とても参考になりました。
ありがとうございます！
