### ISSUE TITLE
Non-committed changes in plugin directory repos don't have effect

### ISSUE THREAD

**Issue by NLKNguyen** [Shougo/dein.vim#131]
# Problems summary
I develop a theme directly in  the plugin directory repo stored in  `dein/repos/github.com/...`, but the changes in there don't have effect. Dein always loads the latest git commit. 

## Expected
A way to have Dein to use the current stage of the plugin directory repo without having to commit changes to the git repo.

When I use Vim with Vundle, it  doesn't have this problem.

Also, is there an alternative/preferable way to develop plugin/theme directly in the repo managed by the plugin manager?

## Environment Information
 * OS: Ubuntu 16.04.1
 * NVIM version: 0.1.6-dev
```
NVIM 0.1.6-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/build/config -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/src -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-6tzDre/neovim-0.1.5ubuntu1+git201609241332+2789+21~ubuntu16.04.1/build/include
Compiled by buildd@lgw01-40

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

## ~/.config/nvim/init.vim

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

set runtimepath+=/home/nlknguyen/.nvim/dein//repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('/home/nlknguyen/.nvim/dein/')

call dein#add('Shougo/dein.vim')
call dein#add('NLKNguyen/papercolor-theme')

call dein#end()

filetype plugin indent on
syntax enable

if dein#check_install()
  call dein#install()
endif

color PaperColor
```

##  Reproduce

 1. Startup NVIM with the installation of PaperColor theme.
 2. Delete the content of `~/.nvim/dein/repos/github.com/NLKNguyen/papercolor-theme/colors/PaperColor.vim`
 3. Re-open NVIM. The theme still loads as if the changes in step 2 don't have any effect

**Comment by Shougo** [comment]
It is feature.  You must call `dein#recache_runtimepath()` after the commit.
dein.vim does not detect the changes.

> Also, is there an alternative/preferable way to develop plugin/theme directly in the repo managed by the plugin manager?

Yes.  You should not change the installed directory.
If you need to develop plugins, you should use `dein#local()` instead.
dein.vim does not cache the directories.
