### ISSUE TITLE
Compared to vim-plug?

### ISSUE THREAD

**Issue by trusktr** [Shougo/dein.vim#135]
Hello @Shougo, could you briefly compare dein to vim-plug (if you have experience with it)? Thanks!

**Comment by Shougo** [comment]
It has many differences though...

* dein is faster than vim-plug
* dein supports more lazy features
* dein support cache
* dein merges the plugins
* dein can load local plugins
* dein can support the other VCS
* dein support the notification
* No commands

vim-plug is
* simpler than dein but less feature
* better UI?  But it creates the buffer
* complex than Vundle
* no Vim documentation.  README only
