### ISSUE TITLE
Support for git protocol

### ISSUE THREAD

**Issue by IngoHeimbach** [Shougo/dein.vim#137]
# Problems summary

Please add support for the git protocol (`git://`). Currently, dein prints a warning message at vim startup and ignores the appropriate plugin.
## Expected

If `dein#add` is called with a git protocol uri, dein should treat the uri as a valid address.
## Environment Information
- OS: Debian Linux (stretch)
- Vim version: 8.0 patches 1-22
## Provide a minimal .vimrc with less than 50 lines (Required!)

``` vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('git://ifflinux.iff.kfa-juelich.de/i.heimbach@fz-juelich.de/vim/plugins/auto_font')
call dein#end()
```
## The reproduce ways from Vim starting (Required!)
1. Just start vim without any arguments
## Upload the log messages by `:redir` and `:message`

```
[dein] Repo: git://ifflinux.iff.kfa-juelich.de/i.heimbach@fz-juelich.de/vim/plugins/auto_font The protocol "git" is unsecure and invalid.
[dein] Repo: git://ifflinux.iff.kfa-juelich.de/i.heimbach@fz-juelich.de/vim/plugins/auto_font The protocol "git" is unsecure and invalid.
```
# Possible solution

Change [this line](https://github.com/Shougo/dein.vim/blob/master/autoload/dein/types/git.vim#L82) from

``` vim
if protocol !=# 'https' && protocol !=# 'ssh'
```

to

``` vim
if protocol !=# 'https' && protocol !=# 'ssh' && protocol !=# 'git'
```

**Comment by Shougo** [comment]
"git" protocol is not encrypted.  So I reject the feature.
https://glyph.twistedmatrix.com/2015/11/editor-malware.html
If you want to install the plugin, you should host the plugin in github.
