### ISSUE TITLE
plugin doesn't load with 'on_ft' option

### ISSUE THREAD

**Issue by mattia72** [Shougo/dein.vim#140]
# Problems summary

I wrote the following line in my vimrc :
```
 call dein#add('mattia72/vim-abinitio' , { 'on_ft': ['dml', 'xfr' ]}) 
```
This plugin doesn't load if I open a file with dml or xfr extension.  

I've tried other ftplugins but they didn't worked either:
```
  call dein#add('vim-scripts/perl-support.vim', {'on_ft': ['pl', 'pm']})   
```
Plugins with 'on_cmd' option are working flowlessly eg.:
```
  " lazy load on command executed
  call dein#add('scrooloose/nerdtree', {'on_cmd': 'NERDTreeToggle'})  
```

## Expected
The vim-abinitio plugin should be loaded if I open a dml file.

## Environment Information
 * OS: Windows 7 32bit (Microsoft Windows [Version 6.1.7601])
 * Vim version:
```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 27 2016 22:04:52)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-51
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +mouse              +syntax
...
```
## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" My minimal .vimrc
if has('vim_starting')
  set nocompatible               " Be iMproved
  set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim/
endif

if dein#load_state(expand('~/.vim/bundle/'))
  call dein#begin(expand('~/.vim/bundle/'))

  "DML syntax
  call dein#add('mattia72/vim-abinitio' , 'on_ft': ['dml', 'xfr' ]}) 

  call dein#end()
endif

filetype plugin indent on         
syntax enable                     
```

## The reproduce ways from Vim starting (Required!)

 1. open a file with dml extension
 2. syntax highlight / indentation not working
 3. `:echom dein#is_sourced('vim-abinitio')` is 0
 4.  type `:call dein#source('vim-abinitio') `
 5. syntax highlight / indentation is working

## Upload the log messages by `:redir` and `:message`
not relevant

**Comment by Shougo** [comment]
on_ft is `filetype` instead of the extension.

```vim
 call dein#add('mattia72/vim-abinitio' , { 'on_ft': 'abintio' ]})
call dein#add('vim-scripts/perl-support.vim', {'on_ft': ['perl']}) 
```
