### ISSUE TITLE
git clone step needs submodule initiation

### ISSUE THREAD

**Issue by forcecore** [Shougo/dein.vim#141]
# Problems summary

When trying to install YouCompleteMe for nvim, this issue arises.

https://github.com/Valloric/YouCompleteMe/issues/582

According to the issue in YouCompleteMe plugin, the plugin manager should invoke
git submodule update --init --recursive
after cloning this repo.

## Expected

After YouCompleteme is cloned, the submodules shoud be initiated recursively aswell.

## Environment Information
 * OS: Arch Linux, as of 2016-11
 * Vim version: Neovim, 0.1.6

## Provide a minimal .vimrc with less than 50 lines (Required!)

The default .vimrc, with YouCompleteMe added

```
" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')

" Add or remove your plugins here:
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/neosnippet-snippets')
call dein#add('junegunn/seoul256.vim')

let g:ycm_python_binary_path = 'python3'
call dein#add('Valloric/YouCompleteMe')


" You can specify revision/branch/tag.
call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

" Required:
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

Add YouCompleteMe to the plugins list.
Try installing the plugin with
call dein#install()

dein will install the plugin but without the submodules.

## Upload the log messages by `:redir` and `:message`
:redir
E475: Invalid argument:

:message
"~/.config/nvim/init.vim" 53L, 1036C
Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/home/users/0x/.config/nvim/.dein/autoload/../python/ycm/base.py", line 27, in <module>
    from ycm import vimsupport
  File "/home/users/0x/.config/nvim/.dein/autoload/../python/ycm/vimsupport.py", line 35, in <module>
    from ycmd import user_options_store
  File "/home/users/0x/.config/nvim/.dein/python/ycm/../../third_party/ycmd/ycmd/user_options_store.py", line 28, in <module>
    from frozendict import frozendict
ImportError: No module named frozendict
E475: Invalid argument:
Press ENTER or type command to continue

**Comment by Shougo** [comment]
dein.vim supports submodule installtion....
OK.  I will test it.

**Comment by Shougo** [comment]
dein.vim executes `git clone --recursive` instead of `git submodule update --init --recursive`.

**Comment by Shougo** [comment]
Fixed.
