### ISSUE TITLE
Cannot start nvim

### ISSUE THREAD

**Issue by wmonk** [Shougo/dein.vim#143]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When opening neovim I get these errors:
```
Error detected while processing function dein#begin[1]..dein#util#_begin[20]..dein#util#_get_runtime_path[5]..dein#util#_get_cache_path:
line    9:
E739: Cannot create directory /Users/willm/.config/nvim/init.vim: file already exists
[dein] Invalid runtimepath.
Error detected while processing /Users/willm/.config/nvim/init.vim:
```
Your latest commits seem to be related. This has only caused since updating all plugins (including dein.vim) in the last couple of days.

## Expected
Neovim works, and loads all plugins. I reset back to commit `3b53b882e50de39e8dc3f54acced34e11821d1e1` and everything works well 👍 .

## Environment Information
 * OS: OSX
 * Vim version: Neovim 0.1.6

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
" Setup dein  ---------------------------------------------------------------{{{
  if &compatible
    set nocompatible
  endif

  set runtimepath+=/Users/willm/.config/nvim/repos/github.com/Shougo/dein.vim
  call dein#begin('/Users/willm/.config/nvim/')
  call dein#add('Shougo/dein.vim')

  " syntax
```

## The reproduce ways from Vim starting (Required!)

 1. nvim

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/175278/20303775/efa22d42-ab24-11e6-990f-aca2e485f434.png)

**Comment by Shougo** [comment]
Fixed.
