### ISSUE TITLE
YouCompleteMe doesn't work with latest dein anymore

### ISSUE THREAD

**Issue by cryptomilk** [Shougo/dein.vim#144]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

:messages
Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/home/asn/.vim/bundle/.cache/.vimrc/.dein/autoload/../python/ycm/base.py", line 27, in <module>
    from ycm import vimsupport
  File "/home/asn/.vim/bundle/.cache/.vimrc/.dein/autoload/../python/ycm/vimsupport.py", line 35, in <module>
    from ycmd import user_options_store
  File "/home/asn/.vim/bundle/.cache/.vimrc/.dein/python/ycm/../../third_party/ycmd/ycmd/user_options_store.py", line 28, in <module>
    from frozendict import frozendict
ImportError: No module named frozendict

Is it possible that it is completely confused by all the directories now?

$ l .vim/bundle
drwxr-xr-x  3 asn users   20 Nov 15 22:41 .cache/
drwxr-xr-x 24 asn users 4096 Nov 15 10:40 .dein/
drwxr-xr-x  3 asn users   20 Jun 21 12:09 .vim/
drwxr-xr-x  5 asn users   62 Nov 15 22:41 .vimrc/
drwxr-xr-x  4 asn users   50 Nov 15 22:42 repos/

I see full .dein plugin directory several times in the following locations:

~/.vim/bundle/.cache/.vimrc/.dein
~/.vim/bundle/.dein
~/.vim/bundle/.vimrc/.dein

Why are there so many copies of the same files?

## Environment Information
 * OS: openSUSE
 * Vim version: 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
https://xor.cryptomilk.org/setup/.vimrc


Thanks!

**Comment by cryptomilk** [comment]
gladiac on freenode

**Comment by Shougo** [comment]
Please update dein.vim and reinstall YouCompleteMe.
Because, YouCompleteMe installation is broken.

**Comment by cryptomilk** [comment]
```
[dein] Update started: (2016/11/17 08:32:06)
[dein] /home/asn/.vim/bundle/repos/github.com/Valloric/YouCompleteMe
[dein] Process timeout.
[dein] Error installing plugins:    
[dein]   YouCompleteMe                       
[dein] Please read the error message log with the :message command.
```

The issue is that dein kills the installation. Setting

```
let g:dein#install_process_timeout = 240
```

fixes the issue. You might want to increase the timeout or document that you need to set a higher value for YouCompleteMe.

**Comment by Shougo** [comment]
OK.  I will update the documentation.

**Comment by epiloque** [comment]
@Shougo thank you, latest update fixes this.

**Comment by igoralmeida** [comment]
Sorry to bump this but I don't think my question requires a new issue. I noticed that to make YCM work with rust/racer I had to manually copy these:
`~/dev/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycm_core.so`
`~/dev/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/third_party/racerd`

to their appropriate locations inside `~/dev/dein/.cache/init.vim/.dein/third_party/ycmd{/,third_party/}`.

How does the caching mechanism work, then? I don't think I opened nvim before YCM was finished with `./install.py  --racer-completer` (though I might have).

**Comment by Shougo** [comment]
@igoralmeida You must execute `:call dein#recache_runtimepath()` or set `'merged': 0` as the option or use `build` option.

**Comment by ertoorule** [comment]
> :call dein#recache_runtimepath(

Shougo my man!!!!!
