### ISSUE TITLE
Runtimepath updated is not output to :messages

### ISSUE THREAD

**Issue by ryunix** [Shougo/dein.vim#146]
# Problems summary

Runtimepath updated が :messages に出力されません。
:Unite dein/log には出力されています。

## Environment Information

- OS: macOS Sierra (v10.12)
- Vim version: MacVim 8.0.0075

## The reproduce ways from Vim starting (Required!)

1. :call dein#update()

## Screen shot (if possible)

![2016-11-20 13 04 35](https://cloud.githubusercontent.com/assets/7754313/20460324/9af8583c-af22-11e6-8a94-0b9f8d839d52.png)

**Comment by ryunix** [comment]
:call dein#recache_runtimepath() を実行した後も :messages に表示されませんでした。

**Comment by Shougo** [comment]
仕様です。メッセージ出ないように変更されたため。

**Comment by ryunix** [comment]
確認ありがとうございます。
これからは :Unite dein/log を使用するようにします。
