### ISSUE TITLE
What is the best practise if I want to make some change for a certain plugin

### ISSUE THREAD

**Issue by chemzqm** [Shougo/dein.vim#148]
Sometimes I need to modify a plugin a bit to fit my needs, but with dein, I can't just change the code as I did before. 
I know I can make it a local plugin or fork the repo to my own account, but then I would loss the power of dein to upgrade the plugin and I have to manage the upgrade by myself, is there a better approach?

**Comment by symbolix** [comment]
I have this in my start-up configuration:

```vimL
" Force local dev version.
let g:enable_dev_banana = 1

if g:enable_dev_banana
    call dein#local('/Users/me/dev/vim', {
                \ 'merged' : 0,
                \ }, ['banana'])
else
    call dein#add('https://myrepo/banana.git', {
                \ 'normalized_name' : 'banana',
                \ 'merged' : 0,
                \ })
endif
```

This is elegant enough and I have never had issues with this approach.

**Comment by Shougo** [comment]
> I know I can make it a local plugin or fork the repo to my own account, but then I would loss the power of dein to upgrade the plugin and I have to manage the upgrade by myself, is there a better approach?

Just commit the change.
dein.vim uses `git pull --rebase`.  So your change is rebased.
