### ISSUE TITLE
[temp] When dein#install(), C directory is made

### ISSUE THREAD

**Issue by hokorobi** [Shougo/dein.vim#15]
# Problems summary
dein#install() 実行時、カレントディレクトリに C というディレクトリが作成される。

Windows でしか発生しない現象なのかもしれません。
Neobundle でも発生していました。
Vim は M ドライブにインストールしていますが、最小構成の vimrc を作って dein#install() したところ、M が作成されました。最初の一文字はドライブ名由来ですね。

## Expected
ディレクトリが作成されない。

## Environment Information
 * OS: Windows7 64bit
 * Vim version:  vim74-kaoriya-win64-20160124
 * git version: 2.7.0 msys2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath+=$VIM/temp/repos/github.com/Shougo/dein.vim
call dein#begin(expand('$VIM/temp'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/neco-syntax')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

```
gvim.exe -u _vimrc_dein_issue15 -U NONE
:call dein#install()
```

**Comment by Shougo** [comment]
Hm...
Cannot reproduce the problem.

Question:

1: the directory is removed after the installtion?

2: please create minimal init.vim.  I will test it.

3: please test it on the other environment.

**Comment by hokorobi** [comment]
1: No, left in it.
2, 3: I will have a try at it.

**Comment by hokorobi** [comment]
再現する vimrc を作って、最初の書き込みを更新しておきました。
git 実行時に作成されているような気がしてきました。
もう少し調べます。

**Comment by hokorobi** [comment]
git clone --recursive https://github.com/hoge/vim-plugin "C:/path/to/vim-plugin" が実行されると作成されるようです。
コマンドプロンプトで実行しても同様でした。

Git for Windows などの git だと動きが違うのかもしれません。

**Comment by Shougo** [comment]
了解です。では、git の仕様みたいなので close します

**Comment by hokorobi** [comment]
clone 先のパスを Windows の場合は \ 区切りにすることはできないでしょうか？

**Comment by Shougo** [comment]
仕様が大幅に変更されるのでやりたくないです。
なぜですか？

**Comment by hokorobi** [comment]
\ 区切りのパスであれば、今回のようなディレクトリは作成されなくなるからです。
仕様の大幅変更をおしてまでは要望しません。
ありがとうございました。
