### ISSUE TITLE
dein does not automatically delete commented out packages

### ISSUE THREAD

**Issue by smackesey** [Shougo/dein.vim#152]
# Problems summary

If you install a plugin with `dein#add('some/repo')` and then later comment out the line, `dein` will not detect the changes to the vimrc and therefore not recache.

## Expected

Commenting out the line should cause a recache.

## Environment Information
 * OS: macOS 10.12.1
 * Vim version: 8.0.106

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('Shougo/neosnippet')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. run the above vimrc
 2. comment out the `call dein#add('Shougo/neosnippet')`
 3. rerun the above vimrc

There will be no recaching.

**Comment by wsdjeg** [comment]
dein merge plugin by default. and the cache will not autoupdate. if you do not want to merge plugin, use {'merge':0}

**Comment by Shougo** [comment]
I cannot reproduce the problem.
The recache works.
I think your dein.vim is old.
