### ISSUE TITLE
Plugin filename collisions

### ISSUE THREAD

**Issue by NullInfinity** [Shougo/dein.vim#153]
# Problems summary
It seems `dein.vim` has problems if two plugins contain a file with the same name. For example, I use `vimwiki` and `taskwiki` which both provide `ftplugin/vimwiki.vim`. Dein caches only one of these two files in the `.dein` folder.

## Expected
Both files should be sourced. I tested this working correctly with `plug.vim` and `vim-pathogen`.

## Environment Information
 * OS: Gentoo Linux
 * Vim version: nvim-0.1.7

## Provide a minimal .vimrc with less than 50 lines (Required!)
(Adjust runtime path as necessary.)
```vim
if &compatible
  set nocompatible
endif

set runtimepath^=/tmp/nvim/dein/repos/github.com/Shougo/dein.vim
call dein#begin(expand('/tmp/nvim/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('tbabej/taskwiki') "
call dein#add('vimwiki/vimwiki', {'rev': 'dev'})
call dein#end()

filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

 1. Install `vimwiki` and `taskwiki` with `call dein#install()`
 2. Set filetype: `set ft=vimwiki`
 3. Attempt to use a Vimwiki command, e.g. `VimwikiFollowLink`
 4. Command fails since only the taskwiki ftplugin was loaded.

Can also do

```sh
diff /tmp/nvim/dein/.dein/ftplugin/vimwiki.vim /tmp/nvim/dein/repos/github.com/tbabej/taskwiki/ftplugin/vimwiki.vim
```
That is, only the taskwiki ftplugin is sourced, and the vimwiki file is ignored.

**Comment by Shougo** [comment]
```vim
call dein#add('tbabej/taskwiki', {'merged': 0}) "
call dein#add('vimwiki/vimwiki', {'rev': 'dev', 'merged': 0})
```

**Comment by NullInfinity** [comment]
Sorry -- should have read the manual... Thanks :+1:
