### ISSUE TITLE
Fugitive doesn't work properly with on_cmd

### ISSUE THREAD

**Issue by waivek** [Shougo/dein.vim#155]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

The tim-pope extension - [fugitive](http://github.com/tpope/vim-fugitive) does not work immediately with 'on_cmd'. If I have the command `Gstatus` mapped to on_cmd in Fugitive, when I first write `:Gstatus` I get the following error message-

    [dein] command Gstatus is not found.

After that if I run `:e` which reloads the current buffer, then running `:Gstatus` gives me the correct output and the plugin has loaded. This is true for all fugitive commands

## Expected

`:Gstatus` and all git commands mapped to on_cmd should load fugitive without any requirement for a reload.

## Environment Information
 * OS: Windows 10 64-Bit
 * Vim version:8.0 (gvim)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
    call dein#add('tpope/vim-fugitive', {'on_cmd' : 'Gstatus'})
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. Open any file in a .git repository
 2. Run `:Gstatus` and get the error
 3. Reload with the command `:e`
 4. Run `:Gstatus` and the plugin has now been loaded.

## Screen shot (if possible)
![fugitive](https://cloud.githubusercontent.com/assets/5134623/21194414/ef283b2a-c255-11e6-8421-8efae35f3028.gif)

## Upload the log messages by `:redir` and `:message`

```
".vimrc" 6L, 345C
[dein] command Gstatus is not found.
".vimrc" 6L, 345C
```

**Comment by Shougo** [comment]
```vim
	call dein#add('tpope/vim-fugitive', {
	    \ 'on_cmd' : 'Gstatus', 'augroup': 'fugitive'
	    \ })
```

**Comment by waivek** [comment]
I'm sorry, that doesn't fix the bug.

![fugitive](https://cloud.githubusercontent.com/assets/5134623/21223435/1c75aa30-c2ed-11e6-9070-9638f2a85e4e.gif)

**Comment by Shougo** [comment]
Fixed again.

**Comment by waivek** [comment]
Thank you so much. It works now. To anyone browsing this issue the following line

    call dein#add('tpope/vim-fugitive', {'on_cmd' : 'Gstatus'})

will be enough. Don't use 'augroup'

**Comment by Shougo** [comment]
Because, dein sets the augroup automatically.
