### ISSUE TITLE
Regarding disabling and uninstalling plugins

### ISSUE THREAD

**Issue by hilman-dayo** [Shougo/dein.vim#156]
I am new in installing  plugins for my nvim and everything looks so weird to me, so, I hope anyone can help me.

How to actually disable and/or uninstall a plugin?

What I did is, I just comment out a `dein#add()` of a certain plugin if I want to disable it, and if I want to uninstall it, I will also delete the plugin file. Is this correct?

And how about `dein#disable()`? How it different from just commenting out a plugin's `dein#add()`?

Also, another little question. Does `dein#add('Shougo/den.vim')` and `dein#add('absolute/path/to/dein.vim/`) means the same thing?

Thanks.

**Comment by Shougo** [comment]
> What I did is, I just comment out a dein#add() of a certain plugin if I want to disable it, and if I want to uninstall it, I will also delete the plugin file. Is this correct?

After the comment out, 

```vim
call map(dein#check_clean(), "delete(v:val, 'rf')")
```

> And how about dein#disable()? How it different from just commenting out a plugin's dein#add()?

The comment out is better.  But `dein#disable()` works after `dein#add()`.

```vim
Also, another little question. Does dein#add('Shougo/den.vim') and dein#add('absolute/path/to/dein.vim/) means the same thing?
```

No.  `absolute path` just uses the repository as plugin.

**Comment by shmup** [comment]
Hey @Shougo I know this is closed but I just need to know what I could possibly be doing wrong.

I have installed vim sneak, which does a thing to `s`. 

I then removed the line from my config and did a `call map(dein#check_clean(), "delete(v:val, 'rf')")`

I also checked the repos and see that it really was removed.

But the plugin still exists. 

What _might_ I be doing wrong?

**Comment by Shougo** [comment]
@shmup You must execute `:call dein#recache_runtimepath()` after the plugin is removed.
