### ISSUE TITLE
Freezing 'dd' if map 'ds' in dein

### ISSUE THREAD

**Issue by Mephistophiles** [Shougo/dein.vim#157]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Freezing 'dd' if 

`call dein#add('tpope/vim-surround', {'on_map': ['cs', 'ys', 'ds']})`

## Environment Information
 * OS: ArchLinux
 * Vim version: 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible              " be iMproved, required
filetype off                  " required
set runtimepath+=~/.vim/bundle/dein.vim/

call dein#begin(expand('~/.vim/bundle/'))
let g:dein#types#git#clone_depth = 1


call dein#add('tpope/vim-surround', {'on_map': ['cs', 'ys', 'ds']})

call dein#end()
filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. Press 'dd' (freezing 1 second)
 2. If press ds freezing stopped.

## Upload the log messages by `:redir` and `:message`
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test_vim-surround.vim" 13L, 343C

**Comment by Mephistophiles** [comment]
:nmapn  ["          *@:call search('\%(^\s*".*\n\)\%(^\s*"\)\@!', "bW")<CR>
n  []          *@m':call search('^\s*endf*\%[unction]\>', "bW")<CR>
n  [[          *@m':call search('^\s*fu\%[nction]\>', "bW")<CR>
n  ]"          *@:call search('^\(\s*".*\n\)\@<!\(\s*"\)', "W")<CR>
n  ][          *@m':call search('^\s*endf*\%[unction]\>', "W")<CR>
n  ]]          *@m':call search('^\s*fu\%[nction]\>', "W")<CR>
n  cs          * :<C-U>call dein#autoload#_on_map('cs', 'vim-surround','n')<CR>
n  ds          * :<C-U>call dein#autoload#_on_map('ds', 'vim-surround','n')<CR>
n  gx            <Plug>NetrwBrowseX
n  ys          * :<C-U>call dein#autoload#_on_map('ys', 'vim-surround','n')<CR>
n  <Plug>NetrwBrowseX * :call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : '<cfile>')),netrw#CheckIfRemote())<CR>

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
Fixed.

**Comment by Mephistophiles** [comment]
Thanks!
