### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by matrinox** [Shougo/dein.vim#158]
I'm just curious what qualities make dein.vim faster than NeoBundle? Is this package manager faster than the included package manager in neovim? I did a test with 90+ plugins and it take 45s vs. 24s. Am I doing something wrong here?

**Comment by Shougo** [comment]
> Is this package manager faster than the included package manager in neovim? 

I think dein is the fastest plugin manager if it is configured properly.
Of course, you have miss-configured, it is slower.

Hint:
My neovim startuptime is less than 20ms.
It impossible using other plugin managers.

**Comment by wsdjeg** [comment]
[time.txt](https://github.com/Shougo/dein.vim/files/659500/time.txt)

it is my start time, I use 180 plugins.

**Comment by matrinox** [comment]
I see so it's faster load not necessarily faster download/update
