### ISSUE TITLE
Confusion in setting up dein

### ISSUE THREAD

**Issue by hilman-dayo** [Shougo/dein.vim#159]
Another question regarding `dein#add` (I am a beginner, pardon me).

I realised in your instruction where you said to put something like this in the `.vimrc`/`init.vim`.

```
call dein#begin({path to plugin base path directory})

call dein#add({path to dein.vim directory}) 
call dein#add('Shougo/neocomplete.vim')
...

call dein#end()
```

I also saw someone did something like this.

```
call dein#begin({path to plugin base path directory})

call dein#add('Shougo/dein.vim') 
call dein#add('Shougo/neocomplete.vim')
...

call dein#end()
```

where the `Shougo/dein.vim` is used instead of the `path/to/the/dein.vim/directory`. What is the difference and which is the right way?

**Comment by Shougo** [comment]
> where the `Shougo/dein.vim` is used instead of the `path/to/the/dein.vim/directory`. What is the difference and which is the right way?

Of course it is not same.
`Shougo/dein.vim` is the remote repository.
`path/to/the/dein.vim/directory` is the local installed repository.

You have installed dein.vim manually.
So, `path/to/the/dein.vim/directory` is better.
