### ISSUE TITLE
E464 Ambiguous use of user-defined command

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#16]
# Problems summary
lazy load plugin get error E464,can not reproduce in neobundle.

## Expected
command works well

## Environment Information
 * OS: ubuntu 
 * Vim version: latest(neovim)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('Shougo/vimfiler.vim',{'lazy' : 1 , 'on_cmd' : 'VimFiler'})
    noremap <silent> <F3> :VimFiler<CR>
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. star vim
 2. type <F3> twice
 3. baz

**Comment by wsdjeg** [comment]
Fixed by `call dein#update()` ,I think it is due to I change the plugin to lazy,but do not delet it from ~/cache/.dein/

**Comment by weilbith** [comment]
@wsdjeg This seems to work for me just temporally. I'm a bit confused about using `depends`, cause it seems not to work, but if I call `call dein#recache_runtimepath()` manually it works for that session. But I guess this is a fault of my configuration. Be sure I will get it one day.
