### ISSUE TITLE
Dein and vim-gitgutter on_event

### ISSUE THREAD

**Issue by Mephistophiles** [Shougo/dein.vim#160]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

vim-gitgutter not loaded after start vim.

## Expected

It must sleep 500 ms (updatetime variable = 500) and be loaded.

## Environment Information
 * OS: Arch Linux
 * Vim version: 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible              " be iMproved, required
filetype off                  " required
set runtimepath+=~/.vim/bundle/dein.vim/

call dein#begin(expand('~/.vim/bundle/'))
let g:dein#types#git#clone_depth = 1

call dein#add('airblade/vim-gitgutter', {'on_event': 'CursorHold'})

call dein#end()
filetype plugin indent on

syntax on


```

## The reproduce ways from Vim starting (Required!)

 1. Open file (vim-gitgutter not loaded)
 2. Wait 10 seconds (not loaded)

## Screen shot (if possible)
with on_event Cursor_Hold
![tmux_002](https://cloud.githubusercontent.com/assets/4850908/21418453/6f205146-c832-11e6-8aa1-839e6350b75a.png)

without on_event:

![tmux_003](https://cloud.githubusercontent.com/assets/4850908/21418458/75e46634-c832-11e6-92d5-5f896c2cf896.png)

## Upload the log messages by `:redir` and `:message`

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
E325: ATTENTION
"test" 4L, 20C
```

**Comment by Shougo** [comment]
Reproduced.
The buffer is not tracked to vim-gitgutter.
But I cannot enable the track using the functions and variables and commands.
Gave up.
You should ask the problem to the authror.
I think vim-gitgutter does not support the lazy loading.
