### ISSUE TITLE
When using on_path, syntax highlighting isn't enabled on first file opened if specific plugins are loaded

### ISSUE THREAD

**Issue by glacambre** [Shougo/dein.vim#161]
# Problems summary
After starting neovim, when trying to open a file, syntax highlighting will not be enabled if plugins such as vim-closer or vim-sleuth are enabled and loaded using a specific on_path rule. It will be enabled when a second file is opened.

## Expected
Syntax highlighting should be enabled when the first file is opened.

## Environment Information
 * OS: Gentoo GNU/Linux 4.4.26
 * Vim version: NVIM v0.2.0-150-g33319b1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/tmp/bundle/repos/github.com/Shougo/dein.vim
call dein#begin("/tmp/bundle")
call dein#add('https://github.com/rstacruz/vim-closer.git', {'on_path': '^\(.*term:\/\/\)\@!.*$'}) " Don't load if only opening a terminal buffer
call dein#add('https://github.com/tpope/vim-sleuth.git', {'on_path': '^\(.*term:\/\/\)\@!.*$'}) " Don't load if only opening a terminal buffer
call dein#end()
filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)
```sh
nvim -u /tmp/init.vim /tmp/init.vim
```
And to enable syntax highlighting:
```vim
:e
```

## Screen shot (if possible)
Nothing interesting to see.

## Upload the log messages by `:redir` and `:message`
Nothing interesting either.

**Comment by Shougo** [comment]
I will test it.
