### ISSUE TITLE
Why is filetype plugin indent on required?

### ISSUE THREAD

**Issue by nhooyr** [Shougo/dein.vim#163]
No error or problem, just wondering why?

**Comment by Shougo** [comment]
Because, dein.vim disables filetype plugin.
If you need to enable filetype plugin, you must enable it.

**Comment by nhooyr** [comment]
But why does dein.vim disable filetype plugin?

**Comment by Shougo** [comment]
dein changes `runtimepath`.
If filetype plugin feature is enabled, new runtimepath filetype plugins are not sourced.
