### ISSUE TITLE
deoplete disabled after adding or removing a plugin in init.vim

### ISSUE THREAD

**Issue by nhooyr** [Shougo/dein.vim#166]
# Problems summary
After adding or removing a plugin in my init.vim and reloading neovim, deoplete becomes disabled until I call `deoplete#enable` even though `g:deoplete#enable_at_startup = 1`.

## Expected
Deoplete should not become disabled.

## Environment Information
 * OS: macOS Sierra 10.12.2
 * Vim version: neovim 0.1.7

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('dag/vim-fish')
call dein#add('Shougo/deoplete.nvim')
call dein#end()
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from Vim starting (Required!)
https://asciinema.org/a/b0tjoh86zs820y6etvd8er140

So first I show you that deoplete works fine. Then I remove the vim-fish plugin from the init.vim, reload neovim and then deoplete stops working until I call `deoplete#enable`.

**Comment by Shougo** [comment]
Fixed.
