### ISSUE TITLE
statusline function

### ISSUE THREAD

**Issue by nhooyr** [Shougo/dein.vim#169]
I don't like having my command line bombarded with many messages by dein. I'd prefer it if I could set it up so that when I update/install a message comes up in my statusline that an installation/update is in progress and then once it is installed, another messages comes up that the installation/update is complete. vim-go has a similar feature and I really like it https://github.com/fatih/vim-go/blob/d7c628ff228c2e6a4d4d5808f198471a775cf8b5/doc/vim-go.txt#L955

**Comment by nhooyr** [comment]
Forget to mention, I should also be be able to silence the information messages from dein then.

**Comment by Shougo** [comment]
> Forget to mention, I should also be be able to silence the information messages from dein then.

let g:dein#install_progress_type = 'none'

**Comment by nhooyr** [comment]
I set it to that but it's still outputting everything. setting it to echo doesn't seem to do anything. From https://github.com/Shougo/dein.vim/search?utf8=%E2%9C%93&q=install_progress_type it doesn't look like dein is using the variable.

**Comment by Shougo** [comment]
https://github.com/Shougo/dein.vim/blob/b71eee788067ea926a419f2cfd4e97f7d08f024a/autoload/dein/install.vim#L815

Please read it.
I have tested it.  It works.

**Comment by nhooyr** [comment]
Oh, I wanted
```
let g:dein#install_progress_type = 'none'
let g:dein#install_message_type = 'none'
```

But, it still shows `[dein] Update started: (2017/01/03 00:47:44)` and `[dein] Done: (2017/01/03 00:47:46)`. Since I want that stuff to appear in my statusline, there should also be a way to disable them.

**Comment by Shougo** [comment]
@nhooyr I have fixed the problem.  Please test the latest vimproc branch.

**Comment by nhooyr** [comment]
It's beautiful!

**Comment by nhooyr** [comment]
Could I make it so that the progress bar doesn't show up? Only `updating...` and `finished` messages?

**Comment by Shougo** [comment]
No.

**Comment by nhooyr** [comment]
Yea, sorry I just realized my mistake. Also, the statusline function should have a timeout period after which it gives an empty string. Just like vim-go

**Comment by Shougo** [comment]
Fixed.

**Comment by nhooyr** [comment]
Right now, it's instantly emptied. In vim-go, it becomes empty after 60 seconds so that you have a chance to look at it.

**Comment by nhooyr** [comment]
well actually nevermind, that's not necessary, once it's disappeared, you know it's done.

Thanks @Shougo
