### ISSUE TITLE
async build

### ISSUE THREAD

**Issue by nhooyr** [Shougo/dein.vim#170]
# Problems summary
The build script is not run asynchronously so it hangs up the entire editor. This is very annoying.

I remember you mentioning that this would be very difficult to implement, why?

**Comment by Shougo** [comment]
Because, the build process is executed after installation process.

**Comment by nhooyr** [comment]
I can try implementing this myself. Can you point me to where I should look?

**Comment by Shougo** [comment]
`dein#install#_build()`

**Comment by Shougo** [comment]
I think you can create async process by post_update hook.

**Comment by nhooyr** [comment]
oh, right. I'll try that first.

**Comment by nhooyr** [comment]
Seems to work fine.
