### ISSUE TITLE
throw an error if a plugin that is not lazy depends on a lazy plugin

### ISSUE THREAD

**Issue by nhooyr** [Shougo/dein.vim#175]
So imagine you have the following TOML

```toml
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni#input_patterns = {}
'''

[[plugins]]
repo = 'dag/vim-fish'
depends = 'deoplete.nvim'
hook_source = '''
let g:deoplete#omni#input_patterns.fish = '\w+'
augroup fish_ft
  autocmd!
  autocmd FileType fish setlocal keywordprg=:Man
augroup END
'''
```

vim-fish isn't lazy, so it will always load deoplete.nvim even though deoplete.nvim is configured to be a lazy loading plugin. It will also not load the `hook_source` of deoplete.nvim. This configuration should throw an error.

**Comment by nhooyr** [comment]
I noticed something really weird. 

Here is the init.vim

```vim
set runtimepath^=/tmp/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('/tmp/dein')
  call dein#begin('/tmp/dein')
  call dein#load_toml('/tmp/dein.toml')
  call dein#end()
  call dein#save_state()
endif
```

dein.toml is the file given above.

Weirdly enough, deoplete works fine the first time neovim is launched, but every time after that, deoplete is not automatically enabled.

Here is a video https://asciinema.org/a/7jemrxquyzqavt8dy0asdbo3w

This seems to only happen with `dein#load_state`, if you remove that if statement then deoplete always loads fine.

**Comment by Shougo** [comment]
I have implemented the feature.
Please create new issue if you have en-counted the problem.
