### ISSUE TITLE
dein.vimが動かない

### ISSUE THREAD

**Issue by yoshinaga-hiroyuki** [Shougo/dein.vim#176]
# Problems summary
昨日
:call dein#update()
を実行してから、dein.vim が動作しなくなってしまいました

他のプラグインの影響かと思い、一度下記のように削除してから再実行を試みましたが
$ rm -r ~/.vim/bundle
$ mkdir -p ~/.vim/bundle/repos/github.com/Shougo/dein.vim
$ git clone https://github.com/Shougo/dein.vim ~/.vim/bundle/repos/github.com/Shougo/dein.vim
$ vim
[dein] Not installed plugins: ['vimproc.vim']
[dein] Update started: (2017/01/05 13:57:49)
[dein] Vim(let):E121: 未定義の変数です: v:t_list
[dein] function dein#install[1]..dein#install#_update[28]..<SNR>16_update_loop[5]..<SNR>16_install_async[5]..<SNR>16_check_loop[5]..<SNR>16_sync[39]..<SNR>16_init_process[40]..<SNR>16_init_job[10]..dein#job#start, 行 22
となります

~/.vim/rc/dein.toml
に
[[plugins]]
repo = 'Shougo/context_filetype.vim'
を追記すると、( ~/.vim/rc/dein.toml の最初の状態は、後術します)
function dein#end[1]..dein#util#_end[39]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[18]..<SNR>17_copy_files[6]..dein#install#_copy_directories[43]..dein#install#_system[10]..11[4]..dein#job#start の処理中にエラーが検出されました:
行   22:
E121: 未定義の変数です: v:t_list
E15: 無効な式です: type(a:args) == v:t_list ? a:args : [&shell, &shellcmdflag, a:args]
function dein#end[1]..dein#util#_end[39]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[18]..<SNR>17_copy_files[6]..dein#install#_copy_directories の処理中にエラーが検出されました:
行   43:
E171: :endif がありません
function dein#end[1]..dein#util#_end[39]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[18]..<SNR>17_copy_files の処理中にエラーが検出されました:
行    6:
E170: :endfor がありません
function dein#end[1]..dein#util#_end の処理中にエラーが検出されました:
行   39:
E171: :endif がありません
/home/user/.vim/vimrc の処理中にエラーが検出されました:
行   26:
E171: :endif がありません
となります

どこを直せばよいのでしょう?

## Environment Information
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
$ uname -a
Linux naonari-note 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 22:32:42)
適用済パッチ: 1-1829
追加拡張パッチ: 8.0.0056

## Provide a minimal .vimrc with less than 50 lines (Required!)
"\~/.vim/vimrc
if has('vim_starting')
  if &compatible
    set nocompatible
  endif
  let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.vim') : $XDG_CACHE_HOME
  let s:dein_dir = s:cache_home . '/bundle'
  let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
  set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim
  if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)
    let g:rc_dir = expand('~/.vim/rc')
    let s:toml = g:rc_dir . '/dein.toml'
    let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'
    call dein#load_toml(s:toml, {'lazy': 0})
    call dein#load_toml(s:lazy_toml, {'lazy': 1})
    call dein#end()
    call dein#save_state()
    if dein#check_install()
      call dein#install()
    endif
  endif
endif
filetype plugin indent on
\"----------------------------------------------------------------------
\# ~/.vim/rc/dein.toml
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

## The reproduce ways from Vim starting (Required!)
概要のとおりです

## Upload the log messages by `:redir` and `:message`
概要のとおりです

**Comment by yoshinaga-hiroyuki** [comment]
Gitだから元に戻せることに今更ながらに気付き、
~/.vim/bundle/repos/github.com/Shougo/dein.vim$ git checkout HEAD^ .
を実行したところ、動くようになりました

**Comment by Shougo** [comment]
修正しました。確認してください。

**Comment by yoshinaga-hiroyuki** [comment]
まっさらにして試してみましいかのとおりです
~$ git clone https://github.com/Shougo/dein.vim ~/.vim/bundle/repos/github.com/Shougo/dein.vim
Cloning into '/home/user/.vim/bundle/repos/github.com/Shougo/dein.vim'...
remote: Counting objects: 4135, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 4135 (delta 1), reused 0 (delta 0), pack-reused 4127
Receiving objects: 100% (4135/4135), 779.05 KiB | 258.00 KiB/s, done.
Resolving deltas: 100% (2383/2383), done.
Checking connectivity... done.
~$ vim
~$ gedit ~/.vim/rc/dein*.toml
~$ git clone https://github.com/Shougo/vimproc.vim ~/.vim/bundle/repos/github.com/Shougo/vimproc.vim
Cloning into '/home/user/.vim/bundle/repos/github.com/Shougo/vimproc.vim'...
remote: Counting objects: 5451, done.
remote: Total 5451 (delta 0), reused 0 (delta 0), pack-reused 5451
Receiving objects: 100% (5451/5451), 1.54 MiB | 357.00 KiB/s, done.
Resolving deltas: 100% (3081/3081), done.
Checking connectivity... done.
~$ cd ~/.vim/bundle/repos/github.com/Shougo/vimproc.vim
~/.vim/bundle/repos/github.com/Shougo/vimproc.vim$ make
make -f make_unix.mak
make[1]: ディレクトリ '/home/user/.vim/bundle/repos/github.com/Shougo/vimproc.vim' に入ります
cc -W -O2 -Wall -Wno-unused -Wno-unused-parameter -std=gnu99 -pedantic -shared -fPIC  -o lib/vimproc_linux64.so src/proc.c -lutil
make[1]: ディレクトリ '/home/user/.vim/bundle/repos/github.com/Shougo/vimproc.vim' から出ます
~/.vim/bundle/repos/github.com/Shougo/vimproc.vim$ cd -
/home/user
~$ gedit ~/.vim/rc/dein*.toml
~$ vim
で処理が帰ってきません
途中で、geditを起動していますが、dein.vimとvimproc.vim以外をコメント・アウトし忘れていたので、それをするためです

topコマンドを見てやると、
Tasks: 260 total,   2 running, 257 sleeping,   0 stopped,   1 zombie
%Cpu(s):  4.6 us, 21.8 sy,  0.0 ni, 73.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8078196 total,  3613800 free,  2120112 used,  2344284 buff/cache
KiB Swap:  8290300 total,  8290300 free,        0 used.  5292536 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 4281 hiroyuki  20   0  172420  15248  11584 R 100.0  0.2   9:38.63 vim
ということで、CPUコアを一つ完全に専有したままです

本日は取り敢えず寝て、明日また以前のに戻すとどうなるか試してみます

**Comment by Shougo** [comment]
修正しました。dein.vim をアップデートしてください。
残念ながら、Vim 7.4 での job サポートが中途半端なので、Vim 7.4 では並列化をサポートできなくなりました。
並列化するには Vim のバージョンを上げてください。

**Comment by yoshinaga-hiroyuki** [comment]
問題なく動作することを確認しました
私の環境依存かも知れず、エラー・ログがないので大丈夫か心配していましたが、動作するようになってよかったです
どうもありがとうございました

P.S
vim をソースから入手しようかと思いましたが、「Ubuntuの公式レポジトリのまま使うユーザのトラブルもそれなりに有用だろうな」とも思い、一先ず 7.4の公式のまま使おうと思います
