### ISSUE TITLE
README: hard to understand installation and principial instruction and

### ISSUE THREAD

**Issue by oroulet** [Shougo/dein.vim#179]
README says following:
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
 $ sh ./installer.sh {specify the installation directory}

What installation directory? is it .config/nvim ? or somethig completely arbitrary. I think that adding an example might be enough

From the README I also kind of understand that the idea is to install all new plusig to a directory called .config/nvim/Shougo. But I am not really sure. The README is missing some information about the main idea of this software

**Comment by Tr4pSt3R** [comment]
@oroulet please have a look at this pull request which updates the README with the instructions you are looking for.

Please let me know if it's of any help to you along with any recommendations you may have.

[Update README with installation instructions from NeoBundle to Dein](https://github.com/Shougo/dein.vim/pull/180/commits/eaf59db777554de637f4e8ebac31fe80465db2af)

**Comment by oroulet** [comment]
Thanks for the update @Tr4pSt3R . But I still thing it is missing background/fundamental behaviour informations. I just found out that the plugins are downloaded automatically from github!?!?! This should be explained in the first line of README. Where else are plugins looked for? Are the plugins automatically updated? What is that installation directory? It seems the installation directory is a directory structures when plugins are automatically downloaded. What about local plugins not on github?

**Comment by christiangenco** [comment]
I have the same question, and @Tr4pSt3R's updated instructions don't help.

What am I supposed to put for the installation directory?

**Comment by Shougo** [comment]
I have not much time to answer them.

But ...

> What that am I supposed to put for the installation directory?

You must define the installation directory.
dein.vim has not define the default directory.
Because, it depends on user usecase.

**Comment by oroulet** [comment]
In the code, this directory is called plugin_dir. It looks like it is where all plugins/packages will be downloaded inclusive dein. But I gave it up and use pathogen. It is simple and well documented.

**Comment by Tr4pSt3R** [comment]
TBH @christiangenco  && @oroulet I gave up on Dein to use @Shougo's NeoBundle which is far easier to use. I may return at some point to improve the documentation on Dein when I figure it out.

**Comment by Shougo** [comment]
> But I gave it up and use pathogen. It is simple and well documented.

pathogen..?
If you need to just pathogen, dein.vim is not needed.
dein.vim have been built to resolve more complex problems.

I will update the documentation.

**Comment by wsdjeg** [comment]
@Shougo as I know, pathogen is not plugin manager, it is just a runtimepath manager.

**Comment by Shougo** [comment]
Yes.
