### ISSUE TITLE
Question about dein#tap() 

### ISSUE THREAD

**Issue by PaBLoX-CL** [Shougo/dein.vim#18]
I've seen some vimrc's and a lot of them that use neobundle, or yours even that uses dein... "wrapping" plugins configuration like:

```vim
if dein#tap('unite.vim') "{{{
  " The prefix key.
  nnoremap    [unite]   <Nop>
  xnoremap    [unite]   <Nop>
  nmap    ;u [unite]
  xmap    ;u [unite]

  nnoremap <silent> ;b
        \ :<C-u>Unite -buffer-name=build`tabpagenr()` -no-quit build<CR>
  …
endif
```

It's strange, because if the plugin is added to dein, why I would want to check again if it exists? Or is it that dein loads the value between that `if … endif` only when the plugin is actually being loaded?

**Comment by wsdjeg** [comment]
because maybe you do not download,and rtp do not change before dein#end()

**Comment by Shougo** [comment]
Yes.

**Comment by wsdjeg** [comment]
I need write something about why hooks.
in vundle or vim-plugin you can not put you config and plugin together,and if you disable you plugin or  do not install you plugin ,you config still be loaded.
example
```vim
set nocompatible
syntax on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Shougo/unite.vim'
" you can not put you confg here ,and you can not call 
"unite's func here because rtp is changed after
" end(),but with the help of hooks ,we can put config 
"and plugin together,it looks better,and if we do 
"not want to use some plugin,just need to disable plugin , 
"and the config will not be loaded,that is 
"why I using dein or neobundle
call vundle#end()
filetype plugin indent on
```
for dein
```vim
call dein#add('Shougo/deoplete.nvim')
if dein#tap('deoplete.nvim') && has('nvim')
	  let g:deoplete#enable_at_startup = 1
	  execute 'autocmd MyAutoCmd User' 'dein#source#'.g:dein#name
	        \ 'source ~/.vim/rc/plugins/deoplete.rc.vim'
endif
```

**Comment by PaBLoX-CL** [comment]
But most times, plugins are saved in another file, like in a toml one. So, you are still going to put the configuration after `dein#end()`. ([bling/dotvim](https://github.com/bling/dotvim/blob/master/vimrc) or [shougo's dotfiles](https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/plugins.rc.vim) for example).

afaik, the `tap` thing make sense when using lazy plugins right? I mean, those configurations (inside tap blocks) are being loaded only when the plugin is actually loaded. For the rest, I don't understand what could be the benefit.

**Comment by Shougo** [comment]
> afaik, the tap thing make sense when using lazy plugins right? I mean, those configurations (inside tap blocks) are being loaded only when the plugin is actually loaded. For the rest, I don't understand what could be the benefit.

It works if the plugin is lazy loaded.

**Comment by PaBLoX-CL** [comment]
Thanks, I understand now. So using `tap` won't give any advantage when using plugins are not being lazily loaded?

**Comment by Shougo** [comment]
> Thanks, I understand now. So using tap won't give any advantage when using plugins are not being lazily loaded?

Yes, it has the advantage.
It works like `installed`.

**Comment by PaBLoX-CL** [comment]
So it's always useful even when plugins that aren't being lazy loaded?

**Comment by Shougo** [comment]
Yes
