### ISSUE TITLE
issue with check install.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#184]
ref: https://github.com/SpaceVim/SpaceVim/issues/157
init.vim
```viml
set runtimepath+=~/.cache/vimfiles/repos/github.com/Shougo/dein.vim/
call dein#begin('~/.cache/vimfiles')

call dein#add('Shougo/dein.vim')
call dein#add('SpaceVim/vim-luacomplete')

call dein#end()

silent! let flag = dein#check_install()
if flag
    augroup SpaceVimCheckInstall
        au!
        au VimEnter * call dein#install()
    augroup END
endif
filetype plugin indent on
syntax enable
```
reproduce step:
1. go to home `cd ~`
2. clone vim-luacomplete : `git clone https://github.com/SpaceVim/vim-luacomplete.git ~/SpaceVim/vim-luacomplete/`
3. clone vim-luacomplete to repos: `git clone https://github.com/SpaceVim/vim-luacomplete.git ~/.cache/vimfiles/repos/github.com/SpaceVim/vim-luacomplete/`
4. clone dein to repos: `git clone https://github.com/Shougo/dein.vim.git ~/.cache/vimfiles/repos/github.com/Shougo/dein.vim/`
5. then open nvim in home `nvim -u init.vim`. you will see checkinstall always return 1, and every time open nvim, will startting installation.

**Comment by Shougo** [comment]
Fixed.

**Comment by hongjiujin** [comment]
Hi Shougo,

I met below issue, can you give some suggestion? I have tried several times, still remain the same. 

[tommy@tommy-VirtualBox ~]$vim
Error detected while processing /home/tommy/~/.cache/vimfiles/.cache/vimrc/.dein/plugin/dwm.vim:
line   19:
E117: Unknown function: unite#custom_action
Press ENTER or type command to continue

[dein] ( 1/63) |Lightning           | ['git', 'clone', '--recursive', 'https://github.com/wimstefan/Lightnin.../.cache/vimfiles/repos/github.com/wimstefan/Lightning']

**Comment by wsdjeg** [comment]
It is issue with unite dwm, plugin should not use autoload functions from other plugins in plugin/*

**Comment by hongjiujin** [comment]
Hi wsdjeg,

So i need to report a "new issue" to trace ?

**Comment by Shougo** [comment]
Yes.  It is not dein issue.
