### ISSUE TITLE
Cannot find color scheme 'molokai' when I type 'view' in RHEL6

### ISSUE THREAD

**Issue by dlintw** [Shougo/dein.vim#185]
# Problems summary

Cannot find color scheme 'molokai' when I type 'view' in RHEL6
/bin/view is a symbolic link to /bin/vi

## Expected

When I launch `view` or `vi`, it won't show error message.

## Environment Information (Required!)

 * dein.vim version(SHA1): commit 68ceee0342260fb843457e2f09ff5cb653c59121

 * OS: RHEL 6.7

 * Vim/neovim version:
/bin/vi --version 
  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 11:13:18)
  Small version without GUI.  Features included (+) or not (-):
/usr/bin/vim --version
  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 11:14:07)
  Huge version without GUI.  Features included (+) or not (-):
## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
call dein#begin(path)
call dein#add('~/.vim/dein/repos/github.com/Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim', {'build' : 'make'})

call dein#add('tomasr/molokai')
call dein#end()
colorscheme molokai
```

## The reproduce ways from Vim starting (Required!)

$ view
Error detected while processing /home/myhome/.vimrc:
line  266:
E185: Cannot find color scheme 'molokai'

**Comment by Shougo** [comment]
view is vi alias.
And your vi is Small version.
It is not supported.

```
/bin/vi --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 11:13:18)
Small version without GUI. Features included (+) or not (-):
```

Additional note:
Do you know what is Small version of Vim?
It disables `all` Vim script features.
Any of plugins does not work.
All of `call` commands are just ignored.
So, `colorscheme molokai` will be error.
