### ISSUE TITLE
Install plugins fails on Windows

### ISSUE THREAD

**Issue by kiran-kp** [Shougo/dein.vim#188]
# Problem summary
Installing any plugin on Windows fails with error
`[dein] fatal: could not create leading directories of '"C:/Users/kiran/AppData/Local/nvim/dein/repos/github.com/Shougo/vimproc.vim"': Invalid argument`

## Expected
Plugin installs correctly

## Environment Information (Required!)
 * dein.vim version(SHA1): git commit: ce4522bc1841fc5ec041986384ab65c0475195c5
 * OS: Windows 10
 * Vim/neovim version: nvim v0.2.0-563-gce453df3

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath^=C:\Users\kiran\AppData\Local\nvim\dein\repos\github.com\Shougo\dein.vim
call dein#begin(expand('~/AppData/Local/nvim/dein/'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim', {'build' : 'make'})
call dein#end()
if dein#check_install()
    call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)
 1. Launch nvim to trigger dein auto-install

## Upload the log messages by `:redir` and `:message` (if errored)
```
[dein] Not installed plugins: ['vimproc.vim']
[dein] Update started: (2017/02/10 00:14:04)
[dein] C:/Users/kiran/AppData/Local/nvim/dein/repos/github.com/Shougo/vimproc.vim
[dein] Maybe wrong username or repository.
[dein] fatal: could not create leading directories of '"C:/Users/kiran/AppData/Local/nvim/dein/repos/github.com/Shougo/vimproc.vim"': Invalid argument
[dein] Error installing plugins:
[dein]   vimproc.vim
[dein] Please read the error message log with the :message command.
[dein] Rename failed.
[dein] src=C:/Users/kiran/AppData/Local/nvim/dein/.cache/init.vim/.dein
[dein] dest=C:/Users/kiran/AppData/Local/nvim/dein/.cache/init.vim/temp/14152/20170210001404
[dein] Done: (2017/02/10 00:14:04)
```

**Comment by kiran-kp** [comment]
Issue #136 seems related

**Comment by xelra** [comment]
I can confirm that Dein doesn't seem to work on Windows. As soon as I run `:call dein#install()`, Neovim crashes.
