### ISSUE TITLE
Escaping issue on Windows

### ISSUE THREAD

**Issue by xelra** [Shougo/dein.vim#189]
# Problems summary
On Windows the runtimepath doesn't seem to be properly constructed. Looks like an escaping issue.

## Environment Information (Required!)

 * dein.vim version(SHA1): e8034fa32b044f9cd0ca956f8a6e0b62e174be53

 * OS: Windows

 * Vim/neovim version: 0.2.0-532-g67356f29

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=C:\Users\xelra\AppData\Local\nvim\dein\repos\github.com\Shougo\dein.vim

" Required:
if dein#load_state('~/AppData/Local/nvim/dein')
	call dein#begin('~/AppData/Local/nvim/dein')

	" Let dein manage dein
	" Required:
	call dein#add('Shougo/dein.vim')

	" Required:
	call dein#end()
	call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

"End dein Scripts-------------------------

let g:python_host_prog  = 'C:\Users\xelra\AppData\Local\Programs\Python\Python27\python.exe'
let g:python3_host_prog = 'C:\Users\xelra\AppData\Local\Programs\Python\Python36\python.exe'

```

## The reproduce ways from Vim starting (Required!)

`:set runtimepath?`

## Screen shot (if possible)
![untitled](https://cloud.githubusercontent.com/assets/908568/22932421/2699f9ca-f2c8-11e6-96ae-7959ca82a93c.png)

## Upload the log messages by `:redir` and `:message` (if errored)
```
Error detected while processing pre-vimrc command line:
E518: Unkown option: Files
```

**Comment by bounceme** [comment]
`Program Files`

**Comment by xelra** [comment]
As discussed on IRC, it's not a Dein issue, but a Neovim-Qt issue.

I was only testing against a clean Neovim with `nvim -u NORC`, which didn't show the problem. When deleting the `init.vim` completely though, the problem shows itself.
