### ISSUE TITLE
Cannot install dein

### ISSUE THREAD

**Issue by nvanggaard** [Shougo/dein.vim#191]
# Problems summary
After running installer.sh and I am opening nvim it throws an error.

 * dein.vim version(SHA1):
N/A

 * OS:
OS: Arch Linux
Kernel: 4.9.8-1

 * Vim/neovim version:
Neovim version 0.1.7

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/nichlas/.config/nvim/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/nichlas/.config/nvim/dein')
  call dein#begin('/home/nichlas/.config/nvim/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/nichlas/.config/nvim/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  "call dein#add('Shougo/neosnippet.vim')
  2call dein#add('Shougo/neosnippet-snippets')

  " You can specify revision/branch/tag.
  2call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

```

## The reproduce ways from Vim starting (Required!)
Open nvim

## Upload the log messages by `:redir` and `:message` (if errored)
Error detected while processing /home/nichlas/.config/nvim/init.vim:
line    9:
E117: Unknown function: dein#load_state
E15: Invalid expression: dein#load_state('/home/nichlas/.config/nvim/dein')

**Comment by ChristianSch** [comment]
Same for me on macOS Sierra and Neovim 0.1.7:
```
Error detected while processing /Users/nexus/.config/nvim/init.vim:
line    7:
E117: Unknown function: dein#load_state
E15: Invalid expression: dein#load_state('~/.dein')
```

**Comment by Shougo** [comment]
dein.vim is not installed in `/home/nichlas/.config/nvim/dein/repos/github.com/Shougo/dein.vim`.

**Comment by joshnabbott** [comment]
@Shougo I had the same faulty config which I believe I copy and pasted from the post install hook. That might need to be updated.

**Comment by Shougo** [comment]
The configuration is already updated.

**Comment by Shougo** [comment]
> @Shougo I had the same faulty config which I believe I copy and pasted from the post install hook. That might need to be updated.

installer.sh works for me.
If it does not work, please provide the reproduce-able instruction.
If you does not, I will ignore your report.

Or you can fix/send the PR for it.  This is open source product.

**Comment by joshnabbott** [comment]
@Shougu you’re right. I did end up getting it working but can double-check the output of installer.sh and open a PR if it needs updating.
