### ISSUE TITLE
Maybe README is a little confusing

### ISSUE THREAD

**Issue by hiro2016** [Shougo/dein.vim#196]
First thank you for creating this excellent plugin.

I hate to complain but README.md was a little confusing.
Particularly this part:

> set runtimepath+={path to dein.vim directory}

What is actually required is not a directory but a path to the dein.vim file. 
I could not figure this out and I was getting the following error:
     
    d@dynabook:~/.config/nvim$ nvim dein.conf 
    Error detected while processing /home/d/.config/nvim/dein.conf:
    line   10:
    E117: Unknown function: dein#load_state
    E15: Invalid expression: dein#load_state('/home/d/nvim/plugins')

Since the install.sh prints the necessary configuration now, maybe you should only mention that in your README.md.

**Comment by wsdjeg** [comment]
`{path to dein.vim directory}` is the path where you clone dein, just add dein to rtp, so that you can use autoload function.

**Comment by hiro2016** [comment]
What an embarrassment!! 
"dein.vim" is a directory!! Not a file...wow,  so obvious!! 

Since init.vim had "vim" as an extension, I was wrongly assuming dein.vim is a file.
Thanks for the tip wsdjeg.

**Comment by Himura2la** [comment]
No installation guide for Windows?

**Comment by Shougo** [comment]
> No installation guide for Windows?

You can create it.

**Comment by TamaHobbit** [comment]
> > No installation guide for Windows?
> 
> You can create it.

Dein doesn't seem to work on Windows. The readme should just state this. Although it is possible to install dein on Linux and then copy over the dein directory, so that the same vimrc can be used on Linux as on windows. As long as you don't (un)install anything, Dein doesn't break anything.

**Comment by Shougo** [comment]
> Dein doesn't seem to work on Windows.

dein.vim has very huge user bases.
But I don't get the error.

Fortunately, you can research the problem.
It is open source.

I need Windows maintainer for dein.vim.
