### ISSUE TITLE
dein.vim does not load some lazy plugins

### ISSUE THREAD

**Issue by delphinus** [Shougo/dein.vim#197]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Some lazy plugins will not be loaded because duplicated filetype setting in vim.

* `scriptnames` output with `lazy` option: https://gist.github.com/delphinus/34fc54ada72588a1f746dad63ded468f
* `scriptnames` output without `lazy` option: https://gist.github.com/delphinus/d7e060ee911d7c6b36ffe5d54e1ffc08

[tsuquyomi][t] is a plugin for editing TypeScript (`*.ts`) that has plugin & ftplugin. It has also ftdetect for `*.ts`, but `*.ts` is detected as XML filetype [by original Vim filetype.vim][v].

[t]: https://github.com/Quramy/tsuquyomi

[v]: https://github.com/vim/vim/blob/036986f1507d223549d110af300144468bd3a1f7/runtime/filetype.vim#L2492

For this reason, dein.vim loads not TypeScript ftplugin but XML one, I think.

(But without `lazy`, both XML and TypeScript filetypes are loaded. It has no serious problem, but unexpected)

## Expected

loaded (only) TypeScript ftplugin successfully

## Environment Information (Required!)

 * dein.vim version(SHA1): b3f786f93d512aec6dd2ac21d092ea242a4ee954

 * OS: macOS Sierra 10.12.3

 * Vim/neovim version: Vim 8.0.0473

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:dein_dir = '/tmp/.cache/dein'
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath^=' . s:dein_repo_dir

call dein#begin(s:dein_dir)
call dein#add('Shougo/vimproc.vim', {'build': 'make'})
call dein#add('Quramy/tsuquyomi', {'lazy': 1})
" call dein#add('Quramy/tsuquyomi')
call dein#end()

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

1. `rm -fr /tmp/.cache && git clone https://github.com/Shougo/dein.vim /tmp/.cache/dein/repos/github.com/Shougo/dein.vim`
2. `vim -N -u ./minimal-vimrc -U NONE -i NONE sample.ts`

```typescript
// sample.ts
const hoge = 'hogehoge';
console.log(hoge);
```

## Screen shot (if possible)

none

## Upload the log messages by `:redir` and `:message` (if errored)

above

**Comment by Shougo** [comment]
This is not dein.vim problem.
tsuquyomi should provide after/ftdetect to overwrite Vim default ftdetect settings.
