### ISSUE TITLE
Running plugin :call dein#update() from shell

### ISSUE THREAD

**Issue by fazlearefin** [Shougo/dein.vim#199]
I want to **update** plugins directly from the shell, without opening vim. I tried this

```
vim "+call dein#update()" +qall
```

But every time it reaches the end of the vim window (see attached screenshots), it asks for user input to continue updating the rest of the plugins. Is there a way to continue updating without asking for user input?

![1](https://cloud.githubusercontent.com/assets/1625934/24331261/24713b08-127c-11e7-9cef-afc5170e1fd6.png)
![2](https://cloud.githubusercontent.com/assets/1625934/24331262/24719c56-127c-11e7-9c76-8e77cbc24c10.png)

**Comment by Shougo** [comment]
```
	$ vim -c "try | call dein#update() | finally | qall! | endtry" \
	-N -u $VIMRC -U NONE -i NONE -V1 -e -s
```
