### ISSUE TITLE
Cannot use vital.vim and other plugins using vital.vim

### ISSUE THREAD

**Issue by delphinus35** [Shougo/dein.vim#20]
# Problems summary

I cannot use original `vital.vim` with vital-based plugins, such as `vim-quickrun`.

## Expected

* can use pure `vital.vim` & vital-based plugins.

## Environment Information
 * OS: Mac OS X El Capitan
 * Vim version: MacVim 7.4.1425

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')

call dein#begin(s:dein_dir)
call dein#add('vim-jp/vital.vim')
call dein#add('thinca/vim-quickrun')
call dein#end()

if dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

1. `rm -fr ~/.cache/dein`
2. `git clone https://github.com/Shougo/dein.vim ~/.cache/dein/repos/github.com/Shougo/dein.vim`
3. `vim -N -u /path/to/minimal-vimrc -U NONE -i NONE`
4. `:echo vim#of('vital').import('Prelude').is_number(123)`
5. It says error below.

  ```
  E716: Key not present in Dictionary: is_number(123)
  E15: Invalid expression: vital#of('vital').import('Prelude').is_number(123)
  Press ENTER or type command to continue
  ```

## Upload the log messages by `:redir` and `:message`

`:message` log

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Not installed plugins:  ['vital.vim', 'vim-quickrun']
[dein] Runtimepath updated: (2016/02/28 13:03:28)
E716: Key not present in Dictionary: is_number(123)
E15: Invalid expression: vital#of('vital').import('Prelude').is_number(123)

Press ENTER or type command to continue
```

**Comment by delphinus35** [comment]
I wondered that I should post to `vital` repo or here...

But it has no problem in NeoBundle, I think it is a dein.vim bug.

**Comment by Shougo** [comment]
https://github.com/vim-jp/vital.vim/pull/401

It is vital.vim problem.

**Comment by Shougo** [comment]
Fixed.
Please update vital.vim

**Comment by delphinus35** [comment]
found fixed. thx!
