### ISSUE TITLE
hook_addで関数を定義するとdeinが起動時に止まる

### ISSUE THREAD

**Issue by u10e10** [Shougo/dein.vim#201]
# Problems summary
hook_addで関数を定義するとdeinが起動時に止まります。

vim8と現時点で[最新](https://github.com/neovim/neovim/tree/18e7d552008b92dd3ecd42bf6855530838fd22ab)のNeovimでは動作したのでNeovim0.1.7のバグだと思いますが一応Issue立てました。 

## Environment Information (Required!)

 * dein.vim version(SHA1): 56eb35a ~ 3def3da

 * OS: ArchLinux

 * Vim/neovim version: NVIM 0.1.7

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let $CACHE = expand('~/.cache')
execute 'set runtimepath^=' . expand('$CACHE/dein') . '/repos/github.com/Shougo/dein.vim'
call dein#begin(expand('$CACHE/dein'), expand('<sfile>'))
call dein#add('Shougo/dein.vim', {'hook_add': "function! OhMyGod()\n endfunction"})
call dein#end()
```

## The reproduce ways from Vim starting
上記の設定で起動すると出力は何もなく停止します。

**Comment by lo48576** [comment]
Neovim 0.1.6 でも再現しました。

## 環境
- dein.vim 3def3dafdd36a552341fb8b5180cee24c26e3368
- OS: gentoo linux (amd64)
- Vim/neovim version: NVIM 0.1.7, NVIM 0.1.6

minimal `.vimrc` (というか `init.vim`)は u10e10 さんのものと同じです。

**Comment by u10e10** [comment]
確認しました。
ありがとうございます!
