### ISSUE TITLE
lazy + on_cmdで定義したコマンドに関数の引数を渡せない

### ISSUE THREAD

**Issue by uplus** [Shougo/dein.vim#203]
# Problems summary
lazy+on_cmdで定義したダミーコマンドでは、コマンド引数を`<q-args>`で扱っているためa:やl:の変数が渡せません。

## Expected
遅延読み込みのコマンドにa\:やl\:の変数を渡したい

## Environment Information 

 * dein.vim version(SHA1): 358a3fe

 * OS: Arch

 * Vim/neovim version: 0.1.7

## Provide a minimal .vimrc
```vim
execute 'set runtimepath^=' . expand('~/.cache/dein') . '/repos/github.com/Shougo/dein.vim'
call dein#begin(expand('~/.cache/dein'), expand('<sfile>'))
call dein#add('rbtnn/vimconsole.vim', {
      \ 'lazy': 1,
      \ 'on_cmd': 'VimConsoleLog'})
call dein#end()

function! Foo(arg) abort
  VimConsoleLog a:arg
endfunction
```

## The reproduce ways from Vim starting (Required!)

 1. startup
 2. \:call Foo('hello')

##  \:messages

```text
Error detected while processing function Foo[1]..dein#autoload#_on_cmd:
line   13:
E121: Undefined variable: a:arg
E116: Invalid arguments for function vimconsole#log
```

**Comment by Shougo** [comment]
申し訳ありませんが、この問題には対応できません。
コマンドがどの時点で引数を評価するかどうかはコマンドの実装に依存するからです。
コマンドの引数を dein 側で評価してしまうと、他のコマンドで問題となります。
このためだけにdein側に専用機能を追加するのは違うと考えています。

**Comment by uplus** [comment]
了解しました。こちらで対応します。
