### ISSUE TITLE
omnisharp vim が動作しない

### ISSUE THREAD

**Issue by nasu-tomoyuki** [Shougo/dein.vim#204]
# omnisharp vim が動作しない

## Environment Information

 * dein.vim version(b90b19be63384567e86f1a6436b778476f383aa6):

 * OS: OS X El Capitan

 * Vim/neovim version: Vim 8.0

## .vimrc

```vim
syntax on
filetype plugin indent on


let g:rc_dir = expand('~/.vim/rc')
let s:dein_dir = expand('~/.vim/dein')
" dein.vim 本体
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)

  call dein#add('Shougo/dein.vim')
  call dein#add('Shougo/vimproc.vim')
  call dein#add('Shougo/unite.vim')
  call dein#add('tpope/vim-dispatch')
  call dein#add('OmniSharp/omnisharp-vim', {'on_ft':'cs'})

  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif


filetype plugin indent on


augroup omnisharp_commands
    autocmd!

	let g:OmniSharp_selector_ui = 'unite'
	let g:OmniSharp_server_type = 'v1'

augroup END
```

## 再現方法

 1. Vim で .cs ファイルを開く
 2. 本来読み込まれるはずの omnisharp vim が読み込まれない

## 回避方法

dein.vim の設定前に filetype することが悪さをしているようで、 2 行目の `filetype plugin indent on` を削除すれば問題を回避できます。

## 最後に

.vimrc の記述ミスではありますが、ご報告として issue を上げさせていただきました。

**Comment by Shougo** [comment]
dein.vim が最新版ではないようです。
最新版ならコードが違うので再現しないはずです。

**Comment by nasu-tomoyuki** [comment]
ご確認ありがとうございます。

手元の OS X El Capitan では最新の 4c00c1f46376777750b10e8df681d38a609577e0 でも再現するので環境に依存するようですね。

再現できる環境を docker で作成しました。文末の Dockerfile を使うと ubuntu:16.04 のイメージを構築します。

再現手順は以下のとおりです。

1. イメージをビルド
 * $ docker build -t test_env .
1. イメージからコンテナを起動
 * $ docker run -it test_env
1. 起動したコンテナの中に上記の .vimrc を作成
1. Vim を起動し、プラグインのダウンロードが終わったら終了
1. プラグインをビルド
 * $ cd ~/.vim/dein/repos/github.com/Shougo/vimproc.vim && make
 * $ cd ~/.vim/dein/repos/github.com/OmniSharp/omnisharp-vim/server && xbuild
1. 適当な .cs ファイルを開いて omnisharp vim が動作しないことを確認
 * 例えば ~/.vim/dein/repos/github.com/OmniSharp/omnisharp-vim/server/OmniSharp/Bootstrapper.cs を開く
 * 本来であれば omnisharp vim が起動するので :OmniSharp* 系のコマンドを使えるはず
1. .vimrc から 2 行目 `filetype plugin indent on` を削除し、再度 .cs を開いて omnisharp vim が起動することを確認


以下、 Dockerfile です。

```Dockerfile
FROM ubuntu:16.04


RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y vim vim-nox-py2

RUN apt-get install -y apt-file
RUN apt-file update
RUN apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:ermshiperete/monodevelop
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
RUN apt-get update
RUN apt-get install -y mono-xbuild mono-complete libunwind-dev

RUN mkdir -p /root/.vim/rc/

CMD ["bash"]


```

**Comment by Shougo** [comment]
再現しました。バグなので修正します。
