### ISSUE TITLE
Do not load plugin on particular filetypes.

### ISSUE THREAD

**Issue by d0u9** [Shougo/dein.vim#205]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

`on_ft` option gives the ability to source a plugin when specific filetypes are matched. However, sometimes we want to load plugins when specific filtypes are NOT matched.

## Expected

Do not load specific plugins when file type are listed in a list.

## Environment Information (Required!)

 * dein.vim version(SHA1): 4c00c1f

 * OS: Linux Arch

 * Vim/neovim version: NVIM v0.1.7

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if dein#load_state(expand(g:plugin_path))
    call dein#begin(expand(g:plugin_path), expand('<sfile>:p'))

    call dein#add('Shougo/deoplete.nvim',
            \ { 'name': 'deoplete',
            \   'on_if': '&ft != "c"' })

    call dein#end()
    call dein#save_state()
endif
```

## The reproduce ways from Vim starting (Required!)

Type something which can trigger the auto completion. the `deoplete` still works.

**Comment by Shougo** [comment]
This is not dein.vim work.
You should disable the plugin on particular filetypes by the plugin's methods.
For example, deoplete has `b:deoplete_disable_auto_complete` feature.
