### ISSUE TITLE
RFC: Provide a string for the 'statusline' similar to ale or fugitive

### ISSUE THREAD

**Issue by kiryph** [Shougo/dein.vim#206]
The plugins ale and fugitive provide following functions which return a string suitable for the `'statusline'` of vim

- fugitive: `%{fugitive#statusline()}`
- [ale](https://github.com/w0rp/ale#5iv-how-can-i-show-errors-or-warnings-in-my-statusline) `%{ALEGetStatusLine()}`

Would you consider adding a similar function to dein.vim?

IMHO it should return the number of outdated plugins and the total number of plugins managed by dein.vim. Most importantly it should not trigger anything since the statusline is updated quite often. It should only return internal variables of dein which should be defined by `dein#check_install()`. A user has to call it manually or add it to startup or an event (possibly triggered after certain periods of time).

**Comment by Shougo** [comment]
I don't want to add the feature.
To implement it is not no cost.

**Comment by kiryph** [comment]
I am not sure what you mean by 
>To implement it is not no cost.

Are you refering to your personal development time or that this might have an impact on the redraw of the status line.

You've already implemented the function `dein#check_update()`. I was expecting that this has the purpose to report if updates are availabe
```
							*dein#check_update()*
dein#check_update([{plugins}])
		Check the plugins update.
		{plugins} is the plugins name list to check.
		If you omit it, dein will check all plugins update.
		Note: If you are using neovim or Vim 8.0+, it runs
		asynchronously.
```
So counting the number of plugins which could be updated does not sound too complicated and costly. This could easily be saved in a global variable.

I would add this myself but I do not understand your code in this respect. I have searched `autoload/install.vim` for the term `'check_update'` to see where I could count outdated plugins.
Apparently, you invoke a `'get_fetch_remote_command'` instead of a sync. Most promising looks like adding this counter to `s:check_output(context, process)`:

```
    call s:log(s:get_plugin_message(plugin, num, max, 'Updated'))
    let g:dein_outdated += 1
```

**Comment by Shougo** [comment]
If you send the PR, I will check the implementation.
But I don't want to add the API.
