### ISSUE TITLE
What is wrong with my .vimrc? 

### ISSUE THREAD

**Issue by lucciisgithub** [Shougo/dein.vim#207]
OS: Kali Linux 
Problem: vim does not pick up the dein plugin, 
Here is my   .vimrc

 if &compatible
  set nocompatible
endif
set runtimepath+={/root/.vim/vplug/repos/github.com/Shougo$

if dein#load_state({/root/.vim/vplug/repos/github.com/Shou$

  call dein#begin({/root/.vim/vplug/repos/github.com/Shoug$

  call dein#add({/root/.vim/vplug/repos/github.com/Shougo}$

  call dein#add('Shougo/neocomplete.vim')
  ...

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

**Comment by concatime** [comment]
It shoulds be like this
>set runtimepath+=~/.vim/vplug/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.vim')
  call dein#begin('~/.vim/vplug/')
  
  call dein#add('~/.vim/vplug/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/neocomplete.vim')
  call dein#add('racer-rust/vim-racer')
  call dein#add('rust-lang/rust.vim')
  
  call dein#end()
  call dein#save_state()
endif
