### ISSUE TITLE
dein#clear_state() does not delete the state file when g:dein#cache_directory is set

### ISSUE THREAD

**Issue by brglng** [Shougo/dein.vim#211]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When `g:dein#cache_directory` is set, `dein#clear_state()` does not delete the state file.

## Expected
The state file is deleted by `dein#clear_state()`.

## Environment Information (Required!)

 * dein.vim version(SHA1): 54dd253d49ed17a9beb69177f70a567038b9ba3f

 * OS: Ubuntu GNOME 16.04

 * Vim/neovim version: Vim 8.0.558

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:dein#install_process_timeout = 3600
let g:dein#cache_directory = $HOME . '/.cache/dein'
set runtimepath+=$HOME/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state($HOME . '/.cache/dein')
  call dein#begin($HOME . '/.vim/dein')
  call dein#add($HOME . '/.vim/dein/repos/github.com/Shougo/dein.vim')
  ...
  call dein#end()
  call dein#save_state()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. Start Vim and install the plugins using `dein#install()`;
 2. Run `:call dein#clear_state()`;
 3. Check if the file `~/.cache/dein/state_vim.vim` is deleted.

**Comment by Shougo** [comment]
Reproduced.  It is bug.

**Comment by brglng** [comment]
Thank you. It works now.
