### ISSUE TITLE
Install procedure is not clear

### ISSUE THREAD

**Issue by opensamba** [Shougo/dein.vim#212]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Is not clear how the vimrc should be
I'm trying to setup my vimrc file, but I've this error:
```
~ » vim .vimrc 
Error detected while processing /home/samba/.vimrc:
line   32:
E15: Invalid expression: /home/samba/.vim/plugins})
E116: Invalid arguments for function dein#load_state({/home/samba/.vim/plugins})
E15: Invalid expression: dein#load_state({/home/samba/.vim/plugins})
Press ENTER or type command to continue
```

## Expected
  - I expect to run the install.sh script and have a dir installed in ~/.vim/plugins or something
  - I expect to have the vimrc configured or at least an example in the docs about how this should be

## Environment Information (Required!)

 * dein.vim version(SHA1):
how can I get a sha1 ? do you want a sha1sum or what?

 * OS:
archlinux

 * Vim/neovim version:

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" map
map <silent> <C-N> :set invhlsearch<CR>
map <f5> :w<CR>:!bash %<CR>
map <f6> :w<CR>:!python %<CR>
map <f7> :w<CR>:!ruby %<CR>

" from:https://github.com/Shougo/dein.vim
if &compatible
  set nocompatible
endif
set runtimepath+={/home/samba/.vim/plugins/dein.vim}

if dein#load_state({/home/samba/.vim/plugins})
  call dein#begin({/home/samba/.vim/plugins})
  call dein#add({/home/samba/.vim/plugins/dein.vim})
  call dein#add('Shougo/neocomplete.vim')
"  ...

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. vim [filename]
 2. get the error
 3. continue and ignore de dein error

## Upload the log messages by `:redir` and `:message` (if errored)

```

**Comment by Shougo** [comment]
Please study Vim script.

```vim
    set runtimepath+={path to dein.vim directory}
```

It means:

```vim
set runtimepath+=/home/samba/.vim/plugins/dein.vim
```

`{}` is just place holder.

**Comment by Shougo** [comment]
```
And set up a path to the repository directory.
>
	set runtimepath+={path to dein directory}
<
Example:
>
	set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim
<
```

Note: Why have not read deoplete.txt?

**Comment by Shougo** [comment]
> how can I get a sha1 ? do you want a sha1sum or what?

Hm.  You can get the sha1 by `git rev-parse HEAD`
