### ISSUE TITLE
synchronous API to install plugin?

### ISSUE THREAD

**Issue by bladechen** [Shougo/dein.vim#216]
# Problems summary
I have a script to setup dev-env automatically, in neobundle, it will install all plugin then quit vim.
```
vim +NeoBundleInstall +qall
```

but in dein
when i try, it will immediately quit vim without install any plugins, so any suggestion for installing all the plugin, then quit vim?
i look through doc of dein, can not find synchronous API, does there any way can achieving this.
thanks
```
$HOME/vim80/bin/vim +'call dein#install()' +qall
```

## Expected

synchronous install plugins, then quit vim

**Comment by Shougo** [comment]
> when i try, it will immediately quit vim without install any plugins, so any suggestion for installing all the plugin, then quit vim?

I think the all plugins are installed.
Because, 

```
vim +'call dein#update()' +qall
```

It works.

**Comment by Shougo** [comment]
You can check the log by `g:dein#install_log_filename`

**Comment by Shougo** [comment]
Note:  Why does not you upload the minimal vimrc?
