### ISSUE TITLE
C indentation disabled

### ISSUE THREAD

**Issue by ctuffli** [Shougo/dein.vim#222]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
It appears C indentation is disabled by installing dein

## Expected
When running the command `nvim foo.c`, inserting a '{' and hitting return should automatically insert a tab:
```C
{
	/* automatic tab here */
}
```
But when using dein, you get this instead

```C
{
/* automatic tab here */
}
```
## Environment Information (Required!)

 * dein.vim version(SHA1):
c320586738875c2d1697f75faaf2b19d938cf403

 * OS:
FreeBSD 12.0

 * Vim/neovim version:
NVIM 0.1.7

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/usr/home/ctuffli/.config/nvim/bundles/repos/github.com/Shougo/dein.vim

let g:dein#enable_notification = 1

if dein#load_state(expand('~/.config/nvim/bundles'))
  call dein#begin(expand('~/.config/nvim/bundles'))
  
  call dein#add('/usr/home/ctuffli/.config/nvim/bundles/repos/github.com/Shougo/dein.vim')

  call dein#end()
  call dein#save_state()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. nvim -u ~/no_c.vim foo.c
 2. go into insert mode
 3. type '{' and hit return
 4. notice that the insertion point is in the first column and not tabbed

## Upload the log messages by `:redir` and `:message` (if errored)
no messages

**Comment by Shougo** [comment]
Have you read the documentation?

`filetype plugin indent on`

is needed.

**Comment by ctuffli** [comment]
Apologies, I missed those lines. Thank you for the help.
