### ISSUE TITLE
Recent regression in causing on_ft race condition

### ISSUE THREAD

**Issue by mqudsi** [Shougo/dein.vim#224]
I don't have too many details, but after updating dein recently I've noticed that on_ft is sometimes failing to take effect for files loaded from within an existing vim session. It is very random, so I imagine it's a race condition of some sort, but editing a file via `:e filepath` is failing to lazy-load certain `on_ft` plugins. Closing the file and trying again sometimes helps, sometimes it doesn't. 

There is never a problem loading them when vim is started up with the filepath explicitly specified from the command line.

The problem happens more often when jumping to a file from quickfix rather than when specifying the path via `:e ...`

When this happens, checking the filetype verifies that it is set correctly. Calling it again specifying the same filetype doesn't do anything, but I will try changing the ft to a different value then changing it back and see if that helps next time.

I was running the latest dein from two days ago, I just updated again and I'll see if it still happens.

**Comment by mqudsi** [comment]
This may not be a dein issue, I just experienced this problem loading a man page in a new buffer. `set ft` says `man` and `set syntax` says `man`, but afaik, syntax highlighting for man pages is from stock neovim, not any plugin I'm loading via dein.

I had to run `syntax on` to get it work, even though `syntax enable` is in my init.vim`.

**Comment by Shougo** [comment]
Have you read the issue template?
`The minimal vimrc` and `the reproduce ways` are needed.

**Comment by Shougo** [comment]
I will close the issue.  If you cannot upload them.
Because I cannot/reproduce the problem without them.

**Comment by mqudsi** [comment]
Thanks.

**Comment by Shougo** [comment]
I think you can create the minimal vimrc and the reproduce ways if it is the real problem of dein.

**Comment by Shougo** [comment]
> This may not be a dein issue, I just experienced this problem loading a man page in a new buffer

You can create the reproduce ways using man buffer.
