### ISSUE TITLE
Include `rev` in dein state/hash

### ISSUE THREAD

**Issue by mqudsi** [Shougo/dein.vim#225]
Can you please include the `rev` in the cached dein state so that changing the rev value triggers a plugin update?

Currently, if I change the `rev` value for a plugin I must manually `:call dein#update('plugin_name')` because dein doesn't recognize a change in rev as a need to update the plugin.

**Comment by Shougo** [comment]
Well, it is really needed?
I think the update should be executed manually.

**Comment by mqudsi** [comment]
Ok that's fine by me.
