### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Shougo/dein.vim#226]
# Problems summary

Unable to install plugins:

```
[dein] copy command failed.
[dein] cmdline: rsync -a -q --exclude '/.git/' '/Users/thomas/.vim/bundle/repos/github.com/scrooloose/nerdcommenter/' '/Users/thomas/.vim/bundle/.cache/init.vim/.dein'
[dein] copy command failed.
[dein] cmdline: rsync -a -q --exclude '/.git/' '/Users/thomas/.vim/bundle/repos/github.com/Shougo/dein.vim/doc/' '/Users/thomas/.vim/bundle/.cache/init.vim/.dein/doc'
[dein] Not installed plugins: ['vim-hybrid-material']
[dein] Update started: (2017/08/25 21:11:15)[dein] Updated plugins:
[dein]   vim-hybrid-material(1 change)
[dein] copy command failed.
[dein] cmdline: rsync -a -q --exclude '/.git/' '/Users/thomas/.vim/bundle/repos/github.com/kristijanhusak/vim-hybrid-material/' '/Users/thomas/.vim/bundle/repos/github.com/scrooloose/nerdcommenter/' '/Users/thomas/.vim/bundle/.cache/init.vim/.dein'
[dein] copy command failed.
[dein] cmdline: rsync -a -q --exclude '/.git/' '/Users/thomas/.vim/bundle/repos/github.com/Shougo/dein.vim/doc/' '/Users/thomas/.vim/bundle/.cache/init.vim/.dein/doc'
```

## Expected

Succesfull install.

## Environment Information (Required!)

 * dein.vim version(SHA1): Hash of git commit of `repos/github.com/Shougo/dein.vim`: 41b59fecf399ad83229f91bf7d868d5c95f38f0e.

 * OS: OS X 10.11.6.

 * Vim/neovim version: NVIM v0.2.1-816-g46a4099 (Noevim after v0.2.0).

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.vim/bundle')
    call dein#begin('~/.vim/bundle')
    call dein#add('~/.vim/bundle/repos/github.com/Shougo/dein.vim')

    " My plugins.
    call dein#add('kristijanhusak/vim-hybrid-material') " Color scheme.
    call dein#add('scrooloose/nerdcommenter')           " Easy comment out code.

    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable

if dein#check_install()
    call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. start neovim, see error log above.

**Comment by Shougo** [comment]
Please execute the command line manually.
I think it is your directory permission error.

**Comment by Shougo** [comment]
And you should test it in other machine.

**Comment by Thomasdezeeuw** [comment]
I doubt it's a permission error, since I own all the directories. I can't test it on another, since I don't have any others. Is there a debug mode I can run?

**Comment by Thomasdezeeuw** [comment]
I tried digging through the code a little bit and removed the `rsync` usage and now it fallback to `cp`, which also fails. However that seems really unlikely. If I try to run the command in the shell, either `rsync` or `cp`, both are successful. Maybe the failure detection is going wrong somewhere..?

**Comment by Shougo** [comment]
> I doubt it's a permission error, since I own all the directories. I can't test it on another, since I don't have any others. Is there a debug mode I can run?

Please use Virtual Machine.

> If I try to run the command in the shell, either rsync or cp, both are successful. Maybe the failure detection is going wrong somewhere..?

What is your 'shell' in Vim?
Please test it in Vim.
`call system()`, `:!`, etc.

**Comment by Thomasdezeeuw** [comment]
It's hard to virtualize Mac OS due to licensing issues, so I would only be able to run Linux.

My shell is bash 4.4.12(1), installed via home brew.

**Comment by Shougo** [comment]
> It's hard to virtualize Mac OS due to licensing issues, so I would only be able to run Linux.

Yes.  Please use Linux VM.

**Comment by Thomasdezeeuw** [comment]
I don't have time to test it on another machine, so I'm closing this.
