### ISSUE TITLE
unmap keys when plugin is loaded

### ISSUE THREAD

**Issue by kraxli** [Shougo/dein.vim#227]
I load the vimwiki plugin by yaml file like:
```
- repo: vimwiki/vimwiki
  on_cmd: [Vimwiki, VimwikiTabIndex]
```
When I load it, I would like to unmap the keys <m-left> and remap the underlying command. Can I let Dein do that when vimwiki is loaded?

**Comment by Shougo** [comment]
`:help dein-options-hook_source`
