### ISSUE TITLE
can not detect filetype when use `on_ft` option.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#228]
hi @Shougo when use dein add a plugin with an option `on_ft`, this plugin will be loaded, when filetype is set to the value of this option, but before the plugin is loaded, we can not detect the filetype, what could I do?

I just find a ways to fix this, add a autocmd to vimrc,  but when open a file, the filetype is set twice, one is from the vimrc, and another one is from the ftdetect script of the plugin.

**Comment by Shougo** [comment]
I think filetype detect is disabled.
Please check it.

I cannot reproduce the behavior.
Have you read the issue template?

**Comment by wsdjeg** [comment]
SORRY, I think it works well now, clossing.

**Comment by Shougo** [comment]
OK
