### ISSUE TITLE
The installation path changes with g:dein#types#git#default_protocol

### ISSUE THREAD

**Issue by thinca** [Shougo/dein.vim#23]
# Problems summary

The installation path of plugin changes with `g:dein#types#git#default_protocol`.

For example, install `Shougo/dein.vim`:
```vim
call dein#add('Shougo/dein.vim')
```

When `g:dein#types#git#default_protocol = 'https'` (default), the plugin is installed to:

```
<dein-base>/repos/github.com/Shougo/dein.vim
```

But when `g:dein#types#git#default_protocol = 'git'`:

```
<dein-base>/repos/Shougo/dein.vim
```

`github.com` is missing.

## Expected

I think this should not be changed.

## Environment Information
* OS: Windows
* Vim version: 7.4.1403 (from Chocolatey)
* Maybe this occurs on all environment (I think).

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let $DEIN_ROOT = expand('~/vimfiles/bundle')
let $DEIN_DIR = expand('$DEIN_ROOT/repos/github.com/Shougo/dein.vim')

set runtimepath^=$DEIN_DIR

let g:dein#types#git#default_protocol = 'ssh'

call dein#begin($DEIN_ROOT)
call dein#add('Shougo/dein.vim')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

1. 
  ```
  mkdir %HOMEDRIVE%%HOMEPATH%\vimfiles\bundle\repos\github.com\Shougo
  git clone https://github.com/Shougo/dein.vim %HOMEDRIVE%%HOMEPATH%\vimfiles\bundle\repos\github.com\Shougo\dein.vim
  ```

2. Start Vim with above vimrc

**Comment by Shougo** [comment]
> But when `g:dein#types#git#default_protocol = 'git'`:

This is `ssh` instead of `git`?
It is bug.  Thanks.

**Comment by Shougo** [comment]
Fixed.

**Comment by thinca** [comment]
> This is `ssh` instead of `git`?

Oh, yes.  Thank you for fix :)
