### ISSUE TITLE
Plugins with identical .vim file names

### ISSUE THREAD

**Issue by rustikus** [Shougo/dein.vim#230]
# Problems summary

I am unable to load two similar plugins and I think it is because they use the same name of the .vim file.

The two plugins which are causing problems for me are:

https://github.com/tbabej/taskwiki
https://github.com/vimwiki/vimwiki/tree/dev

Both of them have a file named ftplugin/vimwiki.vim. I think it is related to https://github.com/tbabej/taskwiki/issues/159

## Expected

Taskwiki and Vimwiki are loaded and available

## Environment Information (Required!)

 * dein.vim version(SHA1):

 * OS:
macOS 10.12.6

 * Vim/neovim version:
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
I use SpaceVim (dein as plugin manager) to load custom plugins:

let g:spacevim_custom_plugins = [
        \ ['Alok/notational-fzf-vim'],
        \ ['ryanoasis/vim-devicons'],
        \ ['vimwiki/vimwiki'],
        \ ['tbabej/taskwiki'],
        \ ['powerman/vim-plugin-AnsiEsc'],
        \ ['farseer90718/vim-taskwarrior'],
        \ ]


```

**Comment by Shougo** [comment]
It is the plugins problem.

I cannot fix it.

Solution:  Please read `:help ftplugin-name`.
