### ISSUE TITLE
How to install plugins from command line with the right exit code?

### ISSUE THREAD

**Issue by joshua7v** [Shougo/dein.vim#232]
# Problems summary
I'm building a docker image with some custom neovim settings.
Normally, plugins can be installed from command line by using `nvim -c 'cmd' or nvim +'cmd'`.
But with dein, when the installation is finished, there's a message in echo area. So I'm not able to install plugins with `nvim +'call dein#update()' +qall` with the right exit code `0`.

I've tried:

I found these two options may help.
I've set both to 'none', but nothing changed. Messages still pop up after installing and progress visible in echo area.

```
let g:dein#install_progress_type = 'none'
let g:dein#install_message_type = 'none'
```

## Expected

with one command, something like this: `nvim +"call dein#install()" +qall`, plugins can be installed correctly, and return to shell with exit code `0`

## Environment Information (Required!)

 * dein.vim version(SHA1): latest

 * OS: docker(alpine)

 * Vim/neovim version: neovim 0.2.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)

call dein#add('terryma/vim-multiple-cursors')

call dein#end()

let g:dein#install_progress_type = 'none'
let g:dein#install_message_type = 'none'
```

## The reproduce ways from Vim starting (Required!)

`nvim +"call dein#install()" +qall`

**Comment by Shougo** [comment]
Sorry, I don't think it cannot.
Because Vim script cannot change the Vim exit code.

**Comment by Shougo** [comment]
I get the problem.  I will fix it later.
