### ISSUE TITLE
airline is not loading powerline font symbols on second session

### ISSUE THREAD

**Issue by diefans** [Shougo/dein.vim#236]
# Problems summary
When I change neovim config, airline powerline font symbols are shown. When I close neovim and open it again, symbols are not shown.

I can manually delete `~/.config/nvim/dein/state_nvim.vim` and the next session shows powerline font symbols as expected.

## Expected
airline powerline font symbols are always shown

## Environment Information (Required!)

 * dein.vim version(SHA1): 3a28810

 * OS: ubuntu 16.04

 * Vim/neovim version: v0.2.2-35-g30a2183

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif

let dein_base=glob('~/.config/nvim/dein')
let dein_plugin=dein_base . '/repos/github.com/Shougo/dein.vim'

exe 'set runtimepath+=' . dein_plugin

if dein#load_state(dein_base)
    call dein#begin(dein_base)
    call dein#add('vim-airline/vim-airline')
        let g:airline_powerline_fonts = 1

    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax on
```

## The reproduce ways from Vim starting (Required!)

 1. nvim -u minimal.vim
 2. nvim -u minimal.vim

**Comment by Shougo** [comment]
You configuration is wrong.


```vim
if dein#load_state(dein_base)
    call dein#begin(dein_base)
    call dein#add('vim-airline/vim-airline')

    call dein#end()
    call dein#save_state()
endif

let g:airline_powerline_fonts = 1
``

or please use `hook_add`.
`dein#load_state()` block is skipped if the state file is cached.
So the behavior is the feature.

**Comment by diefans** [comment]
I understand, but I find a bigger set of plugins hard to maintain, since plugin load location and associated settings are out of sight

**Comment by Shougo** [comment]
If so, you should use `hook_add` instead.
