### ISSUE TITLE
Question : building for different versions of vim

### ISSUE THREAD

**Issue by thecontinium** [Shougo/dein.vim#237]
Hi

Can you let me know the best way to perform the functionality in the below example using Vimplug. 

Thanks

function! BuildComposer(info)
  if a:info.status != 'unchanged' || a:info.force
    if has('nvim')
      !cargo build --release
    else
      !cargo build --release --no-default-features --features json-rpc
    endif
  endif
endfunction

Plug 'euclio/vim-markdown-composer', { 'do': function('BuildComposer') }

**Comment by Shougo** [comment]
Please use `dein-options-hook_post_update`.

**Comment by thecontinium** [comment]
Thanks for the advice:
I removed  build and added hook_post_update
I cleared out all my plugins and reinstalled them with dein.
The hook_post_update was not called on the plugin I added it to.
Some questions to clarify my understanding:
1. is the post_update command executed with working directory in the plugins top directory ?
2. is post_update the equivalent of build but calls a vim function rather that a system call ?
3. when is the post_update executed ?
4. do I need build and hook_post update ?
5. is build script called when the plugin is updated ? 

thanks

**Comment by Shougo** [comment]
>  The hook_post_update was not called on the plugin I added it to.

Really?  It is the another issue.
I must check it.
Please create the new issue for it and read the issue template.
It must be checked by me.
Note: I recommend for you to read the other issues.

> is the post_update command executed with working directory in the plugins top directory ?

Yes.

> is post_update the equivalent of build but calls a vim function rather that a system call ?

Yes.

> when is the post_update executed ?

It is the plugin updated.  It is same with `build` option.

> do I need build and hook_post update ?

`hook_post_update` is needed.  `build` is not needed.

> is build script called when the plugin is updated ?

Yes.

**Comment by Shougo** [comment]
> The hook_post_update was not called on the plugin I added it to.

It is the update hook instead of `called`.

**Comment by thecontinium** [comment]
thanks - let me take a look at the other issues and see if I can see if I am missing something.

I will raise another issue if I cannot get it working or let you know if I do

**Comment by thecontinium** [comment]
I made some further investigations and tested the following cases:

1. If a plugin is added with both `hook_post_update` and `on_ft` options like this:

`call dein#add('thecontinium/vim-markdown-composer', {'hook_post_update': 'let g:markdown_composer_post_update_called = 1', 'on_ft': 'markdown'} )`

then `g:markdown_composer_post_update_called` is **never set**

2. If it is setup with just `hook_post_update` option like this:
`call dein#add('thecontinium/vim-multimarkdown', {'hook_post_update': 'let g:multimarkdown_post_update_called = 1'} )`

then `g:multimarkdown_post_update_called` is set on **initial install and all subsequent updates**


This doesn't seem right; is this expected ?

I can raise a full detailed issue if you want ?

Here is the vimrc that I am using to test this:

```vim
if &compatible
  set nocompatible
endif

" Set main configuration directory, and where cache is stored.
let $VIMPATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
let $VARPATH = expand(($XDG_CACHE_HOME ? $XDG_CACHE_HOME : '~/.cache').'/vim')

let g:dein#install_max_processes = 16
let g:dein#install_progress_type = 'echo'
let g:dein#enable_notification = 0
let g:dein#install_log_filename = $VARPATH.'/dein.log'

" Setup dein {{{
if &runtimepath !~# '/dein.vim'
  let s:dein_dir = expand('$VARPATH/dein').'/repos/github.com/Shougo/dein.vim'
  if ! isdirectory(s:dein_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
  endif

  execute 'set runtimepath+='.substitute(
    \ fnamemodify(s:dein_dir, ':p') , '/$', '', '')
endif


" Initialize dein.vim (package manager)
let s:path = expand('$VARPATH/dein')
if dein#load_state(s:path)
  call dein#begin(s:path)

  call dein#add(s:dein_dir)
  call dein#add('thecontinium/vim-markdown-composer', {'hook_post_update': 'let g:markdown_composer_post_update_called = 1', 'on_ft': 'markdown'} )
  call dein#add('thecontinium/vim-multimarkdown', {'hook_post_update': 'let g:multimarkdown_post_update_called = 1'} )

  ",'on_ft': 'markdown'})

  "call dein#set_hook('vim-markdown-composer', 'hook_post_update', '!cargo build --release')

  call dein#end()
  call dein#save_state()

  if dein#check_install()
    if ! has('nvim')
      set nomore
    endif
    call dein#install()
  endif

endif

filetype plugin indent on
syntax enable
```

**Comment by Shougo** [comment]
OK.  I will check the issue.

@thecontinium Please create the new issue for it.

**Comment by Shougo** [comment]
I get it.  It is the bug.

**Comment by thecontinium** [comment]
ok - thanks. I’ll raise another issue.
