### ISSUE TITLE
hook_post_update option not always called

### ISSUE THREAD

**Issue by thecontinium** [Shougo/dein.vim#238]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

If a plugin is added with both hook_post_update and on_ft options like this:
call `dein#add('thecontinium/vim-markdown-composer', {'hook_post_update': 'let g:markdown_composer_post_update_called = 1', 'on_ft': 'markdown'} )`

then g:markdown_composer_post_update_called is **never set**

If it is setup with just hook_post_update option like this:
call dein#add('thecontinium/vim-multimarkdown', {'hook_post_update': 'let g:multimarkdown_post_update_called = 1'} )
then g:multimarkdown_post_update_called is set on **initial install and all subsequent updates**

## Expected

`hook_post_update` called on any update to the plugin 

## Environment Information (Required!)

 * dein.vim version(SHA1): aead2a8f96e986c9d6b9e5bee074ed587bff4a9a

 * OS: Mac OS Sierra 10.13.1

 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif

" Set main configuration directory, and where cache is stored.
let $VIMPATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
let $VARPATH = expand(($XDG_CACHE_HOME ? $XDG_CACHE_HOME : '~/.cache').'/vim')

let g:dein#install_max_processes = 16
let g:dein#install_progress_type = 'echo'
let g:dein#enable_notification = 0
let g:dein#install_log_filename = $VARPATH.'/dein.log'

" Setup dein {{{
if &runtimepath !~# '/dein.vim'
  let s:dein_dir = expand('$VARPATH/dein').'/repos/github.com/Shougo/dein.vim'
  if ! isdirectory(s:dein_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
  endif

  execute 'set runtimepath+='.substitute(
    \ fnamemodify(s:dein_dir, ':p') , '/$', '', '')
endif


" Initialize dein.vim (package manager)
let s:path = expand('$VARPATH/dein')
if dein#load_state(s:path)
  call dein#begin(s:path)

  call dein#add(s:dein_dir)
  call dein#add('thecontinium/vim-markdown-composer', {'hook_post_update': 'let g:markdown_composer_post_update_called = 1', 'on_ft': 'markdown'} )
  call dein#add('thecontinium/vim-multimarkdown', {'hook_post_update': 'let g:multimarkdown_post_update_called = 1'} )

  ",'on_ft': 'markdown'})

  "call dein#set_hook('vim-markdown-composer', 'hook_post_update', '!cargo build --release')

  call dein#end()
  call dein#save_state()

  if dein#check_install()
    if ! has('nvim')
      set nomore
    endif
    call dein#install()
  endif

endif

filetype plugin indent on
syntax enable
```

**Comment by Shougo** [comment]
Reproduced.  It is bug.
I will fix it later.

**Comment by thecontinium** [comment]
Thanks for the fix. When the hook is called the working directory is the current working directory of Nvim. Is this correct ? What is the best way to get to the root directory of the plugin ?

Cheers

**Comment by Shougo** [comment]
I have fixed it.
Please update dein.vim.

**Comment by thecontinium** [comment]
cheers - tested and the wd is set to the root of the plugin
