### ISSUE TITLE
How to do mappings for plugins like <Plug>(plugin-cmd)

### ISSUE THREAD

**Issue by bigDaddyS1oth** [Shougo/dein.vim#239]
I'm just wanting to know how I would map keystrokes for plugin commands.

How Plug does it:
    
    " for incsearch
    map * <Plug>(incsearch-nohl-*)
    map # <Plug>(incsearch-nohl-#)
    map g* <Plug>(incsearch-nohl-g*)
    map g# <Plug>(incsearch-nohl-g#)

    " for easymotion
    map <Leader>f <Plug>(easymotion-bd-f)
    nmap <Leader>f <Plug>(easymotion-overwin-f)
    map <Leader>L <Plug>(easymotion-bd-jk)
    nmap <Leader>L <Plug>(easymotion-overwin-line)
    map <Leader>w <Plug>(easymotion-bd-w)
    nmap <Leader>w <Plug>(easymotion-overwin-w)

But my only guess to do this with Dein is with `on_map`, maybe? Might be worth putting in the docs. 😛

**Comment by Shougo** [comment]
Please read the documentation.

Yes.  `on_map` is for you.
And it is already documented.

```
							*dein-options-on_map*
on_map		(Dictionary) or (List) or (String)
		If it is the Dictionary, the key is {mode} and the items are
		{mapping} or [{mapping1}, {mapping2}, ...].
		If it is the List, the items are {mapping} or [{mode},
		{mapping1}, [{mapping2}, ...]].
		If {mode} is omitted, "nx" is used.
		Note: You can use plugin prefix mappings.
		For example, you can use "<Plug>(ref-" instead of
		"<Plug>(ref-back)" and so on.
		For example: >
		call dein#add('Shougo/deol.nvim',
		\ { 'on_map': {'n': '<Plug>'} })
<
```
