### ISSUE TITLE
Is it possible to remove "temp" dir automatically?

### ISSUE THREAD

**Issue by zdm** [Shougo/dein.vim#240]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I found, than dein creates "temp" directory under ".vim/bundle/.cache/.vimrc/" and add snapshots of currently installed modules on each update check. After several weeks of work I have this dir size ~ 1.5 Gb. Is it possible to limit number of snapshots and rotate them or completely clear this dir automatically?

## Environment Information (Required!)

 * dein.vim version(SHA1):
d32de9ef54ce364ab5355d829f84d0ecd5be5b26

 * OS:
windows, on linux it's operates normally

 * Vim/neovim version:
vim x64 8.9.1360

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:user_profile_dir = substitute($HOME . "/.vim", '\\', '/', 'g')
let g:bundle_path = g:user_profile_dir . "/bundle"
let g:bundle_local_path = g:user_profile_dir . "/bundle-local"

exec "set rtp+=" . g:bundle_path . "/repos/github.com/Shougo/dein.vim"

if has('win16') || has('win32') || has('win64')
    let g:dein#types#git#command_path="git.cmd"
endif

call dein#begin(expand(g:bundle_path))

call dein#add(g:bundle_path . "/repos/github.com/Shougo/dein.vim")

command! DeinUpdate call s:dein_update()

function! s:dein_update()
    call dein#update()
    Unite -log -wrap dein/log:!
endfunction
```

## The reproduce ways from Vim starting (Required!)

 1. call DeinUpdate several times;
 2. see, that temp dir contains several snapshots;

**Comment by Shougo** [comment]
Please remove the temp directory manually.
It should be removed automatically.
But the old version of the code is buggy.
It may not be removed.

**Comment by Shougo** [comment]
Hm.  It should be Windows only feature.

**Comment by Shougo** [comment]
>  Is it possible to limit number of snapshots and rotate them or completely clear this dir automatically?

It should be removed automatically.
But it cannot be removed the current session.

> see, that temp dir contains several snapshots;

The reproduce ways are wrong.

It should be:

1. remove the dein cache directory manually.
2. `call dein#recache_runtimepath()`.
3. exists some snapshot.
4. Exit Vim
5. `call dein#recache_runtimepath()`
6. previous snapshot is removed but new snapshot is exists (It is the intended behavior)

Please try.

**Comment by Shougo** [comment]
And please try `call dein#install#_rm()` works properly.
It should work.
But it may not work in Windows.

**Comment by zdm** [comment]
thank you, i will try soon

**Comment by zdm** [comment]
```
call dein#install#_rm()
```
error: not enough arguments for function

**Comment by zdm** [comment]
```
call dein#recache_runtimepath()
```
under windows previous snapshot is not removed, new snapshot created every time.

**Comment by zdm** [comment]
so, there is no possibility to do this under windows?

**Comment by Shougo** [comment]
I have removed the feature.

**Comment by zdm** [comment]
Got an error.
![screenshot 2017-12-03 07 56 56](https://user-images.githubusercontent.com/1025608/33522828-b987ec84-d7ff-11e7-8919-6c5f760534c4.png)

**Comment by Shougo** [comment]
Please test below script.

```vim
  call dein#install#_rm(dein#util#_get_runtime_path())

  " Create runtime path
  call mkdir(dein#util#_get_runtime_path(), 'p')
```

It should work.

Please test `call dein#install#_rm(dein#util#_get_runtime_path())` removes the cache directory properly.

**Comment by Shougo** [comment]
I think the remove command is failed.
Please check `:messages`.

**Comment by Shougo** [comment]
I think your cache directory contains dll files.
Please check your vimrc.

**Comment by zdm** [comment]
![screenshot 2017-12-03 11 47 52](https://user-images.githubusercontent.com/1025608/33524153-02e83148-d820-11e7-9983-35066801a245.png)

but directory c:\Users\zdm\.vim\bundle\.cache\.vimrc\.dein\ is exists

**Comment by zdm** [comment]
and yes, it's contains dll's, but it not works, even i comment dll's in vimrc.

**Comment by Shougo** [comment]
@zdm 

> Please test call `dein#install#_rm(dein#util#_get_runtime_path())` removes the cache directory properly.

Please check this.

> maybe you just need to check directory before trying to create it?

Yes.  It is easy.  But I need to know why the delete does not work.

**Comment by Shougo** [comment]
I have added the error check.
Please update dein.vim.

**Comment by zdm** [comment]
yes, it works now without errors.
FYI, rollbacks directory is not cleaned also, so, potentially, it may grow without limits.

**Comment by Shougo** [comment]
> FYI, rollbacks directory is not cleaned also, so, potentially, it may grow without limits.

Hahaha.
Really?
Have you read the rollbacks directory?
You don't have to concern about the directory.
