### ISSUE TITLE
Using the done_update hook to make a first-time install script

### ISSUE THREAD

**Issue by moshen** [Shougo/dein.vim#241]
# Problems summary

I would like to make a setup script that automatically installs my base set of plugins, however I can't seem to figure out how the `done_update` hook works.

## Expected

I expect my minimal vimrc to run `dein#update()`, then quit

## Environment Information (Required!)

 * dein.vim version(SHA1): d32de9ef54ce364ab5355d829f84d0ecd5be5b26

 * OS: Mac OS 10.12.6

 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible

set rtp+=$HOME/.vim/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand($HOME.'/.vim/dein')) " plugins' root path

call dein#add('Shougo/dein.vim')
call dein#add('vim-scripts/wombat256.vim')

call dein#end()

try
  colorscheme wombat256mod
catch
endtry

set background=dark
filetype plugin on
syntax on

call dein#set_hook('dein.vim', 'done_update', 'qa')
call dein#update()
```

## The reproduce ways from Vim starting (Required!)

 1. nvim -u vimrc.min
 2. it seems like the hook never fires, no errors

**Comment by Shougo** [comment]
> call dein#set_hook('dein.vim', 'done_update', 'qa')

It must be `hook_done_update`.
Have you read the documentation?

**Comment by moshen** [comment]
I'm sorry, I was looking at how `dein#call_hook` is used [here](https://github.com/Shougo/dein.vim/blob/d5fadf0f7a10a0ec9d987d2b68b36091d97820bf/autoload/dein/install.vim#L231).  I think I was just a little confused.

My install script works using `hook_done_update`, now I just need to figure out why dein is between 15-30ms longer to start than Vundle (using cache).

**Comment by Shougo** [comment]
> now I just need to figure out why dein is between 15-30ms longer to start than Vundle (using cache).

It should be the new issue.
Please upload the minimal vimrc.
I will check it.
