### ISSUE TITLE
Question: Cannot recursively dein#load_toml ?

### ISSUE THREAD

**Issue by curationing** [Shougo/dein.vim#243]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

dein.vimインストール時にTOMLファイル (リスト渡し)を再帰的にdein#load_tomlしたいができない
- TOMLディレクトリ内のファイル一つしか読み込まない
- 各TOMLファイルは`[[plugins]] repo = 'xxx/xxx'`のみのシンプルなもの
- ディレクトリ内外に読み込まなかったTOMLファイルを出し入れすると読み込む

## Expected

インストール時問わず、すべてのTOMLファイルを再帰的に読み込みたい

私の知識不足なだけかも知れませんが、その際にはご教示頂けるとありがたいです。

## Environment Information (Required!)

 * dein.vim version(SHA1): すみません、分かりませんでした。2017T1205時点最新です。

 * OS: MacOS El Capitan

 * Vim/neovim version: Vim 8.0 macOS version

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:vimcache_dein_dir  = expand('$HOME/.cache/.vim/.plugin/dein')
let s:dein_dir = empty($XDG_CACHE_HOME)
        \ ? s:vimcache_dein_dir
        \ : $XDG_CACHE_HOME.'/.vim/.plugin/dein'
let g:dein_plugin_dir = s:dein_dir.'/repos/github.com'
let s:repo_dein_dir   = g:dein_plugin_dir.'/shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:repo_dein_dir)
    if executable('git')
      execute '!git clone https://github.com/shougo/dein.vim' s:repo_dein_dir
    else
      echomsg 'git has not yet been installed.'
    endif
  endif
  execute 'set runtimepath^='.fnamemodify(s:repo_dein_dir, ':p')
endif

let s:dein_toml_dir  = expand('<sfile>:p:h').'/.dein_toml'
let s:dein_toml_list = split(glob(s:dein_toml_dir.'/*'), '\n')

if !isdirectory(s:dein_toml_dir)
  call mkdir(iconv(s:dein_toml_dir, &encoding, &termencoding), 'p')
endif

if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)
  call dein#add(s:repo_dein_dir, {'rtp': ''})
  for s:i in s:dein_toml_list
    call dein#load_toml(s:dein_toml_list[s:i])
  endfor
  call dein#end()
  call dein#save_state()
endif

if has('vim_starting') && dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. Open iTerm.app
 2. bash (login shell)
 3. vim (~/.vimrc source above dein settings)

**Comment by Shougo** [comment]
```vim
let s:dein_toml_list = split(glob(s:dein_toml_dir.'/*'), '\n')
```

これですが、

```vim
let s:dein_toml_list = split(glob(s:dein_toml_dir.'/**/*.toml'), '\n')
```

として

```vim
if dein#load_state(s:dein_dir)
endif
```

のブロックに入れたほうが良いです。
これで問題は解決するのではないでしょうか。

**Comment by curationing** [comment]
ご返信下さりありがとうございました。
ご指摘頂いたとおりに直してみたのですが、動作状況は変わらずです。

```vim
let s:vimcache_dein_dir  = expand('$HOME/.cache/.vim/.plugin/dein')
let s:dein_dir = empty($XDG_CACHE_HOME)
        \ ? s:vimcache_dein_dir
        \ : $XDG_CACHE_HOME.'/.vim/.plugin/dein'
let g:dein_plugin_dir = s:dein_dir.'/repos/github.com'
let s:repo_dein_dir   = g:dein_plugin_dir.'/shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:repo_dein_dir)
    if executable('git')
      execute '!git clone https://github.com/shougo/dein.vim' s:repo_dein_dir
    else
      echomsg 'git has not yet been installed.'
    endif
  endif
  execute 'set runtimepath^='.fnamemodify(s:repo_dein_dir, ':p')
endif

let s:dein_toml_dir  = expand('<sfile>:p:h').'/.dein_toml'

if !isdirectory(s:dein_toml_dir)
  call mkdir(iconv(s:dein_toml_dir, &encoding, &termencoding), 'p')
endif

if dein#load_state(s:dein_dir)
  let s:dein_toml_list = split(glob(s:dein_toml_dir.'/**/*.toml'), '\n')
  call dein#begin(s:dein_dir)
  call dein#add(s:repo_dein_dir, {'rtp': ''})
  for s:i in s:dein_toml_list
    call dein#load_toml(s:dein_toml_list[s:i])
  endfor
  call dein#end()
  call dein#save_state()
endif

if has('win16') || has('win32') || has('win64')
  if has('gui_running')
    finish
  endif
endif

if has('vim_starting') && dein#check_install()
  call dein#install()
endif
```

初回時(dein.vimインストール時)には、TOMLを格納しているディレクトリ内のソート上最初のファイルを読み込み終了している模様です。初回時に恐らくキャッシュが作られるためか、初回時にディレクトリ内に格納されていたTOMLファイルは、以後ディレクトリより出し入れしても読み込んでもらえません。
初回時以降ディレクトリに加えた新規のTOMLファイルは読み込まれるようです(初回時は別のTOMLファイルが正常に読み込まれている)。
2つのTOMLファイルでしか試していないので3つ以上の場合どうなるのか検証してみます。

**Comment by Shougo** [comment]
> 初回時(dein.vimインストール時)には、TOMLを格納しているディレクトリ内のソート上最初のファイルを読み込み終了している模様です。初回時に恐らくキャッシュが作られるためか、初回時にディレクトリ内に格納されていたTOMLファイルは、以後ディレクトリより出し入れしても読み込んでもらえません。

それをやるなら、`dein#load_state()` を使わないでください。
もちろん起動時間が遅くなります。
`dein#load_state()` はそういう任意のプラグインの追加・削除に弱いのです。

**Comment by Shougo** [comment]
> Question: Cannot recursively dein#load_toml ?

これのタイトルが誤解を生むのでまずくて、おそらく希望は「キャッシュを使いつつ任意にプラグインの追加・削除を行いそれを自動的に読み込んで欲しい」ということでしょうが、そこまで都合の良い機能はありません。

**Comment by curationing** [comment]
TOMLファイルにつき一つの`[[plugins]]`しか書かなかったのがいけないのかとも思ったのですが違うようでした。
そして何故か追加した2つ目のTOMLファイルも読み込まなくなってしまいました。
当然3つ目も読み込めていません。

これは実はループが間違っているのでしょうか。

**Comment by curationing** [comment]
なるほど、キャッシュの兼ね合いだったのですね。
dein.vimの仕組み的な理解が浅かったようです。

ご対応頂きありがとうございました。

**Comment by Shougo** [comment]
> TOMLファイルにつき一つの[[plugins]]しか書かなかったのがいけないのかとも思ったのですが違うようでした。
そして何故か追加した2つ目のTOMLファイルも読み込まなくなってしまいました。
当然3つ目も読み込めていません。

これについては、キャッシュされていたからディレクトリの中身まで見に行かなかったということだと思います。
toml ファイル自体のタイムスタンプも同時にキャッシュされますが、当然ファイル自体の追加・削除は見ていません。

**Comment by curationing** [comment]
となると、以前追加分tomlが読み込まれた際にはキャッシュがまだ作られていなかったから、なんですかね。どのタイミングでキャッシュされるのか、いろいろよく分かっていないので、一度きちんとヘルプテキストを読んでみます。

**Comment by Shougo** [comment]
> となると、以前追加分tomlが読み込まれた際にはキャッシュがまだ作られていなかったから、なんですかね。どのタイミングでキャッシュされるのか、いろいろよく分かっていないので、一度きちんとヘルプテキストを読んでみます。

キャッシュが作られていなかった、ちょうどキャッシュの更新のタイミングだった時には読み込まれます。
更新タイミングとは、

* vimrc が変更された
* キャッシュしている toml ファイルが変更された

の 2 パターンあります。

**Comment by Shougo** [comment]
ドキュメントにはさすがにそこまで詳しい挙動については書いていません。

**Comment by curationing** [comment]
すみません、分かりました。
for文の使い方が間違っているという大変初歩的なミスでした。

```vim
...
  for s:i in s:dein_toml_list
    call dein#load_toml(s:i)
  endfor
...
```

`s:i`だけで足りるところを`s:dein_toml_list[s:i]`などとしていました。
このようなコードでも最初のtomlファイルだけは読み込まれたのが何故かは分かりませんが、まったくをもってdein.vimの挙動による問題ではありませんでした。

キャッシュの読み込むタイミングに関しては大変勉強になりました。
キャッシュの挙動を念頭にdein.vimを今後も使わせて頂きます。
丁寧に対応して頂き、ありがとうございました。
また、貴重なお時間を使わせてしまい申し訳ありませんでした。

**Comment by Shougo** [comment]
あ、それかぁ。気づきませんでした。
確かに C 言語みたいに捉えていたらそういうコードになってしまうと思います。

**Comment by curationing** [comment]
まさか著名な作者様にこれほど丁寧に付き合って頂けるとは思っておりませんでしたので、大変感激しております。
dein.vimの設計思想には沿わないことをやろうとはしていたものの、分からなかったことが分かるようになって嬉しいです。
初学者ながらもvimが好きなので、今回の件にて改めてvimスクリプトをちゃんと勉強しようと思いました。
この度は貴重なお時間と機会を頂き、本当にありがとうございました。
一介のファンとしても、これからもdeinを始めとしたShougoさんのツールを使わせて頂きたいと思っております。

**Comment by Shougo** [comment]
Vim script はなかなか奥が深いので勉強してみると良いかと思います。
