### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by JesusZhao** [Shougo/dein.vim#245]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

how to uninstall?

## Environment Information (Required!)

 * dein.vim version(SHA1):

 * OS: MacOS 10.12.6

 * Vim/neovim version:

vim 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
The uninstall is dein.vim uninstall?

Please remove the dein directory and the `path` directory.
