### ISSUE TITLE
Some more installation info for neovim

### ISSUE THREAD

**Issue by ttxtea** [Shougo/dein.vim#246]
When copying the .vimrc example code into

`~/.config/nvim/init.vim` I get `Undefined variable: path`

The installation does not specify what {path to dein.vim directory} or {path to plugin base path directory} means. Examples would be very helpful

**Comment by Shougo** [comment]
`{path to dein.vim directory}` means the installed dein.vim path.
`{path to plugin base path directory}` means dein.vim installs plugins in the directory.
