### ISSUE TITLE
How to test in command line  : nvim +dein#update +qall

### ISSUE THREAD

**Issue by ca971** [Shougo/dein.vim#247]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Hi,
Happy new year for every body,
I want to write a bash script to install a new mac.
I try this command : **nvim +dein#update +qall**
I have this error : **E492: Not an editor command : dein#update**
It doesn't work.

Help please.
## Expected
Help please.

## Environment Information (Required!)
Macbook pro
 * dein.vim version(SHA1):

 * OS:
Osx High Sierra 10.13
 * Vim/neovim version:
vim 8 and neovim 0.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" If dein, do it first
if (!isdirectory(expand('$HOME/.vim/repos/github.com/Shougo/dein.vim')))
  call system(expand('mkdir -p $HOME/.vim/repos/github.com'))
  call system(expand('git clone https://github.com/Shougo/dein.vim $HOME/.vim/repos/github.com/Shougo/dein.vim'))
endif
set runtimepath+=~/.vim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.vim'))
call dein#add('Shougo/dein.vim')
call dein#add('tomasr/molokai')
if dein#check_install()
  call dein#install()
endif
call dein#end()

" Required:
filetype plugin indent on
syntax enable

```

## The reproduce ways from Vim starting (Required!)

 1. Normal

## Screen shot (if possible)
<img width="742" alt="vim_screen_shot" src="https://user-images.githubusercontent.com/15018684/34618489-4efb13d4-f215-11e7-9b8d-c8139cdcd23d.png">

## Upload the log messages by `:redir` and `:message` (if errored)
E492: Not an editor command : dein#update

**Comment by Shougo** [comment]
`nvim +'call dein#update()' +qall`

`dein#update` is function call.
