### ISSUE TITLE
Error detected while processing function provider#python3#Call: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kierun** [Shougo/dein.vim#251]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

This happens:

Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\usr\.cache\dein\.cache\init.vim\.dein\pymode\lint.py", line 9, in <module>
    from pylama.lint.extensions import LINTERS
  File "C:\Users\usr\Documents\Projects\boltight_top_station\BTTS\Lib\site-packages\pylama\lint\extensions.py", line 6, in <module>
    from pylama.lint.pylama_mccabe import Linter
  File "C:\Users\usr\Documents\Projects\boltight_top_station\BTTS\Lib\site-packages\pylama\lint\pylama_mccabe.py", line 2, in <module>
    from mccabe import McCabeChecker
  File "C:\Users\usr\.cache\dein\.cache\init.vim\.dein\pymode\libs\mccabe.py", line 1
    ../../submodules/mccabe/mccabe.py
    ^
Error detected while processing function provider#python3#Call:
line   18:
SyntaxError: invalid syntax

## Expected

This should work.

## Environment Information (Required!)

 * dein.vim version(SHA1): 

2adba7655

 * OS: 

Windows 10

 * Vim/neovim version: 

Neovim v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:python3_host_prog="C:\\Users\\usr\\Envs\\neovim\\Scripts\\python.exe"
set runtimepath^=C:\Users\usr\AppData\Local\nvim\dein.vim\repos\github.com\Shougo\dein.vim

call dein#begin(expand('C:\Users\usr\.cache\dein'))
call dein#add('C:\Users\usr\AppData\Local\nvim\dein.vim\repos\github.com\Shougo\dein.vim')

" Python mode: https://github.com/python-mode/python-mode
call dein#add("python-mode/python-mode")
  nnoremap <space> za
  let g:pymode_rope_completion = 1
  let g:ropevim_extended_complete=1
  let g:pymode_lint_checkers = ['flake8', 'pep8', 'mccabe']
  " autocmd FileType python setlocal omnifunc=RopeCompleteFunc
  let g:pymode_python = 'python3'

" All done.
call dein#end()

```

## The reproduce ways from Vim starting (Required!)

 1. Run `nvim.exe some-file.py`…
 2. :messages to see the error.

## Screen shot (if possible)

Would not add much I am afraid.

## Upload the log messages by `:redir` and `:message` (if errored)

See above.

**Comment by Shougo** [comment]
It is not dein.vim problem.
It is just plugin error.

**Comment by Shougo** [comment]
You can reproduce the error without dein.vim.
