### ISSUE TITLE
Dein.vim can't be installed when I use fish shell

### ISSUE THREAD

**Issue by name-is-NO** [Shougo/dein.vim#253]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Today,I changed bash to fish when I install high siera.
And brew install vim and I read read.me for dein.vim.
I wrote a text putting out on .vimrc when I used installer.sh
I activated vim.In this time no error.
But,I push :call dean#install(), vim say E177: Unknown function :dein#install
I eliminate comment out

```
 if dein#check_install()
      call dein#install()
endif
```
But, vim only say E177: Unknown function :dein#install.

https://qiita.com/runamoon@github/items/57699d69aa5b80e23ce7
I refered to this qiita.
I add this script on .vimrc.
But can't fixed.

## Environment Information (Required!)

 * dein.vim version(SHA1):Version: 1.0

 * OS:Mac OS high Siera

 * Vim version: 8.0.1400

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/Users/***/.vim/dein/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/Users/***/.vim/dein/specifytheinstallationdirectory')
  call dein#begin('/Users/***/.vim/dein/specifytheinstallationdirectory')

  " Let dein manage dein
  " Required:
  call dein#add('/Users/***/.vim/dein/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim')
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
Please check that the problem is using fish only.

`set shell=bash`

If the problem is from fish, above config fixes it.

I think it is not fish related problem.

**Comment by Shougo** [comment]
Please check whether dein.vim is installed properly in the runtimepath.

```vim
set runtimepath+=/Users/***/.vim/dein/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim
```

I think dein.vim is not installed from the error.

**Comment by name-is-NO** [comment]
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/oosakinaoya/.vim/dein/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/Users/oosakinaoya/.vim/dein/specifytheinstallationdirectory')
  call dein#begin('/Users/oosakinaoya/.vim/dein/specifytheinstallationdirectory')

  " Let dein manage dein
  " Required:
  call dein#add('/Users/oosakinaoya/.vim/dein/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  " You can specify revision/branch/tag.
  call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

if $SHELL =~ '/fish$'
  set shell=/bin/bash
endif
"End dein Scripts-------------------------

This is .vimrc
But now I rewrite set shell in front of dein script.

**Comment by Shougo** [comment]
> But,I push :call dean#install(), vim say E177: Unknown function :dein#install

`dean#install` ?

**Comment by name-is-NO** [comment]
dean#install I push.

E107 Missing parentheses: dein#install

**Comment by Shougo** [comment]
`:call dein#install()` is correct.

**Comment by Shougo** [comment]
I want to check the screencast.

Please use https://asciinema.org/.

**Comment by Shougo** [comment]
Please upload `:verbose set runtimepath?` result and `:scriptnames` result.

**Comment by name-is-NO** [comment]
:verbose set runtimepath?

runtimepath=~/.vim,/usr/local/share/vim/vimfiles,~/.vim/dein/specifytheinstallationdirec
tory/repos/github.com/Shougo/dein.vim,~/.vim/dein/specifytheinstallationdirectory/.cache/.
vimrc/.dein,/usr/local/share/vim/vim80,~/.vim/dein/specifytheinstallationdirectory/.cache/
.vimrc/.dein/after,/usr/local/share/vim/vimfiles/after,~/.vim/after
        Last set from ~/.vim/dein/specifytheinstallationdirectory/state_vim.vim

:scriptnames

 1: ~/.vimrc
  2: ~/.vim/dein/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim/autoload
/dein.vim
  3: ~/.vim/dein/specifytheinstallationdirectory/state_vim.vim
  4: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/filetype.vim
  5: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/ftplugin.vim
  6: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/indent.vim
  7: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/syntax/syntax.vim
  8: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/syntax/synload.vim
  9: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/syntax/syncolor.vim
 10: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/getscriptPlugin.vim
 11: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/gzip.vim
 12: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/logiPat.vim
 13: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/manpager.vim
 14: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/matchparen.vim
 15: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/netrwPlugin.vim
 16: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/rrhelper.vim
 17: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/spellfile.vim
 18: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/tarPlugin.vim
 19: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/tohtml.vim
 20: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/vimballPlugin.vim
 21: /usr/local/Cellar/vim/8.0.1400_4/share/vim/vim80/plugin/zipPlugin.vim

**Comment by Shougo** [comment]
Hm.
dein.vim seems works.

**Comment by Shougo** [comment]
Please upload `:verbose function` result.

**Comment by name-is-NO** [comment]
Last login: Wed Jan 24 19:28:29 on ttys000
Welcome to fish, the friendly interactive shell
 ~  cd .vim/bundles/
 ~/.v/bundles  curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2355  100  2355    0     0   7683      0 --:--:-- --:--:-- --:--:--  7671
 ~/.v/bundles  sh ./installer.sh {specifytheinstallationdirectory}
Install to "/Users/oosakinaoya/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim"...

git is /usr/bin/git

Begin fetching dein...
Cloning into '/Users/oosakinaoya/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim'...
remote: Counting objects: 4662, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 4662 (delta 18), reused 44 (delta 14), pack-reused 4607
Receiving objects: 100% (4662/4662), 916.01 KiB | 1.27 MiB/s, done.
Resolving deltas: 100% (2666/2666), done.
Done.

Please add the following settings for dein to the top of your vimrc (Vim) or init.vim (NeoVim) file:


"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/oosakinaoya/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/Users/oosakinaoya/.vim/bundles/specifytheinstallationdirectory')
  call dein#begin('/Users/oosakinaoya/.vim/bundles/specifytheinstallationdirectory')

  " Let dein manage dein
  " Required:
  call dein#add('/Users/oosakinaoya/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  " You can specify revision/branch/tag.
  call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------


Done.
Complete setup dein!
 ~/.v/bundles  cd
 ~  sudo vim .vimrc
Password:
 ~  vim

function <SNR>25_init_job(process, context, cmd) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function dein#util#_load_merged_plugins() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/util.vim
function dein#install(...) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
function dein#parse#_name_conversion(path) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim
function dein#autoload#_on_map(mapping, name, mode) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/autoload.vim
function <SNR>5_generate_dummy_mappings(plugin) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim
function dein#util#_uniq(list) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/util.vim
function dein#recache_runtimepath() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
function dein#install#_copy_directories(srcs, dest) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function dein#parse#_dict(plugin) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim
function dein#get_progress() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
function <SNR>25_generate_ftplugin() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function <SNR>25_init_context(plugins, update_type, async) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function dein#parse#_add(repo, options) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim

**Comment by Shougo** [comment]
```
function dein#install(...) abort
Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
```

`dein#install()` is defined.
Really does not work?

**Comment by name-is-NO** [comment]
function <SNR>25_init_job(process, context, cmd) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function dein#util#_load_merged_plugins() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/util.vim
function dein#install(...) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
function dein#parse#_name_conversion(path) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim
function dein#autoload#_on_map(mapping, name, mode) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/autoload.vim
function <SNR>5_generate_dummy_mappings(plugin) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim
function dein#util#_uniq(list) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/util.vim
function dein#recache_runtimepath() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
function dein#install#_copy_directories(srcs, dest) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function dein#parse#_dict(plugin) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim
function dein#get_progress() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein.vim
function <SNR>25_generate_ftplugin() abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function <SNR>25_init_context(plugins, update_type, async) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/install.vim
function dein#parse#_add(repo, options) abort
        Last set from ~/.vim/bundles/specifytheinstallationdirectory/repos/github.com/Shou
go/dein.vim/autoload/dein/parse.vim

**Comment by name-is-NO** [comment]
wait, now ,dein is working...!!But why? I don't understand the reason....

**Comment by Shougo** [comment]
I don't know why...
