### ISSUE TITLE
hot to add fatih/vim-go plugin 

### ISSUE THREAD

**Issue by qballer** [Shougo/dein.vim#254]
please bare with me as I'm new to vim concepts. 

# Problems summary
when i do ```call dein#install()``` it says that it can't find the plugin after adding fatih/vim-go

## Expected
to install the plugin

## Environment Information (Required!)

 * dein.vim version(SHA1):  83232de7ef24d8bb9e7d9bd3d101d90991b75173 

 * OS: macos Darwin

 * Vim/neovim version: 0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
set runtimepath+=/Users/qballer/.vim/dein/repos/github.com/Shougo/dein.vim/

if dein#load_state(expand('~/.vim/dein/'))
  call dein#begin(expand('~/.vim/dein/'))

  call dein#add('Quramy/vim-js-pretty-template')
  call dein#add('jason0x43/vim-js-indent')
  call dein#add('joshdick/onedark.vim')
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')
  call dein#add('leafgarland/typescript-vim')
  call dein#add('fatih/vim-go')
  call dein#end()
  call dein#save_state()
endif

```

## The reproduce ways from Vim starting (Required!)
add the package and install

**Comment by Shougo** [comment]
`when i do call dein#install() it says that it can't find the plugin after adding fatih/vim-go`

It seems `vim-go` is already installed or dein cannot find `vim-go` definition.
Please check your installed directory.

**Comment by qballer** [comment]
``` bash
 ~/.vim/dein/repos/github.com  ls -la                                            
total 0
drwxr-xr-x  8 qballer  staff  256 Jan 17 01:53 .
drwxr-xr-x  3 qballer  staff   96 Jan 17 01:52 ..
drwxr-xr-x  3 qballer  staff   96 Jan 17 01:53 Quramy
drwxr-xr-x  3 qballer  staff   96 Jan 17 01:52 Shougo
drwxr-xr-x  3 qballer  staff   96 Jan 17 01:53 jason0x43
drwxr-xr-x  3 qballer  staff   96 Jan 17 01:53 joshdick
drwxr-xr-x  3 qballer  staff   96 Jan 17 01:53 leafgarland
drwxr-xr-x  4 qballer  staff  128 Jan 17 01:53 vim-airline
 ~/.vim/dein/repos/github.com 
```

**Comment by Shougo** [comment]
Hm.  Please remove the cache by `call dein#recache_runtimepath()`.

**Comment by qballer** [comment]
recache and then install solved it.

**Comment by Shougo** [comment]
OK
