### ISSUE TITLE
The installation of the plugin doesn't end

### ISSUE THREAD

**Issue by boldowa** [Shougo/dein.vim#255]
# Problems summary
The installation of the plugin doesn't end.
(**This issue is reproduced every time.**)

## Expected
After displaying the following message, I expected to return to edit screen.
`
[dein] Done: (2018/01/28 13:22:39)
`

## Actual
`
[dein] Done: (2018/01/28 13:22:39)
`

Processing doesn't proceed after displaying the above message, it no longer accepts input other than Ctrl + C.
In the case of Vim, the following message is displayed.

    [dein] Updated plugins:
    [dein]   unite.vim(1 change)
    [dein] Done: (2018/01/28 13:48:05)

<Interrupt with Ctrl+C>

    ^C[dein] Error generating helptags:
    [dein] Vim:Interrupt
    [dein] function dein#install[1]..dein#install#_update[35]..<SNR>13_update_loop[5]..
    <SNR>13_install_async[9]..<SNR>13_done[7]..dein#install#_recache_runtimepath[20]..
    <SNR>13_helptags[10]..<SNR>13_copy_files[6]..dein#install#_copy_directories[37]..
    <SNR>13_list_directory[1]..dein#util#_globlist, line 1
    ^C[dein] Vim:Interrupt
    [dein] function dein#install[1]..dein#install#_update[35]..<SNR>13_update_loop[5]..
    <SNR>13_install_async[9]..
    <SNR>13_done[7]..dein#install#_recache_runtimepath[44]..dein#util#_save_merged_plugins, line 1
    Press ENTER or type command to continue

Also, if it interrupts processing with Ctrl + C, load_state will fail at next startup, failing to load plugin.

## Environment Information

 * dein.vim version(SHA1):
current latest (50629ab368b1cbdfcea0c11aa6276190bf21ca67)

 * OS: **Arch Linux** (Linux  4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux)
 * Vim version : Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:15:12)
 * Neovim version : v0.2.2

## Provide a minimal .vimrc with less than 50 lines

```vim
"-------------------------------------------------
" dein initial script
"-------------------------------------------------

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=$HOME/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state($HOME.'/.cache/dein')
  call dein#begin($HOME.'/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add($HOME.'/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')
  "call dein#add('w0rp/ale')
  "Use unite.vim because it's easy to verify the installation.
  call dein#add('Shougo/unite.vim')

  " You can specify revision/branch/tag.
  "call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from Vim starting

 1. Save the above vimrc as ~ / init.vim
 2. Install dein with the following procedure.
```sh
$ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > dein_installer.sh
$ sh ./dein_installer.sh ~/.cache/dein
```
 3. Launch Neovim (Vim) as `nvim -u ~/init.vim` or ` vim -u ~/init.vim`

---

**[Japanese]**

# 概要
プラグインのインストールが完了しません。
(**この問題は毎回再現します**)

## 想定する動作
以下のメッセージの表示後、vimの編集画面に戻ることを期待していました。
`
[dein] Done: (2018/01/28 13:22:39)
`

## 実際の動作
`
[dein] Done: (2018/01/28 13:22:39)
`

上記メッセージの表示後、処理が進まなくなり、Ctrl+C 以外の入力を受け付けなくなりました。
また、vimの場合は、以下のメッセージが表示されます。

    [dein] Updated plugins:
    [dein]   unite.vim(1 change)
    [dein] Done: (2018/01/28 13:48:05)

<Ctrl+C で中断>

    ^C[dein] Error generating helptags:
    [dein] Vim:Interrupt
    [dein] function dein#install[1]..dein#install#_update[35]..<SNR>13_update_loop[5]..
    <SNR>13_install_async[9]..<SNR>13_done[7]..dein#install#_recache_runtimepath[20]..
    <SNR>13_helptags[10]..<SNR>13_copy_files[6]..dein#install#_copy_directories[37]..
    <SNR>13_list_directory[1]..dein#util#_globlist, line 1
    ^C[dein] Vim:Interrupt
    [dein] function dein#install[1]..dein#install#_update[35]..<SNR>13_update_loop[5]..
    <SNR>13_install_async[9]..
    <SNR>13_done[7]..dein#install#_recache_runtimepath[44]..dein#util#_save_merged_plugins, line 1
    Press ENTER or type command to continue

また、Ctrl+Cで処理を中断した場合、次回起動時のload_stateが失敗するようになり、
プラグインの読み込みに失敗します。

## 環境

 * dein.vim version(SHA1):
current latest (50629ab368b1cbdfcea0c11aa6276190bf21ca67)

 * OS: **Arch Linux** (Linux  4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux)
 * Vim version : Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:15:12)
 * Neovim version : v0.2.2

## 問題発生時のvimrc

```vim
"-------------------------------------------------
" dein initial script
"-------------------------------------------------

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=$HOME/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state($HOME.'/.cache/dein')
  call dein#begin($HOME.'/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add($HOME.'/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')
  "call dein#add('w0rp/ale')
  "インストール確認がしやすいので、unite,vimを使用する
  call dein#add('Shougo/unite.vim')

  " You can specify revision/branch/tag.
  "call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

## 再現手順

 1. 上記vimrcを ~/init.vim に保存する
 2. 以下手順でdeinをインストールする
```sh
$ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > dein_installer.sh
$ sh ./dein_installer.sh ~/.cache/dein
```
 3. `nvim -u ~/init.vim` もしくは `vim -u ~/init.vim` として、Neovim(Vim)を起動する

**Comment by Shougo** [comment]
Really?
I cannot reproduce the problem.

**Comment by Shougo** [comment]
> Also, if it interrupts processing with Ctrl + C, load_state will fail at next startup, failing to load plugin.

You need to `call dein#recache_runtimepath()` manually.

**Comment by Shougo** [comment]
Please check `call dein#recache_runtimepath()` works properly.
Seems `writefile()` failed.

Please test it in another machine.

**Comment by boldowa** [comment]
I tried it in the environment below.
A similar problem has occurred.

## Environment
 * OS : Debian 9 (x64)
 * Neovim version: 0.1.7

## Error log
	Error detected while processing function <SNR>31_timer_handler[1]..dein#install#_polling[1]..<SNR>
	31_install_async[5]..<SNR>31_check_loop[5]..<SNR>31_sync[39]..<SNR>31_init_process[40]..<SNR>31_in
	it_job[66]..<SNR>31_convert_args:
	line    2:
	E121: Undefined variable: v:t_list
	Press ENTER or type command to continue
	Error detected while processing function <SNR>31_timer_handler[1]..dein#install#_polling[1]..<SNR>
	31_install_async[5]..<SNR>31_check_loop[5]..<SNR>31_sync[39]..<SNR>31_init_process[40]..<SNR>31_in
	it_job[66]..<SNR>31_convert_args:
	line    2:
	E15: Invalid expression: type(args) != v:t_list
	Press ENTER or type command to continue
	Error detected while processing function <SNR>31_timer_handler[1]..dein#install#_polling[1]..<SNR>
	31_install_async[5]..<SNR>31_check_loop:
	line    5:
	E170: Missing :endwhile
	Press ENTER or type command to continue
	[dein] Done: (2018/01/28 14:58:49)
	Press ENTER or type command to continue

## Additional Information
> Processing doesn't proceed after displaying the above message, it no longer accepts input other than Ctrl + C.
It doesn't happen when `call dein#install()` is executed manually.
It seems to occur only when executed from vimrc.

**Comment by Shougo** [comment]
> Neovim version: 0.1.7

Too old.
Please install the latest version.
