### ISSUE TITLE
Update not work anymore under windows

### ISSUE THREAD

**Issue by zdm** [Shougo/dein.vim#256]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Hi,
After latest commits dein#update command stop working under windows. On linux it works. Please, look at screenshot below.

## Environment Information (Required!)

 * dein.vim version(SHA1):

 * OS: windows 10 x64

 * Vim/neovim version: vim 8.0.1437

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

## The reproduce ways from Vim starting (Required!)
call dein#update()

## Screen shot (if possible)
![screenshot 2018-01-29 11 25 42](https://user-images.githubusercontent.com/1025608/35503013-8c73b74a-04e7-11e8-9054-97711018e07c.png)

**Comment by Shougo** [comment]
???

I don't understand why it does not work.

**Comment by Shougo** [comment]
I think `git` cannot be executed in the shell.

**Comment by Shougo** [comment]
Please execute `call system('git rev-parse HEAD')` in the plugin directory in Vim.

**Comment by zdm** [comment]
```
call system('git rev-parse HEAD')
```
returns nothing

**Comment by Shougo** [comment]
Please test it instead.

```vim
call system('"git" "rev-parse" "HEAD"')
```

**Comment by zdm** [comment]
also nothing
also, I am tried call system('dir') and also got no results

**Comment by Shougo** [comment]
Please execute it in the plugin directory(you have already installed).
It must return the revision number.

**Comment by Shougo** [comment]
> also, I am tried call system('dir') and also got no results

It seems broken.
Please check your configuration.

**Comment by Shougo** [comment]
```
Provide a minimal .vimrc with less than 50 lines (Required!)

" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

Have you read the issue template?

**Comment by zdm** [comment]
I executing in the git repo dir.
What and how it should return?
Could you tell me, where system call should return results? To the current vim buffer?

>>> please, check your configuration
nothing was changed

**Comment by Shougo** [comment]
> I executing in the git repo dir.
> What and how it should return?

Please check your Vim current directory.
It must return the revision number.(again)

You should create the minimal vimrc.

**Comment by zdm** [comment]
ok, so git rev-parse HEAD works and returns HEAD hash

**Comment by zdm** [comment]
git is works and accessible from vim

**Comment by Shougo** [comment]
It works?

Please execute the below command in the same directory.

`echo dein#install#_system(['git', 'rev-parse', 'HEAD'])`

**Comment by zdm** [comment]
```
The system cannot find the path specified
```

**Comment by Shougo** [comment]
Please execute it instead.

`echo dein#install#_system(['"git" "rev-parse" "HEAD"'])`

**Comment by zdm** [comment]
this issue appears on this commit:

HEAD is now at 764eab6 Use vital-System-Job instead

**Comment by hokorobi** [comment]
I am also using Windows10 x64, but I do not get such an error.

**Comment by Shougo** [comment]
Please use the latest version.

**Comment by zdm** [comment]
works, thank you
