### ISSUE TITLE
Setting vim in dropbox synced directory to share between machines

### ISSUE THREAD

**Issue by mslawins** [Shougo/dein.vim#257]
Hey Shougo,

# Problems summary & expected

The thing I'm trying to achieve is to set up Vim with all dependencies, plugins, configs etc. in Dropbox synced directory to skip annoying installation process each time I'm changing machine or problem of updating vimrc on one machine when there was commit made with some changes on the other machine.

On my main machine (MacOS High Sierra) I have set up vim config [here is a repository](https://github.com/mslawins/configs). Now when I'm trying to share it with other Mac or Ubuntu Linux I'm getting an error. Those errors are detailed below.

I would like to know if it is even possible to achieve what I'm trying to do with dein.vim. If yes, then how? If no, can someone point me to solution of my problem? 

## Environment Information (Required!)

 * dein.vim version(SHA1): 5bbff63c

 * OS: MacOS High Sierra / Ubuntu Linux 16.04 LTS

 * Vim/neovim version: Vim 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

[Here it is](https://github.com/mslawins/configs/blob/master/vim/dein.vim)

## The reproduce ways from Vim starting (Required!)

Hard to reproduce I guess without using Dropbox. Instructions would something like:

1. In dropbox sync account clone my repository
2. Install dein.vim with ~/Dropbox/configs/vim/plugins path
3. Run vim and install  packages (:call dein#install())
4. Use another machine with vimrc pointing to dropbox:
set runtimepath+=~/Dropbox/configs/vim
source ~/Dropbox/configs/vim/vimrc.vim
5. Run vim
6. Type :messages

## Upload the log messages by `:redir` and `:message` (if errored)

:message output:

E185: Cannot find color scheme 'gruvbox'
Error detected while processing FuncUndefined Auto commands for "*":
E218: autocommand nesting too deep
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
Error detected while processing function dein#recache_runtimepath:
line    1:
E117: Unknown function: dein#install#_recache_runtimepath
E492: Not an editor command: log
E475: Invalid argument: 

Thanks in advance for any help.

**Comment by Shougo** [comment]
dein.vim is not installed properly in the shared directory.
You should check synced Dropbox directory.
So I cannot support it.
Sorry.

**Comment by mslawins** [comment]
For anyone trying to achieve similar things as I did:

- reason dein.vim is not working is cache syncing, those files should be excluded on each machine: .cache, cache_vim, state_vim.vim
- therefor it is probably good idea to recache dein.vim on vim startup (not sure about performance), to have the same environment on each machine
- this workflow works until you want to use complex plugins (fzf / YCM etc) cross platform, for that situation this simple sync solution will not work
