### ISSUE TITLE
not running build at update()

### ISSUE THREAD

**Issue by Palpatineli** [Shougo/dein.vim#258]
# Command inside 'build' is not run again at dein#update()
## Expected
If a binary is required to be built/downloaded/etc at install time, it should be acquired the same way when the source is updated.

## Environment Information (Required!)

 * dein.vim version(SHA1): git head 5bbff63c09126580ed1ef0df8ed2496d4c0fee82
 * OS: Debian testing
 * Vim/neovim version: neovim 0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
    if has('win32') || has('win64')
        set runtimepath+=~/AppData/Local/nvim/dein/repos/github.com/Shougo/dein.vim " path to dein.vim
    else
        set runtimepath+=~/.config/nvim/dein/repos/github.com/Shougo/dein.vim " path to dein.vim
    endif
    call dein#begin(expand('~/.config/nvim/dein')) " plugins' root path
    call dein#add('Shougo/dein.vim')
    call dein#add('autozimu/LanguageClient-neovim', {'rev': 'next', 'build': 'bash install.sh'})
    call dein#end()
    call dein#remote_plugins()
```

## The reproduce ways from Vim starting (Required!)

 1. call dein#update()<cr>
 2. check in ~/.config/nvim/dein/repos/githum.com/autozimu/LanguageClient-neovim/bin
 3. languageclient binary is not updated (it's supposed to be downloaded in the install.sh script); if you delete the file before update, it's not there after update.
 4. manually running bash install.sh downloads the binary successfully
 5. comment out the LanguageClient-neovim line, run so %<cr>; call dein#check_clean(), quit, delete the autozimu folder and reopen init.vim, uncomment the line, run call dein#install(). This time the binary file appears in the correct place.

**Comment by Shougo** [comment]
> not running build at update()

> languageclient binary is not updated (it's supposed to be downloaded in the install.sh script); if you delete the file before update, it's not there after update.

languageclient binary is updated only if the plugin is installed/updated.
Not after `dein#update()`.

So it is the feature.  You can execute build manually by `dein#build()`.

Closing.
