### ISSUE TITLE
Uninstall plugins

### ISSUE THREAD

**Issue by DavidParkin** [Shougo/dein.vim#259]
What is the dein way to remove an unwanted plugin?

**Comment by Shougo** [comment]
* Remove the `dein#add()` line

* `call dein#recache_runtimepath()`

* `call map(dein#check_clean(), "delete(v:val, 'rf')")`

**Comment by DavidParkin** [comment]
Thank you.

**Comment by Shougo** [comment]
I don't understand your problem.

`dein#check_clean()` just removes the invalid plugins.

**Comment by DavidParkin** [comment]
Well, I repeated the procedure just to make sure it wasn't me doing something stupid. However the Shougo directory was empty. Note my histfile  contained no dodgy deletes.

What does the map and the delete var do?

**Comment by Shougo** [comment]
`dein#check_clean()` just returns the unneeded plugins path.
So, it can be removed by `call map(dein#check_clean(), "delete(v:val, 'rf')")`.
