### ISSUE TITLE
the dein not work, after :call dein#check_clear.

### ISSUE THREAD

**Issue by hackrole** [Shougo/dein.vim#260]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I want to use    "fatih/vim-go" instead of "Blackrush/vim-gocode",
so I change my vimrc from
```vimscript
    call dein#add("Blackrush/vim-gocode")
```
to 
```vimscript
    "call dein#add("Blackrush/vim-gocode")
    call dein#add("fatih/vim-go")
```
I then :call dein#check_clear()(I was thought this is the way to clean unused plugin).
after that, the nvim seems not load any plugin at all.

I do not know what to do now.

## Environment Information (Required!)

 * dein.vim version(SHA1):  5bbff63c09126580ed1ef0df8ed2496d4c0fee82 Shougo/dein.vim (1.0-23-g5bbff63)

 * OS:  mac os 10.11.6 (15G1217)

 * Vim/neovim version: NVIM v0.2.2

**Comment by hackrole** [comment]
I make it work by :call dein#recache_runtimepath(), the doc save me.

**Comment by Shougo** [comment]
OK
