### ISSUE TITLE
[question] how to disable plugin on specific filetype?

### ISSUE THREAD

**Issue by Palpatineli** [Shougo/dein.vim#267]
# Summary

I have a plugin that I want to run when the ft is not python. How do I acheive that without specifying all the filetypes? 

(why? It's because I'm using LanguageClient-neovim but pyls is not working properly for me, so I turn on ale for python only, but I have a bunch of lsp related settings bundled into a plugin and I need to turn it off when ale is on)

My kludge solution:
```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('palpatinli/lsp-addon', {'on_if': "&ft != 'python"})
call dein#end()
```
But I wonder if there is a switch with 'on_ft' that gives me the same result?

**Comment by Shougo** [comment]
It cannot(Not plugin manager work).
dein.vim can `enable plugin on specific filetype`.
But dein.vim cannot `disable plugin on specific filetype`.

So you should disable lsp in lsp plugin config in Python filetype.
