### ISSUE TITLE
The lastest version of dein.vim cause E741 error

### ISSUE THREAD

**Issue by whisper404** [Shougo/dein.vim#27]
# Problems summary
After I updated dein.vim this morning, I think dein#save_cache() cause vim error. But works fine in neovim. Without  save_cache also works fine in vim.

## Environment Information
 * OS: OS X El Capitan 10.11.3
 * Vim version: 7.4.1468 or MacVim 7.4.1362, NVIM v0.1.3-250-gb01db02

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set nocompatible
let s:cache_dir = expand('~/.cache/')
execute 'set runtimepath^=' . s:cache_dir . '/dein/repos/github.com/Shougo/dein.vim'
call dein#begin(s:cache_dir . '/dein')
if dein#load_cache()
      call dein#add('Shougo/dein.vim')
      call dein#add('xxxxxx.vim') " any other plugin. I tried lightline and neocompletein this minimal vimrc
      call dein#save_cache()
endif
call dein#end()
filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

 1. First run command call dein#clear_cache() in vim then quit.
 2. Open vim again. No error shows at this time. Then quit.
 3. Open vim. This time the error comes up.

## Upload the log messages by `:redir` and `:message`
Error detected while processing function dein#end:
line   34:
E741: Value is locked: plugin.sourced = 1

**Comment by j138** [comment]
:+1:

**Comment by zchee** [comment]
@whisper404 Hi,

I tested this `.vimrc`, but not occur error.
https://gist.github.com/zchee/8ef9cbc6379c65e280c9

- cache_dir: `~/.cache/vim`
- config_dir: `~/.config/vim`
- dein_dir: `~/config/vim/dein.vim` or `~/.cache/vim/dein/repos/github.com/Shougo/dein.vim`

Could you re-try use this `.vimrc`?

**Comment by whisper404** [comment]
https://gist.github.com/whisper404/0cce79fde55b554bc523
Here is the process of use this vimrc. And still got this error.

**Comment by Shougo** [comment]
@whisper404 Please test below script without dein.vim.
It may be Vim's problem.  We cannot reproduce though.

```vim
let plugins = {'foo': {'sourced': 0}}
let plugins2 = json_decode(json_encode(plugins))
let plugins2['foo'].sourced = 1
```

**Comment by Shougo** [comment]
I have reproduced the above script...
It is Vim's bug...

**Comment by Shougo** [comment]
I have removed json support.

**Comment by whisper404** [comment]
Thank you for fix. Now it works fine.
