### ISSUE TITLE
Install steps are failing for Neovim on Mac

### ISSUE THREAD

**Issue by ZackC** [Shougo/dein.vim#270]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When I try to open neovim with the vimrc file specified in the readme at step 2, I get the error: 
$ nvim ~/.config/nvim/init.vim 
nvim(4557,0x7fff9d114380) malloc: *** error for object 0x7fdb3dd00710: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

This error prevents me from doing step 3.

I'm following the installation instructions specified in the Readme with the exception that I have put the config file in ~/.config/nvim/init.vim.  

Happy to provide more information if needed. If so, let me know!

## Expected

I expect nvim to be able to open a file with the the specified vimrc

## Environment Information (Required!)

 * dein.vim version(SHA1): 246c7998281455db76b65e85400c3f91029bbb29

 * OS: new MacBookPro with MacOS 10.13.4.  

 * Vim/neovim version: 0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

if &compatible
 set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
 call dein#begin('~/.cache/dein')

 call dein#add('~/.cache/dein')
 call dein#add('Shougo/deoplete.nvim')
 if !has('nvim')
   call dein#add('roxma/nvim-yarp')
   call dein#add('roxma/vim-hug-neovim-rpc')
 endif

 call dein#end()
 call dein#save_state()
endif

filetype plugin indent on
syntax enable

## The reproduce ways from Vim starting (Required!)

 1. do step 1 in the readme
 2. do step 2 in the readme
 3. try to open a file with nvim

## Screen shot (if possible)
<img width="568" alt="deinerror" src="https://user-images.githubusercontent.com/1201039/38887994-52bfe7c8-4248-11e8-9234-06522780adf0.png">

## Upload the log messages by `:redir` and `:message` (if errored)

**Comment by Shougo** [comment]
It is not dein.vim error.
It seems neovim bug.
It should be reported in neovim issues.

But your neovim is old.
Please test the latest version of neovim.

**Comment by ZackC** [comment]
Ok. Thanks. Tough to tell when it only seems to break with Dein, but I haven't fully tested neovim yet either.

Also, what makes you say that it is an old version of neovim? Their website (https://neovim.io) says that 0.2.2 is the latest version.  It's also the latest version on Homebrew. I'm curious what I am missing. Are your referring to it not being the latest unstable version?

**Comment by kiooss** [comment]
@ZackC I think the "the latest version of neovim" from Shougo is the **latest unstable version** of neovim, but not the latest stable version^^

**Comment by Shougo** [comment]
> @ZackC I think the "the latest version of neovim" from Shougo is the latest unstable version of neovim, but not the latest stable version^^

Yes
