### ISSUE TITLE
Load Plugin Configuration with Hook

### ISSUE THREAD

**Issue by weilbith** [Shougo/dein.vim#275]
Hey! :)
I used to put all configurations for a single plugin into an extra `.vim` file. By this I like to source this configuration for each plugin after it has been added by _dein.vim_. I wrote a tiny source function, which should be called by the `hook_add` hook. The idea was to use the `dein#name` variable to get the name of the current plugin, this hook is called for.
> g:dein#name
> Current plugin name.

Unfortunately this variable seems to contain the name of the current file it is defined/called in. This is what I have wrote, where I explicit define the plugin name for test proposes:

```vim 
function! Source() abort
  let l:config = g:base_configuration_folder . 'plugin-configuration/' . g:dein#name . '.vim'

  if filereadable(l:config)
    execute 'source ' . l:config
  endif
endfunction

" Add dein.vim as plugin manager.
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

" Add all plugins and their configurations.
if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein')

  call dein#add('easymotion/vim-easymotion', {
      \   'name': 'testname',
      \   'hook_add': function('Source')
      \ })

  call dein#end()
  call dein#save_state()
endif
```

A quick echo output in the `Source` function get me the point, that `g:dein#name` isn't `testname` as expected, but the name of the `.vim` file, this code is written.
What am I doing wrong. Can u help me please?

---

Furthermore it would be awesome to not have to define this for each new plugin again. There is the function `dein#set_hook`, which allows to define a hook for a specific plugin by its name. Unfortunately this works only for a single plugin each call. Other functions allows to give an array of plugin names and interpret an empty list as _all_ plugins. It would be awesome if I could simply define this hook for all plugins with a single line. Is this possible? Am I missed something?

Thank u very much for ur help!

**Comment by Shougo** [comment]
Please read the documentation.

```
                                                                 *g:dein#name*
g:dein#name
		Current plugin name.
		You can use it in |dein#tap()| block.
```

It does not work for hooks.

**Comment by weilbith** [comment]
Okay. First I like to say, that this could be rephrased, cause not sure how others see that, but it's not that 100% clear. So something more strong like "This variable is only available in a |dein#tap()| block." would help to avoid such disaccords. 
And furthermore: is it maybe possible to extend this? Would it be an problem to make this variable also available in hooks? Or maybe extend hooks by call hook-functions with an argument which is the plugin name, the hook is called for? Guess this is quite useful for a lot of scenarios, where u use a function as hook.

**Comment by Shougo** [comment]
> Guess this is quite useful for a lot of scenarios, where u use a function as hook.

Why it is needed?
You can plugin name by `g:dein#plugin.name`.

I don't want to set `g:dein#name`...
It is deprecated variable.

**Comment by weilbith** [comment]
1. Needed as example in my use case described in the issue message. :'D
2. Thanks! Haven't tried it yet, but sounds as it could be my solution here. Why don't start with such answer. ^^
3. Understandable. Cause I don't get the use case for this variable. If I request for a specific plugin in the `tap()` function, why I need this variable if it is only available in this block. But don't mind this.

**Comment by weilbith** [comment]
Besides: Thanks for this awesome plugin. It offers unique and awesome options. Also if it is not so easy to handle and understand, cause it is so different than other plugin managers. Have read the documentation two times (will have to read it more times again) and start to read the whole issue history (okay, not the **whole**), to get around all this typical problems and understand the behavior.

**Comment by weilbith** [comment]
Wow, thanks for implementing this! 😄🙏

**Comment by Shougo** [comment]
@weilbith You can improve the documentation.

> Also if it is not so easy to handle and understand, cause it is so different than other plugin managers. 

My plugins are not for beginner.
Yes, the documentation is not easy understand.
But other plugins do not have many features or customization like them.

**Comment by weilbith** [comment]
@Shougo

I define the whole dein begin-end block in an extra file, I source in my original `init.vim`. Therefore I've define `call dein#begin(s:dein_base_folder, [expand("%:p')])`, so changes are recognized. 
As described above, I load all plugin configurations through hooks (are exported as files with plugin name as file name). If I change now something in any configuration file, does this not get into effect, cause the whole thing is cached and the configuration file is not loaded again? So do I have to extend the list in `dein#begin` by all configuration files? Else I don't rly get, why this is a list? 🤔

**Comment by Shougo** [comment]
@weilbith 

> So do I have to extend the list in dein#begin by all configuration files? 

You need to specify the script list.

```
							*dein#begin()*
dein#begin({base-path}, [{vimrcs}])
```

dein.vim detects vimrcs changes.

**Comment by weilbith** [comment]
So, as all plugin configurations are vim scripts, I have to. Okay. I will try it out and see if I recognize an effect.

**Comment by weilbith** [comment]
I guess doing something like
```vim
let s:vimrcs = add(extend(g:config_base_folder . '/plugins/*.vim`), extend('%:p'))
call dein#begin(s:dein_base_folder, s:vimrcs)
```
is a better solution, isn't it?

**Comment by Shougo** [comment]
> Are wildcards allowed as entry in the `[{vimrc}]` array?

You should use `glob()`.

```
glob({expr} [, {nosuf} [, {list} [, {alllinks}]]])		*glob()*
		Expand the file wildcards in {expr}.  See |wildcards| for the
		use of special characters.
```

And `glob()` can return list.  It is better solution.

**Comment by weilbith** [comment]
Ah okay. I guess it's advantage comes by the point it can put all files in a list (if argument is given), instead of having to split the extend output myself. 

Seems to work for now. Will continue working and experimenting with it. Also if I still struggle with some _airline_ issues. But I will open a new issue for that, if I don't get it solved. 
Awesome to work with this plugin! It's fun. :)
