### ISSUE TITLE
Unkown Plugin Function On Hook Add

### ISSUE THREAD

**Issue by weilbith** [Shougo/dein.vim#277]
# Problems summary
When I call a function from a plugin in its `hook_add`, it throws an _unkown function_ error. 
As far as I understand, for non-lazy plugins, there is only the `hook_add` hook, where for lazy ones also the `hook_source` and `hook_post_source` event is thrown. As I read, for non-lazy plugins, this is all the same. Furthermore I could confirm, that no more hooks are called for non-lazy plugins, than the `hook_add`. But if I put a function call into the hook, which is defined by this plugin itself, I get a function unkown exeption.
Also if this behavior seems to be solved after a second time I start nvim, the appereance is destroyed afterwards (example with airline).

Conclusion: 
1st Nvim instance: Airline Theme looks nice, but before it gets up, an unknown function exception is thrown
2nd Nvim instance: No exception, but Airline appearance is destroyed (no arrow separator, no tabling, ...)

Similar behavior of an unknown function exception could been observed on working with the denite.nvim plugin and the `dein#custom#filter()` function.

## Expected
Functions from the non-lazy plugin itself called in its `hook_add` are working.

## Environment Information (Required!)

 * dein.vim version(SHA1):  5940689e
 * OS: Ubuntu 16.4
 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:dein_base_folder = '~/.cache/dein'
execute 'set runtimepath+=' . s:dein_base_folder . '/repos/github.com/Shougo/dein.vim'

if dein#load_state(s:dein_base_folder)
  call dein#begin(s:dein_base_folder)
   
  call dein#add('vim-airline/vim-airline', 
         \ 'merged': 0,
         \ 'hook_add: "call airline#parts#define_accent('mode', 'none')"
         \ })

  call dein#end()
  call dein#save_state()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. Simply start nvim with the provided minimal runtime configuration and the error should occur.

**Comment by Shougo** [comment]
You must use `hook_source` instead.

> As far as I understand, for non-lazy plugins, there is only the hook_add hook, where for lazy ones also the hook_source and hook_post_source event is thrown.

No.  You can use hook_source and hook_post_source for non lazy plugins.

`hook_add` means when dein add the plugin.
`hook_source` means when loading the plugin after adding the path.

It is not same for non lazy plugins.

**Comment by Shougo** [comment]
@weilbith 

> But I can't observe this behaviour. Did I miss something?

```
		Note: non lazy plugins' |dein-options-hook_source| cannot be
		called.  You must call it by |dein#call_hook()| if needed.

		call dein#begin()
		...
		call dein#end()
		call dein#call_hook('source')
```

Sorry, I have forgot the feature.

But please read the documentation...

**Comment by Shougo** [comment]
You need to call `source` hooks manually for non lazy plugins.

**Comment by weilbith** [comment]
Haha okay. I don't get how may times I can read this documentation and always miss something. Sorry for that. 
But I guess the the `post_source` should be fine. :)

**Comment by weilbith** [comment]
Finally I guess I should dunk into the plugin implementation to get a complete understanding of how it works. Thanks for all ur help. Love ur plugins. :+1:
