### ISSUE TITLE
Logical AND for on_ft and on_event (and any other options.)

### ISSUE THREAD

**Issue by Mephistophiles** [Shougo/dein.vim#278]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

if you specify 2 start options at the same time, the plug-in will start by logical or.

## Expected

It would be desirable to have what or a modifier for logic and.

## Environment Information (Required!)

 * dein.vim version(SHA1):
Latest

 * OS:
Arch linux

 * Vim/neovim version:
Neovim 0.2.2-5

**Comment by Shougo** [comment]
No.  I don't want to implement the feature.

You can use `on_if` instead of `on_ft`.

`on_ft` and `on_event` are logical OR.
But `on_if` and `on_event` are logical AND.

Please read the documentation.
