### ISSUE TITLE
Hooks Not Executed When Load Cache

### ISSUE THREAD

**Issue by weilbith** [Shougo/dein.vim#279]
# Problems summary
I recognized, that my hooks are only executed, if _dein_ recache and go trough the configuration. I haven't see it before, cause I was continuously adjusting the _dein_ configuration, so the state polluted.
As shown before in other issues, I load my plugin configurations in hooks for the plugins. That works fine in first place, but doesn't work in further _nvim_ instances, when the cache is used. How can I get these hooks executed also from cache?

## Expected
Hooks are called always, when load from cache or not.

## Environment Information (Required!)

 * dein.vim version(SHA1): 5940689e214d27f258805c24e76d86715622b2a6
 * OS: Ubuntu 16.4
 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:dein_base_folder = '~/.cache/dein'
let s:plugin_configuration_folder = g:base_configuration_folder . 'plugin-configuration/'

function! Source() abort
  " Get the configuration file for the current plugin.
  let l:config = s:base_configuration_folder . 'plugin-configuration/' . g:dein#plugin.name . '.vim'
  let l:config = expand(l:config)

  " Check if the configuration file could been found (not all plugins have one)
  if filereadable(l:config)
    execute 'source ' . l:config
  endif
endfunction

let s:vimrcs = split(expand(s:plugin_configuration_folder . '*.vim')) " All configurations for each plugin.
let s:vimrcs = add(s:vimrcs, expand('<sfile>')) " This file itself.

execute 'set runtimepath+=' . s:dein_base_folder . '/repos/github.com/Shougo/dein.vim'

if dein#load_state(s:dein_base_folder)
  call dein#begin(s:dein_base_folder, s:vimrcs)
  
  call dein#add('Shougo/neosnippet.vim')
  
  call dein#set_hook([], 'hook_post_source', function('Source'))
  call dein#end()
  call dein#save_state()
endif


if has('vim_starting') && dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. Start _nvim_ and check for some global variables defined for the plugins configuration. (will be found)
 2. Close _nvim_.
 3. Start _nvim_ again and check again for the same variable. (is missing)

##
Best example hier is with _neosnippet_ without having installed the snippets, but have disabled them in the configuration. First time everything went fine. Second time, an error is shown by _neosnippet_. Can be observed for many other plugins also.
Removing the sourrounding `if` condition for the state, it works fine. But I would like to use it.

**Comment by Shougo** [comment]
It is feature of `dein#load_state()`.
You cannot use Funcref in `dein#load_state()/dein#save_state()` block.
You must use string instead.

**Comment by Shougo** [comment]
I should update the documentation.

**Comment by Shougo** [comment]
```
HOOKS							*dein-hooks*

		The string will be split by the lines.
		It is useful for the plugins initialization.
		Note: The Function hooks cannot be cached.  You must
		initialize it.
```

**Comment by Shougo** [comment]
Lazy loading works.
But parse and loading is slower than using cache.
It is the same level loading time with vim-plug.

**Comment by weilbith** [comment]
Hmm okay.
Do u c a possible solution where I can still leave my plugin configurations in external files, source them when the plugin gets sourced (some would throw errors if not, cause functions are called to define options e.g. _denite_), but still provide some speed up?
