### ISSUE TITLE
Multiple And Non-Asynchronous Updates By Autocmd

### ISSUE THREAD

**Issue by weilbith** [Shougo/dein.vim#280]
# Problems summary
To don't have to check and install plugin updates manually, I put this into a `augroup` with the `VimEnter` event. The documentation stated, that with _Nvim_ the update function should work asynchronous. Unfortunately is doesn't and my client is blocked as long as it updates.
Furthermore it get updated again and again and again. I can't see in the logs why.

## Expected
The update functions works fine in background so I can continue working.
Ones all plugins are updated, no update is executed as long as no plugin has a new commit/version.

## Environment Information (Required!)

 * dein.vim version(SHA1): 324b547208d3b6b0bfc2923cb666093b2b8ef081
 * OS: Ubuntu 16.4
 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('Shougo/dein.vim')
call dein#end()

augroup DeinUpdate
  autocmd!
  autocmd VimEnter * if dein#check_update() | call dein#update() | endif
augroup END
```

## The reproduce ways from Vim starting (Required!)

 1. Start _NVim_ with a plugin that has an update.
 2. Try to do something while the update is running.

## Log
Update started: (2018/05/21 13:47:11)
(10/41) [====                ] vim-signature
( 2/41) From https://github.com/vim-airline/vim-airline
   02ffdfe..315cf0d  master     -> origin/master

(14/41) [======              ] gutentags
(12/41) From https://github.com/wellle/targets.vim
   c173218..ab5fbfa  master     -> origin/master

(20/41) [=========           ] vim-exchange
(18/41) From https://github.com/ryanoasis/vim-devicons
   c960f30..8ee4c8c  master     -> origin/master
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.1.1     -> v0.1.1
 * [new tag]         v0.1.2     -> v0.1.2
 * [new tag]         v0.1.3     -> v0.1.3
 * [new tag]         v0.1.4     -> v0.1.4
 * [new tag]         v0.10.0    -> v0.10.0
 * [new tag]         v0.2.0     -> v0.2.0
 * [new tag]         v0.2.1     -> v0.2.1
 * [new tag]         v0.3.0     -> v0.3.0
 * [new tag]         v0.3.1     -> v0.3.1
 * [new tag]         v0.3.2     -> v0.3.2
 * [new tag]         v0.3.3     -> v0.3.3
 * [new tag]         v0.3.4     -> v0.3.4
 * [new tag]         v0.4.0     -> v0.4.0
 * [new tag]         v0.4.1     -> v0.4.1
 * [new tag]         v0.4.2     -> v0.4.2
 * [new tag]         v0.4.3     -> v0.4.3
 * [new tag]         v0.4.4     -> v0.4.4
 * [new tag]         v0.5.0     -> v0.5.0
 * [new tag]         v0.5.1     -> v0.5.1
 * [new tag]         v0.5.2     -> v0.5.2
 * [new tag]         v0.5.3     -> v0.5.3
 * [new tag]         v0.5.4     -> v0.5.4
 * [new tag]         v0.6.0     -> v0.6.0
 * [new tag]         v0.6.1     -> v0.6.1
 * [new tag]         v0.7.0     -> v0.7.0
 * [new tag]         v0.7.1     -> v0.7.1
 * [new tag]         v0.8.0     -> v0.8.0
 * [new tag]         v0.8.1     -> v0.8.1
 * [new tag]         v0.8.2     -> v0.8.2
 * [new tag]         v0.8.3     -> v0.8.3
 * [new tag]         v0.8.4     -> v0.8.4
 * [new tag]         v0.8.5     -> v0.8.5
 * [new tag]         v0.8.6     -> v0.8.6
 * [new tag]         v0.9.0     -> v0.9.0
 * [new tag]         v0.9.1     -> v0.9.1
 * [new tag]         v0.9.2     -> v0.9.2
 * [new tag]         v0.9.3     -> v0.9.3

(24/41) [===========         ] nerd-tree_syntax-highlight
(22/41) From https://github.com/Shougo/dein.vim
   5940689..324b547  master     -> origin/master

(30/41) [==============      ] fugitive
(27/41) From https://github.com/Shougo/denite.nvim
   ca124f4..7fb12a3  master     -> origin/master

(34/41) [================    ] lion
(31/41) From https://github.com/tpope/vim-fugitive
   a5a75ac..2a47143  master     -> origin/master

(33/41) From https://github.com/andymass/vim-matchup
   35622fc..c929d7e  master     -> origin/master

(40/41) [=================== ] submode
Done: (2018/05/21 13:48:35)
Update started: (2018/05/21 13:52:13)
(10/41) [====                ] vim-signature
(20/41) [=========           ] vim-exchange
(22/41) [==========          ] twiggy
(30/41) [==============      ] fugitive
(32/41) [===============     ] match-up
(40/41) [=================== ] submode
Done: (2018/05/21 13:53:53)
Update started: (2018/05/21 13:56:17)
(1/1) Updating 5940689..324b547
Fast-forward
 autoload/dein/autoload.vim |  6 +++++-
 autoload/dein/util.vim     | 10 ++++++----
 doc/dein.txt               |  5 +++++
 3 files changed, 16 insertions(+), 5 deletions(-)

(1/1) |dein.vim            | Updated
(1/1) fatal: unrecognized argument: --no-show-signature
Updated plugins:
  dein.vim(1 change)
    https://github.com/Shougo/dein.vim/compare/5940689e214d27f258805c24e76d86715622b2a6...324b547208d3b6b0bfc2923cb666093b2b8ef081
Runtimepath updated: (2018/05/21 13:56:21)
Done: (2018/05/21 13:56:21)
Update started: (2018/05/21 13:56:30)
(10/41) [====                ] vim-signature
(11/41) [=====               ] targets.vim
(20/41) [=========           ] vim-exchange
(21/41) [==========          ] dein.vim
(30/41) [==============      ] fugitive
(31/41) [===============     ] match-tag-always
(39/41) [=================== ] choosewin
Done: (2018/05/21 13:58:05)
Update started: (2018/05/21 14:01:54)
(10/41) [====                ] vim-signature
(20/41) [=========           ] vim-exchange
(30/41) [==============      ] fugitive
(40/41) [=================== ] submode
Done: (2018/05/21 14:03:42)
Update started: (2018/05/21 14:03:51)
(10/41) [====                ] vim-signature
(20/41) [=========           ] vim-exchange
(29/41) [==============      ] agit
(30/41) [==============      ] fugitive
(38/41) [==================  ] close-tag
(40/41) [=================== ] submode
Done: (2018/05/21 14:05:33)
Update started: (2018/05/21 14:10:49)
(10/41) [====                ] vim-signature
(20/41) [=========           ] vim-exchange
(30/41) [==============      ] fugitive
(31/41) [===============     ] match-tag-always
(40/41) [=================== ] submode
Done: (2018/05/21 14:12:34)
Update started: (2018/05/21 14:17:22)
(10/41) [====                ] vim-signature
(11/41) [=====               ] targets.vim
(20/41) [=========           ] vim-exchange
(21/41) [==========          ] dein.vim
(22/41) [==========          ] twiggy
(24/41) [===========         ] nerd-tree_syntax-highlight
(30/41) [==============      ] fugitive
(31/41) [===============     ] match-tag-always
(32/41) [===============     ] match-up
(34/41) [================    ] lion
(40/41) [=================== ] submode
Done: (2018/05/21 14:19:11)
Update started: (2018/05/21 14:23:20)
(10/41) [====                ] vim-signature
(20/41) [=========           ] vim-exchange
(30/41) [==============      ] fugitive
(40/41) [=================== ] submode
Done: (2018/05/21 14:24:59)

**Comment by Shougo** [comment]
You can check async status by `dein#install#_is_async()` in VimEnter autocmd.

**Comment by Shougo** [comment]
But async feature is disabled in `has('vim_starting')` state.

**Comment by Shougo** [comment]
I have tested the script in my vimrc.

```vim
autocmd VimEnter * call dein#update()
```

It is asynchronous.

**Comment by Shougo** [comment]
The update process is asynchronous.
But it is parallel and consumes your background CPU power.

It may be slow.
You can reduce `g:dein#install_max_processes` value.

**Comment by Shougo** [comment]
> Furthermore it get updated again and again and again. I can't see in the logs why.

I cannot reproduce the behavior.
You must create the minimal vimrc.

**Comment by weilbith** [comment]
Ah, thanks for that. I swear I've read the whole documentation again for this. :wink:
I'm not sure if the number of processes are the problem, cause other programs as my web browser have worked fine. Or they are splitted on different cores. Not sure how u spawn them. But I will give it a try of cause. At least when set it to 1, should clear if this is the problem.
