### ISSUE TITLE
on_map question?

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#282]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I can't understand the sentence in dein-options-on_map，see red box in the picture below:
![default](https://user-images.githubusercontent.com/19503791/40342926-ead02a9a-5dbf-11e8-9896-78967743f3f7.png)

**Comment by Shougo** [comment]
It means

```vim
		call dein#add('osyo-manga/vim-anzu', {'on_map': '<Plug>(anzu-'})
```

is same with

```vim
		call dein#add('osyo-manga/vim-anzu', {'on_map': '<Plug>(anzu-foo)'})
```
