### ISSUE TITLE
Depends Abolishs On Command

### ISSUE THREAD

**Issue by weilbith** [Shougo/dein.vim#283]
# Problems summary
If plugin **A** depends on **B** and **B** has a `on_cmd` property, **A** gets loaded without **B** has loaded either.

## Expected
**A** gets loaded when **B** will be sourced based on the defined command.

## Environment Information (Required!)
 * dein.vim version(SHA1): 81a5a46dc503c06661657c2a2bf05ac4bf1f7c96
 * OS: Ubuntu 16.4
 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)
```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('scrooloose/nerdtree', {
      \ 'name': 'nerd-tree',
      \ 'lazy': 1,
      \ 'on_cmd:': ['NERDTree', 'NERDTreeToggle', 'NERDTreeFromBookmark', 'NERDTreeFocus']
      \ })

call dein#add('Xuyuanp/nerdtree-git-plugin', {
      \ 'name': 'nerd-tree_git',
      \ 'depends': 'nerd-tree'
      \ })

call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. Start _NVim_ and call `:echo dein#is_sourced('nerd-tree')`. It print `1`.
 2. Do the negative tests and remove the `nerd-tree_git` plugin, `nerd-tree` is not sourced until call one the listed commands.

**Comment by Shougo** [comment]
> Do the negative tests and remove the nerd-tree_git plugin, nerd-tree is not sourced until call one the listed commands.

I don't understand.
What do you means "Do the negative tests and remove the nerd-tree_git plugin"?

**Comment by Shougo** [comment]
The issue is pending until I understand the problem.

**Comment by Shougo** [comment]
> Setting B (here nerd-tree_git) to lazy also, makes A (here nerd-tree) lazy loaded on the command again, but B does not get loaded after A has.

It is the feature.
If you need to load `B` before `A`, you need to use `on_source` in B.

`:help dein-options-on_source`.

`depends` means `A must be loaded before B`.
It does not mean `B must be loaded before A`.
Please read the documentation :-)

**Comment by Shougo** [comment]
Hm. It jus wrong.

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('scrooloose/nerdtree', {
      \ 'name': 'nerd-tree',
      \ 'on_cmd:': ['NERDTree', 'NERDTreeToggle', 'NERDTreeFromBookmark', 'NERDTreeFocus']
      \ })

call dein#add('Xuyuanp/nerdtree-git-plugin', {
      \ 'name': 'nerd-tree_git',
      \ 'on_source': 'nerd-tree'
      \ })

call dein#end()
```

You need to read/understand dein.vim features carefully....
dein.vim configuration is not easy like vim-plug.
