### ISSUE TITLE
`deol.nvim requires Neovim.` appears when vim is used

### ISSUE THREAD

**Issue by yahonda** [Shougo/dein.vim#284]
# Problems summary
`deol.nvim requires Neovim.` appears when the generated dein scripts used with vim.

## Expected
The generated dein script runs with vim, not only Neovim.

## Environment Information (Required!)

 * dein.vim version(SHA1):81a5a46dc503c06661657c2a2bf05ac4bf1f7c96
 * OS:Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)
 * Vim/neovim version:Vim version 8.1.20

## Provide a minimal .vimrc with less than 50 lines (Required!)

```
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/yahonda/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/yahonda/.cache/dein')
  call dein#begin('/home/yahonda/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/yahonda/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  " You can specify revision/branch/tag.
  call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd' })

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------
```

## The reproduce ways from Vim starting (Required!)

 1.  Execute `installer.sh`
```
$ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
$ sh ./installer.sh ~/.cache/dein
```
2. Copy and paste the generated dein scripts to ~/.vimrc
3. `:call dein#install()` and confirmed `[dein] Done: (2018/05/24 11:51:11)`
4. Startup vim
5. `deol.nvim requires Neovim.` message appears
```
$ vim
deol.nvim requires Neovim.
Press ENTER or type command to continue
```

This message can be suppressed by removing `  call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd' })`

**Comment by delphinus** [comment]
You are simply using old deol. `call dein#add('Shougo/deol.nvim')` goes good to solve this, maybe.

**Comment by yahonda** [comment]
Closed since the issue itself has been resolved by updating .vimrc as above. Also opened #288 to use he deol.vim supporting Vim 8.
