### ISSUE TITLE
Which dein_option should I put in

### ISSUE THREAD

**Issue by amikai** [Shougo/dein.vim#286]
=
# Problems summary

Some plugins used global variable to turn on or adjust setting, and others maybe use call function. How do i choose these two option for plugin. For example:
```
    let g:deoplete#enable_at_startup = 1 
    inoremap <expr><cr> (pumvisible() ? deoplete#close_popup() : "\<cr>")

    call deoplete#custom#option({
    \ 'auto_complete_delay': 200,
    \ 'max_list': 20,
    \ })
```
Like the code above, There are three things, define global variable for deopelete, mapping key, and adjusting deoplete setting. I don't know where these things should put? For example: Maybe `let g:deoplete#enable_at_startup = 1 ` put in hook_add and other put in hook_source.

**Comment by Shougo** [comment]
> Maybe let g:deoplete#enable_at_startup = 1 put in hook_add and other put in hook_source.

Yes. It is true.
