### ISSUE TITLE
Need to manually update state_vim.vim and state_gvim.vim when upgrading Vim version

### ISSUE THREAD

**Issue by john2x** [Shougo/dein.vim#289]
# Problems summary
The `state_vim.vim` and `state_gvim.vim` files modifies the `runtimepath` variable and includes a path to `/usr/share/vim/vim80`. When upgrading to Vim 8.1, the runtime files are moved to `/usr/share/vim/vim81`, but the state files are not updated to reflect this. This causes an error when starting Vim because it can't find any files in the old `vim80` path.

A common symptom of this is when your vimrc loads the `default` colorscheme (or any colorscheme that comes built-in with Vim). It can't find the colorscheme in the non-existent runtime path.

I fixed the issue by modifying the state files to point to the new runtime path.

## Expected
Not sure how dein should handle the new runtime path when upgrading Vim.

## Environment Information (Required!)

 * dein.vim version(SHA1): `3c9f6e3`

 * OS: `Linux arch 4.16.9-1-ARCH #1 SMP PREEMPT Thu May 17 02:10:09 UTC 2018 x86_64 GNU/Linux`

 * Vim/neovim version: Vim 8.1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()

colorscheme default
```

## The reproduce ways from Vim starting (Required!)

 1. Modify the state files to point to an invalid runtime path to simulate the change when upgrading Vim (e.g. change `/usr/share/vim/vim81` to `/usr/share/vim/vim80`)
 2. Run vim/gvim

## Upload the log messages by `:redir` and `:message` (if errored)

```
Error detected while processing /home/john/.vim/vimrc
line 5:
E185: Cannot find color scheme 'default'
```

**Comment by Shougo** [comment]
>dein.vim version(SHA1): 3c9f6e3

It is very old version in 2017 Dec.
Please don't report the old version's bug.

It is fixed in the latest version of dein.vim.
Closing.
