### ISSUE TITLE
Question: argument {vimrcs} of `dein#begin`

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#293]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I can't understand the argument `{vimrcs}` of `dein#begin()` ：
```
{vimrcs} is a list of compared .vimrc and/or other configuration files.
```
I'm reading your vim config, why are you use `dein.rc.vim` to the argument.

**Comment by Shougo** [comment]
It is used for updated vimrcs detection to update the cache automatically.

**Comment by zgpio** [comment]
Got it
