### ISSUE TITLE
dein 'hook_source' FileType autocmd break the highlight

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#294]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
dein 'hook_source' FileType  autocmd break the markdown highlight

## Environment Information (Required!)

 * dein.vim version(SHA1): latest

 * OS: win10

 * Vim/neovim version: vim8.1

## Provide a minimal .vimrc with less than 50 lines (Required!)
clone `plasticboy/vim-markdown` plugin into `~/vimfiles/pack/github/start/`;

```vim
if &compatible
  set nocompatible
endif
set rtp^=~/.cache/dein/repos/github.com/Shougo/dein.vim

let s:path = expand('~/.cache/dein')
if dein#load_state(s:path)
  call dein#begin(s:path)

  call dein#add('kana/vim-smartchr', {
        \ 'on_event': 'InsertEnter',
        \ 'hook_source': 'autocmd FileType c echo "foo"'
        \})

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. clone `plasticboy/vim-markdown` plugin into `~/vimfiles/pack/github/start/`;
 2. use my minimal vimrc
 3. `:e foo.md`
  foo.md is a exist file，contains：
     ```md
        ```vim
        set nu
        ```
     ```
 4. just enter the insert mode, you will find markdown's vim code higlight break
## Screen shot (if possible)
before enter insert:
![default](https://user-images.githubusercontent.com/19503791/41197622-c38c9fd6-6c97-11e8-87fb-ce31485234e6.png)

after enter insert (as you see, the `set nu` highlight broken):
![default](https://user-images.githubusercontent.com/19503791/41197627-d74b5d64-6c97-11e8-89f2-fdc585fd66d7.png)

**Comment by Shougo** [comment]
Reproduced.   But it is feature.

You have changed `autocmd FileType` in hooks.
dein executes `let &filetype = &filetype` to recall FileType autocmd.
It breaks vim syntax highlight.

**Comment by Shougo** [comment]
So, it is `let &fletype = &filetype` breaks mardown highlight.
I don't know `plasticboy/vim-markdown`'s feature.

**Comment by zgpio** [comment]
Maybe I should add it in `hook_add`.
