### ISSUE TITLE
Dein breaks vim-polyglot's typescript syntax highlighting

### ISSUE THREAD

**Issue by glacambre** [Shougo/dein.vim#295]
# Problems summary
Syntax highlighting for typescript files is broken when loading vim-polyglot with dein. Here's a short example file that exhibits this behavior:
```ts
let expr = `string`
let expr = `#string`
let expr = `string`
```

## Environment Information (Required!)

 * dein.vim version(SHA1): 03411970ee364aee4e177819d384fcedcd88c743
 
* OS: Linux 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux

 * Vim/neovim version: NVIM v0.3.0-1401-gb94b59e4e or NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" set runtimepath+=/tmp/bundle/repos/github.com/sheerun/vim-polyglot/
set runtimepath+=/tmp/bundle/repos/github.com/Shougo/dein.vim

if dein#load_state("/tmp/bundle")
	call dein#begin("/tmp/bundle")
	call dein#add('https://github.com/sheerun/vim-polyglot')
	call dein#end()
	call dein#save_state()
endif
```

## Screen shot (if possible)
When loading vim-polyglot with dein:
[https://my.mixtape.moe/vptzzq.png](https://my.mixtape.moe/vptzzq.png)

When loading vim-polyglot with `set runtimepath+=/tmp/bundle/repos/github.com/sheerun/vim-polyglot`:
[https://my.mixtape.moe/betson.png](https://my.mixtape.moe/betson.png)

https://github.com/Shougo/dein.vim/issues/294 might be related, but it seems they're using a combination of both dein and vim's default package manager, which could be the root cause of their issue.
There's also an open issue in typescript-vim's repo: https://github.com/leafgarland/typescript-vim/issues/137

**Comment by Shougo** [comment]
You need to enable syntax highlight.

```vim
" set runtimepath+=/tmp/bundle/repos/github.com/sheerun/vim-polyglot/
set runtimepath+=/tmp/bundle/repos/github.com/Shougo/dein.vim

if dein#load_state("/tmp/bundle")
	call dein#begin("/tmp/bundle")
	call dein#add('https://github.com/sheerun/vim-polyglot')
	call dein#end()
	call dein#save_state()
endif

syntax enable
filetype plugin indent on
```

Because, dein disables the syntax highlight.

**Comment by glacambre** [comment]
Sorry, I forgot to copy the
```vim
syntax enable
filetype plugin indent on
```
lines when opening the issue. 
I can still reproduce this bug with the init.vim you provided.

**Comment by Shougo** [comment]
```vim
set runtimepath^=~/work/dein.vim/

call dein#begin('~/test/dein4')
call dein#add('https://github.com/sheerun/vim-polyglot')
call dein#end()

filetype plugin indent on
syntax enable
```

It works for me.

**Comment by Shougo** [comment]
dein.vim loads `graphql` syntax.
I don't know why though.

I won't fix it.

**Comment by Shougo** [comment]
vim-polygot loads graphql syntax.

https://github.com/sheerun/vim-polyglot/blob/e2404449e4f961c5e6c0e2689078612b36d776c2/after/syntax/typescript/graphql.vim

**Comment by Shougo** [comment]
```vim
let g:polyglot_disabled = ['graphql']
```

fixes the problem.

**Comment by Shougo** [comment]
> How did you find out what the problem was? I want to try to understand exactly what's happening next time a similar bug happens in order to avoid bothering you with bugs unrelated to your plugins.

I have compared the `:scriptnames` results.
