### ISSUE TITLE
dein did not update the cache automatically.

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#300]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I use your vim config, the deinft.toml is in the list dein#_vimrcs. 
When I update deinft.toml, dein did not update the cache automatically.
(I see the cache dir in dein/.cache/vimrc/.dein/after/ftplugin/...)

 
## Environment Information (Required!)

 * dein.vim version(SHA1): latest

 * OS: win10

 * Vim/neovim version: vim8.1

**Comment by Shougo** [comment]
I cannot reproduce the problem.

Please upload minimal init.vim and the reproduce instructions.
If not, I will close the issue.

**Comment by Shougo** [comment]
I have tested and it works for me.
