### ISSUE TITLE
reattach-to-user-namespace is not needed in Tmux >=2.6

### ISSUE THREAD

**Issue by delphinus** [Shougo/dein.vim#301]
[This issue][ti] says `reattach-to-user-namespace` is not needed now. I also confirmed that it is true with tmux 2.7 from homebrew.

```sh
# it operates both correctly
terminal-notifier -message hello
osascript -e 'display notification "hello"'
```

https://github.com/Shougo/dein.vim/blob/654c56bfbdabd6ae623d5816b4f76f901f7ea7ba/autoload/dein/util.vim#L105-L115

I think this `if` block should be removed (or should show note for Tmux <2.6).

[ti]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/66

**Comment by Shougo** [comment]
OK.
