### ISSUE TITLE
dein execute `set filetype=`

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#304]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
dein execute `set filetype=`

## Environment Information (Required!)

 * dein.vim version(SHA1): latest

 * OS: windows10

 * Vim/neovim version: vim8.1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
set rtp^=~/.cache/dein/repos/github.com/Shougo/dein.vim

let s:path = expand('~/.cache/dein')
if dein#load_state(s:path)
  call dein#begin(s:path)

  call dein#add('tpope/vim-fugitive', {'on_event': 'BufRead'})
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

```

## The reproduce ways from Vim starting (Required!)

 1. use my min vimrc and install `vim-fugitive`
 2. start vim and `:e foo.vim` (note: foo.vim is a exist file)
 3. run `set filetype?`, you will find `filetype=`
 4. check `:verbose set filetype`, you will find filetype last changed in `.../dein/autoload.vim`

## Screen shot (if possible)
![default](https://user-images.githubusercontent.com/19503791/43580258-5bf4a17e-9687-11e8-9fad-bcfbb8a50a36.png)

**Comment by zgpio** [comment]
Q: Why does the command `setf vim` in `vim81/filetype.vim` not work after dein `set filetype=`?

**Comment by Shougo** [comment]
I don't know.  It seems Vim's feature.
