### ISSUE TITLE
Q: Why use `&l:filetype` instead of `&filetype` in source

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#306]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I am reading the dein source, I can't understand use `&l:filetype` instead of `&filetype` in file `autoload/dein/autoload.vim`(**line 88**).

**Comment by Shougo** [comment]
It is same.  But filetype is buffer local option.
So `&l:filetype` is better.  I think.
