### ISSUE TITLE
vim.org install help

### ISSUE THREAD

**Issue by jmzagorski** [Shougo/dein.vim#309]
# Problems summary
I use a plugin [dbext](https://www.vim.org/scripts/script.php?script_id=356) that is maintained on vim.org. I could not find an example for adding vim.org during an install and using 
`call dein#add('https://www.vim.org/scripts/download_script.php?src_id=25648', {'on_ft':['sql']})`
fails. I stopped using https://github.com/vim-scripts/dbext.vim because the maintainer, in a recent pull request said:

> I am the maintainer of the plugin, but this is mirrored into github, I have no access to it.
> I post all the updates directly to Vim.org, not Github.

## Expected
Understand syntax to get a vim.org script installed (or do I have to install it locally first?)

## Environment Information (Required!)

 * dein.vim version(SHA1): version 2.1

 * OS: Windows 10

 * Vim/neovim version: Vim 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
filetype off
filetype plugin indent off

if has('vim_starting')
  set nocompatible
  set runtimepath+=$HOME/.vim/bundle/repos/github.com/Shougo/dein.vim/
  " all plugins have their own file calling dein#add
  set runtimepath+=$HOME/.vim/rc/plugins/
endif

call dein#begin(expand('$HOME/.vim/bundle/')) " plugins' root path

call dein#add('Shougo/dein.vim')
 
 " all plugins have their own file calling dein#add
runtime! rc/plugins/*.vim

call dein#end()
call dein#save_state()

filetype plugin indent on

if dein#check_install()
  call dein#install()
endif
```

Example plugin file
```vim
" rc/plugins/dbext.vim

"call dein#add('vim-scripts/dbext.vim', {'on_ft':['sql']}) NOT MAINTAINED
call dein#add('https://www.vim.org/scripts/download_script.php?src_id=25648', {'on_ft':['sql']})

" a bunch of db.ext configurations here
```
## The reproduce ways from Vim starting (Required!)

 1. open vim
 2. dein runs and tries to install all plugins in $HOME/.vim/rc/plugins/ directory

## Upload the log messages by `:redir` and `:message` (if errored)
(i replaced full paths with ~ in the message)
```
[dein] Not installed plugins: ['download_script.php?src_id=25648']
[dein] Update started: (2018/08/19 22:28:06)
[dein] ~/.vim/bundle/repos/www.vim.org/scripts/download_script.php?src_id=25648
[dein] Maybe wrong username or repository.
[dein] fatal: could not create work tree dir '~/.vim/bundle/repos/www.vim.org/scripts/download_script.php?src_id=25648': Invalid argument
[dein] Error installing plugins:
[dein]   download_script.php?src_id=25648
[dein] Please read the error message log with the :message command.
[dein] Done: (2018/08/19 22:29:45)
```

**Comment by Mephistophiles** [comment]
Try github mirror: https://github.com/vim-scripts

For example:
call dein#add('vim-scripts/dbext')

**Comment by Shougo** [comment]
Sorry.  It is not supported.

So, you need to install it manually.

**Comment by jmzagorski** [comment]
i suspected that, and really it is not a difficult task to install manually. Thank you.
