### ISSUE TITLE
Loading from internal bitbucket repository

### ISSUE THREAD

**Issue by kariya2** [Shougo/dein.vim#311]
Was wondering if its possible to set the search path to an internal bitbucket repository cause I can't access github at work. Or if there was any other recommended method to manage packages from an internally hosted vim plugin library, thanks :)

**Comment by Shougo** [comment]
dein.vim supports gitbucket git repository.

```vim
call dein#add('https://bitbucket.org/mortonfox/twitvim.git')
```
