### ISSUE TITLE
Vim 8.1.0349 support

### ISSUE THREAD

**Issue by Shougo** [Shougo/dein.vim#312]
Vim 8.1.0349 change breaks dein.vim asynchronous update feature.

I have fixed for it.  But it is just workaround.

If you upgrade Vim to 8.1.0349+, asynchronous update feature is disabled.
Vim is blocked until update is finished.

Note: neovim has not the limitation.

**Comment by zgpio** [comment]
I am concerned about this.

**Comment by Shougo** [comment]
I have not the solution...

**Comment by ichizok** [comment]
Please tell me the steps to reproduce and the point of confirmation.

**Comment by lambdalisue** [comment]
I couldn't find any issue on System.Job in 8.1.0349 - 8.1.0367.

**Comment by Shougo** [comment]
> Please tell me the steps to reproduce and the point of confirmation.

Unfortunately, I cannot reproduce the problem in minimal vimrc.
It can be reproduced in my vimrc though.
It seems configuration dependent.

**Comment by Shougo** [comment]
I get the reason.

```vim
set guioptions+=!
```

And gvim is needed for me.

**Comment by Shougo** [comment]
Fixed in the latest version.
