### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by DaniG2k** [Shougo/dein.vim#313]
# Problems summary

The `dein.vim` README provides no uninstall instructions.

## Expected

I wanted to give `dein.vim` a spin and am now trying to uninstall but do not know what the correct way to do so is. I was expecting the documentation to provide an uninstallation method.

## Environment Information

 * dein.vim version(SHA1):

 * OS: MacOS 10.13.6

 * Vim/neovim version: 8.0.1283

## Provide a minimal .vimrc with less than 50 lines

```vim
set number

if &compatible
 set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
 call dein#begin('~/.cache/dein')

 call dein#add('~/.cache/dein')
 call dein#add('Shougo/deoplete.nvim')
 if !has('nvim')
   call dein#add('roxma/nvim-yarp')
   call dein#add('roxma/vim-hug-neovim-rpc')
 endif

 call dein#end()
 call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

**Comment by Shougo** [comment]
> I wanted to give dein.vim a spin and am now trying to uninstall but do not know what the correct way to do so is. I was expecting the documentation to provide an uninstallation method.

It is dein.vim uninstall or dein.vim plugins uninstall?

**Comment by DaniG2k** [comment]
dein.vim uninstall

**Comment by Shougo** [comment]
OK.  So, please remove `~/.cache/dein` directory.

**Comment by DaniG2k** [comment]
Thanks for the prompt response @Shougo !

**Comment by Shougo** [comment]
I will add the documentation later.
