### ISSUE TITLE
Install dein plugins without GUI prompt

### ISSUE THREAD

**Issue by jgonsior** [Shougo/dein.vim#314]
Hey!
I'd like to install the plugins from the commandline with a command like `nvim -c ":call dein#install()"`. I need it in order to execute this command from Ansible (so I want to automate the installation process without user interaction). If I run it now, I still need to press some keys in between. Could you add maybe a method like `dein#installNoConfirm()` which could just silently install all needed plugins?

**Comment by Shougo** [comment]
`$ vim -N -u ~/.vim/init.vim -c "try | call dein#update() | finally | qall! | endtry" -V1 -es`
