### ISSUE TITLE
post_source_hooks not called (?)

### ISSUE THREAD

**Issue by SevereOverfl0w** [Shougo/dein.vim#316]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

I do not see post source hooks being called

## Expected

I expect to see them called.

I do not understand "VimEnter" code in docs, and how to use it for my purposes, maybe I just misunderstand this?

Putting the line in my init.vim did not help, as the init was called when vim-sneak wasn't loaded (so I couldn't call, e.g. `sneak#state()`)

## Environment Information (Required!)

 * dein.vim version(SHA1): 5c8f935d062db0ebfa16983d1be9a9487526b875

 * OS: Linux

 * Vim/neovim version: 0.3.1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

call dein#begin('~/.cache/dein')

call dein#add('~/.cache/dein')

function! s:add_hook()
  echom 'Add for ' . g:dein#plugin.name
endf

function! s:post_source_hook()
  echom 'Post source for ' . g:dein#plugin.name
endf

call dein#add('justinmk/vim-sneak',
      \ {'hook_add': function('s:add_hook'),
      \  'hook_post_source': function('s:post_source_hook')})

call dein#end()
```

## The reproduce ways from Vim starting (Required!)

1. Start neovim.
2. Do not see "Post source" message.

**Comment by Shougo** [comment]
Please see dein.vim documentation.

```
					*dein-options-hook_post_source*
hook_post_source (String) or (Function)
		It is executed after plugins are sourced.

		Note: In Vim initializing, you must call the
		"hook_post_source" hooks manually in |VimEnter| if needed.
>
	autocmd VimEnter * call dein#call_hook('post_source')
<
```

So, you must call `dein#call_hook('post_source')` manually.

```vim
...
call dein#end()
autocmd VimEnter * call dein#call_hook('post_source')
```

**Comment by Shougo** [comment]
The below code is invalid.

```
call dein#add('~/.cache/dein')
```

**Comment by Shougo** [comment]
> Putting the line in my init.vim did not help, as the init was called when vim-sneak wasn't loaded (so I couldn't call, e.g. sneak#state())

I don't understand.  Why you don't upload the code?
I think you have misunderstood.

**Comment by SevereOverfl0w** [comment]
Because of:

```
call dein#add('~/.cache/dein')
```

```
function! s:post_source_hook()
  echom 'Post source for ' . g:dein#plugin.name
  " This lines throws exception:
  echom string(sneak#state())
endf

dein#end()

autocmd VimEnter * call dein#call_hook('post_source')
```

Did not work when I tried it. Now I have corrected it to `call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')`, it works.

I copied this from https://github.com/Shougo/dein.vim#unixlinux-or-mac-os-x does this need updating?

**Comment by SevereOverfl0w** [comment]
Thank you for your help!

**Comment by Shougo** [comment]
I have tested your vimrc and it works.

I will fix the README.

QED.
