### ISSUE TITLE
What is "dark powered"?

### ISSUE THREAD

**Issue by adiakritos** [Shougo/dein.vim#317]
I see this in multiple repos regarding VIM plugins and I don't know what it means and I can't find an answer online.

**Comment by talbergs** [comment]
https://salt.bountysource.com/teams/neovim

Q: What means "dark powered"?

A: I think text editor is everything in the world. I want to do everything in
   Vim(neovim) like Emacs. It is not allowed by |design-not| in Vim. It is not
   the light way to use Vim. So I have defined it as the dark way. I am the
   dark Vimmer. My plugins are dark powered.
