### ISSUE TITLE
Airline and dein_log source clash

### ISSUE THREAD

**Issue by petobens** [Shougo/dein.vim#320]
Consider the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

if has('vim_starting')
    execute 'set runtimepath+=' . expand(
                \ '$DOTVIM/bundle/repos/github.com/Shougo/dein.vim')
endif

let g:dein#enable_name_conversion = 1
if dein#load_state(expand('$DOTVIM/bundle/'))
    call dein#begin(expand('$DOTVIM/bundle/'))
    call dein#add('vim-airline/vim-airline')
    call dein#add('Shougo/dein.vim')
    call dein#add('Shougo/denite.nvim')
    call dein#end()
    call dein#save_state()
endif

function! s:dein_update()
  call dein#update()
  Denite -no-quit -mode=normal dein_log:!
endfunction
nnoremap ,bu :call <SID>dein_update()<CR>
```
Now as in the gif:
i) run `,bu`  (notice that airline status line colors are correct)
ii) wait for the update process to complete
iii) once the update process completes check again airline colors: they are broken (i.e they were yellow and green and now they are all gray)

![denite_airline](https://user-images.githubusercontent.com/2583971/50046336-a1b02400-0080-11e9-9fba-3781ba30322f.gif)

I don't know if this is a problem with dein, denite or vim-airline.

**Comment by petobens** [comment]
Actually we don't denite to reproduce this. It's enough to use:

```vim
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

if has('vim_starting')
    execute 'set runtimepath+=' . expand(
                \ '$DOTVIM/bundle/repos/github.com/Shougo/dein.vim')
endif

let g:dein#enable_name_conversion = 1
if dein#load_state(expand('$DOTVIM/bundle/'))
    call dein#begin(expand('$DOTVIM/bundle/'))
    call dein#add('vim-airline/vim-airline')
    call dein#add('Shougo/dein.vim')
    call dein#end()
    call dein#save_state()
endif
```
and run `:call dein#update()`.

**Comment by Shougo** [comment]
It is not dein.vim's issue.
Because dein.vim does not change statusline.
It seems vim-airline's issue.

**Comment by Shougo** [comment]
So, solution: you should restart Vim after updating.

**Comment by petobens** [comment]
Ok. I opened https://github.com/vim-airline/vim-airline/issues/1842 in the airline repo.

**Comment by Shougo** [comment]
The reproduce steps.

```vim
if !has('vim_starting')
  call filter(g:, "stridx(v:key, 'loaded_') != 0")
  silent! runtime! plugin/**/*.vim
else
  set rtp+=~/src/vim-airline/
endif
```

```
$ vim -Nu test.vim
:so test.vim
```

You can reproduce it without dein.vim.

**Comment by Shougo** [comment]
The title is wrong.

This behavior is not crash.   `Airline is disabled if dein update plugins`

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
The recent commit https://github.com/vim-airline/vim-airline/commit/56197d510468f405c630a4a48b1bb207f83d14ac
fixed the Airline reload problem. However I can still reproduce the issue with the dein by using the instructions in https://github.com/Shougo/dein.vim/issues/320#issuecomment-447664229

**Comment by petobens** [comment]
Thank you
