### ISSUE TITLE
What is the difference between the global [ftplugin] and [plugins.ftplugin]'s?

### ISSUE THREAD

**Issue by delphinus** [Shougo/dein.vim#323]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

I wonder the global `[ftplugin]` does not differ from `[plugins.ftplugin]`'s.  When I set for the same filetype, dein.vim gathers them into one file.  Why do both of them exist?  Can you teach me some better use case for them?

## Environment Information (Required!)

 * dein.vim version(SHA1): 5f5c8b9

 * OS: macOS Mojave

 * Vim/neovim version: NVIM v0.3.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath-=~/.vim
let s:dein_dir = expand('/tmp/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')

if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir, './dein.toml')
  call dein#load_toml('./dein.toml')
  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable
```

```toml
[ftplugin]
go = "let b:ftplugin = 'settled'"

[[plugins]]
repo        = 'fatih/vim-go'
on_ft       = ['go']

[plugins.ftplugin]
go = "let b:pluginsFtplugin = 'settled'"
```

## The reproduce ways from Vim starting (Required!)

```sh
# make a directory (ex. /tmp/test) & write vimrc & dein.toml described above.
cd /tmp/test
cat > vimrc
cat > dein.toml
git clone https://github.com/Shougo/dein.vim /tmp/.cache/dein/repos/github.com/Shougo/dein.vim

# run Vim
nvim -N -u ./vimrc -i NONE test.go

# see created
cat /tmp/.cache/dein/.cache/init.vim/.dein/after/ftplugin/go.vim
```

```vim
" gathered into one file! What's the difference between them?

if exists('b:undo_ftplugin')
  let b:undo_ftplugin .= '|'
else
  let b:undo_ftplugin = ''
endif
let b:ftplugin = 'settled'
let b:pluginsFtplugin = 'settled'
```

**Comment by Shougo** [comment]
> Why do both of them exist? Can you teach me some better use case for them?

It is just syntax sugar.  Same means.
But you can write plugin related config in `[plugins.ftplugin]`.

**Comment by delphinus** [comment]
I see. thanks.
