### ISSUE TITLE
Unable to run dein on macOS

### ISSUE THREAD

**Issue by dextermb** [Shougo/dein.vim#325]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When attempting to open vim after setting up dein in the `.vimrc` I get the following errors. And then I am unable to run install.

## Expected
Everything should work as expected

## Environment Information (Required!)

 * dein.vim latest commit: `5f5c8b9a87dedc2e133237056660162da261a366`

 * OS: macOS Sierra (10.12.6 (16G1408))

 * Vimversion: `7.4.8056`

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. Use same OS version
 2. Copy dein to cache
 3. Set up `.vimrc`
 4. See errors before vim opens
 5. See errors when attempting to install

## Screen shot (if possible)

`vim`:

```
➜  ~ vim
Error detected while processing function dein#begin[1]..dein#util#_begin[6]..dein#util#_error[1]..<SNR>5_msg2list:
line    1:
E121: Undefined variable: v:t_list
E15: Invalid expression: type(a:expr) ==# v:t_list ? a:expr : split(a:expr, '\n')
Error detected while processing function dein#begin[1]..dein#util#_begin[6]..dein#util#_error:
line    1:
E714: List required
Press ENTER or type command to continue
```

`:call dein#install()`:

```
Error detected while processing function dein#install[1]..dein#install#_update[27]..<SNR>23_notify[1]..dein#util#_convert2list:
line    1:
E121: Undefined variable: v:t_list
E15: Invalid expression: type(a:expr) ==# v:t_list ? copy(a:expr) : type(a:expr) ==# v:t_string ?   (a:expr ==# '' ? [] : split(a:expr, '\r\?\n', 1)) : [a:expr]
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
>     * Vimversion: `7.4.8056`

Your Vim is too old.

Please read dein.vim documentation

```
Requirements:
* Vim 8.0 or above or NeoVim.
* "git" command in $PATH (if you want to install github or vim.org plugins)
```
