### ISSUE TITLE
dein#check_clean() returns almost all plugins on Windows

### ISSUE THREAD

**Issue by Bakudankun** [Shougo/dein.vim#326]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

In Windows, `globpath()` returns paths with backslashes as separator (by default).

[`dein#util#_check_clean()`](https://github.com/Shougo/dein.vim/blob/5f5c8b9a87dedc2e133237056660162da261a366/autoload/dein/util.vim#L162) compare those paths with slash-separated paths, and thus returns all plugin paths (but dein.vim's) under `repos` directory, resulting in the [command instructed in help to remove unused plugins](https://github.com/Shougo/dein.vim/blob/5f5c8b9a87dedc2e133237056660162da261a366/doc/dein.txt#L1064) removing almost all plugins under `repos`.

## Expected

`dein#check_clean()` returns directory paths of unused plugins as described in document.

## Environment Information (Required!)

 * dein.vim version(SHA1): 5f5c8b9a87dedc2e133237056660162da261a366

 * OS: Windows 10 (64bit)

 * Vim/neovim version: Vim 8.1.875 (64bit)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. Use above .vimrc with clean-installed dein.vim
 2. `:echo dein#check_install()`
 3. Get three paths other than dein.vim's

**Comment by Shougo** [comment]
OK.  Please test the latest version.

**Comment by Bakudankun** [comment]
Confirmed. Thank you for fast fix!
