### ISSUE TITLE
othree/yajs.vim not loaded with dein.vim

### ISSUE THREAD

**Issue by ohcibi** [Shougo/dein.vim#33]
# Problems summary

When I switched to using dein.vim https://github.com/othree/yajs.vim stopped being loaded when opening a javascript file. I examined `:scriptnames` and it is not listed there (and e.g. the syntax highlighting is missing). It is cloned into the repos folder of dein.vim though.

## Expected

othree/yajs.vim should be loaded when opening a javascript file

## Environment Information
 * OS: OS X 10.11.3
 * Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  6 2016 11:21:03)
MacOS X (unix) version
Included patches: 1-1054
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_binary
+arabic          +find_in_path    -mouse_sysmouse  +tag_old_static
+autocmd         +float           +mouse_urxvt     -tag_any_white
+balloon_eval    +folding         +mouse_xterm     +tcl
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+cindent         -gettext         +netbeans_intg   +title
+clientserver    -hangul_input    +odbeditor       +toolbar
+clipboard       +iconv           +path_extra      +transparency
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1  
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.11/Frameworks -L/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.11/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

## .vimrc

This is how I load dein.vim

```vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath^=~/.vim/dein/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin(expand('~/.vim/dein'))

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')

source $HOME/.vim/bundlerc.vim

" Required:
call dein#end()

" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
if dein#check_install()
 call dein#install()
endif

"End dein Scripts-------------------------
```

And this is how I added othree/yajs.vim my `bundlerc.vim`

```vim
call dein#add('othree/yajs.vim')
```

## The reproduce ways from Vim starting (Required!)

 1. Add dein-loading code and bundlerc.vim
 2. Open a js-file
 3. `:scriptnames` does not list yajs files

## Screen shot
With NeoBundle: http://imgur.com/ju9N4rm
With dein.vim: http://imgur.com/agZdD9Y

**Comment by theamazingfedex** [comment]
I seem to be having the same problem, as well as dein freezing every time that I call dein#update() to try out any different plugins.

**Comment by Shougo** [comment]
I cannot reproduce it.  yajs.vim is loaded.
@ohcibi You must add `syntax enable` in your .vimrc.
But you may need execute `dein#recache_runtimepath()`.

**Comment by ohcibi** [comment]
Syntax is enabled as you can see in the screenshots. I'll try the recaching tomorrow and see if it helps.

**Comment by ohcibi** [comment]
@Shougo it turns out that yajs cannot be loaded alongside `isRuslan/vim-es6` which works fine with neobundle. So change your bundlerc to contain both

```
call dein#add('othree/yajs')
call dein#add('isRuslan/vim-es6')
```

**Comment by Shougo** [comment]
@ohcibi Oh, it is the syntax file conflict.
You should avoid it like this.

```vim
call dein#add('othree/yajs', {'merged':0})
call dein#add('isRuslan/vim-es6', {'merged':0})
```

**Comment by ohcibi** [comment]
@Shougo it turns out that I had to invalidate my cache/views/swap completely. I've setup my vim to have a `~/.vim/(swap|views|backup)` folder and I needed to delete all files in there in order for it to work.

**Comment by Shougo** [comment]
@ohcibi You need call `dein#recache_runtimepath()` manually.
I will improve the cache behavior later though...

**Comment by ohcibi** [comment]
@Shougo actually it even works without this. If you want I can add a note to the readme that one needs to delete those swap and view-files when switching to dein.

**Comment by ohcibi** [comment]
@Shougo no it was not about `recache_runteimpath()` it was about the files that vim has stored in `.vim/backup`, `.vim/swap` and `.vim/views`, which need (also?) to be deleted when switching to dein

**Comment by thiru** [comment]
I had a similar issue where my plugins were reported to be installed by dein but none of them were actually loaded.  It turned out this was because I didn't have rsync installed (or at available in my path).  This could probably trip up a lot of users.  Maybe have a check for rsync before installing?

**Comment by Shougo** [comment]
@thiru I have added "cp" command support.  So don't have to install rsync command.
But "rsync" command is faster...

**Comment by thiru** [comment]
@Shougo Thanks Shougo!  I usually have rsync installed.  I just wanted to mention it in case it trips up any else.

Excellent project, keep up the good work!
