### ISSUE TITLE
 Cache is not cleared properly

### ISSUE THREAD

**Issue by taigacute** [Shougo/dein.vim#331]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

I commented out the plugin in deinlazy.toml and I found that it will still load in the .cache folder of the dein I set. Like `ultisnipes` plugin，I commented on it, but it still exists in .cache and is loaded，I tried to clean up `cache_nvim`. It doesn’t seem to have any effect,
The same I commented on the neoformat plugin. But when I edit the file, it still prompts me that neoformat is working.

## Expected

The commented plugin restarts neovim will not be loaded

## Environment Information (Required!)

 * dein.vim version(SHA1):the latest

 * OS: mac os 10.13.6

 * Vim/neovim version: neovim 0.4-dev

## Provide a minimal .vimrc with less than 50 lines (Required!)

I refer to your configuration and rafi configuration
thi is my dein.vim
```Vim
" dein configurations.

let g:dein#install_progress_type = 'title'
let g:dein#enable_notification = 1
let g:dein#install_log_filename = '~/.tmp/dein.log'

let $CACHE = expand('~/.cache')
let s:path = expand('$CACHE/dein')
if !dein#load_state(s:path)
  finish
endif

call dein#begin(s:path, expand('<sfile>'))
let s:toml_dir = expand($CONFIG.'/nvim/rc/dein')
let s:toml =s:toml_dir.'/dein.toml'
let s:lazy_toml = s:toml_dir.'/deinlazy.toml'

call dein#load_toml(s:toml, {'lazy': 0})
call dein#load_toml(s:lazy_toml, {'lazy' : 1})


call dein#end()
call dein#save_state()

if dein#check_install()
  " Installation check.
  call dein#install()
endif

```
I substitute it in vimrc
```Vim
if &compatible
  set nocompatible
endif

let $VIMPATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')

function! s:source_rc(path, ...) abort
  let use_global = get(a:000, 0, !has('vim_starting'))
  let abspath = resolve(expand('~/.config/nvim/rc/' . a:path))
  if !use_global
    execute 'source' fnameescape(abspath)
    return
  endif

  " substitute all 'set' to 'setglobal'
  let content = map(readfile(abspath),
        \ 'substitute(v:val, "^\\W*\\zsset\\ze\\W", "setglobal", "")')
  " create tempfile and source the tempfile
  let tempfile = tempname()
  try
    call writefile(content, tempfile)
    execute 'source' fnameescape(tempfile)
  finally
    if filereadable(tempfile)
      call delete(tempfile)
    endif
  endtry
endfunction

augroup MyAutoCmd
	autocmd!
	autocmd CursorHold *? syntax sync minlines=300
augroup END

if has('vim_starting')
  call s:source_rc('init.vim')
endif

call s:source_rc('dein.vim')
call s:source_rc('plugins/allkey.vim')
syntax enable
filetype plugin indent on
call dein#call_hook('source')
call dein#call_hook('post_source')

" Loading configuration modules
call s:source_rc('general.vim')
call s:source_rc('mappings.vim')
call s:source_rc('/themes/theme.vim')
"---------------------------------------------------------------------------

set secure

" vim: foldmethod=marker

```

## The reproduce ways from Vim starting (Required!)

 1. Comment plugin,
 2. Restart neovim

## Screen shot (if possible)

![1234](https://user-images.githubusercontent.com/41671631/54673990-72ed9200-4b36-11e9-81b6-d92487820428.png)
![12321](https://user-images.githubusercontent.com/41671631/54673992-74b75580-4b36-11e9-9af0-9a9d8fe1515c.png)

**Comment by Shougo** [comment]
It is the feature.
You need to specify `toml`'s path in `dein#begin()` arguments.

You should read the documentation.

```
							*dein#begin()*
dein#begin({base-path}, [{vimrcs}])
		Initialize dein.vim and start plugins configuration
		block.
		{base-path} is where your downloaded plugins will be placed.
		For example, "Shougo/dein.vim" will be downloaded in
		"{base-path}/repos/github.com/Shougo/dein.vim" directory.
		{vimrcs} is a list of compared .vimrc and/or other
		configuration files. The default is |$MYVIMRC|.
		The typical {base-path} is "~/.cache/dein" or
		"~/.local/share/dein".
```

**Comment by Shougo** [comment]
> I tried to clean up cache_nvim. It doesn’t seem to have any effect,

`call dein#recache_runtimepath()` for manual clean.

**Comment by taigacute** [comment]
> It is the feature.
> You need to specify `toml`'s path in `dein#begin()` arguments.
> 
> You should read the documentation.
> 
> ```
> 							*dein#begin()*
> dein#begin({base-path}, [{vimrcs}])
> 		Initialize dein.vim and start plugins configuration
> 		block.
> 		{base-path} is where your downloaded plugins will be placed.
> 		For example, "Shougo/dein.vim" will be downloaded in
> 		"{base-path}/repos/github.com/Shougo/dein.vim" directory.
> 		{vimrcs} is a list of compared .vimrc and/or other
> 		configuration files. The default is |$MYVIMRC|.
> 		The typical {base-path} is "~/.cache/dein" or
> 		"~/.local/share/dein".
> ```


I use` .cache/dein` to store the plugin. I  install `dein` in `.config/nvim/repos`,I  have this in my `.config/nvim/rc/init.vim`
```
let $CONFIG = expand('~/.config')


if !isdirectory(expand($CONFIG))
  call mkdir(expand($CONFIG), 'p')
endif


" Load dein.
let s:dein_dir = finddir('dein.vim', '.;')
if s:dein_dir != '' || &runtimepath !~ '/dein.vim'
  if s:dein_dir == '' && &runtimepath !~ '/dein.vim'
    let s:dein_dir = expand('$CONFIG/nvim')
          \. '/repos/github.com/Shougo/dein.vim'
    if !isdirectory(s:dein_dir)
      execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
    endif
  endif
  execute 'set runtimepath^=' . substitute(
        \ fnamemodify(s:dein_dir, ':p') , '/$', '', '')
endif

```

**Comment by taigacute** [comment]
> > I tried to clean up cache_nvim. It doesn’t seem to have any effect,
> 
> `call dein#recache_runtimepath()` for manual clean.

maybe  i need this.

**Comment by Shougo** [comment]
You need to specify toml files in `{vimrcs}` argument.

**Comment by taigacute** [comment]
These code comes from your `configuration` and I don't see where the` sfile `is defined. How do I set up toml in `{vimrcs}` [dein.rc.vim](https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/dein.rc.vim#L13)

**Comment by Shougo** [comment]
```vim
let s:toml_dir = expand($CONFIG.'/nvim/rc/dein')
let s:toml =s:toml_dir.'/dein.toml'
let s:lazy_toml = s:toml_dir.'/deinlazy.toml'
call dein#begin(s:path, [expand('<sfile>'), s:toml, s:lazy_toml])
```

> These code comes from your configuration and I don't see where thesfileis defined. 

`:help <sfile>`

**Comment by taigacute** [comment]
thanks a lot, i think i should learn vimscript
