### ISSUE TITLE
Failed to install dein following strictly the readme with neovim

### ISSUE THREAD

**Issue by ArnaudValensi** [Shougo/dein.vim#333]
# Problems summary
I failed to install dein following strictly the readme with neovim on macos.
When I do `dein#check_install()`, I get:
```
E492: Commande inconnue: dein#check_install()
[dein] Target plugins are not found.
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
```

## Environment Information (Required!)

 * dein.vim version(SHA1):
Latest
 * OS:
MacOS
 * Vim/neovim version:
NVIM v0.3.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/arnaudvalensi/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/Users/arnaudvalensi/.cache/dein')
  call dein#begin('/Users/arnaudvalensi/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/Users/arnaudvalensi/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------
```

## The reproduce ways from Vim starting (Required!)

Follow strictly the readme.

## Screen shot (if possible)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/604486/54999733-2e984100-4fd1-11e9-98c4-bff99d3d1285.png">

**Comment by Shougo** [comment]
> When I do dein#check_install(), I get:

It must be `call dein#check_install()`.

> [dein] Target plugins are not found.
> [dein] You may have used the wrong plugin name, or all of the plugins are already installed.

Because, you don't list the install plugins.  They are commented out.

**Comment by ArnaudValensi** [comment]
Thank you
