### ISSUE TITLE
dein not using --rebase on git pull

### ISSUE THREAD

**Issue by paroxayte** [Shougo/dein.vim#335]
# Problems summary
I pruned a useless and large file from my git history on a vim plugin. Afterwards I found that on `:call dein#update()` I get the error "Fatal: Not possible to fast-forward, aborting". I see [here](https://github.com/Shougo/dein.vim/issues/148#issuecomment-263560593) that dein is supposed to use git pull --rebase. Upon manually cd'ng to my dein directory (~/.cache/dein/repos/github.com/) and into the plugin directory, running `git pull --rebase origin master` works without issue. 

## Expected
`:call dein#update()` should pull with rebase.

## Environment Information (Required!)

 * dein.vim version(SHA1):  c802e3a

 * OS: Arch Linux x86_64

 * neovim version: v0.4.0-567-gae2401621

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('paroxayte/vkmap.vim') "Any repo will do
  call dein#end()
  call dein#save_state()
endif

```

## The reproduce ways from Vim starting (Required!)

 1. Rewrite history
 2. Push new commit
 3. Call `dein#update()`

## Upload the log messages by `:redir` and `:message` (if errored)
```
[dein] /home/azae/.cache/dein/repos/github.com/paroxayte/autocd.vim                                                                                                                                               
[dein] From https://github.com/paroxayte/vkmap.vim                                                                                                                                                               
[dein]  + *original hash N/A*...c8ccaac master     -> origin/master  (forced update)                                                                                                                                          
[dein] fatal: Not possible to fast-forward, aborting. 
Error installing plugins:
    vkmap.vim
Please read the error message log with the :message command.
```
Edit: I tested on another personal plugin repo I have; behavior is confirmed replicable.

**Comment by Shougo** [comment]
I don't want to change the default behavior.

You can change it by `g:dein#types#git#pull_command`.
