### ISSUE TITLE
Switch between revisions automatically

### ISSUE THREAD

**Issue by petobens** [Shougo/dein.vim#338]
Suppose I load `denite` with dein by means of:
```viml
    call dein#add('Shougo/denite.nvim')
```
If I now want to test your new `ui` branch then I change that line to
```viml
    call dein#add('Shougo/denite.nvim', {'rev' : 'ui'})
```
However in order for dein to pick up that change I need to first erase the dein folder and reinstall de denite plugin. My question then is: is it possible to automatically switch between packages revisions/branches so that whenever I change the `{'rev': }` argument and restart nvim then dein picks up that change without having to manually delete and reinstall the plugin? Thanks in advance

**Comment by petobens** [comment]
Thank you! One small thing: if for instance I switch from the master branch to the ui branch my commenting the master branch call:
```viml
    " call dein#add('Shougo/denite.nvim')
    call dein#add('Shougo/denite.nvim', {'rev': 'ui'})
```
then in order for the change to take effect I need to manually run `:call dein#recache_runtimepath()` (otherwise I'm still on the master branch). Can that be done automatically (i.e avoid the manual call)?

**Comment by Shougo** [comment]
I have added revision detection feature.

**Comment by petobens** [comment]
How does this work? I still seem to need to run `dein#recache_runtimepath()`

**Comment by Shougo** [comment]
The check is executed by `autocmd BufWritePost *.vim,*.toml,vimrc,.vimrc call dein#util#_check_vimrcs()`.

So it should be called after vimrc saved.
Please check `dein#util#_check_vimrcs()` is called.

You are not Vim script beginner.

**Comment by petobens** [comment]
Ok I will check it (I tried manually calling ` dein#util#_check_vimrcs()` but still the branch/revision doesn't switch)

**Comment by Shougo** [comment]
I have tested the feature.
It works expected.

So my work is done.

**Comment by Shougo** [comment]
You can reproduce the problem and you have the source code.
So you can find/fix the problem easily.
