### ISSUE TITLE
Update [ftplugin] section of toml can't make dein recache

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#343]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When I update the [ftplugin] section of toml, it does not cause dein to automatically recache.

## Environment Information (Required!)

 * dein.vim version(SHA1):  220ea12

 * OS: macos

 * Vim/neovim version: v0.4.0-964-gf6f9e4a23

## Provide a minimal .vimrc with less than 50 lines (Required!)
* init.vim
```vim
if &compatible
  set nocompatible
endif

set runtimepath+=~/test_vim/dein.vim/

if dein#load_state('~/test_vim/.cache/dein')
  call dein#begin('~/test_vim/.cache/dein')

  call dein#load_toml('~/test_vim/lazy.toml', {'lazy': 1})

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

```
* lazy.toml
```toml
[ftplugin]
vim = '''
nmap <c-k> :echo 'fool'<cr>
'''
```

## The reproduce ways from Vim starting (Required!)

 1. `nvim -u init.vim`
 2. `set ft=vim` and test `<c-k>`, it echo `fool`
 3. `:e lazy.toml` and modify `fool` to `bar`, `:w` and `:q`
 4. `nvim -u init.vim`
 5. `set ft=vim` and test `<c-k>`, it stll echo `fool`, but `bar` is expected.

**Comment by Shougo** [comment]
You need to specify toml files in `dein#begin()` argument.

Please read the documentation.

```
							*dein#begin()*
dein#begin({base-path}, [{vimrcs}])
		Initialize dein.vim and start plugins configuration
		block.
		{base-path} is where your downloaded plugins will be placed.
		For example, "Shougo/dein.vim" will be downloaded in
		"{base-path}/repos/github.com/Shougo/dein.vim" directory.
		{vimrcs} is a list of compared .vimrc and/or other
		configuration files. The default is |$MYVIMRC|.
		The typical {base-path} is "~/.cache/dein" or
		"~/.local/share/dein".
```

**Comment by Shougo** [comment]
```vim
let s:toml = '~/test_vim/lazy.toml'
if dein#load_state('~/test_vim/.cache/dein', [$MYVIMRC, s:toml])
  call dein#begin('~/test_vim/.cache/dein')
  call dein#load_toml(s:toml, {'lazy': 1})
  call dein#end()
  call dein#save_state()
endif
```

**Comment by zgpio** [comment]
I tried it, but still can't recache.

**Comment by Shougo** [comment]
Please update to the latest version.
