### ISSUE TITLE
Cannot build helptags

### ISSUE THREAD

**Issue by NihilityT** [Shougo/dein.vim#345]
# Problems summary
I tried to add a plugin `chemzqm/wxapp.vim` and run `call dein#recache_runtimepath()`, but I got an error: 
```
E670: Mix of help file encodings within a language: /home/.../.dein/doc/wxapp.txt
```

## Expected
make the `helptags` can to build tags for `wxapp.vim`

## Environment Information (Required!)

 * dein.vim version(SHA1): c2416cfa43702973dd84a404f45c9b8bef405ec4

 * OS: Ubuntu 18.04.2 LTS

 * Vim/neovim version: Vim 8.1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" normal

set nocompatible
let $bundle = expand('~/.vim/bundle')
let $dein_dir = expand($bundle.'/repos/github.com/Shougo/dein.vim')
set runtimepath^=$dein_dir

call dein#begin($bundle)

call dein#add('chemzqm/wxapp.vim')

call dein#end()
```

```vim
" error

set nocompatible
let $bundle = expand('~/.vim/bundle')
let $dein_dir = expand($bundle.'/repos/github.com/Shougo/dein.vim')
set runtimepath^=$dein_dir

call dein#begin($bundle)

call dein#add($dein_dir)
call dein#add('chemzqm/wxapp.vim')

call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. use the first vimrc and run `call dein#recache_runtimepath()`, the `helptags` can build tags and work well.
 2. add `call dein#add($dein_dir)` to vimrc and run `call dein#recache_runtimepath()`, will get an error `E670`

## Upload the log messages by `:redir` and `:message` (if errored)
```
[dein] Error generating helptags:
[dein] Vim(helptags):E670: Mix of help file encodings within a language: /home/.../.dein/doc/wxapp.txt
[dein] function dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[1
9]..<SNR>20_helptags, line 12
```

**Comment by Shougo** [comment]
Sorry.  It is wxapp's documentation problem.

https://github.com/chemzqm/wxapp.vim/blob/master/doc/wxapp.txt
It includes Chinese characters for English documentation.

**Comment by Shougo** [comment]
Same problem exists when you copy wxapp's documentation in ~/.vim/doc.
So it is not dein's problem.
