### ISSUE TITLE
Question on rev with a tag syntax

### ISSUE THREAD

**Issue by thecontinium** [Shougo/dein.vim#347]
Is this the correct syntax for using rev with a tag or release v0.2.1

`
call dein#add('Shougo/deol.nvim', { 'rev': 'master/v0.2.1' })
`
cheers

**Comment by Shougo** [comment]
`call dein#add('Shougo/deol.nvim', { 'rev': 'v0.2.1' })`

**Comment by thecontinium** [comment]
cheers

**Comment by thecontinium** [comment]
I have used `call dein#add('Olical/conjure',` { 'rev': 'v0.22.0' `})`

on `:call dein#update()` I get the following error:

`[dein] Update started: (2019/07/13 11:52:35)
[dein] /Users/continium/.cache/vim/dein/repos/github.com/Olical/conjure_v0.22.0
[dein] fatal: invalid reference: fatal: ref HEAD is not a symbolic ref
[dein] /Users/continium/.cache/vim/dein/repos/github.com/Olical/conjure_v0.22.0
[dein] You are not currently on a branch.
[dein] Please specify which branch you want to merge with.
[dein] See git-pull(1) for details.
[dein]     git pull <remote> <branch>
[dein] Error installing plugins:
[dein]   conjure
[dein] Please read the error message log with the :message command.
[dein] Done: (2019/07/13 11:53:53)
`
Have you seen this before ?
Is there another setting I need to use ?

I can give full details; min config etc, if you need.   

cheers

**Comment by Shougo** [comment]
It works for me.

```vim
set nocompatible
set runtimepath^=~/work/dein.vim

call dein#begin(expand('~/.cache/sample/dein'))

call dein#add('Olical/conjure', { 'rev': 'v0.22.0' })

call dein#end()

filetype plugin indent on
```

**Comment by Shougo** [comment]
Reproduced.  Fixed the error.
Please use the latest version.

**Comment by thecontinium** [comment]
I concur. Fixed.
Thanks for the super quick turnaround.

Cheers
