### ISSUE TITLE
Plugins with `on_path=.*` are loaded on startup

### ISSUE THREAD

**Issue by rafi** [Shougo/dein.vim#352]
# Problems summary
Something changed recently with lazy plugins with `on_path=.*`, it seems they are immediately loaded now, _maybe_ because of recent Neovim changes?

## Expected
Lazy plugins shouldn't be loaded in clean startup.

## Environment Information (Required!)

 * dein.vim version(SHA1): a372c83
 * OS: macOS 10.14.6
 * Vim/neovim version: NVIM v0.5.0-3218-g618045685

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible | set nocompatible | endif

" Set configuration paths
let $VIMRC_DIR = fnamemodify(expand($MYVIMRC), ':h')
let $BUNDLE_DIR = $VIMRC_DIR . '/bundle'
let $DEIN_DIR = $BUNDLE_DIR . '/repos/github.com/Shougo/dein.vim'

" Install dein.vim
if ! isdirectory($DEIN_DIR)
	execute '!git clone https://github.com/Shougo/dein.vim' expand($DEIN_DIR)
endif
execute 'set runtimepath+='.substitute(
	\ fnamemodify($DEIN_DIR, ':p') , '/$', '', '')

" Add plugins to bundle
call dein#begin($BUNDLE_DIR, [ expand('<sfile>') ])
call dein#add('airblade/vim-gitgutter', { 'on_path': '.*' })
call dein#end()

if dein#check_install()
	call dein#install()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

1. Start nvim 0.5.x once to install dein and plugins.
2. Quit nvim
3. Run: `nvim --startuptime /tmp/vim.log +q && cat /tmp/vim.log`

You will see gitgutter's autoload and plugin files loaded on startup, even if no files were loaded.

**Comment by Shougo** [comment]
Reproduced.  But it is neovim issue.
I don't reproduce the problem in Vim8.

I have bisected it.

https://github.com/neovim/neovim/commit/8b8ecf44f2cda43bbd710ec22ef99439b71888cd

is the bad commit.

https://github.com/neovim/neovim/pull/10898

You should report it in neovim issues.

**Comment by rafi** [comment]
@Shougo thank you for bisecting. I want to open an issue, but I'm not sure how `on_path` mechanism works in Dein, is it trigger by a specific _event_? which one? do you have any clue/intuition how it's related to neovim's jumplist changes?

**Comment by Shougo** [comment]
> is it trigger by a specific event?

Yes.  BufNew and BufRead are used.

> do you have any clue/intuition how it's related to neovim's jumplist changes?

I don't know why.
