### ISSUE TITLE
Feature - Version locking support

### ISSUE THREAD

**Issue by jmitchener** [Shougo/dein.vim#353]
Arbitrarily updating the cache with no built-in rollback mechanism can be rather frustrating and dangerous. One of the biggest advantages of submodules/pathogen is having exact versions of dependencies tracked via git.

It would be nice if we could have some kind of version-locking mechanism during dein#install() that tracked the current rev of all dependencies and only updating them during dein#update(). This file could be tracked in git with the vim configuration and used to get identical installs across machines or rollback in the event of a breaking update.

**Comment by Shougo** [comment]
I have added `dein#save_rollback()` and `dein#load_rollback()`.
