### ISSUE TITLE
Nothing happens when attempting to install a plugin

### ISSUE THREAD

**Issue by markfaine** [Shougo/dein.vim#355]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
At first I got no response when I tried to install using call: dein#install(), but it eventually did install.  I think.
Now I'm trying to install wsdjeg/dein-ui.vim but it simply does nothing.  No error, just nothing at all.

## Expected
The plugin would install.

## Environment Information (Required!)

 * dein.vim version(SHA1):  commit 7ea274e3582710b7d6476270c8050c4db277e818

 * OS: Redhat Enterprise 6.10 and 7.7

 * Vim/neovim version:
VIM version 8.1.2112

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/mfaine/cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/mfaine/cache/dein')
  call dein#begin('/home/mfaine/cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/mfaine/cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------
```

## The reproduce ways from Vim starting (Required!)

 1. Open Vim
 2. :call dein#add('wsdjeg/dein-ui.vim')

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/949949/66328769-e26c7880-e8f2-11e9-8bb0-b9420950c49b.png)

**Comment by Shougo** [comment]
It must be:

```vim
" Required:
if dein#load_state('/home/mfaine/cache/dein')
  call dein#begin('/home/mfaine/cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/mfaine/cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')
  call dein#add('wsdjeg/dein-ui.vim')

  " Required:
  call dein#end()
  call dein#save_state()
endif
```

Please read the comment.
`" Add or remove your plugins here like this:`

You need to write `dein#add()` in your vimrc instead of command line.

**Comment by markfaine** [comment]
Ok. I will give that a try. Thanks!

-------- Original Message --------
