### ISSUE TITLE
Removing plugins does not work with custom configuration file

### ISSUE THREAD

**Issue by TamaHobbit** [Shougo/dein.vim#357]
# Problem summary
In issue #71 it is mentioned by trisys3 that: "if you have your package configuration in another file besides ~/.vimrc (vundle recommended it for first installation, but it is probably not as useful for dein), dein will not detect the removal of the dein#add, so you will need to run call dein#recache_runtimepath()"

This means that after removing a plugin, I will need to run recache_runtimepath manually every time.

## Expected
Ideally, the add call should write somewhere which file it was called from, so that that file is added to a watchlist that is checked to see if the add call is removed. Easier but less desirable would be an option specifying which file to watch, that defaults to the current ~/.vimrc.

## Environment Information (Required!)

 * dein.vim version(SHA1):  2.0, master branch from 2nd october 2019, commit hash 7ea274e3582

 * OS: Windows 7

 * Vim/neovim version: NVIM v0.4.2

## Minimal .vimrc:

```vim
source ~/my_deinpackages.vim
```

my_deinpackages.vim:
```vim
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('vim-scripts/taglist.vim')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

1. Start vim.
2. Remove the added line.
3. Restart vim.
4. Observe that the plugin is still loaded.

**Comment by Shougo** [comment]
```vim
call dein#add('vim-scripts/taglist.vim', {'merged': 0})
```

Or

```vim
let g:dein#auto_recache = 1
```

**Comment by TamaHobbit** [comment]
I don't understand what setting merged to 0 means. I'm using dein as a black box, as far as I am concerned, plugins are either installed or not. Could you explain how that solves this issue?

auto_recache is helpful in that it automates the recaching, but the recaching should be unnecessary. So this is a bandaid where more is necessary.

I recommend you reopen this issue until there really is a way of having dein monitor files other than .vimrc for removals of plugins.

**Comment by Shougo** [comment]
I don't reopen it.  Because it is intended behavior.

**Comment by Shougo** [comment]
```
Q: Why I need to call |dein#recache_runtimepath()|| manually after removing
plugins?
https://github.com/Shougo/dein.vim/issues/357

A: You can use |g:dein#auto_recache| option instead.
Dein.vim has merge feature.  It copys the plugins into the merge directory.
You can disable the feature by |dein-options-merged|.  It is like other plugin
managers behavior.
Why dein.vim has the feature?  It is for loading performance.
Other plugin add 'runtimepath' to load external plugins.
But if 'runtimepath' is very big, plugin loading is slower.  Because Vim needs
to search all huge 'runtimepath' to load it.  Dein.vim has not the problem.
```

**Comment by TamaHobbit** [comment]
Thank you for explaining.

I only now saw issue #138, which seems to indicate this should be fixed. I guess I will try his repro steps and reopen that if the issue remains.

**Comment by TamaHobbit** [comment]
I see in the code change though that my issue was not fixed; what I would want is to be able to source other vimrc files that contain the plugins, and have those also checked for needing a recache. Issue #138 is slightly different; he specifies a particular vimrc on the command line.

**Comment by Shougo** [comment]
You can specify check vimrcs by dein#begin argument.
Please read the documentation.
