### ISSUE TITLE
[Feature Request] Load plugins lazily on calling lua functions (or modules)

### ISSUE THREAD

**Issue by delphinus** [Shougo/dein.vim#359]
Some plugins, like [nvim-lsp][], does not have vimscript functions but lua ones only. Can I source them on event such as `on_lua` and write settings as below?

[nvim-lsp]: https://github.com/neovim/nvim-lsp

```toml
[[plugins]]
repo = 'neovim/nvim-lsp'
on_lua = ['nvim_lsp']

[plugins.ftplugin]
typescript = "lua require'nvim_lsp'.tsserver.setup{}"
```

**Comment by Shougo** [comment]
The feature is useful, but I cannot implement the feature.
Because neovim has not hook autocmd for lua functions like `CmdUndefined`, `FuncUndefined`.

You need to request the feature in neovim issues.

**Comment by erw7** [comment]
I don't think any changes on the neovim side are needed to implement this. You can implement lazy loading of plugins by loading modules by adding a handler to `package.loader`. In the case of functions, I think it is possible to define a function with the same name, load the plugin there, and call the original function.

I tried to implement lazy loading of plugins by using the above method in the user side settings. You should be able to confirm that the lazy loading works with the above three files in `~/tmp/.config/nvim`, and `env HOME=/home/${USER}/tmp nvim`.

https://gist.github.com/erw7/509c566910bc1a5c4251bf1394cd6f38

**Comment by Shougo** [comment]
I have implemented it.  Thanks.

**Comment by krisfans** [comment]
> 
> 
> I don't think any changes on the neovim side are needed to implement this. You can implement lazy loading of plugins by loading modules by adding a handler to `package.loaders`. In the case of functions, I think it is possible to define a function with the same name, load the plugin there, and call the original function.
> 
> I tried to implement lazy loading of plugins by using the above method in the user side settings. You should be able to confirm that the lazy loading works with the above three files in `~/tmp/.config/nvim`, and `env HOME=/home/${USER}/tmp nvim`.
> 
> https://gist.github.com/erw7/509c566910bc1a5c4251bf1394cd6f38
Could you  give a simple example of setting up the `neovim/nvim-lspconfig` plugin using the `toml` file, please?

**Comment by krisfans** [comment]
> 
> 
> I don't think any changes on the neovim side are needed to implement this. You can implement lazy loading of plugins by loading modules by adding a handler to `package.loaders`. In the case of functions, I think it is possible to define a function with the same name, load the plugin there, and call the original function.
> 
> I tried to implement lazy loading of plugins by using the above method in the user side settings. You should be able to confirm that the lazy loading works with the above three files in `~/tmp/.config/nvim`, and `env HOME=/home/${USER}/tmp nvim`.
> 
> https://gist.github.com/erw7/509c566910bc1a5c4251bf1394cd6f38

Could you give a simple example of setting up the `neovim/nvim-lspconfig` plugin using the `toml` file, please?

**Comment by Shougo** [comment]
```toml
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_lua = 'lspconfig'
```
