### ISSUE TITLE
node.js eating CPU

### ISSUE THREAD

**Issue by kierun** [Shougo/dein.vim#361]
#271 Problems summary

Every instance of neovim I use causes a node.js process to be spawn which in time eats all the CPU cycles.

The process is:

```/usr/bin/node --no-warnings /home/usr/.cache/dein/.cache/init.vim/.dein/build/index.js```

## Expected

Dein not to eat all my CPU cycles?

## Environment Information (Required!)

 * dein.vim version(SHA1):

```commit c371175fa5ee769e7cc0a4fb8167281071b7732b```

 * OS:

Cent OS 7

 * Vim/neovim version:

NVIM v0.4.3

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/home/usr/.config/nvim/dein.vim/repos/github.com/Shougo/dein.vim
call dein#begin(expand('~/.cache/dein'))
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. Start neovim.
 2. Look at (h)top.
 3. Node.js process appears at the top…

## Screen shot (if possible)

NA.

## Upload the log messages by `:redir` and `:message` (if errored)

> :redir

E475: Invalid agrument:

> :message

Same as above.

**Comment by Shougo** [comment]
This is not dein problem.
dein doesn't include any of js scripts.

**Comment by Shougo** [comment]
You should upload minimal vimrc.

**Comment by kierun** [comment]
> You should upload minimal vimrc.

I did, the above shows the problem. This is really odd. Anyway, thanks for your help.

**Comment by Shougo** [comment]
You should remove the cache directory and reinstall dein.
Because the index.js is not included in dein.

**Comment by Shougo** [comment]
You should check what plugin includes index.js.

**Comment by kierun** [comment]
> You should remove the cache directory and reinstall dein.

Yup, tried that.

> You should check what plugin includes index.js.

And we found the culprit: `repos/github.com/neoclide/coc.nvim_release/build/index.js`

Thank you. That is super helpful. I shall look into it some more…

**Comment by Shougo** [comment]
Oh... I have thought it may be coc problem.
