### ISSUE TITLE
Copy fails when file and folder with same name

### ISSUE THREAD

**Issue by p7g** [Shougo/dein.vim#362]
# Problems summary

Similar to https://github.com/Shougo/dein.vim/issues/230 and https://github.com/Shougo/dein.vim/issues/153, but different.

When installing 2 plugins where one has a file and the other has a folder with the same name, the `cp` command fails like so:

```
cp: cannot overwrite directory '/home/me/.cache/dein/.cache/test.vim/.dein/build' with non-directory
```

This issue was mentioned at https://github.com/sheerun/vim-polyglot/issues/275 but I think this should be handled by dein. If you have an idea for a fix, I can open a PR.

One thing I tried was to add a `/` to the end of the path, like this:

```diff
- let cmdline = printf('cp -Ra %s* %s', src, shellescape(a:dest))
+ let cmdline = printf('cp -Ra %s*/ %s', src, shellescape(a:dest))
```

But this caused some other issues.

## Expected

Expected conflicts to be resolved somehow... not sure what way would be best.

## Environment Information (Required!)

 * dein.vim version(SHA1): c371175fa5ee769e7cc0a4fb8167281071b7732b

 * OS: linux

 * Vim/neovim version:
  ```
  NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.3/build/config -I/builddir/neovim-0.4.3/src -I/usr/include -I/builddir/neovim-0.4.3/build/src/nvim/auto -I/builddir/neovim-0.4.3/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/cache/dein')
    call dein#begin('~/.cache/dein')

    call dein#add('neoclide/coc.nvim', {'rev': 'release'})
    call dein#add('sheerun/vim-polyglot')

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. plugins will install when vim starts
 2. check `:messages` after to see error message

## Upload the log messages by `:redir` and `:message` (if errored)

```
[dein] Not installed plugins: ['coc.nvim', 'vim-polyglot']
[dein] Update started: (2020/02/19 20:28:30)
[dein] copy command failed.
[dein] cp: cannot overwrite directory '/home/me/.cache/dein/.cache/test.vim/.dein/build' with non-directory
[dein] cmdline: cp -Ra '/home/me/.cache/dein/repos/github.com/sheerun/vim-polyglot/'* '/home/me/.cache/dein/.cache/test.vim/.dein'
[dein] Done: (2020/02/19 20:28:35)
```

**Comment by Shougo** [comment]
> Expected conflicts to be resolved somehow... not sure what way would be best.

I cannot fix it completely.

But you can fix it by `'merged': 0`.

```vim
call dein#add('sheerun/vim-polyglot', {'merged': 0})
```
