### ISSUE TITLE
GitHub release package support

### ISSUE THREAD

**Issue by zgpio** [Shougo/dein.vim#363]
What is the support of zip in TODO? GitHub release package?

**Comment by Shougo** [comment]
Sorry.  I don't add the feature.
Few years later, the feature is not useful.

And no the PR for dein.

**Comment by zgpio** [comment]
> Few years later, the feature is not useful.

What exactly does this mean？

**Comment by Shougo** [comment]
Many plugins use git repository.
I don't need the feature.
