### ISSUE TITLE
When dein lazy load this plugin, the plugin cannot work.

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/dein.vim#364]
https://github.com/junegunn/vim-peekaboo/issues/65

When dein lazy load this plugin, the plugin cannot work.

OS: linux
gvim: 8.2
dein: lateset

```
call dein#add('junegunn/vim-peekaboo', {
				\ 'on_map': ['"', '@'],
				\ })
```

**Comment by Shougo** [comment]
Hm.  I will test the plugin.
But you should know lazy loaded plugin may not work.

**Comment by Shougo** [comment]
You need to specify `augroup`.

```vim
call dein#add('junegunn/vim-peekaboo', {
				\ 'on_map': ['"', '@'],
                                \ 'augroup': 'peekaboo_init',
				\ })
```
