### ISSUE TITLE
Question: Is the code in hook_xxx behaving differently in the saved state(.cache/dein/state_[g]vim.vim) intended?

### ISSUE THREAD

**Issue by tsuyoshicho** [Shougo/dein.vim#365]
# Problems summary

The following operation produced different results, with the latter unintentionally polluting the global variable.
If that is what is intended, does that mean I should do the conflict avoidance and cleanup of each variable myself?

I have checked HELP but could not confirm that this is the case.

## Environment Information (Required!)

 * dein.vim version(SHA1): 444b333ab3908ca49ca3b22ad15e4e1c0ae712f4

 * OS: Windows 10 Pro 1909 18363.752

 * Vim/neovim version: 

```text
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  6 2020 07:51:55)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-357
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

Invoke

`gvim -N -u testvimrc.vim`

```vim:testvimrc.vim
set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.vim/rc')
  call dein#begin('~/.vim/rc', [$MYVIMRC, '~/.vim/rc/test.toml'])

  call dein#load_toml('~/.vim/rc/test.toml', {'lazy': 0})

  call dein#end()
  call dein#save_state()

endif
```

```toml:test.toml
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
for [name, value] in [['a',0], ['b', 1]]
  echo name value
endfor
'''
```

## The reproduce ways from Vim starting (Required!)

0. add the following code to hook_add of optional plugins
1. modify the toml file or `call dein#clear_cache()` (disable the cache).
2. vim startup
3. Try `echo name` or `echo value` -> it says undefined.
4. exit and start vim (using state_vim.vim)
5. Try `echo name` or `echo value` -> 'b' or 1 is given.

## Screen shot (if possible)

nothing.

## Upload the log messages by `:redir` and `:message` (if errored)

When using `lightline` var, broke Lightline setting in startup time.
(rename to recover).

Error user specific, not write in it.

**Comment by Shougo** [comment]
Fixed.

Note: `hook_add` was executed, but it was silent.

**Comment by Shougo** [comment]
> call dein#clear_cache()

It must be `dein#clear_state()`.

**Comment by tsuyoshicho** [comment]
Thanks OK.
