### ISSUE TITLE
dein fails to load theme color

### ISSUE THREAD

**Issue by cybaol** [Shougo/dein.vim#376]
My previous plugmanager is vim-plug, but now I am using dein

but I encounter a confusing problem

if I add below:

```
if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('tomasr/molokai', {'merged': 0})
    call dein#end()
    call dein#save_state()
endif
set t_Co=256
set termguicolors
colorscheme molokai
```

the molokai color failed to load, the fonts is pure white.

and then I try follows:

```
if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('tomasr/molokai', {'merged': 0})
    call dein#end()
    call dein#save_state()
endif

call plug#begin('~/.config/nvim/plugged')
call plug#end()

set t_Co=256
set termguicolors
colorscheme molokai
```

the molokai theme is normal, beause I added vim-plug, though I am not install any plugin with it.
I have read FAQ, I was so confused.

**Comment by Shougo** [comment]
Please execute `call dein#install()`.
Please read the documentation.

**Comment by Shougo** [comment]
Minimal vimrc.

```vim
set runtimepath^=~/work/dein.vim

call dein#begin('~/work/test')
call dein#add('tomasr/molokai', {'merged': 0})
call dein#end()

filetype plugin indent on
syntax enable

set t_Co=256
set termguicolors
colorscheme molokai
```

**Comment by cybaol** [comment]
Oh Thank you!
I put those

filetype plugin indent on
syntax enable

before dein#begin('') 

because it existed in my init.vim long long ago

**Comment by Shougo** [comment]
Oh.  You need to put them after dein#end.
