### ISSUE TITLE
A plugin sometimes doesn't update with `dein#check_update()`

### ISSUE THREAD

**Issue by hexium310** [Shougo/dein.vim#384]
# Problems summary
When the command that updates the timestamp of `.git` (e.g. `git reset --hard HEAD~`) was run in a plugin directory, a plugin sometimes doesn't update  with `dein#check_update()`. This issue occur when the timestamp of `.git` after running command is newer than `pushedAt` of its repository.

## Environment Information (Required!)

 * dein.vim version(SHA1): 0c96f85

 * OS: macOS 10.14.6

 * Vim/neovim version: NVIM v0.5.0-639-g46e74142a

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
const s:dein_dir = expand('$XDG_CACHE_HOME/dein')
const s:dein_core_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if isdirectory(s:dein_core_dir)
  let &runtimepath .= ',' . s:dein_core_dir
  let g:dein#install_github_api_token = '***'

  if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)

    call dein#add('Shougo/dein.vim')
    call dein#add('vim-jp/syntax-vim-ex')

    if dein#check_install()
      call dein#install()
    endif

    call dein#end()
    call dein#save_state()
  endif
endif

```

## The reproduce ways from Vim starting (Required!)

 1. `:call dein#update()`
 2. 
```sh
$ cd $XDG_CACHE_HOME/dein/repos/github.com/vim-jp/syntax-vim-ex
$ git reset --hard HEAD~
```
 3. `:call dein#check_update(v:true)`

**Comment by Shougo** [comment]
sorry.  It is the feature.
`dein#check_update()` is not perfect solution.

dein does not save the repository update time, so it uses `.git` directory timestamp.

If you have better implementation, please send the PR.

**Comment by Shougo** [comment]
Please test https://github.com/Shougo/dein.vim/pull/385 changes.

**Comment by hexium310** [comment]
I checked that the plugins updated after `git reset`. Thank you.

**Comment by Shougo** [comment]
OK.  Merged.
