### ISSUE TITLE
[Little help to start]

### ISSUE THREAD

**Issue by lesar** [Shougo/dein.vim#388]
**Warning:  i am new to neovim **

# First installation show strange chars E612 E613 E608 E609 

## Ubuntu 20.04 64bit on rpi4

 * dein.vim version(SHA1): tell me how find it. I use your instruction to install on quick start https://github.com/Shougo/dein.vim ... to see version I usually do `apt policy` command 

 * Vim/neovim version: 0.4.4-1\~ubuntu20.04.1~ppa1

## Provide a minimal .vimrc with less than 50 lines (Required!)
this is my .config/nvim/init.vim  
```vim
scriptencoding utf-8
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif
" Required:
set runtimepath+=/home/leonardo/.local/share/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/leonardo/.local/share/dein')
  call dein#begin('/home/leonardo/.local/share/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/leonardo/.local/share/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')

  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')

  "source /home/leonardo/.config/nvim/loaded-plugins.vim

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------

"-------------------Load files-----------------
"source ~/.config/nvim/base.vim
"source ~/.config/nvim/plugins.vim
"source ~/.config/nvim/ui.vim
"source ~/.config/nvim/mappings.vim
"source ~/.config/nvim/misc.vim

```

## The reproduce ways from Vim starting (Required!)

$ nvim .  
all subfolder have strange char

## Screen shot (if possible)
![Schermata del 2020-10-09 12-39-39](https://user-images.githubusercontent.com/6347403/95574122-c2ebbc80-0a2c-11eb-9de2-ff6a8c7af424.png)

This chars are normal?  
Have to install something?

I know this is silly question but I'm stopped: I do not understand what was go wrong.

best regard,
Leonardo

**Comment by lesar** [comment]
Ok I see that is a NerdTree airline problem sorry

**Comment by Shougo** [comment]
Please read this.
https://github.com/vim-airline/vim-airline#integrating-with-powerline-fonts
