### ISSUE TITLE
Undefined behavior when using same repo with multiple rtps and no name

### ISSUE THREAD

**Issue by hasufell** [Shougo/dein.vim#391]
## Problems summary

With the following plugin config

```vim
call dein#add('https://gogs.hasufell.de/hasufell/vim-unmanaged.git', { 'rtp': 'L9' })
call dein#add('https://gogs.hasufell.de/hasufell/vim-unmanaged.git', { 'rtp': 'bufonly' })
```

dein will only import the last plugin, because of name clash I assume. You have to explicitly set a name to fix this.

Whether this is made into an error or fixed by considering `rtp` for the default identifier, I don't know. But the current behavior seems rather surprising and implicit.

## Expected

All plugins are loaded.

## Environment Information (Required!)

 * dein.vim version(SHA1): 80aae6bdd80b3f85f8ab39fc5a57a8c908d50222

 * OS: Exherbo Linux

 * Vim/neovim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim

call dein#begin('~/.cache/dein')
call dein#add('https://gogs.hasufell.de/hasufell/vim-unmanaged.git', { 'rtp': 'L9' })
call dein#add('https://gogs.hasufell.de/hasufell/vim-unmanaged.git', { 'rtp': 'bufonly' })

call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. start vim
 2. try to run an L9 command, such as `:L9Assert`

**Comment by Shougo** [comment]
Please specify name.

```vim
call dein#add('https://gogs.hasufell.de/hasufell/vim-unmanaged.git', { 'name': 'unmanaged-L9', 'rtp': 'L9' })
call dein#add('https://gogs.hasufell.de/hasufell/vim-unmanaged.git', { 'name': 'unmanaged-bufonly', 'rtp': 'bufonly' })
```

**Comment by Shougo** [comment]
> You have to explicitly set a name to fix this.

Yes.  And I don't change the behavior.

> Whether this is made into an error or fixed by considering rtp for the default identifier, I don't know. But the current behavior seems rather surprising and implicit.

Because the directory structure is not standard and ugly.
The plugins should be provided by separated repository.
Note: I don't see the problem ever.
To support the feature, it breaks current implementation.  So I reject the feature request.

**Comment by Shougo** [comment]
I have added overwrite check for it.
