### ISSUE TITLE
Dein save_state and load_state behaves different for vim and neovim

### ISSUE THREAD

**Issue by PanagiotisS** [Shougo/dein.vim#394]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

`dein#save_state()` and `dein#load_state()` have different behaviour in neovim and vim.

In vim `dein#load_state()` returns 0 after `dein#save_state()` has been called and no futher changes have been made.

In neovim `dein#load_state()` return 1 every time we open neovim, even though `dein#save_state()` has been called, no furhter changes have been made, and the `state_nvim.vim` file exists.

## Expected

If I understand correctly the documentation then I would expect vim (step 8a) and neovim (step 8b) to behave the same.
The expected behaviour to be the one that vim has.

## Environment Information (Required!)

 * dein.vim version(SHA1): https://github.com/Shougo/dein.vim/commit/f8b3868cb8f844c5cd598130230d5155f2a94dd4

 * OS:  CentOS Linux release 7.8.2003 (Core)

 * Vim version: VIM - Vi IMproved 8.0, Included patches: 1-1813

* neovim version: NVIM v0.5.0-799-g186ba3b68 - https://github.com/neovim/neovim/commit/186ba3b68868dd35013b96b795ff17952b0853cb

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set encoding=utf-8
scriptencoding utf-8

if has('nvim')
    let &runtimepath .= ',' . expand(stdpath('cache') . '/dein/repos/github.com/Shougo/dein.vim/')
    let s:path = expand(stdpath('cache') . '/dein')
else
    let &runtimepath .= ',' . expand('$HOME/.vim/dein/repos/github.com/Shougo/dein.vim/')
    let s:path = expand('$HOME/.vim/dein')
endif

echom dein#load_state(s:path)

if dein#load_state(s:path)
    call dein#begin(s:path)

    call dein#add('Shougo/dein.vim')

    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

1. open vim/neovim
2. `:call dein#clear_state()`
3. close vim/neovim
4. open vim/neovim
5. `dein#load_state()` will return 1 and therefore will read the plugins' configuration and subsequently will call `dein#save state()`
6. close vim/neovim
7. open vim/neovim
8. Line number 12 `echom dein#load_state(s:path)` will 
    a. **vim**: will return 0 and therefore it will continue without reading the plugins' configuration again.
    b. **neovim**: will return 1 and therefore it will read the plugins' configuration again even though no changes were made

## Screen shot (if possible)
I can create a video clip if it will be useful. 

## Upload the log messages by `:redir` and `:message` (if errored)
At step 8 we have the following messages:

vim:
```
Messages maintainer: Mike Williams <mrw@eandem.co.uk>
0
"vimrc" 25L, 582C

Press ENTER or type command to continue
```
neovim
```
1
```

## Futher comments

If we open the file `state_nvim.vim` we are intereseted in the first line where the comparison
` g:dein#_init_runtimepath !=# ... ` fails.

```
if g:dein#_cache_version !=# 150 || g:dein#_init_runtimepath !=# '/home/ps/.config/nvim,/etc/xdg/nvim,/home/ps/.local/share/nvim/site,/home/ps/.local/share/flatpak/exports/share/nvim/site,/var/lib/flatpak/exports/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/tmp/.mount_nvimkcp4Eu/usr/share/nvim/runtime,/tmp/.mount_nvimkcp4Eu/usr/lib/nvim,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/var/lib/flatpak/exports/share/nvim/site/after,/home/ps/.local/share/flatpak/exports/share/nvim/site/after,/home/ps/.local/share/nvim/site/after,/etc/xdg/nvim/after,/home/ps/.config/nvim/after,/home/ps/.cache/nvim/dein/repos/github.com/Shougo/dein.vim/' | throw 'Cache loading error' | endif
let [plugins, ftplugin] = dein#load_cache_raw(['/home/ps/.config/nvim/init.vim'])    
if empty(plugins) | throw 'Cache loading error' | endif    
let g:dein#_plugins = plugins    
let g:dein#_ftplugin = ftplugin    
let g:dein#_base_path = '/home/ps/.cache/nvim/dein'    
let g:dein#_runtime_path = '/home/ps/.cache/nvim/dein/.cache/init.vim/.dein'    
let g:dein#_cache_path = '/home/ps/.cache/nvim/dein/.cache/init.vim'    
let &runtimepath = '/home/ps/.config/nvim,/etc/xdg/nvim,/home/ps/.local/share/nvim/site,/home/ps/.local/share/flatpak/exports/share/nvim/site,/var/lib/flatpak/exports/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/home/ps/.cache/nvim/dein/repos/github.com/Shougo/dein.vim,/home/ps/.cache/nvim/dein/.cache/init.vim/.dein,/tmp/.mount_nvimkcp4Eu/usr/share/nvim/runtime,/home/ps/.cache/nvim/dein/.cache/init.vim/.dein/after,/tmp/.mount_nvimkcp4Eu/usr/lib/nvim,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/var/lib/flatpak/exports/share/nvim/site/after,/home/ps/.local/share/flatpak/exports/share/nvim/site/after,/home/ps/.local/share/nvim/site/after,/etc/xdg/nvim/after,/home/ps/.config/nvim/after,/home/ps/.cache/nvim/dein/repos/github.com/Shougo/dein.vim/'
filetype off 
```

For clarity, on the first line `g:dein#_init_runtimepath` compares to the following strings
```
/home/ps/.config/nvim,
/etc/xdg/nvim,
/home/ps/.local/share/nvim/site,
/home/ps/.local/share/flatpak/exports/share/nvim/site,
/var/lib/flatpak/exports/share/nvim/site,
/usr/local/share/nvim/site,
/usr/share/nvim/site,
/tmp/.mount_nvimj1pPcC/usr/share/nvim/runtime,
/tmp/.mount_nvimj1pPcC/usr/lib/nvim,
/usr/share/nvim/site/after,
/usr/local/share/nvim/site/after,
/var/lib/flatpak/exports/share/nvim/site/after,
/home/ps/.local/share/flatpak/exports/share/nvim/site/after,
/home/ps/.local/share/nvim/site/after,
/etc/xdg/nvim/after,
/home/ps/.config/nvim/after,
/home/ps/.cache/nvim/dein/repos/github.com/Shougo/dein.vim/
```

I think the problem lies with the following
```
/tmp/.mount_nvimj1pPcC/usr/share/nvim/runtime,
/tmp/.mount_nvimj1pPcC/usr/lib/nvim,
```
where each time we open a new neovim instance, is using a different socket/path and therefore it will be different each time.

For comparison the `state_vim.vim` file has
```
if g:dein#_cache_version !=# 150 || g:dein#_init_runtimepath !=# '/home/ps/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/home/ps/.vim/after,/home/ps/.vim/dein/repos/github.com/Shougo/dein.vim/' | throw 'Cache loading error' | endif 
let [plugins, ftplugin] = dein#load_cache_raw(['/home/ps/.vim/vimrc'])
if empty(plugins) | throw 'Cache loading error' | endif
let g:dein#_plugins = plugins
let g:dein#_ftplugin = ftplugin
let g:dein#_base_path = '/home/ps/.vim/dein'
let g:dein#_runtime_path = '/home/ps/.vim/dein/.cache/vimrc/.dein'
let g:dein#_cache_path = '/home/ps/.vim/dein/.cache/vimrc'
let &runtimepath = '/home/ps/.vim,/usr/share/vim/vimfiles,/home/ps/.vim/dein/repos/github.com/Shougo/dein.vim,/home/ps/.vim/dein/.cache/vimrc/.dein,/usr/share/vim/vim80,/home/ps/.vim/dein/.cache/vimrc/.dein/after,/usr/share/vim/vimfiles/after,/home/ps/.vim/after,/home/ps/.vim/dein/repos/github.com/Shougo/dein.vim/'
filetype off
```

**Comment by Shougo** [comment]
>where each time we open a new neovim instance, is using a different socket/path and therefore it will be different each time.

Why the mount path is used?
I don't reproduce problem, so it is your environment problem.
Please describe it.

And the runtimepath cache is needed. Because in the statefile, runtimepath is overwritten!

**Comment by Shougo** [comment]
I don't want to change current behavior.
It affects dein's performance.
To change neovim runtimepath is better.

**Comment by PanagiotisS** [comment]
> > where each time we open a new neovim instance, is using a different socket/path and therefore it will be different each time.
> 
> Why the mount path is used?
> I don't reproduce problem, so it is your environment problem.
> Please describe it.
>
> And the runtimepath cache is needed. Because in the statefile, runtimepath is overwritten!

After your reply I did some further testing and apparently this behaviour happens only when using the appimage.
In the initial post I was using appimage. It did not occur to me that this might be the issue before I see your reply.

I tested it on my (fedora 32) laptop and

1. neovim using the package manager (dnf package from a copr repo - version https://github.com/neovim/neovim/commit/5b5848f2fb1f4b7995bb8a59d94b6766d2182070).
    -  The runtimepath and therefore the state file did not include the mount path.

2. neovim appimage (https://github.com/neovim/neovim/commit/eee0668818bee673b0f1637340c358cf83da2347)
    - Reproduced the same problem as the initial post on my CentOS workstation. The mount path in the runtimepath and therefore in the state file. 

> I don't want to change current behavior.
> It affects dein's performance.
> To change neovim runtimepath is better.

Understandable. This problem seems to occur only when using the appimages.

**Comment by Shougo** [comment]
OK.  If so, dein.vim does not support neovim appimage environment.
