### ISSUE TITLE
Hooks can not be functions

### ISSUE THREAD

**Issue by hackaugusto** [Shougo/dein.vim#398]
# Problems summary

The hook documentation says that these hooks can be functions, however, providing a function to a hook results in a runtime error.

Example hook:

https://github.com/Shougo/dein.vim/blob/f817ef6a3a710cd397f538f131385b4fab99e5f8/doc/dein.txt#L879

Code checking the hook type:

https://github.com/Shougo/dein.vim/blob/f817ef6a3a710cd397f538f131385b4fab99e5f8/autoload/dein/util.vim#L334-L339 

## Expected

Either the hook should be allowed to be a function or the documentation should be updated

## Environment Information (Required!)

 * dein.vim version(SHA1): f817ef6a3a710cd397f538f131385b4fab99e5f8

 * OS: Fedora 33

 * Vim/neovim version: neovim v0.5.0-dev

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
function TreeSitterUpdateParsers()
endfunction
call dein#begin(path)
call dein#add('nvim-treesitter/nvim-treesitter', {'hook_post_update': function('TreeSitterUpdateParsers')})
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

run `call dein#clear_state()` and open neovim
 
## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/310139/105634011-28d54600-5e5c-11eb-91ab-5ef7ab79c5a9.png)

## Upload the log messages by `:redir` and `:message` (if errored)

> [dein] nvim-treesitter: "hook_post_update" must be string

**Comment by Shougo** [comment]
Please read this.

```
HOOKS							*dein-hooks*

		The string will be split by the lines.
		It is useful for the plugins initialization.
		Note: The Function hooks cannot be cached.  You must
		initialize it.
```

**Comment by Shougo** [comment]
Please don't make a lie in the minimal vimrc.
You have called `dein#save_state()` in init.vim.

But it is not included in the vimrc.
So you have not tested the vimrc.

>Either the hook should be allowed to be a function or the documentation should be updated

It cannot be allowed because function objects cannot be cached.
It is not magic.
