### ISSUE TITLE
dein#local() and frozen option: strange behavior

### ISSUE THREAD

**Issue by AlexMasterov** [Shougo/dein.vim#4]
### dein#local()
From the documentation:
> dein#local(**{directory}**, [{options}, [{names}]])

Simplest test:
```viml
call dein#local("~/vim/dotvim", {}, ['plugin'])

call dein#update()
```
The plugin will be loaded, but with the message:
> [dein] ~/vim/dotvim/plugin
> [dein] fatal: Not a git repository (or any of the parent directories): .git

### frozen option (no doc.)
```viml
call dein#add('Shougo/unite.vim', {'frozen': 1})
call dein#local("~/vim/dotvim", {'frozen': 1}, ['plugin'])

call dein#update()
```
In both cases we get the exception (and interruption update):
> Error detected while processing function dein#update[1]..dein#install#_update[9]..<SNR>35_install[23]..<SNR>35_sync[46]..vimproc#pgroup_open[15]..<SNR>36_pgroup_open:
> line 5:
> E684: list index out of range: 0
> E116: Invalid arguments for function vimproc#util#cd

It seems to run an "empty" command, because "cmd" var. will be empty when there is the frozen option: [dein/install.vim#L172](https://github.com/Shougo/dein.vim/blob/master/autoload/dein/install.vim#L172)

**Comment by Shougo** [comment]
> frozen option (no doc.)

I have added the doc.
