### ISSUE TITLE
Extra-step required for sniprun

### ISSUE THREAD

**Issue by galou** [Shougo/dein.vim#400]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

The [sniprun package](https://github.com/michaelb/sniprun) is not fully-install without manual step. A manual step is required: `cp $HOME/.cache/dein/repos/github.com/michaelb/sniprun/target/release/sniprun $HOME/.cache/dein/.cache/init.vim/.dein/target/release/sniprun`. A rust installation is required.

## Expected

`call dein#add('michaelb/sniprun', {'do': 'bash install.sh'})` should suffice.

## Environment Information (Required!)

 * dein.vim version(SHA1):

0712ab04f2aabefb656cb1e1973c32b9e6c1393b (commit 5c8f935d062db0ebfa16983d1be9a9487526b875)

 * OS: Ubuntu 20.04 (also Ubuntu 18.04)

 * Vim/neovim version:

NVIM v0.5.0-dev

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
call dein#begin(expand('~/.cache/dein'))
call dein#add('michaelb/sniprun', {'do': 'bash install.sh'})
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. vim

## Upload the log messages by `:redir` and `:message` (if errored)
```
Error detected while processing function <SNR>124_connect[1]..<SNR>124_initRpc:                            
line    2:
E475: Invalid value for argument cmd: '/home/gael/.cache/dein/.cache/init.vim/.dein/target/release/sniprun' is not ex
ecutable
Error detected while processing function <SNR>124_connect:
line    5:
sniprun: rpc process is not executable
```

**Comment by Shougo** [comment]
Please read `dein-options-build`.
dein is not vim-plug.  `do` does not work in dein.
