### ISSUE TITLE
README.md does not contain vital .vimrc example comments

### ISSUE THREAD

**Issue by albertas** [Shougo/dein.vim#402]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
README.md does not contain some informative comments for .vimrc file configuration. It was not clear for me how to add new Plugins using dein until I have installed dein and saw some text in the terminal.

## Expected
README.md contains this example (including all comments) - I got this printed in the terminal when installing this plugin manager and found it to be extremely useful:

> if &compatible
>   set nocompatible               " Be iMproved
> endif
> 
> " Required:
> set runtimepath+=/home/niekas/.vim/bundle/repos/github.com/Shougo/dein.vim
> 
> " Required:
> if dein#load_state('/home/niekas/.vim/bundle')
>   call dein#begin('/home/niekas/.vim/bundle')
> 
>   " Let dein manage dein
>   " Required:
>   call dein#add('/home/niekas/.vim/bundle/repos/github.com/Shougo/dein.vim')
> 
>   " Add or remove your plugins here like this:
>   "call dein#add('Shougo/neosnippet.vim')
>   "call dein#add('Shougo/neosnippet-snippets')
> 
>   " Required:
>   call dein#end()
>   call dein#save_state()
> endif
> 
> " Required:
> filetype plugin indent on
> syntax enable
> 
> " If you want to install not installed plugins on startup.
> "if dein#check_install()
> "  call dein#install()
> "endif

## Environment Information (Required!)

 * dein.vim version(SHA1): 531a4bfc12784848162d89290d2d71028a5c8134

 * OS: Ubuntu 20.04

 * Vim/neovim version: 8.1 1-2269 Vim

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
" Its empty, however I really want this issue to be accepted and solved
" To make this package manager more accessible to others
```

## The reproduce ways from Vim starting (Required!)

 1. Open  https://vimawesome.com/plugin/dein-vim
 2. Read the description (some informative comments are missing)
 3. Open https://github.com/Shougo/dein.vim
 4. Read the description (some informative comments are missing)

**Comment by Shougo** [comment]
> README.md contains this example (including all comments) - I got this printed in the terminal when installing this plugin manager and found it to be extremely useful:

Really???  I have added the example.
Why don't you read the documentation...
