### ISSUE TITLE
"call dein#save_state()" prevents deoplete in neovim

### ISSUE THREAD

**Issue by MasaYan24** [Shougo/dein.vim#404]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When deoplete is installed, the default call
```vim
call dein#save_state()
```
prevents deoplete suggestions in neovim.

## Expected
deoplete works fine.

## Environment Information (Required!)

 * dein.vim version(SHA1): 2.0

 * OS: Ubuntu, (macOS)
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

 * Vim/neovim version: 
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/root/.vim/bundles/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/root/.vim/bundles/dein')
  call dein#begin('/root/.vim/bundles/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/root/.vim/bundles/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  call dein#add('Shougo/deoplete.nvim')
    if !has('nvim')
      call dein#add('roxma/nvim-yarp')
      call dein#add('roxma/vim-hug-neovim-rpc')
    endif
  let g:deoplete#enable_at_startup = 1

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

let g:python3_host_prog = "/usr/bin/python3"
```

## The reproduce ways from Vim starting (Required!)
1. docker run -it ubuntu bash
1. apt update
1. apt install neovim
1. apt install curl
1. apt install git
1. apt install python3-pip
1. pip3 install pynvim -U
1. curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
1. sh installer.sh ~/.vim/bundles/dein
1. mkdir -p ~/.config/nvim
1. create above ~/.config/nvim/init.vim

## Screen shot (if possible)
https://user-images.githubusercontent.com/7567050/109255012-859a9680-7836-11eb-9e4c-6f876bd1d909.mov

**Comment by MasaYan24** [comment]
Dockerfile is also created.
[dockerfile.zip](https://github.com/Shougo/dein.vim/files/6047448/dockerfile.zip)

**Comment by Shougo** [comment]
OK. I have get the reason.

```
							*dein#load_state()*
dein#load_state({base-path})
		Load dein's state from the cache script,
		which is located in `dein#util#_get_runtime_path() . '/state_'
		.  fnamemodify(v:progname, ':r') . '.vim'`.
		{base-path} is where your downloaded plugins will be placed.
		Note: You must call it before |dein#begin()|.  It clears dein
		all configuration.
		Note: It overwrites your 'runtimepath' completely, you must
		not call it after change 'runtimepath' dynamically.
		Note: The block is skipped if dein's state is loaded.
```

> Note: The block is skipped if dein's state is loaded.

Your `let g:deoplete#enable_at_startup = 1` is inside the block.

So it will be skipped.

Solution:

```vim
" Required:
if dein#load_state('/root/.vim/bundles/dein')
  call dein#begin('/root/.vim/bundles/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/root/.vim/bundles/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  call dein#add('Shougo/deoplete.nvim')
    if !has('nvim')
      call dein#add('roxma/nvim-yarp')
      call dein#add('roxma/vim-hug-neovim-rpc')
    endif

  " Required:
  call dein#end()
  call dein#save_state()
endif

let g:deoplete#enable_at_startup = 1
```
