### ISSUE TITLE
Question: How to install specific version or commit ID of plugins

### ISSUE THREAD

**Issue by huyu398** [Shougo/dein.vim#406]
Plugins often contain bugs, so the plugin manager needs to have the ability to install a specific version of a plugin.
dein.vim is a very good plugin manager, but it doesn't seem to have this kind of version-specific installation feature.
ex) On pip, "pip install pip==21.1".

Is it possible to install a specific version with dein.vim?
If it is not possible now, do you plan to develop it?

Thank you.

**Comment by Shougo** [comment]
Please use rev option.

```
							*dein-options-rev*
rev		(String)
		Specify a revision number or branch/tag name.
		If it is "*" in "git" type, dein will use latest released tag.
		You can specify the wildcards like "0.*".
		Note: If the type is "raw", rev must be hash number.

		Example:
>
		call dein#add('Shougo/deol.nvim', { 'rev': 'a1b5108fd5' })
<
```

**Comment by huyu398** [comment]
@Shougo Thanks a lot!
I was in great trouble.
