### ISSUE TITLE
Question: Is it possible to exclude specific file type for on_ft of lazy load  ?

### ISSUE THREAD

**Issue by JohnRama** [Shougo/dein.vim#408]
Thank you very much for the great plugin.

I am a beginner for vim/nvim, so let me ask just one simple question.

I would like to load a plugin when the file type is not hoge.
Is it possible to do that ?

> 
> [[plugins]]
> repo = 'SirVer/ultisnips'
> on_ft = ['!hoge'] "something like this

If not, what would be good as the alternative way ?

Thanks !!

John

**Comment by Shougo** [comment]
The feature is not so useful.

The feature is really needed, you can use `dein#source()` for it.
