### ISSUE TITLE
[Feature Request] Silence unwanted notifications

### ISSUE THREAD

**Issue by IhsanGunay** [Shougo/dein.vim#410]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Can you add a g:dein#silence_notifications setting? I get a notification every time I modify my toml files. g:dein#auto_recache also sends a notification. 

## Environment Information (Required!)

 * dein.vim version(SHA1):

 * OS:

 * Vim/neovim version:

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by IhsanGunay** [comment]
Solved the problem with adding this line to my init.vim:

au Bufread ~/.config/nvim/* let g:dein#auto_recache=1

**Comment by Shougo** [comment]
> Can you add a g:dein#silence_notifications setting? I get a notification every time I modify my toml files. g:dein#auto_recache also sends a notification.

???

I don't get the behavior.  I think you have modified dein loaded toml files.
If so, it is intended behavior.

We have not ESP skills.

**Comment by Shougo** [comment]
You can check `dein#util#_check_vimrcs()` implementation.

**Comment by IhsanGunay** [comment]
Hi Shougo,

I was talking about the messges displayed by the dein#util#_notify calls in the echo area. The function is called no matter what but for some reason echo area is clear with the autocommand I posted above and the dein cache is handled proparly. If anyone else cares about the messages too they can find the workaround here.

I think the messages I complained about are produced by the functions below.

dein.vim/autoload/dein/util.vim
`function! dein#util#_save_state(is_starting) abort
  if g:dein#_block_level != 0
    call dein#util#_error('Invalid dein#save_state() usage.')
    return 1
  endif

  if dein#util#_get_cache_path() ==# '' || !a:is_starting
    " Ignore
    return 1
  endif

  if get(g:, 'dein#auto_recache', v:false)
    call dein#util#_notify('auto recached')
    call dein#recache_runtimepath()
  endif`

dein.vim/autoload/dein.vim
`function! dein#clear_state() abort
  call dein#util#_clear_state()

  if !get(g:, 'dein#auto_recache', v:false) && !empty(g:dein#_ftplugin)
    call dein#util#_notify(
          \ 'call dein#recache_runtimepath() is needed for ftplugin feature')
  endif
endfunction`

**Comment by Shougo** [comment]
> I was talking about the messges displayed by the dein#util#_notify calls in the echo area. The function is called no matter what but for some reason echo area is clear with the autocommand I posted above and the dein cache is handled proparly. If anyone else cares about the messages too they can find the workaround here.

`call dein#recache_runtimepath()` should be called silently??  Really??
The main thing is why the cache is re-generated.
I think you have edit dein loaded toml files.  It is true?

**Comment by Shougo** [comment]
> I think the messages I complained about are produced by the functions below.

It is true.  But this is intended.

**Comment by Shougo** [comment]
Please check `dein#util#_check_vimrcs()` behavior.
The cache is only cleared if you have edit dein config files.
But it may contain some bugs.
I cannot reproduce your problem.

**Comment by IhsanGunay** [comment]
I just prefer it that way. Yeah, I am using toml files to load plugins. I thought it wouldn't be possible to silence the messages without touching source code but the hack I posted works. So it's up to you if you want to add the setting or not. Either way I don't have an issue anymore.

**Comment by IhsanGunay** [comment]
I couldn't eproduce my problem either but I had to clear cache manually twice so I want it recached every time I edit the tomls.

**Comment by Shougo** [comment]
https://github.com/Shougo/dein.vim/issues/410#issuecomment-875136234

Why it fixes your problem?  I don't understand.
If your config is under `~/.config`, it seems same.

**Comment by Shougo** [comment]
> I just prefer it that way. Yeah, I am using toml files to load plugins. I thought it wouldn't be possible to silence the messages without touching source code but the hack I posted works. So it's up to you if you want to add the setting or not. Either way I don't have an issue anymore.

I don't understand.  Need minimal vimrc.  I will test your config.

**Comment by IhsanGunay** [comment]
It doesn't produce the messages in the echo area. I don't know why. I am guessing it discards the messages before vim startsup completely.

**Comment by IhsanGunay** [comment]
```
set runtimepath+=~/.local/share/dein/repos/github.com/Shougo/dein.vim
let s:hare = '~/.config/nvim/dein.toml'
let s:tortoise = '~/.config/nvim/deinlazy.toml'
let s:elephant = '~/.config/nvim/deinft.toml'

if dein#load_state('~/.local/share/dein')
 call dein#begin('~/.local/share/dein')
 call dein#load_toml(s:hare, {'lazy': 0})
 call dein#load_toml(s:tortoise, {'lazy': 1})
 call dein#load_toml(s:elephant)
 call dein#end()
 call dein#save_state()
endif

au Bufread ~/.config/nvim/* let g:dein#auto_recache=1
```

**Comment by IhsanGunay** [comment]
If I set auto_recache at init.vim, I get the 'auto recached' message at every vim startup.
If I set `au Bufwritepost ~/.config/nvim/*.toml call dein#recache_runtimepath()`, I still get the annoying warning.

I looked at your dotfiles repo and it looks like you redirected the messages to your system notifications. Do you get a 'auto recached' notification at every vim startup?

**Comment by Shougo** [comment]
OH, really?  If so, your configuration is wrong.
Because

> If I set auto_recache at init.vim, I get the 'auto recached' message at every vim startup.

It should not if you don't edit config.

**Comment by Shougo** [comment]
> I looked at your dotfiles repo and it looks like you redirected the messages to your desktop notifications. Do you get a 'auto recached' notification at every vim startup?

NO.  It is only displayed after I edit config files.

**Comment by IhsanGunay** [comment]
Anyway, I have a working setup now. 
If you don't think a g:dein#silence_notifications setting is worth implementing, I have a workaround that works. 
If anyone else is annoyed by the messages, they can comment here to show that the setting would be used by more people.

**Comment by Shougo** [comment]
https://github.com/Shougo/dein.vim/issues/410#issuecomment-875232021

I have tested your vimrc and it works for me.
I don't get recache messages every startup.

**Comment by Shougo** [comment]
The main problem is not `silence unwanted notification`.
`I get the 'auto recached' message at every vim startup.` is the real problem.  But I cannot reproduce it.

**Comment by Shougo** [comment]
Hm...  You should create new environment in clear machine with minimal vimrc.
It should work.

**Comment by Shougo** [comment]
dein's cache feature seems disabled and I don't know why.
Because I cannot reproduce your problem with your vimrc.
We have not ESP skills!

But you can investigate the problem because it is open source.
