### ISSUE TITLE
hook_post_update fails

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/dein.vim#411]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
hook_post_update fails.

## Expected
hook_post_update does not fail.

## Environment Information (Required!)

 * dein.vim version(SHA1): 2cb22882bd00665657c425043b45dafb53d419aa

 * OS: Mac

 * Vim/neovim version: NVIM v0.6.0-dev+69-gbebca7bbe

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif
let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#add('tzachar/compe-tabnine', {
          \ 'hook_post_update': 'call system("bash install.sh")'
          \ })

call dein#end()
call dein#save_state()

if has('vim_starting') && dein#check_install()
    call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. Stat neovim.
 2. Run `call  dein#update()`
 3. An error will occur.

## Screen shot (if possible)
![スクリーンショット 2021-07-27 1 34 50](https://user-images.githubusercontent.com/3197942/127025729-190c7b34-723b-432b-a66b-798bf3197338.png)

**Comment by nabezokodaikon** [comment]
The same symptoms no longer occur. However, the plugin is no longer installed, as shown below.

![スクリーンショット 2021-07-27 5 05 31](https://user-images.githubusercontent.com/3197942/127052013-d7c141e2-7f9a-452a-bf51-6d65169155ce.png)

**Comment by Shougo** [comment]
It works for me.

```vim
set nocompatible
set rtp+=~/work/dein.vim/

call dein#begin('~/.cache/dein')

call dein#add('tzachar/compe-tabnine', {
          \ 'hook_post_update': 'call system("bash install.sh")'
          \ })

call dein#end()
```

Please test it in the clean environment.
Really have you tested the vimrc?
The error message seems you have used `'hook_post_update': 'bash install.sh'` instead.

**Comment by nabezokodaikon** [comment]
Is a clean environment with `~/.cache/dein` or `~/.local/share/dein` removed?

**Comment by Shougo** [comment]
Yes.

**Comment by nabezokodaikon** [comment]
No matter how many times I erase it and try again, it doesn't work ...

**Comment by Shougo** [comment]
Really?  Please test it on the another machine with my vimrc.

**Comment by Shougo** [comment]
It is not reproduced with another machine.

**Comment by Shougo** [comment]
https://github.com/Shougo/dein.vim/issues/411#issue-953113090

It is reproduced by `'hook_post_update': 'bash install.sh'`.
But I don't reproduce https://github.com/Shougo/dein.vim/issues/411#issuecomment-886991265 problem.
nvim-compe is installed.

**Comment by Shougo** [comment]
I think your plugin is already installed.

**Comment by nabezokodaikon** [comment]
I've tried other plugins, but why do I see `Not installed plugins: ['tzachar/compe-tabnine']` in the message even though it's installed on `~/.cache/dein`?

**Comment by Shougo** [comment]
I think you have cleared `~/.cache/dein`.

**Comment by gamoutatsumi** [comment]
https://github.com/Shougo/dein.vim/issues/411#issuecomment-886991265 isn't after delete `~/.cache/dein`?
I deleted `~/.cache/dein` then started neovim, found install log.
Then I restarted neovim (don't delete `~/.cache/dein`) no anything happened.

**Comment by nabezokodaikon** [comment]
Yes. This is the message when neovim is started after deleting `~/.cache/dein`. After that, if you restart neovim without doing anything, nothing happens.

**Comment by Shougo** [comment]
So it is right behavior.  What is the problem??

**Comment by nabezokodaikon** [comment]
I thought the problem was that message `Not installed plugins` was displayed even though the plugin was installed.

**Comment by Shougo** [comment]
So your problem is already resolved.

> After that, if you restart neovim without doing anything, nothing happens.

Because the plugin is already installed.

**Comment by nabezokodaikon** [comment]
Sorry. I see.
