### ISSUE TITLE
I can install the plugins

### ISSUE THREAD

**Issue by XtraSavx** [Shougo/dein.vim#412]
**Warning:This is the configuration that i want to clone: https://github.com/TeoDev1611/RocketVim **

# Problems summary
Well I have cloned a configuration that I liked but when I installed the plugins with the command **call dein # install ()**, it did not work for me and I already uninstalled dein and everything but it gives me the same error that nvim does not know that function.

## Expected
I want to clone and install the plugins

## Environment Information (Required!)

 **dein.vim version(SHA1):** Download today

 **OS:** Windows 10 Home

 **Vim/neovim version:** NVIM v0.6.0-dev+43-g02bf251bb

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
"------------------------------------------------------------------------------"
"                              Vim Plug Plugin Manager                         "
"------------------------------------------------------------------------------"
let g:coc_load = 0
let g:native_lsp = 1
let g:elixir_lang = 1
let g:rust_lang = 1
let g:python_lang = 1
let g:powershell_lang = 1
let g:editor_config = 1
let g:rocket_aparience = 1
let g:ide_tools = 1
let g:usefull_ide = 1
let g:colors_tools = 1
let g:fuzzy_find = 1
let g:golang_lang = 0

if g:coc_load
  if has('win32') || has('win64')
    source ~/appdata/local/nvim/lightline.vim
    " source ~/appdata/local/nvim/coc.vim
  elseif has('linux') || has('osxdarwin')
    " source ~/.config/nvim/coc.vim
    source ~/.config/nvim/lightline.vim
  else
    echoerr "Platform Unsupported"
  endif
endif


"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"                               Utils for manager                              "
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

if &compatible
  set nocompatible
endif

set runtimepath+=~/.cache/rocket/repos/github.com/Shougo/dein.vim

" Prefix your commands
function! s:prefix(str, args) abort
    return map(a:args, {_, s -> a:str . s})
endfunction

" Same as prefix but after :)
function! s:suffix(str, args) abort
    return map(a:args, {_, s -> s . a:str})
endfunction
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/81933734/127580664-a7a06f30-a912-46f4-a8fc-f459c8fb926e.png)

**Comment by Shougo** [comment]
This is not QA site.

```vim
set runtimepath+=~/.cache/rocket/repos/github.com/Shougo/dein.vim
```

You need to install dein.vim under `~/.cache/rocket/repos/github.com/Shougo/dein.vim`.

`$ git clone https://github.com/Shougo/dein.vim ~/.cache/rocket/repos/github.com/Shougo/dein.vim`

No magic.
