### ISSUE TITLE
Question: Have support for Lua?

### ISSUE THREAD

**Issue by TeoDev1611** [Shougo/dein.vim#414]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Dein have support for Lua API

## Expected
Support for the Lua API like require('dein') 

Any idea for this ?

**Comment by Shougo** [comment]
I don't add the support.  You can call Vim functions from Lua script.
If you want to manage plugins by Lua, you should use other plugin manager like packer.nvim.

You can request it for other plugin managers.  It will be rejected.
