### ISSUE TITLE
Disable with :if now not working 

### ISSUE THREAD

**Issue by thecontinium** [Shougo/dein.vim#418]
I am using `:if 0 `to disable an already defined plugin and then define it again with the same name ( from a different repo )

This is now failing after: https://github.com/Shougo/dein.vim/commit/42e21ad8c3147ff5d37eb1a9d14f98db3a78953e with `Plugin name .... is already defined.`

The help says use `:if` 

Is there a way to do this a different way now ?

**Comment by Shougo** [comment]
Please explain it more clearly.
It means `dein-options-if`?

You should not use `dein-options-if` for it.
It defines the plugin name if it is false.  Because to disable plugins more dynamically.

Your desired behavior is ...

```
if 0
  call dein#add()
else
  call dein#add()
endif
```

**Comment by thecontinium** [comment]
I will try and explain the situation. 

I am using a setup where plugins have already been added with dein#add(). I **cannot** change this addition.

I now would now like the option to either disable the plugin that has already been added or change the repo where the plugin is being installed from.  I was achieving this by using `:if 0`

The following example previously resulted in the plugin in repo2 being added. 
 ```
dein#add(repo1/plugin) (I cannot stop this)
dein#add(repo1/plugin, :if 0 )
dein#add(repo2/plugin)
```

Since your recent changes this no longer works.

I hope this makes sense.

**Comment by Shougo** [comment]
Oh, really?
Please use `overwrite` for it.

```vim
dein#add(repo1/plugin) (I cannot stop this)
dein#add(repo2/plugin, :overwrite 1)
```

**Comment by thecontinium** [comment]
Thanks.  I’ll try that.

**Comment by thecontinium** [comment]
works - thanks
