### ISSUE TITLE
error report: github submodule permission error in Windows

### ISSUE THREAD

**Issue by tsuyoshicho** [Shougo/dein.vim#421]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

[vim-gf-user](https://github.com/kana/vim-gf-user) plugin include git submodule.

Use this in dein, error message occur in Windows environment. 

## Expected

No error affected by repository.

## Environment Information (Required!)

 * dein.vim version(SHA1): [178e30a0c9db17a6c202c873dcfccd52acc197c5](https://github.com/Shougo/dein.vim/tree/178e30a0c9db17a6c202c873dcfccd52acc197c5)

 * OS: Windows 10 Pro (2021/08/22 latest Updated)

 * Vim/neovim version: 

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 19 2021 15:54:25)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-3358
```
(compiled by vim-tux project)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

setup minimal error vimrc in my repo

[commit hash](https://github.com/tsuyoshicho/testvimrc.vim/tree/1066131f7807442a18a149c83e78ab4428f966d2)

I think occur only `vim-gf-user`, but do not occur.
I send reproducing minimal set, sorry.

## The reproduce ways from Vim starting (Required!)

`vim -N --clean -u testvimrc.vim`

## Screen shot (if possible)

nothing.

## Upload the log messages by `:redir` and `:message` (if errored)

log message attach

```text
日本語メッセージ翻訳/監修: 村岡 太郎 <koron.kaoriya@gmail.com>
[dein] Not installed plugins: ['reword.vim', 'capture.vim', 'wilder.nvim', 'vim-altercmd', 'vim-gf-user', 'vim-gf-diff']
[dein] Update started: (2021/08/22 10:26:26)
[dein] Vim(py3):shutil.Error: [('D:/Data/ReposWork/git/testvimrc.vim/cache/dein/repos/github.com/kana/vim-gf-user\\.git\\modules\\mduem\\objects\\pack\\pack-ee177a31e6cf5a12387d19c37e2f9544ac6d983a.idx', 'D:/Data/ReposWork/git/testvimrc.vim/cache/dein/.cache/testvimrc.vim/.dein\\.git\\modules\\mduem\\objects\\pack\\pack-ee177a31e6cf5a12387d19c37e2f9544ac6d983a.idx', "[Errno 13] Permission denied: 'D:/Data/ReposWork/git/testvimrc.vim/cache/dein/.cache/testvimrc.vim/.dein\\\\.git\\\\modules\\\\mduem\\\\objects\\\\pack\\\\pack-ee177a31e6cf5a12387d19c37e2f9544ac6d983a.idx'"), ('D:/Data/ReposWork/git/testvimrc.vim/cache/dein/repos/github.com/kana/vim-gf-user\\.git\\modules\\mduem\\objects\\pack\\pack-ee177a31e6cf5a12387d19c37e2f9544ac6d983a.pack', 'D:/Data/ReposWork/git/testvimrc.vim/cache/dein/.cache/testvimrc.vim/.dein\\.git\\modules\\mduem\\objects\\pack\\pack-ee177a31e6cf5a12387d19c37e2f9544ac6d983a.pack', "[Errno 13] Permission denied: 'D:/Data/ReposWork/git/testvimrc.vim/cache/dein/.cache/testvimrc.vim/.dein\\\\.git\\\\modules\\\\mduem\\\\objects\\\\pack\\\\pack-ee177a31e6cf5a12387d19c37e2f9544ac6d983a.pack'")]
[dein] D:\Data\ReposWork\git\testvimrc.vim\testvimrc.vim[40]..function dein#install[1]..dein#install#_update[34]..<SNR>8_update_loop[5]..<SNR>8_install_async[9]..<SNR>8_done[9]..dein#install#_recache_runtimepath[20]..<SNR>8_copy_files[6]..dein#install#_copy_directories[7]..dein#install#_copy_directories_py, 行 6
```

**Comment by Shougo** [comment]
Fixed.
