### ISSUE TITLE
deinアップデート後、全てのプラグイン読み込みが動かなくなる

### ISSUE THREAD

**Issue by azarashichop** [Shougo/dein.vim#423]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
call dein#update()を実施すると、全てのプラグインが読み込まれなくなり、動作しません。

## Expected
正常に動作すること

## Environment Information (Required!)
 * dein.vim version(SHA1):
2e2a958
 * OS:
Windows 10
 * Vim/neovim version:
Vim8.2（kaoriya最新版）

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
  set runtimepath+=~\.vim\dein\repos\github.com\Shougo\dein.vim
  call dein#begin('~\.vim\dein\.')
  call dein#end()
  call dein#save_state()
```

## The reproduce ways from Vim starting (Required!)
現時点で、call dein#update()を実行すると再現できます。
42e21ad まで戻すと、現象を回避できることを確認済

**Comment by Shougo** [comment]
全体的に説明不足です。もっと詳細な情報をお願いします。
私がこの問題をどうでもよいと思っているわけではなく、重要だと思うからこそ質問しています。

>call dein#update()を実施すると、全てのプラグインが読み込まれなくなり、動作しません。

アップデート時に何かエラーが出ていましたか？ログが欲しいです。 `dein#get_log()` で取得か `g:dein#install_log_filename` で保存してください。

> Vim8.2（kaoriya最新版）

https://github.com/koron/vim-kaoriya/releases/tag/v8.2.1287-20200724

これですか？ Python のバージョンを教えてください

> 現時点で、call dein#update()を実行すると再現できます。
> 42e21ad まで戻すと、現象を回避できることを確認済

もうちょっと調べてください。
この rev まで戻したら直ったではなく、この rev を適用したら壊れたという情報が必要です。

**Comment by azarashichop** [comment]
情報不足で申し訳ありません。

1.   アップデート時のエラー
     特に発生していません。  
2.   vim/Pythonバージョン
    - vimのバージョン : 記載のものです。
    - Python 3.7.9　Pythonはパスを通してあります。
3.   現象発生のコミット
    c5b3a80 までは問題なし、 1835ddd に上げると現象発生します。

また、別Issueを切るべきかもしれませんが、 c5b3a80 に上げるとdeopleteのエラーが発生します。
`[deoplete] Duplicated source: around  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\around.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\source\around.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: buffer  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\buffer.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\source\buffer.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: denite  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\denite.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\denite.nvim\rplugin\python3\deoplete\source\denite.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: file  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\file.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\source\file.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: member  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\member.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\source\member.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: omni  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\omni.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\source\omni.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: syntax  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\syntax.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\neco-syntax\rplugin\python3\deoplete\source\syntax.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: vim  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\source\vim.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\neco-vim\rplugin\python3\deoplete\source\vim.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: ale  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\sources\ale.py" "C:\Users\yosuke\.vim\dein\repos\github.com\dense-analysis\ale\rplugin\python3\deoplete\sources\ale.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: look  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\sources\look.py" "C:\Users\yosuke\.vim\dein\repos\github.com\ujihisa\neco-look\rplugin\python3\deoplete\sources\look.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: vimshell  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\sources\vimshell.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\vimshell\rplugin\python3\deoplete\sources\vimshell.py"  Use :messages / see above for error details.
[deoplete] Duplicated source: vimshell_history  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\sources\vimshell_history.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\vimshell\rplugin\python3\deoplete\sources\vimshell_history.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_auto_delimiter  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_auto_delimiter.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_auto_delimiter.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_auto_paren  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_auto_paren.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_auto_paren.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_case  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_case.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_case.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_remove_overlap  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_remove_overlap.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_remove_overlap.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_remove_paren  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_remove_paren.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_remove_paren.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_reorder_attr  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_reorder_attr.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_reorder_attr.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_truncate_abbr  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_truncate_abbr.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_truncate_abbr.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_truncate_info  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_truncate_info.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_truncate_info.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_truncate_kind  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_truncate_kind.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_truncate_kind.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_truncate_menu  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_truncate_menu.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_truncate_menu.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_word_abbr  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\converter_word_abbr.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\converter_word_abbr.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: matcher_cpsm  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\matcher_cpsm.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\matcher_cpsm.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: matcher_full_fuzzy  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\matcher_full_fuzzy.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\matcher_full_fuzzy.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: matcher_fuzzy  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\matcher_fuzzy.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\matcher_fuzzy.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: matcher_head  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\matcher_head.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\matcher_head.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: matcher_length  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\matcher_length.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\matcher_length.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: matcher_matchfuzzy  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\matcher_matchfuzzy.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\matcher_matchfuzzy.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: sorter_rank  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\sorter_rank.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\sorter_rank.py"  Use :messages / see above for error details.
[deoplete] Duplicated filter: sorter_word  Use :messages / see above for error details.
[deoplete] path: "C:\Users\yosuke\.vim\dein\.cache\_vimrc\.dein\rplugin\python3\deoplete\filter\sorter_word.py" "C:\Users\yosuke\.vim\dein\repos\github.com\Shougo\deoplete.nvim\rplugin\python3\deoplete\filter\sorter_word.py"  Use :messages / see above for error details.
`

**Comment by Shougo** [comment]
OK. 原因が分かりました。Python 3.7 環境なのが原因ですね。
対応したので dein.vim を最終版にアップデートしてください。

**Comment by azarashichop** [comment]
対応ありがとうございます。
最新版のdeinインストール、dein#update()実施後も正常に動作していることを確認しました！
