### ISSUE TITLE
issue with readme

### ISSUE THREAD

**Issue by pjalsGit** [Shougo/dein.vim#424]
is "No Vundle/NeoBundle compatibility" really a feature?

**Comment by Shougo** [comment]
Yes.

**Comment by Shougo** [comment]
What is the problem?  Please describe it.

**Comment by pjalsGit** [comment]
shouldnt it have compatibility or am i just dumb?

**Comment by Shougo** [comment]
Sorry.  To keep the compatibility is hard.
