### ISSUE TITLE
Lazy loaded previm breaks lightline.vim when displaying function information by LSP

### ISSUE THREAD

**Issue by Omochice** [Shougo/dein.vim#427]
# Problems summary
Lazy loaded previm breaks lightline.vim when displaying function information by LSP.

## Expected
lightline.vim show mode, filetype etc always.

## Environment Information (Required!)

 * dein.vim version(SHA1): ee6a5fc

 * OS: Manjaro

 * Vim/neovim version: NVIM v0.6.0-dev+43-g02bf251bb

## Provide a minimal .vimrc with less than 50 lines (Required!)

(`init.vim`)
```vim
set runtimepath^=~/.config/nvim/dein/repos/github.com/Shougo/dein.vim/
if dein#load_state('~/.config/nvim/dein')
  call dein#begin('~/.config/nvim/dein')
  call dein#add('prabirshrestha/vim-lsp')
  call dein#add('mattn/vim-lsp-settings')
  call dein#add('itchyny/lightline.vim')
  call dein#add('previm/previm', {'lazy': 1, 'on_ft': 'markdown'})
  call dein#end()
  call dein#save_state()
endif
set laststatus=2
```

Note: If set previm to "non-lazy", this problem does not occur.

## The reproduce ways from Vim starting (Required!)

1. `:call dein#install()`
2. Restart vim and execute `:set filetype=python`.
3. execute `:LspInstallServer pylsp-all` for install Langage server.
4. execute `:edit foo.py` and write `print(`. The function information will be displayed.
5. At the same time, mode, filetype etc is disappear.

Note: This problem also occurs with other file types and language server combinations. For example, `foo.ts` and `deno`. 

## Screen shot (if possible)

This is a gif after step 2.

![](https://i.gyazo.com/550dac8c86a04261c6017a06a75c5d99.gif)

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
previm is loaded by the documentation loading.
The documentation is markdown.

**Comment by Shougo** [comment]
It seems lightline's problem.

https://github.com/previm/previm/blob/master/plugin/previm.vim#L31

The autocmd breaks lightline. `call lightline#update()` fixes the problem.
But if I call it in hooks, it does not work.
