### ISSUE TITLE
[bug] conflict with vimtex

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/dein.vim#429]
```vim
" cat ~/.config/nvim/test.vim
let $XDG_DATA_HOME = $HOME . '/.local/share'
set runtimepath=$VIMRUNTIME
set runtimepath+=$XDG_DATA_HOME/nvim/repos/github.com/Shougo/dein.vim
if dein#load_state($XDG_DATA_HOME . '/nvim')
  call dein#begin($XDG_DATA_HOME . '/nvim')
  call dein#add('Shougo/dein.vim')

  call dein#add('lervag/vimtex', {
        \ 'merged': 0,
        \ })
  call dein#end()
  call dein#save_state()
endif
" vi -u ~/.config/nvim/test.vim a.tex
" :colorscheme default<CR>
```

E20 occurs.

```
Error detected while processing ColorScheme Autocommands for "<buffer=1>":
E20: Mark not set
```
If don't use dein, E20 will not occur.

About `merge`, see <https://github.com/lervag/vimtex/issues/237>.

I have deleted `~/.local/share/nvim/.cache` `~/.local/share/nvim/.cache_vi` `~/.local/share/nvim/state_vi.vim` before testing.

This bug occur recently. Maybe it is related to dein's or vimtex's update.

Thanks!

**Comment by Shougo** [comment]
It is not dein.vim conflict.

It is vimtex implementation error.  It can be reproduced without dein.vim.

```vim
" It works!
autocmd ColorScheme <buffer> call vimtex#syntax#core#init_highlights()
" It is broken
"autocmd ColorScheme <buffer> * call vimtex#syntax#core#init_highlights()

colorscheme default
```

**Comment by rahimmalekzad** [comment]
> ```viml
> " cat ~/.config/nvim/test.vim
> let $XDG_DATA_HOME = $HOME . '/.local/share'
> set runtimepath=$VIMRUNTIME
> set runtimepath+=$XDG_DATA_HOME/nvim/repos/github.com/Shougo/dein.vim
> if dein#load_state($XDG_DATA_HOME . '/nvim')
>   call dein#begin($XDG_DATA_HOME . '/nvim')
>   call dein#add('Shougo/dein.vim')
> 
>   call dein#add('lervag/vimtex', {
>         \ 'merged': 0,
>         \ })
>   call dein#end()
>   call dein#save_state()
> endif
> " vi -u ~/.config/nvim/test.vim a.tex
> " :colorscheme default<CR>
> ```
> 
> E20 occurs.
> 
> ```
> Error detected while processing ColorScheme Autocommands for "<buffer=1>":
> E20: Mark not set
> ```
> 
> If don't use dein, E20 will not occur.
> 
> About `merge`, see [lervag/vimtex#237](https://github.com/lervag/vimtex/issues/237).
> 
> I have deleted `~/.local/share/nvim/.cache` `~/.local/share/nvim/.cache_vi` `~/.local/share/nvim/state_vi.vim` before testing.
> 
> This bug occur recently. Maybe it is related to dein's or vimtex's update.
> 
> Thanks!

**Comment by Shougo** [comment]
Really???  It is not dein problem.  I will try it later.  Please wait.

**Comment by Shougo** [comment]
Oh, it seems just comment.
