### ISSUE TITLE
 After vimrc changed, load_state() occurs error

### ISSUE THREAD

**Issue by kashewnuts** [Shougo/dein.vim#43]
# Problems summary

vimrc変更後load_state()がエラーになる

## Environment Information
 * OS & Vim version: 
  * Windows7 &  (G)Vim 7.4 p1444 kaoriya  
  * Ubuntu 14.04 LTS & Vim 7.4 p52
  * Mac OX 10.11(OS X El Capitan) & (G)Vim 7.4 p1537

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" $HOME/.vimrc
if &compatible
  set nocompatible
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
let s:path = expand('~/.cache/dein')
if dein#load_state(s:path)
  call dein#begin(s:path)
  call dein#load_toml('~/.vim/rc/dein.toml', {'lazy': 0})
  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif
syntax on
```

```
" $HOME/.vim/rc/dein.toml
[[plugins]]
repo = 'Shougo/dein.vim'
```

## The reproduce ways from Vim starting (Required!)

 1. 上記の vimrc と TOML を配置して (g)vim で起動する。
 2. 起動後 vimrc を変更(改行の追加もしくは削除でよい)して保存する。
 3. 新規に (g)vim を起動するとダイアログでエラー

## Screen shot (if possible)
![cacheloadingerror](https://cloud.githubusercontent.com/assets/1122795/13872924/34415b56-ed31-11e5-8fe9-c9a99dcfa388.png)

## Upload the log messages by `:redir` and `:message`

```text
[dein] Error occurred while loading state : Cache loading error
```

**Comment by Shougo** [comment]
Your TOML file is broken.

```
# $HOME/.vim/rc/dein.toml
[[plugins]]
repo = 'Shougo/dein.vim'
```

The comment string is `#`.
