### ISSUE TITLE
Set g:dein#plugin.build value in hook_post_update do not affect

### ISSUE THREAD

**Issue by tsuyoshicho** [Shougo/dein.vim#430]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Set `g:dein#plugin.build` value in `hook_post_update` do not affect.

But toml `build` key work fine.

## Expected

`g:dein#plugin` can use in `hook_*`

from help
https://github.com/Shougo/dein.vim/blob/8f5fa9b0034daa3915370c3617e8ac72a8b398f7/doc/dein.txt#L603-L606

## Environment Information (Required!)

 * dein.vim version(SHA1): 8f5fa9b0034daa3915370c3617e8ac72a8b398f7

 * OS: Windows 10 Pro (21H1 latest 2021/09/17)

 * Vim/neovim version:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2021 15:40:25)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-3434
```
build in vim-tux project

## Provide a minimal .vimrc with less than 50 lines (Required!)

https://github.com/tsuyoshicho/testvimrc.vim/tree/test/dein-20210917

Minimal vimrc and toml

## The reproduce ways from Vim starting (Required!)

1. vim start 1st : fetch plugins and work build
2. vim start 2nd : use plugin if installed

### toml `build` key : success

1. toml vimproc's `build` key set system specific command
2. vimproc file create/download success
   -  `ls cache/dein/repos/github.com/Shougo/vimproc.vim/lib/` : file exists.
   - `:echo vimproc#version()` report version

### `g:dein#plugin.build` value in `hook_post_update` : failed

0. toml vimproc's `build` comment out, `hook_post_update` uncomment
1. toml vimproc's `hook_post_update` `g:dein#plugin.build` value are system specific command
2. vimproc file create/download failed
   -  `ls cache/dein/repos/github.com/Shougo/vimproc.vim/lib/` : file do not exists.

## Screen shot (if possible)

nothing.

## Upload the log messages by `:redir` and `:message` (if errored)

nothing.

**Comment by Shougo** [comment]
Wow!  vimproc is 10 years ago plugin...

**Comment by tsuyoshicho** [comment]
Why this plugin select reason, build command will be clear. 
Fix thanks
