### ISSUE TITLE
Neovim's delete() function bug where it cannot handle a file name that looks like a pattern creates issues for `dein#recache_runtimepath`

### ISSUE THREAD

**Issue by PanagiotisS** [Shougo/dein.vim#437]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Neovim's `delete()` function has a bug which has been fixed for Vim in this patch https://github.com/vim/vim/commit/701ff0a3e53d253d7300c385e582659bbff7860d

To copy the patch's description 

```
patch 8.1.1378: delete() can not handle a file name that looks like a pattern

Problem:    Delete() can not handle a file name that looks like a pattern.
Solution:   Use readdir() instead of appending "/*" and expanding wildcards.
            (Ken Takata, closes #4424, closes #696)
```

So, when calling `:call dein#recache_runtimepath()`, if a plugin has a directory with a name that looks like a pattern, the neovim's delete function reports "Reverse range in character class".

Similar/same issue for `packer`  https://github.com/wbthomason/packer.nvim/issues/669

## Expected

To delete the directory without issues or to not report the error message maybe.

## Environment Information (Required!)

 * dein.vim version(SHA1): https://github.com/Shougo/dein.vim/commit/613e90ec2d9f10940f970052e8973b564ca133a0

 * OS: Windows 10

 * Vim/neovim version: Tested with both `nvim v0.5.1` and `NVIM v0.6.0-dev+558-g3ba800f15`

```
:version
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-633

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```

```
:version
NVIM v0.6.0-dev+558-g3ba800f15
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-482

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set encoding=utf-8
scriptencoding utf-8

let &runtimepath .= ',' . expand(stdpath('data') . '/dein/repos/github.com/Shougo/dein.vim/')
let s:path = expand(stdpath('data') . '/dein')

if dein#load_state(s:path)

    call dein#begin(s:path, [expand('<sfile>')])

    call dein#add('Shougo\dein.vim')

    call dein#end()
    call dein#save_state()
endif
" }}}
filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. Manually delete `C:\Users\ps\AppData\Local\nvim-data\dein\.cache` and state files to ensure clean state
 2. Open nvim 
 3. Run `call dein#recache_runtimepath()`
 4. Create a directory with `[z-a]` in the name `:call mkdir(stdpath('data') .. '/dein/.cache/init.vim/.dein/[z-a]')`
 5. `call dein#recache_runtimepath()` which returns the error message
 6. `:messages`
 

## Upload the log messages by `:redir` and `:message` (if errored)
```
[dein] Error deleting directory: C:/Users/ps/AppData/Local/nvim-data/dein/.cache/init.vim/.dein
[dein] Vim(call):E944: Reverse range in character class
[dein] function dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[8]..<SNR>30_clear_runtimepath[9]..dein#install#_rm, line 6
```

## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/11048776/140652659-020dbaf2-a523-48b0-8de2-be4fbd8cc192.png)

## Test 2
Alternatively we can test it with a plugin.

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set encoding=utf-8
scriptencoding utf-8

let &runtimepath .= ',' . expand(stdpath('data') . '/dein/repos/github.com/Shougo/dein.vim/')
let s:path = expand(stdpath('data') . '/dein')

if dein#load_state(s:path)

    call dein#begin(s:path, [expand('<sfile>')])

    call dein#add('Shougo\dein.vim')
    call dein#add('lervag/vimtex`)

    call dein#end()
    call dein#save_state()
endif
" }}}
filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)

 1. Manually delete `C:\Users\ps\AppData\Local\nvim-data\dein\.cache` and state files to ensure clean state
 2. Open nvim 
 3. Run `call dein#recache_runtimepath()`
 4. Run again `call dein#recache_runtimepath()` which returns the error message
 5. `:messages`

```
[dein] Error deleting directory: C:/Users/ps/AppData/Local/nvim-data/dein/.cache/init.vim/.dein
[dein] Vim(call):E944: Reverse range in character class
[dein] function dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[8]..<SNR>30_clear_runtimepath[9]..dein#install#_rm, line 6
Press ENTER or type command to continue
```

(Screenshot would be the same no reason to upload twice the same)

To find the faulty directory
6. Manually call `:echo delete('C:/Users/ps/AppData/Local/nvim-data/dein/.cache/init.vim/.dein', 'rf')` as dein would run
7. `:messages`

```
E944: Reverse range in character class
```

8: Check the `.cache` directory

```
(base) PS C:\Users\ps\AppData\Local\nvim-data\dein> tree .\.cache\
Folder PATH listing
Volume serial number is 
C:\USERS\PS\APPDATA\LOCAL\NVIM-DATA\DEIN\.CACHE
└───init.vim
    ├───.dein
    │   └───test
    │       └───test-get-main
    │           └───test-ugly-paths
    │               └───[code college-1] title
    └───rollbacks
        └───nvim
(base) PS C:\Users\ps\AppData\Local\nvim-data\dein>
```

We can see that `[code college-1] title` is the one that creates the issue for neovim's `delete()` function.

**Comment by Shougo** [comment]
I know.  But I have tired the porting.
Please read this.

https://github.com/neovim/neovim/pull/14540

**Comment by PanagiotisS** [comment]
I see. Thank you for you work!

**Comment by Shougo** [comment]
I have tired the porting.

**Comment by Shougo** [comment]
It is merged in the latest neovim.
