### ISSUE TITLE
Lua's script is pulled into ftdetec.vim

### ISSUE THREAD

**Issue by Martins3** [Shougo/dein.vim#441]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

Originally, I thought it was a problem of orgmode, the way to reproduce is documented here https://github.com/nvim-orgmode/orgmode/issues/210
# Problems summary
[orgmode](https://github.com/nvim-orgmode/orgmode) has a file named [filetype.lua](https://github.com/nvim-orgmode/orgmode/blob/master/ftdetect/filetype.lua). When the plugin managed by dein,  it's loaded into .dein/ftdetect/ftdetect.vim, which leads to an error whenever opening the neovim.

**Comment by Shougo** [comment]
Fixed.  Please use the latest.
