### ISSUE TITLE
Error executing lua vim/filetype.lua:0: attempt to index a nil value

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/dein.vim#442]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Setting `g:do_filetype_lua` to `1` causes an error.

## Expected
No error occurs when `g:do_filetype_lua` is set to `1`.

## Environment Information (Required!)

 * dein.vim version(SHA1): 137ec38f2316b7d973e89d7c2d4de46a9b73afdc

 * OS: Mac

 * Vim/neovim version:
```
NVIM v0.7.0-dev+997-g21cdecc8e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nabezokodaikon@MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-21cdecc/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:do_filetype_lua = 1

if &compatible
    set nocompatible
endif

let $CACHE = expand('~/.cache')

if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))
call dein#end()
call dein#save_state()
```

## The reproduce ways from Vim starting (Required!)

 1. Start Neovim
 2. Close Neovim
 3. `touch foo.txt`
 4. `nvim foo.txt`

## Screen shot (if possible)
![スクリーンショット 2022-02-03 14 48 16](https://user-images.githubusercontent.com/3197942/152288432-c6b536fb-8fbe-4ec1-bfc7-340a39fde1ff.png)

**Comment by Shougo** [comment]
Have you read dein's documentation?
`filetype plugin indent on` is needed!

```vim

call dein#begin(s:dein_dir, expand('<sfile>'))
call dein#end()
call dein#save_state()

filetype plugin indent on
```

is correct.  Because `dein#end()` disables filetype plugins.

**Comment by Shougo** [comment]
`g:do_filetype_lua` requires filetype plugins.
Because `g:do_filetype_lua` is filetype detect lua implementation.

**Comment by nabezokodaikon** [comment]
Thank you for telling me.
