### ISSUE TITLE
Problems under windows

### ISSUE THREAD

**Issue by zdm** [Shougo/dein.vim#446]
**Warning: I will close the bug issue without the minimal init.vim and the
reproduce ways.**

# Problems summary

After latest commits it stopped work under windows at all. I just updated dein ti the lates version and restarted. No plugins loaded. .cache directory is empty. This is under windows only, under linux it wirks with the same config.

## Environment Information (Required!)

- dein.vim version(SHA1): 3f4206b

- OS: windows 11 x64

- Vim/neovim version: nvim 0.6.1

**Comment by zdm** [comment]
Is it possible to dubeg the problem somehow?
I can provide any information required.
I need to work but editor is not functional completely.

**Comment by Shougo** [comment]
Hi, I have not tested Windows environment.
I will test it in the weekend, sorry.

It should be fixed in the latest version.  Can you test it?

**Comment by Shougo** [comment]
> I need to work but editor is not functional completely.

sorry.  But it is midnight in Japan!  I am not superman and I cannot respond quickly.

**Comment by zdm** [comment]
Yes, latest commit fixed the problem. Thanks.
