### ISSUE TITLE
[Request] Find a correct directory of dein.vim in runtimepath and update.

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/dein.vim#45]
# Problems summary
`call dein#update()` update `~/.vim/bundle/repos/github.com/Shougo/dein.vim` rather than dein.vim in `runtimepath` (e.g. `~/.vim/bundle/dein.vim`) so users might not notice that they are actually using a old dein.vim even after `call dein#update()`

## Request
`call dein#update()` update a correct dein.vim, namely dein.vim in `runtimepath`.

## Related
https://github.com/kannokanno/previm/issues/54#issuecomment-198664842

**Comment by lambdalisue** [comment]
I would like to say "Find a correct directory of ANY plugins in runtimepath and update" but I thought it might slow Vim's start up time so I limited this request to only *dein.vim*.

While dein.vim itself is different from plugins managed by dein.vim, `call dein#update()` for *dein.vim* and for other managed plugins are intristically different.
That's why I think it is OK to introduce a code for finding a correct directory of *dein.vim* from `runtimepath` but of others.

**Comment by Shougo** [comment]
It seems your configuration fault.
Please upload the example.
I don't want to add the feature.

**Comment by lambdalisue** [comment]
> It seems your configuration fault.
> Please upload the example.

As long as I know, there is not documentation about install path limitation of *dein.vim* itself.
So I add *dein.vim* into `~/.vim/bundle/repos/dein.vim` and add that into `runtimepath`.

e.g. https://github.com/lambdalisue/rook/blob/master/home/.vim/rc/dein.vim#L1-L26

> I don't want to add the feature.

It's fine. I understand that this is configuration problem. But I suggest that there should be a documentation about install path limitation of *dein.vim* itself.

**Comment by zchee** [comment]
@lambdalisue Hi,

FYI, I (and maybe also @Shougo) initial `dein.vim` dir is `/path/to/cache/dein/repos/Shougo/dein.vim` directly. not separate.
If does not exists `dein_dir`, git clone to cache dir path.
See https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/init.rc.vim#L65 also https://github.com/zchee/.nvim/blob/master/init.vim#L42

**Comment by zchee** [comment]
@lambdalisue Ah, sorry... :(

**Comment by Shougo** [comment]
@lambdalisue It seems your configuration problem.

https://github.com/lambdalisue/rook/blob/master/home/.vim/rc/dein/define.toml#L2

You must specify the correct dein.vim path.

If not, dein.vim installs dein.vim to the default directory.

> As long as I know, there is not documentation about install path limitation of dein.vim itself.
So I add dein.vim into ~/.vim/bundle/repos/dein.vim and add that into runtimepath.

The install path limitation is not exists.

**Comment by lambdalisue** [comment]
> ou must specify the correct dein.vim path.

So you mean that `rtp` ?

**Comment by Shougo** [comment]
No.  It is `path`.

**Comment by lambdalisue** [comment]
Got it.
https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt#L429-L445
