### ISSUE TITLE
How to install on unix ?

### ISSUE THREAD

**Issue by lewisadm** [Shougo/dein.vim#454]
**Warning: I will close the bug issue without the minimal init.vim and the
reproduce ways.**

I run the following:
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
# For example, we just use `~/.cache/dein` as installation directory
sh ./installer.sh ~/.cache/dein

Then added the following to init.vim:
if &compatible
  set nocompatible " Be iMproved
endif

" Required:
" Add the dein installation directory into runtimepath
set runtimepath+={path to dein.vim directory}

" Required:
call dein#begin({path to plugin base path directory})

" Let dein manage dein
call dein#add({path to dein.vim directory})
if !has('nvim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')
endif

" Add or remove your plugins here like this:
"call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')

" Required:
call dein#end()

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
" call dein#install()
"endif

# Problems summary

Error detected while processing /home/lewis/.config/nvim/init.vim:
line   10:
E15: Invalid expression: ~/.config/nvim/plugin})
E116: Invalid arguments for function dein#begin
line   13:
E15: Invalid expression: ~/.config/nvim/plugin})
E116: Invalid arguments for function dein#add
line   24:
E117: Unknown function: dein#end

## Expected

oh my dream would be:
wget github.com/blah/blah/path/dein.vim/install.sh
./install.sh
and it works.

## Environment Information (Required!)

- dein.vim version(SHA1):
current

- OS:
openbsd 7.1

- Vim/neovim version:

nvim v0.6.1

## Provide a minimal .vimrc with less than 50 lines (Required!)

$ cat .vimrc
cat: .vimrc: No such file or directory

## The reproduce ways from Vim starting (Required!)

1. vim
2. errors

## Screen shot (if possible)
![104831_10-07-2022](https://user-images.githubusercontent.com/69764521/178138007-b7b52f54-7649-4caf-9bf8-2058c0206945.png)

**Comment by lewisadm** [comment]
I tried to install again... (it about 2 hours I'm trying)... 

```
$ rm -rf .cache/dein
$ mkdir .nvim/dein
$ sh ./installer.sh .nvim/dein
```

after this I created the nvim conf file in .config/nvim/init.vim like this:

```
if &compatible
  set nocompatible      
endif
set runtimepath+=/home/lewis/.nvim/dein//repos/github.com/Shougo/dein.vim
call dein#begin('/home/lewis/.nvim/dein/')
call dein#add('/home/lewis/.nvim/dein//repos/github.com/Shougo/dein.vim')
call dein#end()
filetype plugin indent on
syntax enable
```
Then I run nvim and then **:call dein#install()**, and the following are the new errors:
```
[dein] Target plugins are not found.
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
```

**Comment by Shougo** [comment]
You have specified only one plugin dein.vim.
It is already installed.
So dein.vim cannot find install plugins.
