### ISSUE TITLE
Plugins are not sourced when installing them after VimEnter, but `dein#is_sourced` returns `1`

### ISSUE THREAD

**Issue by Matts966** [Shougo/dein.vim#459]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Thank you for this great plugin! I was moved by the asynchronous installation feature!

My problem is about installing plugins after entering vim.
It seems that plugins are not sourced when installing them after VimEnter, but `dein#is_sourced` returns `1`.

## Expected

`dein#install()` sources plugins even after entering vim.

## Environment Information (Required!)

- dein.vim version(SHA1): `803fd0aa2fe0e7ac7c952921c2321cb1dc9efc47`

- OS: macOS Monterey 12.4

- neovim/Vim `:version` output: 

<details>
  <summary>NVIM v0.8.0-dev-784-g5f0fbe7c2 (full output collapsed)</summary>

NVIM v0.8.0-dev-784-g5f0fbe7c2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1659757490287.local

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/share/nvim"

Run :checkhealth for more info

</details>

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim
call dein#begin(expand('~/.cache/test'))
call dein#add('lambdalisue/gin.vim')
call dein#end()
syntax enable
filetype plugin indent on

" call dein#install() 
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Use vimrc above
2. Type `:call dein#install()`
3. `Gin` command is not found but `:echo dein#is_sourced('gin.vim')` prints `1`

Plugins are sourced correctly if I type `call dein#install()` inside the vimrc above like the last line.

**Comment by Shougo** [comment]
Fixed.

**Comment by Matts966** [comment]
Confirmed! 🎉 
Thank you!
