### ISSUE TITLE
Timing of execution of `s:LoadFTPlugin()` changes when a plugin is lazy loaded

### ISSUE THREAD

**Issue by yuki-yano** [Shougo/dein.vim#460]
# Problems summary

If a lazy loaded plugin( use `on_ft` ) contains `ftplugin` or `after/ftplugin`, the result of `:verbose autocmd FileType` for that ft will change so that `s:LoadFTPlugin()` ignores what I wrote in the vimrc and runs last.

## Expected

When a plugin is lazy loaded, `s:LoadFTPlugin()` is executed first.

## Environment Information

- dein.vim version(SHA1): `00bb3a1ddb601c7500ab541d968a9b6035fc2086`

- OS: macOS Big Sur 11.6.1

- neovim/Vim `:version` output:
```
:version
NVIM v0.8.0-dev-2402-ge4e0e8ce6
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by yuki-yano@YukinoMBP

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e4e0e8c_1/share/nvim"
```

## Provide a minimal init.vim/vimrc without plugin managers

```vim
set runtimepath^=~/path/to/dein.nvim/

if dein#load_state(path)
  call dein#begin(path)

  " OK
  call dein#add('Shougo/dein.vim', {'on_ft': ['vim']})

  " OK
  call dein#add('heavenshell/vim-jsdoc')
  call dein#add('lambdalisue/vim-backslash')

  " Bad
  " call dein#add('heavenshell/vim-jsdoc', {'on_ft': ['typescript', 'typescriptreact', 'javascript'], 'build': 'make install'})
  " call dein#add('lambdalisue/vim-backslash', {'on_ft': ['vim']})

  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable

function s:set_format_options() abort
  set formatoptions-=c
  set formatoptions-=r
  set formatoptions-=o
  set formatoptions+=j
  set formatoptions+=B
  set formatoptions+=n
endfunction

autocmd FileType * call <SID>set_format_options()
```

## How to reproduce the problem from neovim/Vim startup

- Open `vim` or `typescript` file
- `verbose set formatoptions`
- `verbose autocmd FileType`

**Comment by Shougo** [comment]
Reproduced.  But it is intended behavior.
I can change the implementation, but it has the side effects.

**Comment by Shougo** [comment]
If you want to overwrite ftplugin options, you should use `after/ftplugin` instead.

**Comment by yuki-yano** [comment]
I understand.
I will try to handle this by using `after/ftplugin` or another event.

**Comment by Shougo** [comment]
I have removed ftplugin reset.
But it is the test.  I may revert the changes.

**Comment by Shougo** [comment]
I have reverted the changes.  filetype plugin reset is needed to load ftplugins lazily!

**Comment by Shougo** [comment]
So this is your configuration problem.  I cannot help.
