### ISSUE TITLE
g:dein#types#git#clone_depth not working

### ISSUE THREAD

**Issue by so1ar** [Shougo/dein.vim#463]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

When I add `let g:dein#types#git#clone_depth = 1` in my init.vim, dein still tries to clone the entire repo.

## Expected

Dein should shallow clone the repo.

## Environment Information (Required!)

- dein.vim version(SHA1): de3e94417fd0912c5dccd0933cebb66d64b4be46

- OS: Archlinux

- neovim/Vim `:version` output: 
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

     system vimrc file: "$VIM/sysinit.vim"
         fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Required:
set runtimepath+=/home/liu/.config/dein/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('/home/liu/.config/dein')
let g:dein#types#git#clone_depth = 1
" Let dein manage dein
" Required:
call dein#add('/home/liu/.config/dein/repos/github.com/Shougo/dein.vim')

" Add or remove your plugins here like this:
"call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')
call dein#add('neoclide/coc.nvim', { 'merged': 0, 'rev': 'release'  })
" Required:
call dein#end()

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. add `let g:dein#types#git#clone_depth = 1` in init.vim
2. run `:call dein#install()`
3. check the repo folder

**Comment by Shougo** [comment]
Fixed.
