### ISSUE TITLE
Suggestion to improve installation process

### ISSUE THREAD

**Issue by santosned** [Shougo/dein.vim#467]
Hi! hope you're doing great. Here I'll suggest one change to the project.

# Installation process

Currently, the installation process requires the execution of two commands, which are:

1. run ```curl``` to get the installation script and save in a ```install.sh``` file and
2. run the script with the installation directory location

Even thought it's simple, This process could be simplified with just one line command. Which would make the life of everyone easier. 

## Example

```sh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh)"
```

Of course, we would need to update the installation script.

I've been writing sh & bash for years and this simplification would be a nice feature to this wholesome project
If you don't have time, I can make one and open an PR just to give you an north about what I meant. Stay safe!

**Comment by Shougo** [comment]
Sorry.  I don't want to change the example.
Yes, your script is simpler.  But it is intended. User should check your installation script before the execution.

I will check your installation script later.

**Comment by santosned** [comment]
_"User should check your installation script before the execution."_ @Shougo 

Got it. But remember, this is **open source**.  Any user can check the script before installing it, anytime they feel like it, either by a web browser or using curl/wget and saving it to a file.

If we think of a user who executes this new script without checking it, would they even check the current one?

As I said, both ways allow the user to check out the code. You're not hiding anything currently, and you wouldn't be if you did improve the installation process.

Think about the users who know the project, trust it, and just want to get it installed, as quick as possible. The current script offers close to nothing to them, but an improved version can.

[See it here](https://raw.githubusercontent.com/santosned/dein.vim/master/bin/installer.sh)

Or view it on terminal:
```sh
curl -o- https://raw.githubusercontent.com/santosned/dein.vim/master/bin/installer.sh | less
```
```sh
wget -qO- https://raw.githubusercontent.com/santosned/dein.vim/master/bin/installer.sh | less
```
