### ISSUE TITLE
dein uses lua even when lua is not installed.

### ISSUE THREAD

**Issue by krischik** [Shougo/dein.vim#468]
# Problems summary

deim aborts load_state with with "lua53.dll not found" error on windows system:

## Expected

deim starts without the need to install lua.

## Environment Information (Required!)

- dein.vim version(SHA1):

- OS:

Windows 10

- neovim/Vim `:version` output:

:version
VIM - Vi IMproved 9.0 (2022 Jun 28 kompiliert am Jun 28 2022 12:46:00)
MS-Windows 32 Bit GUI Version mit OLE-Unterstützung
Übersetzt von mool@tororo
Riesige Version mit GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl                +ex_extra           +mzscheme/dyn       +tcl/dyn
+arabic             +extra_search       +netbeans_intg      -termguicolors
+autocmd            -farsi              +num64              +terminal
+autochdir          +file_in_path       +ole                -termresponse
+autoservername     +find_in_path       +packages           +textobjects
+balloon_eval       +float              +path_extra         +textprop
-balloon_eval_term  +folding            +perl/dyn           -tgetent
+browse             -footer             +persistent_undo    +timers
++builtin_terms     +gettext/dyn        +popupwin           +title
+byte_offset        -hangul_input       -postscript         +toolbar
+channel            +iconv/dyn          +printer            +user_commands
+cindent            +insert_expand      +profile            +vartabs
+clientserver       +ipv6               +python/dyn         +vertsplit
+clipboard          +job                +python3/dyn        +vim9script
+cmdline_compl      +jumplist           +quickfix           +viminfo
+cmdline_hist       +keymap             +reltime            +virtualedit
+cmdline_info       +lambda             +rightleft          +visual
+comments           +langmap            +ruby/dyn           +visualextra
+conceal            +libcall            +scrollbind         +vreplace
+cryptv             +linebreak          +signs              -vtp
+cscope             +lispindent         +smartindent        +wildignore
+cursorbind         +listcmds           -sodium             +wildmenu
+cursorshape        +localmap           +sound              +windows
+dialog_con_gui     +lua/dyn            +spell              +writebackup
+diff               +menu               +startuptime        -xfontset
+digraphs           +mksession          +statusline         -xim
+directx            +modify_fname       -sun_workshop       +xpm_w32
-dnd                +mouse              +syntax             -xterm_save
-ebcdic             +mouseshape         +tag_binary
+emacs_tags         +multi_byte_ime/dyn -tag_old_static
+eval               +multi_lang         -tag_any_white

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=/Users/martin/vimfiles/bundles/repos/github.com/Shougo/dein.vim
"if dein#load_state('/Users/martin/vimfiles/bundles')
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type gvim in cmd.exe

## Upload the log messages by `:redir` and `:message` (if errored)

```
Fehler beim Ausführen von "function dein#load_state[1]..dein#min#load_state[2]..dein#min#_init":
Zeile   49:
E370: Konnte Bibliothek lua53.dll nicht laden
Lua bibliothek kann nicht geladen werden.
```

Translation: "E370: Library lua53.dll not loaded"

**Comment by krischik** [comment]
Ignore it. An old version left behind on the system was started instead of the current vim 9.0.

**Comment by Shougo** [comment]
It seems your neovim version is too old and it does not support lua.
