### ISSUE TITLE
`[ftplugin]` in toml is not loaded

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/dein.vim#473]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

## Expected

I want to use the [ftplugin] section in deinft.toml to override formatoptions.

## Environment Information (Required!)

- dein.vim version(SHA1): 09cb888d78f9838b57ec7e1c5c46d4a7733cea75

- OS: Ubuntu 20.04 on WSL2

- neovim/Vim `:version` output: NVIM v0.9.0-dev-84465a8c1

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
let $TEMP = expand('/tmp')
if &runtimepath !~# '/dein.vim'
  let s:dein_dir = $TEMP . '/dein/repos/github.com/Shougo/dein.vim'
  if !isdirectory(s:dein_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_dir, ':p')
endif

let s:base_dir = fnamemodify(expand('<sfile>'), ':h')
let s:dein_ft_toml = s:base_dir . '/deinft.toml'

let s:path = $TEMP . '/dein'
call dein#begin(s:path)
call dein#load_toml(s:dein_ft_toml)
call dein#end()
```

And deinft.toml

```toml
[ftplugin]

_ = '''
    setl formatoptions-=t
    setl formatoptions-=c
    setl formatoptions-=r
    setl formatoptions-=o
    setl formatoptions+=mMl
'''
```

## How to reproduce the problem from neovim/Vim startup (Required!)

After startup, open init.vim and you will see that formatoptions has not been overwritten.

**Comment by Shougo** [comment]
`filetype plugin indent on` is needed after `call dein#end()`.

**Comment by uga-rosa** [comment]
Oh, it's true. It's fixed. Thank you.
