### ISSUE TITLE
vim-altercmd setting in hook_add block

### ISSUE THREAD

**Issue by hoggen** [Shougo/dein.vim#48]
# Problems summary
If I comment out AlterCommand di Dictionary -no-duplicate,  the rest of altercommand define not works.
 
## Expected
comment should work fine.

## Environment Information
 * OS: OS X El Capitan 10.11.3
 * Vim version:7.4.1556

## Provide a minimal .vimrc with less than 50 lines (Required!)
before
```toml
[[plugins]]
repo = 'tyru/vim-altercmd'
on_cmd = 'Altercommand'
hook_add = '''
  call altercmd#load()
  AlterCommand du call dein#update()
  AlterCommand dcs call dein#clear_state()
  AlterCommand di Dictionary -no-duplicate
  AlterCommand ref Unite ref
'''
```
after
```toml
[[plugins]]
repo = 'tyru/vim-altercmd'
on_cmd = 'Altercommand'
hook_add = '''
  call altercmd#load()
  AlterCommand du call dein#update()
  AlterCommand dcs call dein#clear_state()
  " AlterCommand di Dictionary -no-duplicate
  AlterCommand ref Unite ref
'''
```

## The reproduce ways from Vim starting (Required!)

 1. use " to comment out AlterCommand di Dictionary -no-duplicate
 2. call dein#clear_state() to reload setting.
 3. input di or ref does not work. But works fine with du and dcs

**Comment by Shougo** [comment]
Reproduced.  It is the fatal problem.
Fixed.
