### ISSUE TITLE
Operator mapping does not work correctly for lazy plugin at the beggining

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/dein.vim#49]
# Problems summary
`ciX` does not work and `<Plug>(textobj-X-i)` is inserted at the beginning if `textobj-X` is a lazy plugin.

## Expected
Operator works as expected from the beginning.

## Environment Information
 * OS: Ubuntu 15.04 / Mac OS X
 * Vim version: neovim 1.0.2, GVim 7.4.1556, MacVim 7.4.1553

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if has('vim_starting')
  if &compatible | set nocompatible | endif
  set runtimepath& runtimepath+=~/.vim/bundle/repos/dein.vim
endif

call dein#begin(expand('~/.vim/bundle/minimum'))
call dein#add('kana/vim-textobj-user')
call dein#add('osyo-manga/vim-textobj-multiblock', {
      \ 'depends': 'vim-textobj-user',
      \ 'on_map': [['ox', '<Plug>']],
      \ 'hook_add': join([
      \   'omap ab <Plug>(textobj-multiblock-a)',
      \   'omap ib <Plug>(textobj-multiblock-i)',
      \   'xmap ab <Plug>(textobj-multiblock-a)',
      \   'xmap ib <Plug>(textobj-multiblock-i)',
      \ ], "\n"),
      \})
call dein#end()

filetype plugin indent on
syntax on
```

## The reproduce ways from Vim starting (Required!)

 1. Hit `i(aaaaaaaaaaaaaaaaaaaaa)<Esc>hh`
 2. Hit `cib`
 3. Instead of removing `aaa...aaa`, `c<Plug>(textobj-multiblock-i)` is inserted
 4. Hit `<Esc>u` to return the previous status
 5. Hit `cib` again
 6. Then works as expect.

## Screen shot (if possible)
![Screencast](http://g.recordit.co/srXo4bABBU.gif)

**Comment by Shougo** [comment]
Fixed.  It is the dirty hack though.

**Comment by whisper404** [comment]
Still have a problem when I use vim-textobj-parameter. The default key mapping is i,.

**Comment by Shougo** [comment]
@whisper404 Please create new issue.
