### ISSUE TITLE
Config example error

### ISSUE THREAD

**Issue by zsaw** [Shougo/dein.vim#491]
## Description

set runtimepath+=s:dein_src
"+=" cannot be assigned correctly

## Expected behavior

"runtimepath" should be="/home/winston/.vim,/var/lib/vim/addons,/etc/vim,/usr/share/vim/vimfiles,/usr/share/vim/vim82,/usr/share/vim/vimfiles/after,/etc/vim/after,/var/lib/vim/addons/after,/home/winston/.vim/after,/home/winston/.cache/dein/repos/github.com/Shougo/dein.vim"

It should not be "/home/winston/.vim,/var/lib/vim/addons,/etc/vim,/usr/share/vim/vimfiles,/usr/share/vim/vim82,/usr/share/vim/vimfiles/after,/etc/vim/after,/var/lib/vim/addons/after,/home/winston/.vim/after,s:dein_src"

## Screenshots

![图片](https://user-images.githubusercontent.com/56421950/206825050-f846c340-0366-4db1-8fd4-ddb14cfecfd4.png)

## Desktop:

Please complete the following information, when reporting bugs related to the Dein.vim.

 - OS: debian:11
 - Vim or Neovim version: 8.2.2434
 - Commit/Version: 634756a

### Minimal Config

```vim" Ward off unexpected things that your distro might have made, as
" well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Set Dein base path (required)
let s:dein_base = '/home/winston/.cache/dein'

" Set Dein source path (required)
let s:dein_src = '/home/winston/.cache/dein/repos/github.com/Shougo/dein.vim'

echo s:dein_src
echo &runtimepath
" Set Dein runtime path (required)
set runtimepath+=s:dein_src
echo &runtimepath

" Call Dein initialization (required)
call dein#begin(s:dein_base)

call dein#add(s:dein_src)

" Your plugins go here:
"call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')

" Finish Dein initialization (required)
call dein#end()

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
if has('filetype')
  filetype indent plugin on
endif

" Enable syntax highlighting
if has('syntax')
  syntax on
endif

" Uncomment if you want to install not-installed plugins on startup.
"if dein#check_install()
" call dein#install()
"endif
```

**Comment by Shougo** [comment]
Fixed.  Please use `execute 'set runtimepath+=' . s:dein_src` instead.
