### ISSUE TITLE
When the plugin is not lazy, hook_source and hook_post_source does not fire on second or later startup.

### ISSUE THREAD

**Issue by kawaz** [Shougo/dein.vim#50]
# Problems summary

## Expected

If lazy option of the plugin is disabled, all hooks (`hook_add`, `hook_source`, `hook_post_source`) will be fired in this order on always startup.

## Actual

If lazy option of the plugin is disabled,

- on first startup
  - `hook_add` and `hook_source` and `hook_post_source` will be fired. (this is expected)
- on second or later startup
  - `hook_add` fire will be fired
  - `hook_source` and `hook_post_source` will be never fired. (this is not expected)

## Environment Information
 * OS: OSX10.11.3
 * Vim version: nvim (brew latest)

## Provide a minimal .vimrc with less than 50 lines (Required!)

Add this to my dein.toml. and call 'dein#load_toml('/path/to/dein.toml', {'lazy':1})` in init.vim.

```toml
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  echo "hook_add"
'''
hook_source = '''
  echo "hook_source"
'''
hook_post_source = '''
  echo "hook_post_source"
'''
```

## The reproduce ways from Vim starting (Required!)

 1. clear state cache
 2. start nvim(or vim)
    - hook_add / hook_source / hook_post_source are displayed.
    - quit nvim(or vim)
 3. start nvim(or vim) again
    - hook_add is displayed. (expected)
    - hook_source / hook_post_source are not displayed. (not expected)

**Comment by kawaz** [comment]
I understood, this is in the specifications.
I solved in using `autocmd` in `hook_add`.

This is what I wanted to do in `hook_post_source`.

```toml
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  autocmd MyAutoCmd VimEnter * colorscheme hybrid
'''
```

**Comment by wsdjeg** [comment]
I cam not understande why none lazy plugin can not auto call hooks.as I know neobundle support it.

**Comment by Shougo** [comment]
It is for optimization.

`dein#call_hook()` is slow.

**Comment by lambdalisue** [comment]
So which is better?

1. Call `dein#call_hook('source')` and `dein#call_hook('post_source')` when `dein#load_state()` return `0`
2. Move code in `hook_source` or `hook_post_source` into `hook_add` for **non lazy** plugins

```vim
  if dein#load_state(s:dein_basepath)
    call dein#begin(s:dein_basepath, [
          \ expand('$MYVIM_VIMRC'),
          \ expand('$MYVIM_GVIMRC'),
          \ expand('$MYVIM_HOME/rc/dein/define.toml'),
          \ expand('$MYVIM_HOME/rc/dein/config.vim'),
          \ expand('$MYVIM_HOME/rc/dein/command.vim'),
          \])
    call dein#load_toml(expand('$MYVIM_HOME/rc/dein/define.toml'))
    call dein#local(s:dein_localpath, {
          \ 'frozen': 1,
          \ 'merged': 0,
          \})
    call dein#end()
    call dein#save_state()
  else
    " IS THIS BAD HACK?
    call dein#call_hook('source')
    call dein#call_hook('post_source')
  endif
```

**Comment by Shougo** [comment]
```vim
 if dein#load_state(s:dein_basepath)
    call dein#begin(s:dein_basepath, [
          \ expand('$MYVIM_VIMRC'),
          \ expand('$MYVIM_GVIMRC'),
          \ expand('$MYVIM_HOME/rc/dein/define.toml'),
          \ expand('$MYVIM_HOME/rc/dein/config.vim'),
          \ expand('$MYVIM_HOME/rc/dein/command.vim'),
          \])
    call dein#load_toml(expand('$MYVIM_HOME/rc/dein/define.toml'))
    call dein#local(s:dein_localpath, {
          \ 'frozen': 1,
          \ 'merged': 0,
          \})
    call dein#end()
    call dein#save_state()
endif

" THIS IS NOT BAD HACK
call dein#call_hook('source')
call dein#call_hook('post_source')
```

**Comment by lambdalisue** [comment]
Hum... But `'source'` or `'post_source'` are called (in somewhere in the block) when `dein#load_state()` return `1` right? Then calling `dein#call_hook()` for these hook after `dein#load_state()` block may duplicate for the initial run I guess. Am I wrong?

**Comment by Shougo** [comment]
`dein#load_state()` does not call source and post_source hooks.
