### ISSUE TITLE
E723 occurs when there is a line continuation in the argument of extend() in a file read by hooks_files

### ISSUE THREAD

**Issue by hokorobi** [Shougo/dein.vim#503]
## Description

The error in the screenshot appears when starting with vimrc, described below.

## To Reproduce

gvim.exe -N -u ~/vimfiles/vimrc-min-dein-hooks_file -U NONE -i NONE

## Expected behavior

Starts without error.

## Screenshots

![image](https://user-images.githubusercontent.com/99910/230765615-5984146e-bb3a-4fef-b97c-bc849884f6df.png)
Ignore the "OFF" in screenshot.

## Desktop:

 - OS: Windows11
 - Vim or Neovim version: Vim v9.0.1425
 - Commit/Version: https://github.com/Shougo/dein.vim/commit/f8091f4119f23611a10667cba3851aad149a6a2e
 
### Minimal Config

~/vimfiles/vimrc-min-dein-hooks_file
```vim
set nocompatible
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\Shougo\dein.vim
let g:testdic = {}
call dein#begin('~/_vim/dein')
call dein#add('tweekmonster/helpful.vim', #{
      \ hooks_file: '~/vimfiles/vimrc-min-dein-hooks_file_helpful.vim',
      \ })
call dein#end()
filetype plugin indent on
syntax enable
```

~/vimfiles/vimrc-min-dein-hooks_file_helpful.vim
```vim
" hook_add {{{
call extend(g:testdic, #{
   \ test: 'test',
   \})
" }}}
```

**Comment by hokorobi** [comment]
The line feed code for both files is LF.

**Comment by hokorobi** [comment]
The same result with CRLF.

**Comment by Shougo** [comment]
Fixed.
