### ISSUE TITLE
Lazy plugin isn't sourced on command argument completion

### ISSUE THREAD

**Issue by leonidborisenko** [Shougo/dein.vim#51]
# Problems summary

When command listed in `on_cmd` plugin option isn't matched to any substring of the plugin's name, argument completion doesn't work. Instead, the command line is printed infinitely, until `Ctrl-C` is hit.

## Expected

Command argument completion works for every command listed in `on_cmd` plugin option.

## Environment Information
 * OS: Linux
 * Vim version: 
```
NVIM v0.1.3-317-gbd81239
Build type: Release
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Directory where this minimal vimrc file is located.
let s:rcdir = expand('<sfile>:p:h')
" Base path of dein.vim.
let s:dein_base_path = s:rcdir.'/dein'
" Path to cloned repository of dein.vim.
let s:dein_clone_path = s:rcdir.'/dein/dein.vim'

if has('vim_starting')
  if &compatible | set nocompatible | endif
  let &runtimepath .= ','.s:dein_clone_path
endif

call dein#begin(s:dein_base_path)
call dein#add('thinca/vim-prettyprint', {
     \ 'on_cmd': ['PP', 'PrettyPrint']
     \})
call dein#end()

filetype plugin indent on
syntax on
```

## The reproduce ways from Vim starting (Required!)

 1. Press `:PP`
 2. Hit the `<Space>` key
 3. Hit the `<Tab>` key

## Screen shot (if possible)

Here `:PP`'s argument completion is invoked with following infinite command printing (because plugin isn't sourced). Then `:PrettyPrint`'s argument is completed just fine (because plugin is sourced). Then `:PP`'s argument is completed also just fine (because plugin was already sourced on `:PrettyPrint` argument completion).
 
![a](https://cloud.githubusercontent.com/assets/509638/13981265/17b6804e-f0f4-11e5-84ec-6e714be23ea6.gif)

**Comment by Shougo** [comment]
Fixed.
