### ISSUE TITLE
VIM Plugins with the `<some_name>/vim` format result in duplicate plugin error.

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#519]
## Related Issues
None

## Description
Duplicate plugin warning when there are more than 1 plugin that follows the repo format of `<some_name>/vim`. For example:
```
call dein#add('dracula/vim',
            \ {'merged' : 0,
            \ 'normalized_name' : 'dracula'})
```
and
```
call dein#add('catppuccin/vim',
            \ {'merged' : 0,
            \ 'normalized_name' : 'catppuccin'})
```
will result in the following error:
```
[dein] plugin 'vim' already defined
```

## To Reproduce

Just try installing the plugins listed above.

## Expected behavior

Ability to have both plugins installed.

## Screenshots
None

## Desktop:

Please complete the following information, when reporting bugs related to the
Dein.vim.

- OS: Linux
- Vim or Neovim version: Vim 9.1 (1-954)

### Minimal Config
```vim
" Add your minimal .vimrc or init.vim here.
" Example:
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('dracula/vim',
            \ {'merged' : 0,
            \ 'normalized_name' : 'dracula'})
call dein#add('catppuccin/vim',
            \ {'merged' : 0,
            \ 'normalized_name' : 'catppuccin'})
call dein#end()
```

**Comment by Shougo** [comment]
It is feature.

Because `name` is not same with `normalized_name`.
If you want to use `normalized_name` as `name`, please enable `g:dein#enable_name_conversion` for it.
