### ISSUE TITLE
ftdetect ignored  if `call dein#begin` is after `syntax enable`

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Shougo/dein.vim#52]
# Problems summary
dein's ftdetect is ignored if `call dein#begin` is after `syntax enable`

## Expected
ftdetect should work wherever `syntax enable` is placed

## Environment Information
 * OS: Ubuntu Linux
 * Vim version: NVIM 0.1.3-dev, Build type: RelWithDebInfo

## minimal .vimrc

```vim
syntax enable

set rtp+=~/.vim/dein/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.vim/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('HerringtonDarkholme/yats.vim')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)
First, `touch test.ts` in shell
 1.  nvim test.ts
 2. :set ft
 
it prints `xml` rather than `typescript` as specified in ftdetec.vim

p.s. ftdetect works if `syntax enable` is placed after `dein#begin`

**Comment by Shougo** [comment]
Please test the latest dein.vim.
