### ISSUE TITLE
Plugins disabled at start-up are still active.

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#54]
# Problems summary
I have a block in my .vimrc that would selectively load some plugins. This looks roughly like this:

    "/Users/myUser/.vim/bundle
    call dein#begin('/Users/myUser/.vim/bundle')
    " Initial plugin is the plugin manager.
    call dein#add('Shougo/dein.vim')
    " Add or remove your plugins here:
    call s:InitMyPlugins()
    call dein#end()

The `s:InitMyPlugins()` is simply sourcing `.vim` files with `dein#` command(s) inside. For example:
    
    " vim-airline-init.vim
    call dein#add('bling/vim-airline')

    " vim-syntastic-init.vim
    call dein#add('scrooloose/syntastic')

## Expected
I would expect that the `syntastic` plugin is not loaded if I skip sourcing the `vim-syntastic-init.vim` or in a similar fashion I would expect the `vim-airline` plugin to be offline if I am not sourcing the `vim-airline-init.vim`. Instead, after a VIM restart, those plugins are still around. Only after running `dein#recache_runtimepath()` and another restart, those plugins are disabled.

## Environment Information
 * OS:
OSX, Yosemite, 10.10.5
 * Vim version:
7.4 (Included patches: 1-1553)

## Provide a minimal .vimrc with less than 50 lines (Required!)
This might be some kind of a feature that I was not able to understand, so before creating a minimal .vimrc I would like to see if I can fix this.

## The reproduce ways from Vim starting (Required!)
(not available)

## Screen shot (if possible)
(not available)

## Upload the log messages by `:redir` and `:message`
(not available)

**Comment by lambdalisue** [comment]
You need to specify `{ 'merged': 0 }` to NOT merge plugin in this case. https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt#L484

**Comment by symbolix** [comment]
I am not sure if I understand this. So I need to have that option included in my `#add` call. For example, like the following?

    call dein#add('bling/vim-airline',
        \ { 'merged': 0 })

But, what exactly is that option is doing? And why it has to be used? I would expect that the plugin loading chain is updated every time VIM is restarted.

Right now, without using `{ 'merged': 0 }`, I disable a plugin by taking it out of the VIM startup process and it still loads, for example, in the case of `vim-airline`:

I am not sourcing the script that has the `call dein#add('bling/vim-airline')` in it, so theoretically the plugin is disabled. However, when VIM starts, I can still see the `airline` status bar, but as it is not registered with `dein` any more, non of the settings that are coming through the `if dein#tap('vim-airline')` are there. So the `airline` status line is all wrong fonts etc.

Is this an expected behaviour?

**Comment by lambdalisue** [comment]
Because dein.vim merge plugins into a single directory (`~/.vim/bundle/.dein` in your case) to improve the performance. Plugins in that directory is forced to loaded because the directory is in `&runtimepath` from the beginning. So there is no other way to disable plugins in that directory unless you clear it by `dein#recache_runtimepath()`.

`{ 'merged': 0 }` tell dein.vim to NOT merge the plugin into that directory so that you can disable it.

**Comment by symbolix** [comment]
@lambdalisue Thanks. I can confirm that this works. Once I have added `{ 'merged': 0 }` to each of the add statements, the plugins are turned OFF and ON with each VIM restart, in respect to the enabled and disabled `dein#add()` calls.

**Comment by Shougo** [comment]
Yes.  This is feature.  Closing.

Additional info: dein.vim can detect the files change.
Please specify 2nd argument in `dein#begin()`.
