### ISSUE TITLE
dein#check_install(['some-plugins']) does not work well

### ISSUE THREAD

**Issue by tamy0612** [Shougo/dein.vim#57]
# Problems summary
If I try to use 'dein#check_install' with a list of plugin names, it is failed with error messages and does not install any plugins.

## Expected

Specific plugins can be checked and installed successfully with "dein#check_install('plugin')" and "dein#install('plugin')".

## Environment Information
 * OS:  OS X 10.11.4
 * Vim version:  NVIM 0.1.3-dev

## Provide a minimal .vimrc with less than 50 lines

```vim
" After some configurations for dein.vim

if has('vim_starting')
  " I want to install vimproc before installing any other plugins
  if dein#check_install(['vimproc'])
    call dein#install(['vimproc'])
  endif
  if dein#check_install()
    call dein#install()
  endif
endif
```

## The reproduce ways from Vim starting

 1. Add the code 'call dein#check_install(['vimproc'])' in vimrc.
 2. Remove caches.
 3. Start vim.

## Upload the log messages by `:redir` and `:message`

```sh
Error detected while processing function dein#check_install:
line    8:
E715: Dictionary required
E712: Argument of map() must be a List or Dictionary
[dein] Not installed plugins: 0
```

## Consideration

I think that this error is caused by the function "dein#get".

The function returns a dictionary of dictionaries for plugins when it is called without argument.
On the other hand, it returns a dictionary for plugins (not a dictionary of dictionaries) when it is called with an argument.
Hence, the function 'map' with the function 'values' (at lines 76-77 in autoload/dein.vim) may cause errors.

**Comment by Shougo** [comment]
Thank you!
