### ISSUE TITLE
dein#check_install not working

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#58]
# Problems summary
echo dein#check_install(['syntastic']) returns 0

## Expected
Syntastic is installed and I would expect the function to return 1

## Environment Information
 * OS:
OSX
 * Vim version:
7.4 (1-1553)

## Provide a minimal .vimrc with less than 50 lines (Required!)
```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. Start VIM and run `echo dein#check_install(['syntastic'])` or do this for any plugin.

**Comment by lambdalisue** [comment]
Read https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt#L223

**Comment by symbolix** [comment]
Well, it seems like the function always returns **0**.

`echo dein#check_install(['banana'])` returns **0**. Not really sure if that is the intention.

**Comment by lambdalisue** [comment]
did you add banana as a plugin with dein#add?

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 木, 3月 31, 2016 at 12:06 午前, symbolix <notifications@github.com> wrote:
Well, it seems like the function always returns 0 .

echo dein#check_install(['banana']) returns 0 . Not really sure if that is the intention.

**Comment by symbolix** [comment]
No :) Maybe I am confused about the aim of this function. I would expect this:

     " I have installed `syntastic` using the `dein#add('scrooloose/syntastic')`     
     echo dein#check_install(['`syntastic'])

returns **0**

     " I have **NOT** installed `no_such_plugin` using the `dein#add('no_such_repo/no_such_plugin')`     
     echo dein#check_install(['`no_such_plugin])

returns **0**

I am going to build my own checker as the following:

     echo has_key(dein#get(), 'syntastic')

this returns **1**

     echo has_key(dein#get(), 'no_such_plugin')

and this **0**

However, still curious about the purpose of `dein#check_install()`

**Comment by lambdalisue** [comment]
The usage is

```vim
if dein#check_install(['syntastic'])
  " Assume that installing syntastic require $FOO environment value for instance
  let $FOO = 'hoge'
  call dein#install(['syntastic'])
endif
```

Note that I'm not the author so all of what I said is just a guess from dein's help.

**Comment by symbolix** [comment]
I see. Ok. I got the purpose wrong. I thought it is a simple `TRUE` or `FALSE` check to see if the plugin has been installed. And I mean **INSTALLED** not _SOURCED_. Lazy plugins are still installed, but might not be sourced immediately.

Probably the docs are not very clear at that point:

`Check the plugins installation.`
`If the plugins are not installed, it will return non zero.`
`{plugins} is the plugins name list to check.`
`If you omit it, dein will check all plugins installation.`

Nothing to suggest environment variables etc. It simply says: "Checks if the plugin is installed."

**Comment by lambdalisue** [comment]
Then you can use `dein#tap()`

**Comment by lambdalisue** [comment]
> Nothing to suggest environment variables etc. It simply says: "Checks if the plugin is installed."

I'm not sure but if you correct English, Shougo would thank you I guess ;-)

**Comment by lambdalisue** [comment]
(Personally, I think the description is enough though).

**Comment by symbolix** [comment]
I can confirm that `dein#tap()` is sufficient for checking if a plugin has been added by dein. Thanks.

> I'm not sure but if you correct English, Shougo would thank you I guess ;-)

Sure. I would be really happy to help with that. However, I need to test that function and fully understan what it does.

I keep trying, but with no success so far:

    :if dein#check_install(['no_such_a_plugin'] | echo 'Not Ok' | else | echo 'Ok' | endif

    :if dein#check_install(['vimproc'] | echo 'Not Ok' | else | echo 'Ok' | endif

would, in both cases return  **Ok**. So I do not really see how your example would work:

    if dein#check_install(['syntastic'])
      " Assume that installing syntastic require $FOO environment value for instance
      let $FOO = 'hoge'
      call dein#install(['syntastic'])
    endif

as it will never generate an non-zero value.

**Comment by lambdalisue** [comment]
> as it will never generate an non-zero value.

If `{plugins}` is not registered, it returns 0. Try below.



1. Add `call gita#add('Shougo/neobundle.vim', { 'merged': 0 })`
2. Restart your vim
3. `echo dein#check_install(['neobundle.vim'])`

The procedure above showed me message like:

![](https://i.gyazo.com/484e7a00f51d587377ea3ae7cebf9823.png)

(I used 'Shougo/neobundle.vim' while I assumed that you don't use it. If you are somehow using it, replace that to other plugin.)

**Comment by symbolix** [comment]
What is `gita#add` ?

**Comment by lambdalisue** [comment]
Oops. `dein#add` sorry.

**Comment by symbolix** [comment]
By `Add call dein#add('Shougo/neobundle.vim', { 'merged': 0 })`, you mean add it to my `.vimrc`, yeah this is exactly how I am adding my plugins. But `dein#check_install(['neobundle.vim'])` does not work for me.

Well, in my case it is other plugins `vimproc`, `unite.vim` etc.

**Comment by lambdalisue** [comment]
Make sure that you are using latest dein.vim.

If you are using the latest, create a minimal `.vimrc` file **for reproducing**. The one you pasted at the beginning is not a proper minimal vimrc while I don't think nobody can reproduce the situation with that one.

**Comment by lambdalisue** [comment]
s/nobody/anybody

**Comment by lambdalisue** [comment]
I think you miss understand terms.

gita#add just add a plugin to manage. actual installation is not performed until dein#install is called. so that 

dein#check_install stands for checking plugins which are added but not installed yet. 

dein#tap check if a plugin is added. 

dein#is_sourced check if plugin is sourced (mainly for lazy plugin).

**Comment by Shougo** [comment]
Yes, it is feature.

**Comment by symbolix** [comment]
That is great. It makes sense now. I never thought about the concept of _adding_ and _installing_ the plugins without restarting vim. As all my plugins are already added and installed during vimstart-up, `dein#check_install()` was always returning `0`. Thanks for the explanation.

**Comment by Shougo** [comment]
Tips:  You can install plugins by `dein#direct_install()` without modifing .vimrc.
