### ISSUE TITLE
[temp] rev でブランチを指定しても、そのブランチが checkout されない

### ISSUE THREAD

**Issue by hokorobi** [Shougo/dein.vim#6]
# Problems summary
rev でブランチを指定しても、そのブランチが checkout されない

rev の使い方が変わっていそうな気はします……。

## Expected
rev でブランチを指定したら、そのブランチが checkout される

## Environment Information
 * OS: Windows7 64bit
 * Vim version: vim74-kaoriya-win64-20160124

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
It is not implemented yet.
Please see in https://github.com/Shougo/dein.vim#future-works-not-implemented-yet.

**Comment by hokorobi** [comment]
Thank you.
これも Revision lock になるんですね。なるほど、確かに。

**Comment by Shougo** [comment]
It is already implemented.

**Comment by hokorobi** [comment]
Thank you!
