### ISSUE TITLE
:Unite dein, 'X'(not installed) mark not output

### ISSUE THREAD

**Issue by ryunix** [Shougo/dein.vim#60]
# Problems summary

`:Unite dein`を実行した際に、未インストールのプラグインに'X'(not installed)マークがつかない。

## Expected

未インストールのプラグインの、`g:dein#_plugins[{plugin-name}]['sourced']`が1になっている。
`is_sourced`と`is_installed`の判定順番を入れ替えるか、`g:dein#_plugins[{plugin-name}]['sourced']`が0になるのが良いのかなと思いましたが、いかがでしょうか？

```vim
let candidate.abbr =
      \ candidate.source__is_sourced ? ' ' :
      \ candidate.source__is_installed ? '#' : 'X'
```

## Environment Information
 * OS: OS X v10.9 Mavericks
 * Vim version: 7.4.1641

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath^=~/sample/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/sample/dein'))
call dein#add('Shougo/unite.vim')
call dein#add('Shougo/vimfiler.vim')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

0. call dein#install('unite.vim')
0. echo dein#_plugins['unite.vim']['sourced'] " => 1
0. echo dein#_plugins['vimfiler.vim']['sourced'] " => 1
0. echo isdirectory(dein#_plugins['unite.vim']['path']) " => 1
0. echo isdirectory(dein#_plugins['vimfiler.vim']['path']) " => 0

## Upload the log messages by `:redir` and `:message`

```
[dein] Update started: (2016/04/01 21:53:36)
[dein] Updated plugins:
[dein]   unite.vim
[dein]     https://github.com/Shougo/unite.vim/compare/...bb2654fdcf79383216b1707c021351a05b630985
[dein] Runtimepath updated: (2016/04/01 21:53:46)
```

**Comment by Shougo** [comment]
Fixed.

**Comment by ryunix** [comment]
修正確認中ですが、今の修正だと`is_sourced`が`#(not sourced)`としてマークされるのでおかしいかと思います。

以下に出力予想パターンを整理しました。

0. インストール済 + ソース済 => ' '
0. インストール済 + 未ソース => '#(not sourced)'
0. 未インストール + ソース済 => 'X(not installed)'
0. 未インストール + 未ソース => 'X(not installed)'

Expectedに修正前ソースを貼ってしまったのが混乱を招きましたね、申し訳ないです。
次のような修正でいかがでしょうか？(手元では確認済ですが書き方に自信がないので確認させてください)

```vim
let candidate.abbr =
      \ !candidate.source__is_installed ? 'X' :
      \ candidate.source__is_sourced ? ' ' : '#'
```

**Comment by Shougo** [comment]
Thanks.

**Comment by ryunix** [comment]
確認しました、ありがとうございます。
