### ISSUE TITLE
dein#call_hook() call hooks of plugins which has not installed yet

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/dein.vim#61]
# Problems summary
`dein#call_hook('source')` or `dein#call_hook('post_source')` call hook functions of plugins which has not installed yet so that the initial run raise E117 exception if an autoload function of the plugin has used.

## Expected
`dein#call_hook('source')` or `dein#call_hook('post_source')` call hook functions of plugins which **has installed and sourced**.

Or

`dein#load_state()` call such hooks so that users does not need to call `dein#call_hook()` manually even there is state cache (but this is rejected at https://github.com/Shougo/dein.vim/issues/50)

## Environment Information
 * OS: Ubuntu 15.04
 * Vim version: NVIM 0.1.3-dev / 

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" ~/.vimrc.min
if has('vim_starting')
  if &compatible | set nocompatible | endif
  set runtimepath& runtimepath+=~/.vim/bundle/repos/dein.vim
endif

let s:dein_basepath = expand('~/vim_minimum_bundle')

call dein#begin(s:dein_basepath)
call dein#add('Shougo/unite.vim', {
      \ 'hook_post_source': 'call unite#custom#profile("default", "context", {"start_insert": 1})',
      \})
call dein#end()
call dein#save_state()
call dein#call_hook('source')
call dein#call_hook('post_source')

filetype plugin indent on
syntax on
```

## The reproduce ways from Vim starting (Required!)

 1. `vim -u ~/.vimrc.min` and you will see

```
[dein] Error occured while executing hook: unite.vim
[dein] Vim(call):E117: Unknown function: unite#custom#profile
```

**Comment by Shougo** [comment]
Fixed.

**Comment by lambdalisue** [comment]
That's so quick. Thanks ;-)
