### ISSUE TITLE
dein#util#_load_merged_plugins() raise E474

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/dein.vim#62]
# Problems summary

https://github.com/Shougo/dein.vim/blob/3f9b6412bb35c1e807e5c72563bd10e54a0fc53c/autoload/dein/util.vim#L433-L438

`json_decode({string})` raise E474: Invalid argument when an item in a list is quoted by **single quotes** instead of double quotes (invalid json, like vimson).

## Expected
`json_decode` should not be used while user might use neovim and vim and json and vimson is completely different.

Or

Do not use `string({object})` to create a vimson and create a valid json (quote with double quotes) even in neovim or old vim.

Or

Simply use `writefile()` and `readfile()` instead of making json while `merged` just contain plugin names (but it solved `_load_merged_plugins()` function only)

## Environment Information
 * OS:
 * Vim version: NVIM-0.1.3 vs Vim 7.4.1685

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" In neovim, eval is used instead of js_decode
eval("['A']")
" => ['A']

" In Vim, js_decode is used instead of eval
js_decode("['A']")
" => E474: Invalid argument

" Opposite is OK
eval('["A"]')
" => ['A']
js_decode('["A"]')
" => ['A']
```

## Reproduce

1. Remove `~/.vim/bundle/merged`
2. Start neovim to create `~/.vim/bundle/merged`
3. Start vim to load `~/.vim/bundle/merged`

## Screen shot (if possible)
The E474 raise cause something like the below

![selection_020](https://cloud.githubusercontent.com/assets/546312/14224688/5a12f118-f8e0-11e5-850b-34f4f527bf6d.png)

**Comment by Shougo** [comment]
OK.  Fixed.

**Comment by lambdalisue** [comment]
Thanks :+1:
