### ISSUE TITLE
:Unite dein, cause E716 error

### ISSUE THREAD

**Issue by ryunix** [Shougo/dein.vim#64]
# Problems summary

`:Unite dein`を実行した際に、E716(辞書型にキーが存在しません)エラーが発生する。
スマホからなので.vimrcとlogは省略させてください。

## Expected

`g:dein#_plugins`に存在しないキー(`uri`)を使用している箇所がある。
https://github.com/Shougo/dein.vim/blob/afebba478f20461d9913452d7fa629f5fe56f8a2/autoload/unite/sources/dein.vim#L50
エラーが発生するのは afebba4 からです。

## Environment Information

* OS: Windows Server 2008 R2
* Vim version: 7.4.1655

## The reproduce ways from Vim starting (Required!)

0. Unite dein

**Comment by Shougo** [comment]
Fixed

**Comment by ryunix** [comment]
確認しました、修正ありがとうございます。
