### ISSUE TITLE
Some vim plugins do not work with dein

### ISSUE THREAD

**Issue by matthauck** [Shougo/dein.vim#65]
# Problems summary
Trying to move from NeoBundle to dein and cannot get all my vim plugins to work. The plugin in particular that I am stumbling on with dein is https://github.com/Quramy/tsuquyomi.

## Expected

After loading this plugin, I expect there to be a command named `TsuquyomiDefinition`. There is not.

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: `7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)`

Will try to set aside time to get a minimal .vimrc setup for this. Thought I'd file the issue anyway since you seem to be eager to get people off of NeoBundle and this is a show-stopper for me...

**Comment by zchee** [comment]
@matthauck Hi .
I understand error. but error information is not exists.
Could you post minimum init.vim?

**Comment by matthauck** [comment]
I was able to repro with this: 

```
set nocompatible
set runtimepath+=~/.vim/dein/dein.vim
call dein#begin(expand('~/.vim/dein'))

call dein#add('Quramy/tsuquyomi') 

call dein#end()

if dein#check_install()
  call dein#install()
endif
```

Setup: I have a `~/.vim/dein` directory, and inside that cloned dein.vim into `~/.vim/dein/dein.vim`.

Result:
![image](https://cloud.githubusercontent.com/assets/1308591/14297046/d16d101a-fb31-11e5-837d-79dd42f921ce.png)

**Comment by zchee** [comment]
@matthauck Okay, I understand.

[tsuquyomi](https://github.com/Quramy/tsuquyomi) has a [vimproc.vim](https://github.com/Shougo/vimproc.vim) of dependency.
https://github.com/Quramy/tsuquyomi#how-to-install

If you `call dein#add('Quramy/tsuquyomi')` before `call dein#add('Shougo/vimproc.vim')`, tsuquyomi does not works.

minimal vimrc is Here.
```vim
set nocompatible
set runtimepath+=~/.vim/dein/dein.vim
call dein#begin(expand('~/.vim/dein'))

" Need before Quramy/tsuquyomi!!
call dein#add('Shougo/vimproc.vim', {'build': 'make'}) 
call dein#add('Quramy/tsuquyomi') 

call dein#end()

if dein#check_install()
  call dein#install()
endif

autocmd! BufNew,BufRead *.ts setlocal filetype=typescript
```

test ts file is
```typescript
class Greeter {
    constructor(public greeting: string) { }
    greet() {
        return "<h1>" + this.greeting + "</h1>";
    }
};

var greeter = new Greeter("Hello, world!");
    
document.body.innerHTML = greeter.greet();
```

**Comment by matthauck** [comment]
Ah right. Forgot that was a dependency. That was in my original vimrc but didn't make it over to the minimal repro I posted above. 

Adding in vimproc though, as you have above, it still does not work for me. I still do not have the `TsuquyomiDefinition` command available.

**Comment by zchee** [comment]
@matthauck Do you already tested my comment vimrc? It's will works `TsuquyomiDefinition` command.

**Comment by Shougo** [comment]
@matthauck TsuquyomiDefinition is available on typescript buffer.
https://github.com/Quramy/tsuquyomi/blob/master/ftplugin/typescript.vim

Did you test it on typescript buffer?
Please provide the reproduce ways from Vim starting.

**Comment by matthauck** [comment]
Yes, I have tested the vimrc from your comment and can still repro the issue. Attached an animated gif as some proof. =)

1. Opened `.vimrc` to verify it is the same as the one in your comment
2. Call `set filetype` to verify the autocmd worked properly and it is indeed a `typescript` filetype buffer.
3. Call `TsuquyomiDefinition` to verify the command is still invalid

![vim-typescript](https://cloud.githubusercontent.com/assets/1308591/14306668/ea825b7c-fb7d-11e5-97d6-e8d840653d01.gif)

I took another look at my NeoBundle setup, and found a difference, actually. Looks like the difference is `filetype plugin indent on` documented as necessary in NeoBundle, but was missing from my dein setup. Adding that gets it work properly now with dein, even without the `autocmd`.

Interesting that you that .vimrc worked above for you without the `filetype plugin indent on`. In any case, I think I am okay now. It still is not working in my larger `.vimrc`, but looks like something else may be conflicting there I suppose. Probably not a bug in dein if it works in this minimal case. 

/shrug

**Comment by matthauck** [comment]
Ah. Looks like the problem with my main `.vimrc` was again the ordering of vimproc. :blush:

**Comment by Shougo** [comment]
> I took another look at my NeoBundle setup, and found a difference, actually. Looks like the difference is filetype plugin indent on documented as necessary in NeoBundle, but was missing from my dein setup. Adding that gets it work properly now with dein, even without the autocmd.

Yes, `filetype plugin indent on` is needed.
