### ISSUE TITLE
autocmd in hook_add in toml cause exceptions

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/dein.vim#67]
# Problems summary
autocmd in `hook_add` attribute in TOML file cause one of the following exception

- E215: Illegal character after *: *
- E216: No such group or event:

## Environment Information
 * OS: Ubuntu 15.04
 * Vim version: neovim / vim 7.4.1685

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" vim -u ~/.vim/vimrc.min
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/repos/dein.vim
endif

call dein#begin(expand('~/.vim/bundle/minimum'))
call dein#load_toml('~/test.toml')
call dein#end()

filetype plugin indent on
syntax on
```

And `~/test.toml` is

```toml
[[plugins]]
repo = 'lambdalisue/vim-findent'
hook_add = '''
  augroup findent
    autocmd! *
    autocmd FileType vim Findent --no-warnings
  augroup END
'''
```

## The reproduce ways from Vim starting (Required!)

1. `vim -u ~/vimrc.min`
2. `autocmd! *` cause E215 and `autocmd!` cause E216

## Upload the log messages by `:redir` and `:message`

```
# with autocmd! *
alisue *> vim -u ~/.vim/vimrc.min
[dein] Error occurred while executing hook: vim-findent
[dein] Vim(autocmd):E215: Illegal character after *: *
[dein]     autocmd FileType vim Findent --no-warnings
[dein]   augroup END
Press ENTER or type command to continue
# with autocmd!
alisue *> vim -u ~/.vim/vimrc.min
[dein] Error occurred while executing hook: vim-findent
[dein] Vim(autocmd):E216: No such group or event: 
[dein]     autocmd FileType vim Findent --no-warnings
[dein]   augroup END
Press ENTER or type command to continue
```

**Note** that `~/.vim/bundle/state_nvim.vim` or so looks correct so this happen only during TOML parse even the parsed value is correct.

**Comment by Shougo** [comment]
I cannot reproduce the error.
I think your dein.vim version is old.

**Comment by lambdalisue** [comment]
I see. I confirmed my dein.vim version by `cd ~/.vim/bundle/repos/dein.vim; git log` and it was 2b3d52d1b37c.
As you said, updating dein.vim fix this issue.

But **I run `call dein#update()` everyday so I thought I was using a latest version**.
Is `call dein#update()` won't update dein.vim itself or is my configuration wrong?

```vim
let s:dein_basepath = expand('~/.vim/bundle')
let s:dein_abspath  = printf(
      \ '%s/repos/dein.vim',
      \ s:dein_basepath,
      \)

execute 'set runtimepath^=' . fnameescape(s:dein_abspath)
if dein#load_state(s:dein_basepath)
  call dein#begin(s:dein_basepath, [
        \ expand('~/.vimrc'),
        \ ...
        \])
  call dein#load_toml(expand('~/.vim/rc/dein/define.toml'))
  call dein#local(s:dein_localpath, {
        \ 'frozen': 1,
        \ 'merged': 0,
        \})
  call dein#end()
  call dein#save_state()
endif
" ...
```

```toml
[[plugins]]
repo = 'Shougo/dein.vim'
directory = 'dein.vim'
```

Thanks for the help ;-)

**Comment by Shougo** [comment]
I don't know why.
I think it just update timing problem.
Please update dein.vim before creating issues.

**Comment by lambdalisue** [comment]
I did call dein#update() just before creating the issue and also after your comment. And confirmed that dein is not updated by call dein#update()... that's why I asked if it is a feature or not.

**Comment by Shougo** [comment]
Please create minimal .vimrc.

**Comment by lambdalisue** [comment]
> Please create minimal .vimrc.

See #72
