### ISSUE TITLE
Can I get g:dein#plugin in `hook`s?

### ISSUE THREAD

**Issue by delphinus35** [Shougo/dein.vim#70]
Since 19e721a, `build` dict is disabled in plugin setting. I wrote setting to build vimproc by `hook_post_update` with referring to doc.

```toml
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#tap('vimproc.vim')
    if dein#util#_is_windows()
      let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
      let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
      let cmd = 'gmake'
    else
      let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
  endif
'''
```

I could get the desirable result, but this `if dein#tap()` block seems redundant to me.

Can I use the `plugin` dict with more simple way? Such as...

```toml
# local variable `plugin` has the `g:dein#plugin` value
hook_post_update = '''
  let plugin.build = 'make'
'''
```

I think this can be useful in other cases.

**Comment by Shougo** [comment]
Implemented.

**Comment by delphinus35** [comment]
thx a lot! 

ref 7679fc0479381fada06425c2efd8197e215510e0
