### ISSUE TITLE
Need to be able to disable/uninstall plugins

### ISSUE THREAD

**Issue by matthauck** [Shougo/dein.vim#71]
There are sometimes problems with a particular plugin that I would like to disable temporarily, or when one decides to stop using a plugin, it is nice to be able to remove it. There does not appear to be a way to do that with dein because it puts all the vim files in one directory `~/.vim/dein/.dein`. This makes it very difficult both to to disable something temporarily as well as to remove completely.

**Comment by wsdjeg** [comment]
lazy load plugin will not be moved to `~/.vim/dein/.dein`,you can use lazy load feature.also `call dein#recache_runtimepath()` can recache `~/.vim/dein/.dein`.

**Comment by wsdjeg** [comment]
for `uninstall plugin` or `disable plugin`,I do not know this feature will be added to dein.

**Comment by Shougo** [comment]
@matthauck You can disable the merge feature by `'merged': 0`.
And I will add disable plugins feature.

**Comment by Shougo** [comment]
Implemented.

**Comment by matthauck** [comment]
Wow, that was fast, thanks!

On Friday, April 8, 2016, Shougo <notifications@github.com> wrote:

> Implemented.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Shougo/dein.vim/issues/71#issuecomment-207683327>
>


-- 
Matt

**Comment by matthauck** [comment]
Question: So if there is no uninstall that will be added to dein, how would you suggest we uninstall things? The only options seem to be:
1. Keep a list forever of things disabled
2. Blow away the `.dein` directory and reinstall everything

Neither of these seem optimal. Is there another workflow that you have for removing plugins that you can share?

**Comment by Shougo** [comment]
@matthauck 

You can get the directories by `dein#check_clean()`.
So, you can remove the directories like this.

```vim
call map(dein#check_clean(), "delete(v:val, 'rf')")
```

**Comment by schoettl** [comment]
I think it's still complicated. I will never remember this command to remove disabled plugins.

What do you think of a `dein#uninstall([{plugins}])` or `dein#remove([{plugins}])` function? Every package manager out there has it. It could call `disable()` and then filter `check_clean()`'s result for the plugin to remove. And then delete it.

Also, I have a question on `dein#disable()`: The documentation says
> Note: This command must be executed before dein loads
> the plugins.

Does this mean I have to put the call to `disable()` in my vimrc between `dein#begin()` and `dein#end()`? Or can I also call it in a running vim/nvim?

**Comment by Shougo** [comment]
@schoettl Why this feature is needed?
I can add `dein#uninstall()`, but you must remove the `dein#add()` line from your vimrc.
It is the same behavior with Bundle.

> Does this mean I have to put the call to disable() in my vimrc between dein#begin() and dein#end()? Or can I also call it in a running vim/nvim?

You cannot disable the plugin after it is loaded.
Because, Vim cannot unload the loaded plugins.

**Comment by schoettl** [comment]
I don't know Bundle. Ok, I don't understand how to disable a plugin. Is deleting the `dein#add()` in the vimrc enough?

**Comment by Shougo** [comment]
Yes.

**Comment by wsdjeg** [comment]
@schoettl if it is not a lazy load plugin, you need run `:call dein#recache_runtimepath()` after start vim I think.

**Comment by Shougo** [comment]
@wsdjeg 
Dein.vim detects the vimrc changes and calls `dein#recache_runtimepath()` automatically.

**Comment by wsdjeg** [comment]
@Shougo thanks
but will dein detect these changes?
1. `call dein#add('foo/abc')` to `call dein#add('foo/abc',{'on_i':1})`   ===> not sure dein will remove plugin from cache dir
2. `call dein#add('zaa/abc')` to `call dein#add('foo/abc')`     ===> I think dein could rechche this by enable checkinstall feature at vim startup.
3.  `call dein#add('foo/abc',{'on_i':1})` to `call dein#add('foo/abc')`   ===> for this, how dein works?

**Comment by schoettl** [comment]
Thank you two! I got it; it's really simple.

I was confused earlier because it seemed to not work, but that was obviously my mistake.

**Comment by Shougo** [comment]
@wsdjeg Yes.

But you must specify `dein#begin()` 2nd argument.

**Comment by wsdjeg** [comment]
@Shougo thanks, maybe I should add compared vimrcs in to my config

**Comment by trisys3** [comment]
I just want to note that if you have your package configuration in another file besides `~/.vimrc` (`vundle` recommended it for first installation, but it is probably not as useful for `dein`), `dein` will not detect the removal of the `dein#add`, so you will need to run `call dein#recache_runtimepath()` anyway.

**Comment by gotgenes** [comment]
@trisys3 Thank you for saving me time! I was going nuts trying to figure out why plugins were lingering after I was using a file `~/testvimrc` even when I had removed the `dein#add` lines as well as called 

``` vim
call map(dein#check_clean(), "delete(v:val, 'rf')")
```

as suggested by @Shougo [above](https://github.com/Shougo/dein.vim/issues/71#issuecomment-208601678). I was not aware of this caching and I found it surprising and unintuitive that a plugin still seemed to be installed even though I had called the "recommended" uninstallation method.

**Comment by devth** [comment]
So what's the conclusion? I ran all these commands and the plugin still remains in `~/.config/nvim/.cache/`.

Is the solution to just `rm -rf ~/.config/nvim/.cache/` and restart nvim?

**Comment by Shougo** [comment]
> Is the solution to just rm -rf ~/.config/nvim/.cache/ and restart nvim?

It removes all installed plugins.
You should not do this.

> Is it safe to include `call map(dein#check_clean(), "delete(v:val, 'rf')")` in init.vim?

Safe.
But it must be after plugins loaded.
I don't recommend to uninstall automatically.
Other plugin/package managers don't do it.
