### ISSUE TITLE
Could you please explain how the "merging" works with dein.vim

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#73]
Hi,

I am having a bit of a hard time understanding how `merging` and the `caching` system work. Of course, if `merging` and `caching` are the same thing? Could you please add some case studies to the `docs` or maybe use this issue to explain how that specific aspect of `dein.vim` works.

When I first switched from `neobundle` to `dein.vim`, I did not really know about the **merging** and **caching** functionality. So I experienced some issues because of this. As far as I understand, so far there are two main options: **[A] Not using the caching/merging back-end** and **[B] Using the merging/caching option**.

Let's assume we would like to go with option **[A]**. So how should the user be initializing `dein.vim` for this specific scenario? Below is a list of what I think I kind of  understand when it comes to this option:

_[A] No Caching, No Merging_

1.  `call dein#begin('my_bundle_path')`: Pointing dein to the `bundles` folder.

2. No need to use the following functions: `dein#save_cache()`, `dein#load_cache`, `dein#load_state`, `dein#save_state`? I assume that we do not need to use the `dein#recache_runtimepath()` function as the `bundles` folder is where all the plugins are being installed? Is that correct?

3. All plugins have to be added using the `{'merged' : 0}` option.

Now, let's assume that we would like to take advantage of the caching/merging infrastructure `dein.vim` provides. Below is a list of my observations and questions:

_[B] With Caching and With Merging_

1. What should be used in the  `dein#begin()` function? Should it be some kind of a temp folder such as `call dein#begin('/.vim/.cache/dein')` or should we use the bundles folder as in  `call dein#begin('my_bundle_path')`?

2. How do we use the following `dein#save_cache()`, `dein#load_cache`, `dein#load_state`, `dein#save_state` functions?

3. As far as I understand, merging means that all the plugins are merged into a `.cache` folder in order to speed up the loading process. So, when do we need to run the `dein#recache_runtimepath()` command in this case? How we specify the location of the plugin cache?

I hope @Shougo or some of the more experienced users can help me to understand this a bit better. 

Below is how I use `dein.vim` in my `.vimrc`:

    if &compatible
       set nocompatible
    endif
    
    set runtimepath+=/Users/me/.vim/bundle/repos/dein.vim
    call dein#begin('/Users/me/.vim/bundle')
    call dein#add('Shougo/dein.vim')
    call dein#add('SomeRepo/SomePlugin.vim', {'merged': 0})
    call dein#end()

    if dein#check_install()
        call dein#install()
    endif
    
    filetype plugin indent on

Is this a correct application? How would one modify that to utilize the caching/merging approach? Can we have a hybrid workflow where some of the plugins would be merged and some would NOT be merged?

Thanks.

**Comment by lambdalisue** [comment]
### `dein#save_cache()` and `dein#load_cache()`

It is deprecated. Forget about it.

### `dein#save_state()` and `dein#load_state()`

It caches initialization code of dein.vim.

For example, if you define `hook_add` to several plugins, the codes are cached into a single file rather than multiple functions or autocmds or whatever. Sourcing a single file improves performance a lot.

### merging

To reduce the size of `runtimepath`, dein.vim merge plugins into a single directory.
This is a most unique point of dein.vim while other plugin manager simply add the path of each plugins into `runtimepath` (and it makes Vim slow if you have tons of plugins, Vim need to find a particular function from tons of `runtimepath`.)

In ideal situation, users do not need to call `dein#recache_runtimepath()` manually.
dein.vim should call the function when it's needed.
But sometime, user need to call it manually so it is a public function I guess.

**Comment by symbolix** [comment]
Thanks. However, I would like to learn a bit more on this topic. So even if I have `{'merged' : 0}` on all my plugins (and no additional hooks or options), the caching will still be active? For example this will still be cached?

    call dein#add('SomeRepoA/SomePluginA.vim', {'merged': 0})
    call dein#add('SomeRepoB/SomePluginB.vim', {'merged': 0})

How about this?
    
    call dein#add('SomeRepoA/SomePluginA.vim', {'merged': 0})
    call dein#add('SomeRepoB/SomePluginB.vim', {'merged': 0})
    call dein#add('SomeRepoC/SomeRepoC')
        call dein#config('SomeRepoC/SomeRepoC', {
            \ 'merged' : 0,
            \ 'hook_source': 'autocmd FileType java
            \                 setlocal omnifunc=javacomplete#Complete'
            \ })

In this case, the caching will take place because there is a `hook_sourced`?

Let's say I have those two plugins:

    call dein#add('SomeRepoA/SomePluginA.vim', {'merged': 0})
    call dein#add('SomeRepoB/SomePluginB.vim')

Where `SomePluginB` will be cached? How can I specify a location to hold the cache?

If I do not have any merged plugins, for example, all  have the `{'merged': 0}` option, do I still need to use the `dein#save_state()` and `dein#load_state()` commands in my `.vimrc` file?

Could you please share a minimal `.vimrc` configuration here, that uses the `dein#save_state()` and `dein#load_state()` commands?

`dein.vim` is a great plugin with lots of unique and bright ideas in there. However, I feel like there is a steep learning curve to it. I am looking forward to understand it better. Thanks for your time.

**Comment by Shougo** [comment]
@symbolix The cache feature is independent of the merge feature.
You can use the cache feature without the merge.

> How about this?

This can be cached.  `hook_source` is can be cached.

> Where SomePluginB will be cached? How can I specify a location to hold the cache?

`SomePluginB` will be cached.
The cache is saved on the dein base directory(You have specified it by `dein#begin()`).

> If I do not have any merged plugins, for example, all have the {'merged': 0} option, do I still need to use the dein#save_state() and dein#load_state() commands in my .vimrc file?

Yes.

> Could you please share a minimal .vimrc configuration here, that uses the dein#save_state() and dein#load_state() commands?

I have not much time.  Other people can make it.

**Comment by jasontwong** [comment]
Example from documentation:

```
	if dein#load_state(path)
	  call dein#begin(path)
	  " My plugins here:
	  " ...
	  call dein#end()
	  call dein#save_state()
	endif
```

**Comment by symbolix** [comment]
Thanks you. Will share mine soon.

**Comment by symbolix** [comment]
Well,  I adapted the example provided by @jasontwong and things seems to be still working. I did not have the `if dein#load_state(path)` and the `call dein#save_state()` bits in there. One question though, here is my exact dein related bit from my .vimrc

    " Set compatibility mode
    if &compatible
        set nocompatible
    endif

    let g:vim_bunde_path = '/Users/me/.vim/bundle'
    if dein#load_state(g:vim_bunde_path)
        call dein#begin(g:vim_bunde_path)
        call dein#add('Shougo/dein.vim')
        " This is a function that runs multiple dein#add() commands
        call InitPluginChain()
        call dein#end()
        call dein#save_state()
   endif

    if dein#check_install()
        call dein#install()
    endif

    " Reset settings
    filetype plugin indent on

Do you see anything wrong with those lines?

I can see a folder called `.dein` inside my `~/.vim/bundle` folder and inside there is an `ftdetect` folder with an `ftdetect.vim` file. When I examine the contents of that file, I can see bits and pieces from an experimental plugin that I am working on. I am loading that plugin with a

    call dein#local('some_path_to_a_folder', {
            \ 'merged : 0,
            \ 'normalized_name' : 'MyPlugin',
            \ }, ['plugin_sub_folder'])

So, I wondering, how those plugin bits ended up in that `.dein` folder, probably, I was installing the plugin without the `{'merged' : 0} option and it got merged into that temp cache folder? Is it safe to delete that `.dein` folder? I need my experimental plugin to be live all the time, so I can immediately see the results after each restart of vim. I am a bit worried that those cached bits might be getting in the way.

Thanks.

**Comment by symbolix** [comment]
I also have noticed that if I use `if dein#load_state(g:vim_bunde_path)` and `call dein#save_state()` this bit is skipped:

    " This is a function that runs multiple dein#add() commands
    call InitPluginChain()

But the plugins are loaded. But plugins like `vim-localvimrc` are not functional. Do I need to assign hooks to those? if I am using the `state` commands?

**Comment by Shougo** [comment]
> Is it safe to delete that .dein folder?

You must not remove it.

> Probably, I was installing the plugin without the {'merged' : 0} option and it got merged into that temp cache folder at some point? 

You don't have to set `'merged': 0` for it.
The local plugins are not merged.

> ftdetect folder with an ftdetect.vim file. When I examine the contents of that file, I can see bits and pieces from an experimental plugin that I am working on. I am loading that plugin with the following lines:

ftdetect is merged. It is feature.

**Comment by symbolix** [comment]
Thank you very much for the information.
