### ISSUE TITLE
Two different plugin set for Vim and Neovim

### ISSUE THREAD

**Issue by markwu** [Shougo/dein.vim#75]
Should I prepare two different bundle path for Vim and Neovim if they use different plugin sets?  I just found I have to use the following function calls to make the proper plugin set working correctly when I switch back and forth.

```vim
call dein#clear_state() | call dein#recache_runtimepath()
```
The only way I can think about to solve this problem is to create two bundle folders for Vim and Neovim. Does there any better way to solve this problem?

Any help would be much appreciated.

Mark

**Comment by wsdjeg** [comment]
no need you can use {merge : 0} ,the plugin will not be copy to cache dir,also you can use if has('nvim') block

**Comment by Shougo** [comment]
Yes, so no problem.

**Comment by markwu** [comment]
I see, it works great. Thanks for your help!

**Comment by markwu** [comment]
One more question, does there any function to regenerate merged folder?

**Comment by Shougo** [comment]
`call dein#recache_runtimepath()`

**Comment by markwu** [comment]
I see, so dein#recache_runtimepath() regenerate everything. Thanks.

**Comment by rpuntaie** [comment]
To load less plugins in `nvim`, for example, instead of

```
  call dein#add('Shougo/deoplete.nvim')
```

you do

```
  if !has('nvim') | call dein#add('Shougo/deoplete.nvim',{'merged':0}) | endif
```

After this change you need to call one time

```
call dein#recache_runtimepath()
```

else you will get `Duplicated source: around  Use :messages / see above for error details.`

**Comment by Shougo** [comment]
`if` is better for it.  `:help dein-options-if`

```vim
call dein#add('Shougo/deoplete.nvim',{'if': `has("nvim")`})
```

**Comment by rpuntaie** [comment]
This worked:

``` vim
call dein#add('Shougo/deoplete.nvim',{'if':'!has("nvim")','merged':0})
```
