### ISSUE TITLE
vim-localvimrc not working with dein.vim

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#76]
# Problems summary
**vim-localvimrc** is a plugin designed to source vim setting per project by sourcing a `.localvimrc` file in the root directory of the project. When using the  `dein#load_state(g:vim_bundle_path)` / `call dein#save_state()` the live stage that sources the plugin seems to be skipped, but the plugin is listed as added. However does not work.

## Expected
I have a minimal `.localvimrc` file inside a project dir:

    let g:my_current_project_name = 'vectorExample'

I am expecting to see the text `vectorExample` when I do `echo g:my_current_project_name` but that is not the case. When I take out the `dein#load_state(g:vim_bundle_path)` / `call dein#save_state()` bits, the plugin is sourced and the functionality is as expected.

## Environment Information
 * OS: OSX 10.10.5

 * Vim version:
7.4 (1-1553)

## Provide a minimal .vimrc with less than 50 lines (Required!)

    " Minimal DEBUG .vimrc file
    if &compatible
        set nocompatible
    endif

    " Path to the plugin manager:
    set runtimepath^=/Users/me/.vim/bundle/repos/github.com/Shougo/dein.vim
    let g:tmp_bundle_path = '/Users/me/.tmp/tmp_bundle'

    " (DISABLE_TO_MAKE_THIS WORK)
    if dein#load_state(g:tmp_bundle_path)
    	" Start the plugin block.
    	call dein#begin(g:tmp_bundle_path)

    	" Initial plugin is the plugin manager.
    	call dein#add('Shougo/dein.vim')

    	" Add or remove your plugins here:
    	call dein#add('embear/vim-localvimrc',
		\ {'merged' : 0,
                \ 'normalized_name' : 'localvimrc'})
    	" Plugin configuration.
    	if dein#tap('vim-localvimrc')
        	" The plugin is active.
        	let g:localvimrc_name = [".vixrc"]
        	let g:localvimrc_sandbox = 0
        	let g:localvimrc_script_dir = 1
        	let g:localvimrc_debug = 0
        	let g:localvimrc_persistent = 2
        	let g:localvimrc_event = [ "BufWinEnter",  "BufWritePost" ]
        	let g:localvimrc_ask = 0
        endif
    	" End the plugin block.
    	call dein#end()
	" (DISABLE_TO_MAKE_THIS WORK)
	call dein#save_state()
    endif

    " Install the plugins that have not been installed  so far.
    if dein#check_install()
        call dein#install()
    endif

    " Reset settings.
    filetype plugin indent on

## The reproduce ways from Vim starting (Required!)

 1. Start Vim.
 2. Load a script file (py/vim/cpp) from a folder with a `.localvimrc` file
 3. Run: `echo g:my_current_project_name`

## Screen shot (if possible)
(Not provided.)

## Upload the log messages by `:redir` and `:message`
(Not provided.)

**Comment by lambdalisue** [comment]
```
    " Plugin configuration.
    if dein#tap('vim-localvimrc')
        " The plugin is active.
        let g:localvimrc_name = [".vixrc"]
        let g:localvimrc_sandbox = 0
        let g:localvimrc_script_dir = 1
        let g:localvimrc_debug = 0
        let g:localvimrc_persistent = 2
        let g:localvimrc_event = [ "BufWinEnter",  "BufWritePost" ]
        let g:localvimrc_ask = 0
    endif
```

This part need to be after `call dein#save_state()`

**Comment by symbolix** [comment]
Thanks for the examples. In my case all my plugins are sourced and configured between the `call dein#begin` and the `call dein#end()` commands. I am not sure if I understand the hooks. I will look at your examples more carefully however, this is confusing me a lot. From a setup point of view, I need to add the plugins and configure them in one cycle. Cause I do this:

    " This is pseudo code!

    if dein#load_state 
        
        call dein#begin

        for each [plugin] in list of [plugins]
            call dein#add([plugin])
            configure([plugin])

        call dein#end
    
     call dein#save_state

So I need to take the `configure([plugin])` bit outside the main dein block?

**Comment by lambdalisue** [comment]
> So I need to take the configure([plugin]) bit outside the main dein block?

Yes. The block is not called when you have a latest state cache. Read `:help dein`

**Comment by symbolix** [comment]
Ok then I have two choices, I guess. Take out the state commands and only leave the:

    call dein#begin

    for each [plugin] in list of [plugins]
        call dein#add([plugin])
        configure([plugin])

    call dein#end

... bit in there. Will that work? I mean, I did not know about the `state` command and I have been using **dein.vim** with only the begin/end block. On the other hand, I would love to learn about the `hooks`. Could you please help me write the hook for `localvimrc`? I keep reading and reading, but it is hard to understand. This is a really hard learning curve :( Thanks for the help so far.

**Comment by lambdalisue** [comment]
Well... First of all, `dein#load_state()` return 1 if there is a latest state cache. So **you cannot put any code to configure individual plugins in `if dein#load_state()` block**.

The followings are example of each situation. Read `:help dein-hooks` for detail about hooks.

### Without using `dein#load_state()`

```vim
call dein#begin(...)
call dein#add({plugin})
call dein#add({plugin})
call dein#add({plugin})
call dein#end()

if dein#tap('plugin')
   " something
endif
if dein#tap('plugin')
   " something
endif
if dein#tap('plugin')
   " something
endif
```

### With using `dein#load_state()`

```vim
if dein#load_state(...)
  call dein#begin(...)
  call dein#add({plugin})
  call dein#add({plugin})
  call dein#add({plugin})
  call dein#end()
  call dein#save_state()
endif

if dein#tap('plugin')
   " something
endif
if dein#tap('plugin')
   " something
endif
if dein#tap('plugin')
   " something
endif
```

### With hooks

```vim
if dein#load_state(...)
  call dein#begin(...)
  call dein#add({plugin}, {
\ 'hook_add': 'some code',
\})
  call dein#add({plugin}, {
\ 'hook_add': 'some code',
\})
  call dein#add({plugin}, {
\ 'hook_add': 'some code',
\})
  call dein#end()
  call dein#save_state()
endif
```

**Comment by symbolix** [comment]
Thank you very much for the help and for your time you have put in to explain this. What exactly the difference between _Without using dein#load_state()_ and _With using dein#load_state()_? As far as I understand the `state` functions cache plugin initialisation (not merging them) so this speeds up the process, right? So if I avoid the `state` block, things might be slower at start-up time, is it going to break things?

On the other hand, I will need to write the configuration of each plugin as a function and inject is as a hook, which might be really painful, is that the case?

**Comment by lambdalisue** [comment]
> What exactly is the difference between Without using dein#load_state() and With using dein#load_state()? As far as I understand the state functions caches the plugin initialisation (not merging the plugins though) so this speeds up the process, right? So if I avoid the state block, things might be slower at start-up time, is it going to break things?

Basically, you don't need `dein#load_state()`. dein.vim is fast enough and you won't notice the improvement. The exception is when you are using a TOML (a syntax sugar of `dein#add()`) to list your plugins. The TOML parser is really slow so `dein#load_state()` would drastically improve the start-up time in this case.

> On the other hand, I will need to write the configuration of each plugin as a function and inject is as a hook, which might be really painful, is that the case?

You don't need to write the configuration of each plugins as a function **and** as a hook.
You need to write the configuration of each plugins as an **if-block** **or** as a hook.

Note that there are several hooks but I'm talking about `hook_add`. Other hooks have different role which is well explained in the help.

**Comment by symbolix** [comment]
> You don't need to write the configuration of each plugins as a function **and** as a hook.
> You need to write the configuration of each plugins as an if-block **or** as a hook.

I get that. In case it is a hook, it can live inside the `state` block. In case it is an `if-block` it has to be called after the `state` block. If no state blocks are used, the `if-block` can be inside the `begin/end` block.

I will try the `hooks` just to understand how they work. Why we are using `hook_add`? Shouldn't we be using the `hook_source`, as the plugin configuration is something that is needed when the plugins are sourced? I though the `state` block skips the `adding` if the state is up-to-date. However, the plugin is still sourced. So should I use the `hook_source` hook? Thanks.

**Comment by lambdalisue** [comment]
> I will try the hooks just to understand how they work. Why we are using hook_add? Shouldn't we be using the hook_source, as the plugin configuration is something that is needed when the plugins are sourced? I though the state block skips the adding if the state is up-to-date. However, the plugin is still sourced. So should I use the hook_source hook? Thanks.

- `hook_add` - Called when a plugin is added
- `hook_source` - Called when a **lazy** plugin is sourced
- `hook_post_source` - Called after a **lazy** plugin is sourced

So `hook_source/hook_post_source` are not called for non lazy plugins (except if you call these explicitly like my vimrc.)

**Comment by symbolix** [comment]
I see. Thank you very much.

Look at your config, you are using TOML, so the `hook` API is a bit obscure if we are using vimL

    hook_add = '''
      let g:netrw_nogx = 1 " disable netrw's gx mapping
      nmap gx <Plug>(openbrowser-smart-search)
      vmap gx <Plug>(openbrowser-smart-search)
    '''

What would be the way to write this with the vimL API, for example for the `vim-localvimrc` plugin?

    call dein#add('embear/vim-localvimrc', {
		\ 'hook_add':
                         let g:localvimrc_name = [".vixrc"],
                         let g:localvimrc_sandbox = 0,
                         let g:localvimrc_script_dir = 1,
                         let g:localvimrc_debug = 0,
                         let g:localvimrc_persistent = 2,
                         let g:localvimrc_event = [ "BufWinEnter",  "BufWritePost" ],
                         let g:localvimrc_ask = 0)
		 \ })

**Comment by lambdalisue** [comment]
Something like that but the value of `hook_add` need to be a string (your example would raise a syntax error of Vim).

**Comment by symbolix** [comment]
Yes :) I know. It was just rough representation, so all these settings has to go into on single string?

    'let g:localvimrc_name = [".vixrc"] let g:localvimrc_sandbox = 0 let g:localvimrc_script_dir = 1 ...'

In the help, there are no examples demonstrating the use of global variables inside the `hooks`.

**Comment by Shougo** [comment]
> Yes :) I know. It was just a rough representation, so all these settings has to go into on single string?

Yes.

> In the help, there are no examples demonstrating the use of global variables inside the hooks.

I have added it.

**Comment by symbolix** [comment]
Thank you very much! Finally I start to understand how this works. Here is my `hook_add` for the `vim-localvimrc` plugin:

    call dein#add('embear/vim-localvimrc',
                \ {'merged' : 0,
                \ 'normalized_name' : 'localvimrc',
                \ 'hook_add': "
                \ let g:localvimrc_name = ['.vixrc']\n
                \ let g:localvimrc_sandbox = 0\n
                \ let g:localvimrc_script_dir = 1\n
                \ let g:localvimrc_debug = 0\n
                \ let g:localvimrc_persistent = 2\n
                \ let g:localvimrc_event = ['BufWinEnter', 'BufWritePost']\n
                \ let g:localvimrc_ask = 0\n
                \ "})

I can confirm that the above block works with the `if dein#load_state() ... dein#save_state`. The plugin gets added, after that the sourcing is not repeated, yet the global variables required for the plugin are valid. Exactly as it is intended to be.

**Comment by Shougo** [comment]
:-)

**Comment by Shougo** [comment]
You don't have to set "normalized_name".
It is set automatically.

**Comment by symbolix** [comment]
I also can confirm that if I change the above block, for example, add a new global variable:

    \ let g:my_test_variable = 'banana'\n

... the `if dein#load_state() ... dein#save_state()` is re-evaluated and the variable is added to the configuration.

> You don't have to set "normalized_name".
> It is set automatically.

Sure, good to know.

**Comment by Shougo** [comment]
> ... the if dein#load_state() ... dein#save_state() is re-evaluated and the variable is added to the configuration.

Yes, it is the feature.
