### ISSUE TITLE
Plugin installation at start-up breaks a local plugin.

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#77]
# Problems summary
I am not exactly sure about what exactly is going on. This might be my mistake. So appologies if that is the case. However, I have been experiencing issues with **dein.vim** related to a local plugin that I am working on. Every time a plugin is installed at start-up time, my local plugin starts with some errors. I need to close vim and restart, then it is all good. One of the error is that VIM complains about duplicate key-mappings related to my local plugin. However, the most significant error is the loss of highlight groups.

## Expected
When new plugins are installed on start time, the local plugin (which is also maintained by dein.vim) should load normally.

## Environment Information
 * OS:
OSX 10.10.5
 * Vim version:
7.4 (1-1553)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
    " Your minimal .vimrc
    "  (Step_1): I have a tiny core vim plugin that I source before everything.
    set runtimepath^=/Users/me/dev/my_core_plugin/

    " (Step_2): dein.vim block
    if &compatible
        set nocompatible
    endif
    " Path to the plugin manager:
    set runtimepath^=/Users/me/.vim/bundle/repos/github.com/Shougo/dein.vim
    let g:tmp_bundle_path = '/Users/me/.dummy/tmp_bundle'

    " Start the plugin block.
    call dein#begin(g:tmp_bundle_path)
    " Initial plugin is the plugin manager.
    call dein#add('Shougo/dein.vim')
    " Add or remove your plugins here:
    call dein#add('tpope/vim-unimpaired')
    " Load the target plugin.
    call dein#local(local_dev_folder, ['my_plugin'])
    " End the plugin block.
    call dein#end()

    " Install the plugins that have not been installed  so far.
    if dein#check_install()
        call dein#install()
     endif
    " Reset settings.
    filetype plugin indent on

    " (Step_3): Some tests
    call LocalError('Banana')
    call LocalError('Apple')
    call LocalError('Orange')

    " Test multi-line terminal message.
    call mycoreplugin#utils#Message('test', '1<', g:log.DEBUG,
            \ 'Message: [%s] for hook:\n[%s]', 'FOO', 'BAR')

    call LocalError('Cat')
    call LocalError('Dog')
    call LocalError('Fox')
```

This is how I put the messages into the message stack:

```vim
function! LocalInfo(info)
    " Register a terminal message.
    echo a:info
    " Register a vim message.
    execute 'augroup myStartupMessages | autocmd VimEnter * echohl myInfoMessage | echomsg ' . string(a:info) . ' | echohl None | augroup END'
endfunction
```

## The reproduce ways from Vim starting (Required!)

 1. Start vim, everything is normal.
 2. Delete the `tpope/vim-unimpaired` from the bundles and restart.
 3. `tpope/vim-unimpaired` is installed at start-up.
 4. Errors and broken highlight groups. Restart.
 5. Everything is fine again.

## Screen shot (if possible)
VIM after an installed plugin:
<img width="467" alt="dein_vim_post_install" src="https://cloud.githubusercontent.com/assets/474655/14567636/f5f2a172-032c-11e6-80c4-b7d17082397a.png">

VIM after no plugins are installed at start-up:
<img width="448" alt="dein_vim_no_install" src="https://cloud.githubusercontent.com/assets/474655/14567667/21e10698-032d-11e6-8ee7-f9f76fbf6257.png">

## Upload the log messages by `:redir` and `:message`
(Not provided.)

**Comment by symbolix** [comment]
It might be something related to how dein.vim is handling au groups and highlight groups when a plugin is installed? Maybe something to do with the ` rtp` settings? I am investigating, as I said, it might be something to do with how I designed my plugin. But the problem definitely occurs after **dein.vim** adds a new plugin during the start-up. No other plugin is erroring, only my own plugin that I load with the `local` mode of **dein.vim**.

**Comment by symbolix** [comment]
I think this has something to do with the **rtp** line.

In the example at the end of the docs it is:

    set runtimepath^={path to dein.vim directory}

In the installation information it is:

    set runtimepath+={path to dein directory}

In the example at the top of the page, it is:

    set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim

So which one is the correct syntax?

When I move the following line after the dein block and change the ^ to +:

    set runtimepath+=/Users/me/dev/my_core_plugin/

the problem is solved. So this is about the handling of the `runtimepath` option.

 1. Manually force add a core plugin.
 2. dein.vim is used to load the rest of the plugins.

I can change the order of how things are done in my .vimrc but I would rather install my core plugin before dein takes over.

 1. dein.vim is used to load the rest of the plugins including the the core plugin.

Is there a way to install a plugin before the `dein [begin] / dein [end]` block?

**Comment by symbolix** [comment]
I guess, the best way to explain what I am trying to do is:

 1. Load a core local plugin called **my-core-vim**
 2. Load a main local plugin that is depending on the core plugin called **my-main-vim**
 3. Then finally load all other plugins.

I think I can do all of that with dein.vim at one go, just need to know if local plugins support dependencies.

**Comment by symbolix** [comment]
There is also the issue of the repeated keymap initialization:

To reproduce:

 1. Create a dummy-plugin: `vim-dummy/plugin/keymaps.vim`.
 2. Inside the `keymaps.vim` add the custom keymaps.
    
    nnoremap <unique> <silent>  <Plug>vixMoveToRightBuffer  <C-W>l
    nmap <silent> <C-l>     <Plug>vixMoveToRightBuffer

 3. Local source the `vim-dummy` plugin.

    call dein#local('path_to_a_local_bundle_folder', {}, ['vix-main'])

  4. Make sure that **dein.vim** will be installing a plugin at start up by also adding a brand new plugin as well. For example, assuming `vim-unimpaired` is not installed:

    call dein#add('tpope/vim-unimpaired', {'merged':0})

 5. Start vim, the new plugin gets installed but the keymaps are repeated and cause an error.

<img width="523" alt="keymaps_after_instal" src="https://cloud.githubusercontent.com/assets/474655/14576415/ca72b378-0360-11e6-9949-f4719360d084.png">

**Comment by Shougo** [comment]
> Start vim, the new plugin gets installed but the keymaps are repeuated and cause an error.

Your plugin implementation is wrong.

You must add the loaded variabe like this:

```vim
if exists('g:loaded_keymaps')
  finish
endif
let g:loaded_keymaps = 1

nnoremap <unique> <silent> <Plug>vixMoveToRightBuffer  <C-W>l
nmap <silent> <C-l> <Plug>vixMoveToRightBuffer
```

**Comment by Shougo** [comment]
Please explain `my-core-vim` and `my-main-vim` plugin.
I have not ESP skills.

**Comment by symbolix** [comment]
The keymaps problem is solved. Thanks. I somehow have forgotten to put the `let g:loaded_keymaps = 1` bit in there and that was the issue. The other problem is still there, I am explaining it in the next comment.

**Comment by symbolix** [comment]
These are the steps that I am trying to implement in my `.vimrc` start-up. Please assume that the following is my minimal `.vimrc` file.

**Step [1]**
Loading of a core plugin that I would like to install before `dein.vim`. I am adding it to the `rtp` in the following way:

```vim
    let g:path_to_core_plugin = '/Users/me/dev/my_core_plugin'
    exec 'set runtimepath^=' . g:path_to_core_plugin
````

The core plugin is a very simple vim plugin that contains some functions and routines that I would like to use inside my `.vimrc` before reaching the `dein.vim` stage. For example:

```vim
" As my_core_plugin is loaded, I can access its functions
call mycore#utils#PrepareHomeFolder()
call mycore#utils#StartLogger()
call mycore#utils#SetPluginManager('dein')
call mycore#logger#Verbose('Moving to the dein.vim stage.')
```

**Step [2]**
Now I can move on and `call dein.vim` and perform all the other tasks.

```vim
    " ;------------------------;
    " ; Plugin Manager: Begins ;
    " ;------------------------;
    if l:isPluginSequenceValid
        " Path to the plugin manager
        let g:plugin_manager_fullpath = '/Users/me/.vim/bundle/repos/github.com/Shougo/dein.vim'
        exec 'set runtimepath+=' . g:plugin_manager_fullpath

        " Start the plugin block.
        let g:plugin_manager_fullpath = '/Users/me/.vim/bundle'
        call dein#begin(g:vim_bundle_path)

        " Initial plugin is the plugin manager.
        call dein#add('Shougo/dein.vim')

        " Add or remove your plugins here:
        " Using a function inside my core plugin, I am running the `dein.vim` plugin cycle here.
        call mycore#utils#InitPlugins(g:my_plugin_chain)

        " End the plugin block.
        call dein#end()
        
        " Install the plugins that have not been installed  so far.
        if dein#check_install()
            call dein#install()
        endif
    endif
    " ;----------------------;
    " ; Plugin Manager: Ends ;
    " ;----------------------;
```

Have you noticed that I called a function from my tiny core plugin, inside the dein `begin/end` block. It does nothing more than running multiple `dein#add()` calls for the plugins. This works perfectly fine. No issue there. What goes wrong is explained below.

**The Problem**
There are some highlight groups defined inside _my_core_plugin_.

```vim
    " Inside my_core_plugin/plugin/mycore.vim
    hi CoreErrorMessage cterm=reverse ctermfg=DarkRed ctermbg=0 gui=reverse guifg=#dc322f

```
These are working just fine if vim starts up with no new plugins being installed by `dein.vim`. However, if `dein.vim` is required to install a new plugin on start-up those highlight groups are cleared.

    :verbose hi VixInfoMessage
    CoreErrorMessage xxx cleared

If I restart vim and no new plugin is installed at start up by dein.vim, the highlight groups are working perfectly. No prolem at all. So, somehow, `dein.vim` is clearing the highligh groups of the plugin that is added to the `rtp` before the `dein#begin()/dein#end()` cycle. The is way, if you look at the images provided above, the first image have no highlight groups, everything is mono, where the second image has the highligh groups behaviour correct.

How can we fix this? If there is a way to fix it.

Obviously I cannot load my tiny plugin with `dein.vim` cause I need it before the `dein.vim` stages. I tried multiple `dein#begin()/dein#end()` blocks, for example.

```vim
    " Load the tiny plugin first.
    dein#begin()
        dein#add('my_core_plugin')
    dein#end()`

    " Do stuff not related to dein using the tiny plugin.
    call mycore#utils#TakeCareOfThis()
    call mycore#utils#TakeCareOfThat()
    ...

    " Then load the rest of the plugins.
    dein#begin()
        dein#add('PopularPluginA')
        dein#add('PopularPluginB')
        dein#add('PopularPluginC')
    dein#end()`
```

Maybe we can get `dein.vim` to respect the highlight groups of plugins manually added to the `rtp` before it takes over the `rtp` management? Thank you very much.

**Comment by Shougo** [comment]
You can reproduce the problem by `dein#recache_runtimepath()`.

Please upload `my_core_plugin`.
I will test it.

**Comment by Shougo** [comment]
> Obviously I cannot load my tiny plugin with dein.vim cause I need it before the dein.vim stages. I tried multiple dein#begin()/dein#end() blocks, for example:

It does not work.  Dein does not support the multiple blocks.  It is slow.

But you can load the plugin manually.

```vim
" Load the tiny plugin first.
dein#begin()
dein#add('my_core_plugin')
dein#source('my_core_plugin')

" Do stuff not related to dein using the tiny plugin.
call mycore#utils#TakeCareOfThis()
call mycore#utils#TakeCareOfThat()
...

" Then load the rest of the plugins.
dein#add('PopularPluginA')
dein#add('PopularPluginB')
dein#add('PopularPluginC')
dein#end()
```

**Comment by symbolix** [comment]
Thanks for your time. So I can do anything between the `dein#begin()``dein#end()` calls? For example if the `call mycore#utils#TakeCareOfThis()` is echoing messages or setting some variables, like `let g:my_varaible = '1'` I thought the stuff we can do between the `dein#begin()``dein#end()` calls is limited? I will definitely try your solution.

**Comment by Shougo** [comment]
> Thanks for your time. So I can do anything between the dein#begin()dein#end() calls?

If the plugin is already loaded, you can call it.
If you don't call `dein#source()`, the plugin is loaded after `dein#end()`.  So you cannot.

**Comment by symbolix** [comment]
I prepared a small test plugin, but while I was doing that, I might have figured out a solution to my highlights problem. I think this whole mess related to the highlight groups is a VIM thing. It seems like the only way to accumulate messages with highlight groups is not only sending the messages into a `VimEnter` event, but also attaching the highlight commands to that. Something like this:

```vim
    " In addition to this:
execute 'augroup myStartupMessages | autocmd VimEnter * echohl myInfoMessage | echomsg ' . string(a:info) . ' | echohl None | augroup END'

    " I also need this:
    augroup myStartupMessages
        autocmd VimEnter * hi CoreErrorMessage cterm=reverse ctermfg=DarkRed ctermbg=0 gui=reverse guifg=#dc322f
    augroup END
```

Anything else is not working. I mean, the highlight groups are being cleared. But this is probably a VIM thing in general. So I will close the issue as soon as I am sure.

In the meantime, about this:

> dein#add('my_core_plugin')
> dein#source('my_core_plugin')

Can I do this?
```vim
    call dein#local(local_dev_folder, ['my_plugin'])
    dein#source('my_core_plugin')
```

I tried it and it did not work.

**Comment by Shougo** [comment]
> I tried it and it did not work.

`my_plugin` is valid name?  Why do you think `did not work`?
I want to see the correct code.

```vim
set runtimepath^=~/work/dein.vim/
call dein#begin(expand('~/.cache/test'))

call dein#add('altercation/vim-colors-solarized', {'merged': 0})
call dein#source('vim-colors-solarized')
colorscheme solarized
call dein#end()

if dein#check_install()
  call dein#install()
endif

syntax enable
filetype plugin indent on
```

It works.

**Comment by symbolix** [comment]
It is all working good now. Thank you very much for your help. The keymaps issue is solved with the variable check, and the colours / highlight issue was a VIM problem that had nothing to do with **dein.vim**. This bit was very helpful though:

```vim
call dein#source('vim-colors-solarized')
colorscheme solarized
call dein#end()
```

I knew from the FAQs that the colorscheme has to be called somewhere around the dein block, but was not sure where exactly.

Thanks.
