### ISSUE TITLE
Error with latest neovim and dein.vim

### ISSUE THREAD

**Issue by cellinho** [Shougo/dein.vim#79]
When i run my nvim i got this one:

`no notification handler registered for "/Users/cellinho/.vim/.dein/rplugin/python3/deoplete:function:_deoplete"`

i reinstalled neovim and dein.vim i didn't work for me please help. thanks.

**Comment by cellinho** [comment]
I was dumbass the path was totally wrong.

**Comment by Shougo** [comment]
I cannot reproduce it in the latest neovim.
Please update it to the latest version.

**Comment by Shougo** [comment]
I think you should kill the python process or reboot your machine.
The old Python process seem alives.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/4599
