### ISSUE TITLE
Error when lazy loading Ultisnips

### ISSUE THREAD

**Issue by gbcreation** [Shougo/dein.vim#81]
# Problems summary

Error when lazy loading Ultisnips and `:filetype on`.
The following error is displayed by Nvim:

Error detected while processing FileType Auto commands for "*":
E117: Unknown function: UltiSnips#FileTypeChanged

## Environment Information
 * OS: ArchLinux
 * Vim version: NVIM 0.1.3

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:plugins_dir = expand('~/.cache/nvim/dein-test')
let s:dein_plugin_dir = s:plugins_dir . '/repos/github.com/shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_plugin_dir)
        if executable('git')
            execute '!git clone https://github.com/shougo/dein.vim' s:dein_plugin_dir
        else
            echohl WarningMsg | echom "Git must be installed for Dein to work" | echohl None
            finish
        endif
    endif
    execute 'set runtimepath^=' . substitute( fnamemodify(s:dein_plugin_dir, ':p'), '/$', '', '')
endif

if dein#load_state(s:plugins_dir)
    call dein#begin(s:plugins_dir, [expand('<sfile>')])
    call dein#add('SirVer/ultisnips', { 'on_i': 1 })
    call dein#end()
endif

call dein#save_state()

if !has('vim_starting') && dein#check_install()
    call dein#install()
endif

filetype on
```

## The reproduce ways from Vim starting (Required!)

Launch Nvim with a filename on the command line, or launch Nvim without a filename on the command line, then open a file.

## Other information
```vim
:verb au filetype
--- Auto-Commands ---
dein  FileType
    *         if &filetype != '' |   call dein#autoload#_on_ft() | endif
        Last set from ~/.cache/nvim/dein-test/repos/github.com/shougo/dein.vim/autoload/dein.vim
UltiSnipsFileType  FileType
    *         call UltiSnips#FileTypeChanged()
        Last set from ~/.cache/nvim/dein-test/.dein/ftdetect/ftdetect.vim
```

**Comment by gbcreation** [comment]
The error continues to occur after commenting the line
`call dein#add('SirVer/ultisnips', { 'on_i': 1 })`

**Comment by Shougo** [comment]
It is feature.  You must not use UltiSnips as lazy plugins.
UltiSnips calls UltiSnips function in ftdetect.  So UltiSnips must be loaded in initialize.

**Comment by Shougo** [comment]
> The error continues to occur after commenting the line

You must call `dein#recache_runtimepath()`.

**Comment by gbcreation** [comment]
> You must call `dein#recache_runtimepath()`.

It works. Thanks for the tip.
However, the file `~/.cache/nvim/dein-test/.dein/ftdetect/ftdetect.vim` still exists and is empty. Shouldn't it be removed ?

**Comment by gbcreation** [comment]
For information, it is also necessary to call `dein#recache_runtimepath()` when using `'if': 0` instead of commenting the `call dein#add(...)` line.

Couldn't Dein call `dein#recache_runtimepath()`automatically when it detects that some plugins are no longer added or enabled ? It would be more user-friendly.

**Comment by Shougo** [comment]
> However, the file ~/.cache/nvim/dein-test/.dein/ftdetect/ftdetect.vim still exists and is empty. Shouldn't it be removed ?

Yes, it should be.  I will fix it.

**Comment by Shougo** [comment]
> Couldn't Dein call dein#recache_runtimepath()automatically when it detects that some plugins are no longer added or enabled ? It would be more user-friendly.

```
Q: I don't want to call |dein#recache_runtimepath()| manually.
A: Please specify your vimrc path to |dein#begin()| 2nd argument.
It detects the vimrc changes.
>
	call dein#begin(path, expand('<sfile>'))
<
```

**Comment by gbcreation** [comment]
```
Error detected while processing function dein#begin[1]..dein#util#_begin:
line   16:
E706: Variable type mismatch for: g:dein#_vimrcs
[dein] Invalid dein#save_state() usage.
```
No error if the second argument is a list: `call dein#begin(path, [expand('<sfile>')])`

**Comment by Shougo** [comment]
I have fixed the doc.

**Comment by gbcreation** [comment]
As you can see in the minimal .vimrc I provided in this issue, `[expand('<sfile>')]` is given as second argument to `call dein#begin(...)`. However, I have to call `dein#recache_runtimepath()` manually every time I comment or uncomment the line `call dein#add('SirVer/ultisnips', { 'on_i': 1 })`.

**Comment by Shougo** [comment]
Really?  I will try it.

**Comment by Shougo** [comment]
I get it.  It is feature.  It detects merged plugins changes only.
