### ISSUE TITLE
docs: wrong example to remove disabled plugins

### ISSUE THREAD

**Issue by gbcreation** [Shougo/dein.vim#82]
# Problems summary

In the FAQ section of the dein help is written:
```
Q: How to remove the disabled plugins?

A: You can get them by |dein#check_clean()|.
So you can remove them like below.

	call map(dein#check_clean(), "delete(v:val, 'rf')")
```

When I run `:echo dein#check_clean()`, I get
`['/home/myname/.cache/nvim/dein-test/repose/github.com/SirVer/ultisnips']`

When I run `call map(dein#check_clean(), "delete(v:val, 'rf')")` as indicated in the help, I get this error:
E118: Too many arguments for function: delete

`:help delete()` says that the delete() function takes only one argument.

# Environment Information

Vim version: NVIM 0.1.3

**Comment by Shougo** [comment]
@gbcreation Current neovim does not support the feature.
The patch is available.
https://github.com/neovim/neovim/pull/4367
