### ISSUE TITLE
ci, does not work when loading vim-textobj-parameter

### ISSUE THREAD

**Issue by whisper404** [Shougo/dein.vim#83]
# Problems summary
vim-textobj-parameter's default key mapping is a, and i,. But ci, does not working at the beginning when vim-textobj-parameter is a lazy plugin.

## Expected
ci, should change text immediately.

## Environment Information
 * OS:Mac OS X
 * Vim version:7.4-1752

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set nocompatible
let s:cache_dir = expand('~/.cache/')
execute 'set runtimepath^=' . s:cache_dir . 'dein/repos/github.com/Shougo/dein.vim'
call dein#begin(s:cache_dir . 'dein')
call dein#add('Shougo/dein.vim')
call dein#add('kana/vim-textobj-user')
call dein#add('sgur/vim-textobj-parameter')
call dein#config('vim-textobj-parameter', {
 \ 'depends': 'vim-textobj-user',
 \ 'lazy': 1,
 \ 'on_map': [['xo', 'a,'], ['xo', 'i,']]})
call dein#end()
filetype plugin indent on
syntax on
```

## The reproduce ways from Vim starting (Required!)

 1. Input some text like (ab, cd, ef)
 2. Move cursor to c, then press ci,. Nothing happened.
 3. Press ESC
 4. Press ci, again, then cd is deleted

## Screen shot (if possible)
![screen](https://cloud.githubusercontent.com/assets/17585720/14660887/2d02b5e8-06e4-11e6-8882-3078640f03a3.gif)

## Upload the log messages by `:redir` and `:message`

**Comment by gbcreation** [comment]
I have this bug too on Neovim 1.3.0. But it works as expected for `vi,`. The argument is selected.

**Comment by Shougo** [comment]
Fixed.

**Comment by gbcreation** [comment]
It works. Thank you.
