### ISSUE TITLE
FAQ error? check_clean and delete map

### ISSUE THREAD

**Issue by EmilRehnberg** [Shougo/dein.vim#84]
# Problems summary

I looked in the FAQ for a `:BundleClean` replacement (command for removing plugins)
I found this: 
```{vim} 
call map(dein#check_clean(), "delete(v:val, 'rf')")
```
but got error `E118: Too many arguments for function: delete`. Is the FAQ wrong or is it my set-up?

## Environment Information
 * OSX 10.11.4
 * NVIM 0.1.3

**Comment by whisper404** [comment]
#82 
I think you should read this issue.

**Comment by EmilRehnberg** [comment]
どうもありがとう
