### ISSUE TITLE
airline lost color after dein check install plugin when neovim startup

### ISSUE THREAD

**Issue by mhartington** [Shougo/dein.vim#86]
# Problems summary
When running dein check install, vim-airline throws error

## Environment Information
 * OS:
 * Neovim version: head

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('vim-airline/vim-airline')
call dein#end()

if dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)

Use minimal dein setup provided
add vim-airline
Install plugin
open init.vim and add random plugin
Next time you open nvim, you should get this error

## Screen shot (if possible)
![screen shot 2016-04-25 at 4 47 54 pm](https://cloud.githubusercontent.com/assets/2835826/14798446/9c4af9ae-0b05-11e6-91d8-491cdceba59e.png)

Note this only happens in neovim, and only happens if you check for missing plugins.

**Comment by Shougo** [comment]
It seems the plugin conflict.
Please disable the statusline update feature.

```vim
let g:dein#install_progress_type = 'echo'
```

**Comment by mhartington** [comment]
Sorry, but this doesn't seem to resolve the issue.

Even disabling the progress still doesn't prevent it 

```
  let g:dein#install_progress_type = 'none'
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.  Airline is the latest version?
It seems airline bug.  You should report it to airline issues.

**Comment by mhartington** [comment]
Hmm, seems related to a custom theme. My apologies!
