### ISSUE TITLE
load_state() completely overwrites runtimepath

### ISSUE THREAD

**Issue by rkitover** [Shougo/dein.vim#88]
This can cause some unexpected behavior

It's not really a big deal, but it may be nice if it would just prepend the plugin paths to runtimepath or something along those lines.

This came up here:

https://github.com/rkitover/vimpager/issues/166#issuecomment-214762771

**Comment by Shougo** [comment]
This is feature.  Yes, it should be documented though.
You must call `dein#save_state()`, `dein#load_state()` before overwrites runtimepath.

**Comment by Shougo** [comment]
> It's not really a big deal, but it may be nice if it would just prepend the plugin paths to runtimepath or something along those lines.

`dein#load_state()` does not do it.  Because it is slow.
