### ISSUE TITLE
Plugin loaded because of on_if condition, but on_event has not occurred

### ISSUE THREAD

**Issue by gbcreation** [Shougo/dein.vim#89]
# Problems summary

See the minimal .vimrc below. The Deoplete plugin is loaded as soon as a .vim file is edited, while the InsertEnter event has not occured yet.

## Expected

The Deoplete plugin must be loaded only when the InsertEnter event occurs and the current filetype is "vim".

## Environment Information
 * OS: ArchLinux
 * Vim version: Neovim 0.1.3

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let s:plugins_dir = expand('~/.cache/nvim/dein-test')
let s:dein_plugin_dir = s:plugins_dir . '/repos/github.com/shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_plugin_dir)
        if executable('git')
            execute '!git clone https://github.com/shougo/dein.vim' s:dein_plugin_dir
        else
            echohl WarningMsg | echom "Git must be installed for Dein to work" | echohl None
            finish
        endif
    endif
    execute 'set runtimepath^=' . substitute( fnamemodify(s:dein_plugin_dir, ':p'), '/$', '', '')
endif

if dein#load_state(s:plugins_dir)
    call dein#begin(s:plugins_dir, [expand('<sfile>')])
    call dein#add('shougo/dein.vim')
    call dein#add('shougo/deoplete.nvim', {
    \    'on_event': 'InsertEnter',
    \    'on_if': '&filetype == "vim"'
    \})
    call dein#end()
endif

call dein#save_state()

if !has('vim_starting') && dein#check_install()
    call dein#install()
endif

filetype on
```

## The reproduce ways from Vim starting (Required!)

 1. Run `nvim`
 2. Edit a .vim file
 3. Run `:scriptnames`to see that deoplete.nvim is loaded or `:echo dein#is_sourced("deoplete.nvim")`

**Comment by wsdjeg** [comment]
I do not see any issue.the filetype is vim.so the plugin was loaded.
the args means
`on_if || on_event` not `on_if && on_event`

**Comment by gbcreation** [comment]
@wsdjeg I don't think so. Read the help:
> The default evaluate timings are "BufRead", "BufNewFile",
"BufNew", "VimEnter" and "FileType".
If |dein-options-on_event| exists, it is evaluated when
|dein-options-on_event|.

So `on_if` should be evaluated when the event declared with `on_event` occurs in my example.
Shougo, can you please confirm this ?

**Comment by Shougo** [comment]
Fixed.

**Comment by gbcreation** [comment]
It works. Thank you.
