### ISSUE TITLE
Inconsistencies between dein#check_update() and dein#update()

### ISSUE THREAD

**Issue by gbcreation** [Shougo/dein.vim#93]
# Problems summary

I run `:call dein#check_update()` to know if updates are available for the Vim plugins I use and get these messages:
```
[dein] Update started: (2016/05/05 15:14:04)
[dein] Updated plugins:
[dein]   tcomment_vim
[dein]   vim-textobj-function-javascript
[dein]   vim-textobj-indent
dein] Done: (2016/05/05 15:14:30)
```
So I expect that updates are available for `tcomment_vim`, `vim-textobj-function-javascript` and `vim-textobj-indent` plugins. Then I run `:call dein#update()` to update my plugins and get these messages:
```
[dein] Update started: (2016/05/05 15:14:51)
[dein] Updated plugins:
[dein]   tcomment_vim(1 change)
[dein]     https://github.com/tomtom/tcomment_vim/compare/7c4277754b6b77fb80b47cd4a7384d1e2d6c1538...d2df45fdf66f33ae7e267d45846aece6ea82ae66
[dein]   yajs.vim(2 changes)
[dein]     https://github.com/othree/yajs.vim/compare/a679e3c8835ee68a1193bc832285710f0af5518f...45d3aa8d4ce59e91b3b3949c5fec7f4a84a77435
[dein]   tern_for_vim
[dein]     https://github.com/ternjs/tern_for_vim/compare/...064a3368277f7b4cdf14d2197d2dd737be40eb2d
[dein]   deoplete-ternjs
[dein]     https://github.com/carlitux/deoplete-ternjs/compare/...71f3255ded6eee42ce4c0ead0308fd1298887dc6
remote/host: python3 host registered plugins ['deoplete']
remote/host: generated the manifest file in "/home/gbc/ownCloud/dotfiles/nvim/.init.vim-rplugin~" 
[dein] Runtimepath updated: (2016/05/05 15:14:58)
```
We can see that the `tcomment` plugin is updated as expected (1 change). But `vim-textobj-function-javascript` and `vim-textobj-indent` plugins are not updated while `dein#check_update()` told there are available updates for them.

Some plugins are also updated while `dein#check_update()` did not list them: `yasm.vim`(2 changes), `tern_for_vim` and `deoplete-ternjs`. For the last two, the number of changes is not indicated.

When I follow the Github links indicated for each updated plugin, I can indeed see the changes for `tcomment` and `yasm.vim`. But there is no change reported by Github for `tern_for_vim` and `deoplete-ternjs`. So those last two plugins seem to have been unnecessarily updated.

## Expected

`dein#check_update()` should list all plugins for which updates are available.
`dein#update()` should only update plugins for which updates are available.

## Environment Information
 * OS: ArchLinux
 * Vim version: Neovim 0.1.4
 * Git version: 2.8.2

**Comment by wsdjeg** [comment]
as I know `dein#check_update()` is not multithreading.
but `dein#update()` has 8 thread by default.so I think maybe `call dein#update()` will update all plugins ,it is very fast.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please create minimal init.vim and reproduce ways.
HInt:  You can reset the repository by `git reset --hard revision`.

**Comment by gbcreation** [comment]
Maybe some of my git clones are in an invalid state due to bad Internet connection previously. I fully deleted my dein cache and made a small init.vim to test with a subset of the plugins I'm using. I will give you a feedback in some days.

**Comment by Shougo** [comment]
No response.
