### ISSUE TITLE
dein.vim breaks when loading a local plugin that is under git control

### ISSUE THREAD

**Issue by symbolix** [Shougo/dein.vim#96]
# Problems summary
I have a local plugin that I am loading using dein. I had no issues up until I got my plugin on bitbucket, so it is now git version controlled. However, dein breaks when the local plugin is being loaded. 

## Expected
I would expect the `dein#local()` just to work.

## Environment Information
 * OS:
OSX El Capitan 10.11.4
 * Vim version:
7.4 (1-1553)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
call dein#local(g:vix_directory_tree.base.path, {},
    \ ['my_local_plugin'])
```

## The reproduce ways from Vim starting (Required!)
Just try adding a local plugin that is under .git control.

## Screen shot (if possible)
<img width="953" alt="dein_local_issue" src="https://cloud.githubusercontent.com/assets/474655/15259607/245b547c-194a-11e6-9b4b-31bdd88b4565.png">

## Upload the log messages by `:redir` and `:message`
    Error detected while processing function dein#local[1]..dein#parse#_local[19]..dein#add[1]..dein#parse#_add[1]..dein#parse#_init[1]..1[5]..<SNR>9_is_git_dir:
    line   17:
    E117: Unknown function: dein#util#join_paths
    E15: Invalid expression: dein#util#join_paths(path, matches[1])
    Error detected while processing function dein#local[1]..dein#parse#_local[19]..dein#add[1]..dein#parse#_add[1]..dein#parse#_dict:
    line    6:
    E712: Argument of extend() must be a List or Dictionary`

**Comment by AlexMasterov** [comment]
I have something similar, the exception is thrown once after restart Vim with a previously saved vimrc:
```vim
[dein] Error occurred while loading state : Vim(let):E714: List required
```
**state_gvim.vim**
```vim
let [plugins, ftplugin] = dein#load_cache_raw(['C:/Apps/Vim/_vimrc'], 1)
if empty(plugins) | throw 'Cache loading error' | endif
let g:dein#_plugins = plugins
let g:dein#_ftplugin = ftplugin
let g:dein#_base_path = 'C:/Apps/Vim/dein'
let g:dein#_runtime_path = 'C:/Apps/Vim/dein/.dein'
let &runtimepath = 'C:/Apps/Vim/vimfiles/dev/gist,C:/Apps/Vim/vimfiles/dev/dotvim,C:/Apps/Vim/vimfiles/dev/snippetus,C:/Apps/Vim/vimfiles/dev/twig.vim,C:/Apps/Vim/dein/.dein,C:/Apps/Vim/dein/repos/github.com/Shougo/dein.vim,C:/Apps/Vim/vim74,C:/Apps/Vim/dein/.dein/after'
// ...
```

**Comment by symbolix** [comment]
I managed to get this working by actually using the:
`call dein#add('URI_TO_MY_PLUGIN')`

But it would be nice to be able to add a local git-repo version of the plugin without committing the changes to the remote repo, while testing etc.

Every time I tried to access the local repo of my plugin, I got the error above. Any ideas?

Thanks.

**Comment by Shougo** [comment]
Fixed.

@AlexMasterov Your dein cache file is old.  Please call `dein#clear_state()`.

**Comment by symbolix** [comment]
Works. Thank you very much.
