### ISSUE TITLE
`<silent>` feature does not work in on_map

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#98]
```vim
        call s:add('dyng/ctrlsf.vim',{'on_cmd' : 'CtrlSF', 'on_map' : '<Plug>CtrlSF'})
        if s:tap('ctrlsf.vim')
            call s:defind_hooks('ctrlsf.vim')
            nmap <silent><leader>sn <Plug>CtrlSFCwordPath<CR>
        endif
```
the first time I type `<leader>sn`,I will see `:CtrlSF foo` in cmdline,and the ctrlsf buffer will be opened as expected.
and the second time I type the `<leader>sn` I will not see `:CtrlSF foo` in cmdline,also ctrlsf buffer will be auto opened.
so I think in the first time dein exec the mapping as expected,just not take care of the `<silent>` option.

**Comment by wsdjeg** [comment]
I have read the doc,and the doc sais,on_map support mode feature,so I change the config to
```vim
        call s:add('dyng/ctrlsf.vim',{'on_cmd' : 'CtrlSF', 'on_map' : ['<silent> n', '<Plug>CtrlSF']})
        if s:tap('ctrlsf.vim')
            call s:defind_hooks('ctrlsf.vim')
            nmap <silent><leader>sn <Plug>CtrlSFCwordPath<CR>
        endif
```
but still same result.
IMO,use dict for on_map feature is better than list;
for example
```vim
   call s:add('dyng/ctrlsf.vim',{'on_cmd' : 'CtrlSF', 'on_map' : {'<silent> n': '<Plug>CtrlSF',
                                                                          \'i':'<Plug>CtrlSFPromate'}})
```

**Comment by Shougo** [comment]
https://github.com/dyng/ctrlsf.vim/blob/master/plugin/ctrlsf.vim#L223

It is ctrlsf.vim problem.
`<silent>` is needed for the mappings.

**Comment by wsdjeg** [comment]
wow,thanks.

**Comment by wsdjeg** [comment]
thanks for impl this feature!
